### ISSUE TITLE
ApierV1.SetTPAccountActions not allow empty ActionTriggersId

### ISSUE THREAD

**Issue by miromiky** [cgrates/cgrates#1001]
Hi @danbogos 
API: https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.SetTPAccountActions
Can we make ActionTriggers optional. ("ActionTriggersId": "") 
Thanks

**Comment by Anevo** [comment]
Hi @miromiky , 
this feature is now available in master.

Regards, Cezar

**Comment by miromiky** [comment]
Thanks Anevo.
Have a nice day
