### ISSUE TITLE
ThresholdS Execution of Action

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1014]
Hello, Dear CGRateS Team!

While trying to test StatUpdate with ThresholdS, the Threshold is not executing actions.
Here are my configs:
[Thresholds.zip](https://github.com/cgrates/cgrates/files/1812665/Thresholds.zip)

Here is my API 
```
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"StatSv1.ProcessEvent",
  "params":[
     {
    	"Tenant": "golant",
		"ID": "a0e8f0d2-62fa-4302-a51b-aaedaa9158f5",
		"Context": null,
		"Time": null,
		"Event": {
			"Account": "972536213067",
			"BalanceID": "data",
			"EventSource": "AccountS",
			"EventType": "BalanceUpdate",
			"Units": 100000.0
		}

    }
  ]
}

{
"id": "0",
"result": "OK",
"error": null
}
```

Check StatsQueue:

```
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"StatSv1.GetQueueStringMetrics",
  "params":[
   {
     "ID": "STS_972536213067",
    "Tenant":"golant"
   
    }
  ]
}
{
"id": "0",
"result":{
"*sum": "100000"
},
"error": null
}

```

Check for threshold returns "NOT FOUND", which is perfectly fine because my threshold is non-recurrent.

Please assist,
Thanks,
Michael

**Comment by TeoV** [comment]
Hey Michael , 
Answered on group . 
I will close this issue now .

Thanks,
TeoV
