### ISSUE TITLE
min_dur_low_balance feature 

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#1015]
Hi guys,

Could you please add min_dur_low_balance feature to freeswitch_agent
Here is the issue from the forum:
https://groups.google.com/forum/#!topic/cgrates/Bm5nM82V0yw

Thank you!
Arsen

**Comment by ccppprogrammer** [comment]
Hey Dan!
Any update on this feature request?

**Comment by danbogos** [comment]
hey Sergei,

No update right now, it is still on nice-to-have list on our side.

DanB

**Comment by Trial97** [comment]
Hi @ccppprogrammer,

This feature was added to the master(https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L447 and https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L475).

Thanks,
Trial97
