### ISSUE TITLE
min_call_duration issue

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#1016]
Hi guys,

"min_call_duration" parameter seems currently doesn't work as described. 
Could you please check it.

Thanks,
Arsen.

**Comment by danbogos** [comment]
hi @arsperger 

Please retest with latest master and report back if any issues.

Ta,
DanB

**Comment by gmclaren** [comment]
I'm getting a {"id":1360510658,"result":null,"error":"SERVER_ERROR: UNAUTHORIZED_MIN_DURATION"} with the latest release cgrates_0.9.1~rc8_amd64.deb 
Here is my request.
{ "method": "SMGenericV1.GetMaxUsage", "id": 2108246000, "params": [ { "RequestType": "*postpaid", "Tenant": "sx9001.xxxxxxxhiddenxxxx", "OriginID": "e68c0bbb97e1f0223f8189b3abfabdc6@0:0:0:0:0:0:0:0", "Account": "1000", "SetupTime": "1523861927", "Destination": "xxxhiddenxxx" } ] }

I'm using opensips 2.3 and the cgrates module.

No issue with my working version: CGRateS 0.9.1~rc8 git+b6a1f0a (2018-02-09T20:11:22+01:00)

**Comment by danbogos** [comment]
hi @gmclaren 

Try adding Usage field in your event. If missing, we will consider Usage as 0 and that would be smaller than your configured MinDuration configured by you in sessions.

DanB

**Comment by gmclaren** [comment]
With OpenSips I'm using the cgrates_auth function
    if (!cgrates_auth("$fU", "$rU")) {
	sl_send_reply("403", "Forbidden");
	exit;
    }
The work around for me was to set the "min_call_duration": "-1s"  in the cgrates.json file.
Thanks

**Comment by danbogos** [comment]
hi @gmclaren 

Please retest and let us know if issue gone.

Thanks,
DanB
