### ISSUE TITLE
ApierV1.SetResourceProfile not allow UsageTTL = "*unlimited" 

### ISSUE THREAD

**Issue by miromiky** [cgrates/cgrates#1027]
Hi @danbogos ,

https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.SetResourceProfile

If I try to put UsageTTL = "*unlimited" instead of for example 6000000000 I have this error: json: cannot unmarshal string into Go struct field ResourceProfile.UsageTTL of type time.Duration

Is correct instead of "*unlimited" put "UsageTTL": -1?
Or can you fix it?
Thanks

**Comment by TeoV** [comment]
Hi @miromiky,
As you know we have implemented *unlimited on this issue https://github.com/cgrates/cgrates/issues/965 
If you use API (SetResourceProfile) you will have to use -1 as value for UsageTTL, and if you load them from files you can use *unlimited. 

Thanks,
TeoV
