### ISSUE TITLE
mongodb replica set support

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#1031]
Hi guys,

can you please add replica set support to mongo db connection URL.

Our mongodb connection string look like this:
mongodb://root:password@mongocluster1.example.com:3717,mongocluster2.com:3717/cgrates_db_name?replicaSet=mgset-12345&authSource=admin

I found this file: https://github.com/cgrates/cgrates/blob/master/engine/storage_mongo_datadb.go and made the settings, so CGRates can initialize connection

"data_db": {
        "db_type": "mongo",                                
        "db_host": "mongocluster1.example.com:3717,mongocluster2.com:3717",                                             
        "db_name": "cgrates_db_name?replicaSet=mgset-12345&authSource=admin",
        "db_user": "root",
        "db_password": "password",
        "load_history_size": 10,                                
 },

Then I execute cgr-migrator with the following parameters:
 -datadb_host="mongocluster1.example.com:3717,mongocluster2.com:3717" -datadb_name="cgrates_db_name?replicaSet=mgset-12345&authSource=admin" -datadb_type=mongo -datadb_user=root -datadb_passwd=password

Finally it seems to connect to the mongo cluster but it creates database with the name: "cgrates_db_name?replicaSet=mgset-12345&authSource=admin" instead of "cgrates_db_name"

Thanks,
Arsen

**Comment by TeoV** [comment]
Hi, Arsen
Please update from master and test it. 
Here you have a sample config 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/mongoreplica/cgrates.json#L18
I will close the issue now.
If something doesn't work as you expected please reopen this issue.

Thanks,
TeoV
