### ISSUE TITLE
GetLCRSuppliers Problem

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#1039]
When working with USA dialler decks I have found that not all suppliers have every single destination in each deck.

This causes GetLCRSuppliers to fail with "SERVER_ERROR:LCR_COMPUTE_ERRORS" so the call would fail.

I understand that we can use filtering and I assume these filters would be applied for larger groups rather than the odd prefix. It seems that you would need to check that every possible dialled prefix had a match in every rateplan.

I have fixed this for now by adding the parameter "IgnoreErrors":true to the GetLCRSuppliers API call.

I'm not sure if there is a better way to handle this at all.

**Comment by danbogos** [comment]
hey @DigiDaz 

In old LCR there is already IgnoreErrors. I assumed you want the same for new SupplierS. Is this the case?

DanB

**Comment by DigiDaz** [comment]
DanB,

I think so, yes, if getsuppliers is the new one, yes.
