### ISSUE TITLE
Cdrstats - count unique destinations

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#106]
There is an increased demand of offerings like: first 20 destinations dialed are free. To cope with that we should create a new stats metric for it counting the different numbers hitting a stats queue. This queue should have the normal filters also and only after filtering we should count the destinations.
ActionTriggers should work on the metric and as part of the http post sent as result, we should send the numbers out.

DanB

**Comment by rif** [comment]
Closed by commit by mistake
