### ISSUE TITLE
cgr-migrator error

### ISSUE THREAD

**Issue by pasanmdev** [cgrates/cgrates#1074]
Hi Guys,

I'm trying out cgrates for the first time and I'm stuck at cgr-migrator setup in the installation. I tried the following command in my setup and it throws me following error. do I need to set all param in cgr-migrator in order to get it working ?

cgr-migrator -stordb_type="postgres" -stordb_host="localhost" -stordb_port="5432" -migrate="*set_versions"  -stordb_passwd="xxxxx"  
2018/05/08 19:58:40 Unknown db '*dynamic' valid options are [mysql, mongo, postgres]

what is difference between -datadb_host and -out_datadb_host ? also -stordb_host vs -out_stordb_host ?

**Comment by andrewvmail** [comment]
Omg what a coincidence funny you mentioned this right now, I'm also scratching my head  
```CGRateS 0.9.1~rc8 git+180ad31 (2018-05-07T18:50:23+02:00)```

**Comment by danbogos** [comment]
hey guys,

We have recently added support for .json config options, so there are chances that this created some issues.

@pasanmdev, you should normally only use -datadb_host and not the -out_datadb_host. The later is for cases when you want to migrate data from one DB(dataDB) to another (outDataDB). Please try specifying clearly the datadb_type="redis" in your migrator command (or load all settings from .json file via config_dir option) and let me know how that works. I will also check and fix the *dynamic complain you are seeing.

DanB

**Comment by pasanmdev** [comment]
@danbogos  I tried following now getting a different error. 

cgr-migrator -datadb_type="redis" -stordb_type="postgres" -stordb_host="localhost" -stordb_port="5432"  -stordb_passwd="eshoaLia4I" -migrate="*set_versions"   -dry_run
2018/05/08 20:18:36 Unknown db '*dynamic' valid options are [mysql, mongo, postgres]

and how to I get cgr-migrator to use the config file ? cli usage doesn't indicate that I can pass a config file.

**Comment by andrewvmail** [comment]
Awesome! Also Dan what do you guys dev on debian stretch ? for some reason im having issue building from source. maybe this should be in another ticket.
```
Building CGRateS ...
cdrc/cdrc.go:36:2: cannot find package "gopkg.in/fsnotify.v1" in any of:
        /root/go/src/github.com/cgrates/cgrates/vendor/gopkg.in/fsnotify.v1 (vendor tree)
        /usr/lib/go-1.7/src/gopkg.in/fsnotify.v1 (from $GOROOT)
        /root/go/src/gopkg.in/fsnotify.v1 (from $GOPATH)
# github.com/cgrates/cgrates/engine
engine/libattributes.go:54: undefined: sort.Slice
engine/libstats.go:200: undefined: sort.Slice
engine/libsuppliers.go:66: undefined: sort.Slice
engine/libsuppliers.go:74: undefined: sort.Slice
engine/resources.go:193: undefined: sort.Slice
engine/suppliers.go:67: undefined: sort.Slice
engine/thresholds.go:111: undefined: sort.Slice
# github.com/cgrates/cgrates/engine
engine/libattributes.go:54: undefined: sort.Slice
engine/libstats.go:200: undefined: sort.Slice
engine/libsuppliers.go:66: undefined: sort.Slice
engine/libsuppliers.go:74: undefined: sort.Slice
engine/resources.go:193: undefined: sort.Slice
engine/suppliers.go:67: undefined: sort.Slice
engine/thresholds.go:111: undefined: sort.Slice
# github.com/cgrates/cgrates/engine
engine/libattributes.go:54: undefined: sort.Slice
engine/libstats.go:200: undefined: sort.Slice
engine/libsuppliers.go:66: undefined: sort.Slice
engine/libsuppliers.go:74: undefined: sort.Slice
engine/resources.go:193: undefined: sort.Slice
engine/suppliers.go:67: undefined: sort.Slice
engine/thresholds.go:111: undefined: sort.Slice
# github.com/cgrates/cgrates/engine
engine/libattributes.go:54: undefined: sort.Slice
engine/libstats.go:200: undefined: sort.Slice
engine/libsuppliers.go:66: undefined: sort.Slice
engine/libsuppliers.go:74: undefined: sort.Slice
engine/resources.go:193: undefined: sort.Slice
engine/suppliers.go:67: undefined: sort.Slice
engine/thresholds.go:111: undefined: sort.Slice

```

**Comment by danbogos** [comment]
@andrewvmail 

Right now building packages on an older jessie, however it should not matter. The reason you are getting that error is due to older version of Go (you need at least 1.8 as far as I can remember). However you should be safe to always run the latest Go stable (which is 1.10 right now).

DanB

**Comment by andrewvmail** [comment]
Got it thanks Dan!

**Comment by pasanmdev** [comment]
@danbogos Thanks a heap :) Waiting for u r green light ..

**Comment by danbogos** [comment]
hey guys,

Please retest and report if any issues. I will also update the packages.

Thanks for reporting!

DanB

**Comment by andrewvmail** [comment]
I think it works I'm getting data migrated now.

```
root@voice-debian-s-2vcpu-2gb-sfo1-01:~/cgrates# cgr-migrator -stordb_passwd="CGRateS.org" -migrate="*set_versions" -verbose
2018/05/08 17:41:42 Data migrated: map[]
```
Curious @danbogos what does migrate="*set_versions" do? i was expecting it inserting a field to version table but it didn't do that.

**Comment by pasanmdev** [comment]
Hey Dan,

I'm still getting the error. :/ I tried the latest pkg.

cgr-migrator -datadb_type="redis" -stordb_type="postgres" -stordb_host="localhost" -stordb_port="5432"  -stordb_passwd="xx" -migrate="*set_versions"  
2018/05/09 12:06:18 Unknown db '*dynamic' valid options are [mysql, mongo, postgres]

**Comment by andrewvmail** [comment]
cgr-engine -version
happened to me too i didnt install properly

**Comment by pasanmdev** [comment]
@andrewvmail Thanks. I mistakenly installed the previous version. All good now 
Thanks Dan

**Comment by andrewvmail** [comment]
haha lucky guess !
