### ISSUE TITLE
inconsistency with how to cgr-migrator switches works

### ISSUE THREAD

**Issue by andrewvmail** [cgrates/cgrates#1076]
Does not work ``` cgr-migrator datadb_host="redis" -stordb_passwd="CGRateS.org" -migrate="*set_versions" ```

Works ``` cgr-migrator  -datadb_host "redis"  -stordb_passwd="CGRateS.org" -migrate="*set_versions" ```

seems like datadb_host doesn't like = sign

**Comment by danbogos** [comment]
hi @andrewvmail 

It appears that in the first case you did not properly run the command, you need to add - in front of datadb_host.

DanB

**Comment by andrewvmail** [comment]
oh my bad! thanks
