### ISSUE TITLE
export CDRs data race issue

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#1078]
Hi Dan,

I open this issue as mentioned in your comment here https://github.com/cgrates/cgrates/issues/1043#issuecomment-387478763

log file is attached.
Thanks!
[cgrates_cps_issue.txt](https://github.com/cgrates/cgrates/files/1987783/cgrates_cps_issue.txt)

**Comment by Trial97** [comment]
The races should be fixed in master.
Please retest and reopen if needed.
