### ISSUE TITLE
CGRMaxSessionTime Not capture by Asterisk

### ISSUE THREAD

**Issue by YohaiAllouche** [cgrates/cgrates#1079]
Hi Dan,

Integrating CGRates with Asterisk 15.3 via AIR

The call cost is working well.

The problem is retrieving the CGRMaxSessionTime back to extension flow.

The extension code:
exten => _X.,n,Set(CGRMaxSessionTime=0); use it to disconnect automatically the call if CGRateS is not active
exten => _X.,n,DumpChan()
exten => _X.,n,Stasis(cgrates_auth,cgr_category=voice,cgr_reqtype=*prepaid,cgr_supplier=supplier1,cgr_tenant=num2.il,cgr_account=972${Caller:1},cgr_destination=972${Called:1},cgr_tor=voice,cgr_subject=972${Called:1}) ;
exten => _X.,n,Verbose(CGRMaxSessionTime:${CGRMaxSessionTime})

I don't see it on channel variables dump.

From AIR flow we can see:
The ngrep log:
T 2018/05/09 10:07:41.623833 192.168.XXX.ZZZ:8088 -> 192.168.XXX.YYY:37714 [AP]
.~.P{
  "type": "StasisStart",
  "timestamp": "2018-05-09T10:08:07.926+0300",
  "args": [
    "cgr_category=voice",
    "cgr_reqtype=*prepaid",
    "cgr_supplier=supplier1",
    "cgr_tenant=num2.il",
    "cgr_account=972ZZXXXXXX",
    "cgr_destination=972ZZXXXXXXX",
    "cgr_tor=voice",
    "cgr_subject=972ZZXXXXXXX"
  ],
  "channel": {
    "id": "1525849685.761",
    "name": "SIP/CELLACT_GB_1-00000115",
    "state": "Ring",
    "caller": {
      "name": "ABC EFG",
      "number": "ZZXXXXXX"
    },
    "connected": {
      "name": "",
      "number": ""
    },
    "accountcode": "",
    "dialplan": {
      "context": "shadow_1",
      "exten": "0ZZXXXXXX",
      "priority": 49
    },
    "creationtime": "2018-05-09T10:08:05.716+0300",
    "language": "he"
  },
  "asterisk_id": "00:50:56:8a:56:f4",
  "application": "cgrates_auth"
}
#####
T 2018/05/09 10:07:41.626329 192.168.XXX.YYY:37954 -> 192.168.XXX.ZZZ:8088 [AP]
POST /ari/applications/cgrates_auth/subscription?eventSource=channel:1525849685.761 HTTP/1.1.
Host: 192.168.XXX.ZZZ:8088.
User-Agent: CGRateS 0.9.1~rc8.
Content-Length: 0.
Authorization: Basic Y2dyYXRlczpDR1JhdGVTLm9yZw==.
Accept-Encoding: gzip.
.

##
T 2018/05/09 10:07:41.627171 192.168.XXX.ZZZ:8088 -> 192.168.XXX.YYY:37954 [AP]
HTTP/1.1 200 OK.
Server: Asterisk/15.3.0.
Date: Wed, 09 May 2018 07:08:07 GMT.
Cache-Control: no-cache, no-store.
Content-type: application/json.
Content-Length: 137.
.
{
  "name": "cgrates_auth",
  "channel_ids": [
    "1525849685.761"
  ],
  "bridge_ids": [],
  "endpoint_ids": [],
  "device_names": []
}
##
T 2018/05/09 10:07:41.643898 192.168.XXX.YYY:37954 -> 192.168.XXX.ZZZ:8088 [AP]
POST /ari/channels/1525849685.761/variable?variable=CGRMaxSessionTime HTTP/1.1.
Host: 192.168.XXX.ZZZ:8088.
User-Agent: CGRateS 0.9.1~rc8.
Content-Length: 13.
Authorization: Basic Y2dyYXRlczpDR1JhdGVTLm9yZw==.
Accept-Encoding: gzip.
.
value=3174000
#
T 2018/05/09 10:07:41.644702 192.168.XXX.ZZZ:8088 -> 192.168.XXX.YYY:37954 [AP]
HTTP/1.1 204 No Content.
Server: Asterisk/15.3.0.
Date: Wed, 09 May 2018 07:08:07 GMT.
Cache-Control: no-cache, no-store.
Content-Length: 0.
.

#
T 2018/05/09 10:07:41.645009 192.168.XXX.YYY:37954 -> 192.168.XXX.ZZZ:8088 [AP]
POST /ari/channels/1525849685.761/continue HTTP/1.1.
Host: 192.168.XXX.ZZZ:8088.
User-Agent: CGRateS 0.9.1~rc8.
Content-Length: 0.
Authorization: Basic Y2dyYXRlczpDR1JhdGVTLm9yZw==.
Accept-Encoding: gzip.
.

#
T 2018/05/09 10:07:41.645414 192.168.XXX.ZZZ:8088 -> 192.168.XXX.YYY:37954 [AP]
HTTP/1.1 204 No Content.
Server: Asterisk/15.3.0.
Date: Wed, 09 May 2018 07:08:07 GMT.
Cache-Control: no-cache, no-store.
Content-Length: 0.
.

##
T 2018/05/09 10:07:41.824346 192.168.XXX.YYY:8088 -> 192.168.XXX.ZZZ:37714 [AP]
.~..{
  "variable": "CGRMaxSessionTime",
  **"value": "",**
  "type": "ChannelVarset",
  "timestamp": "2018-05-09T10:08:08.126+0300",
  "channel": {
    "id": "1525849685.761",
    "name": "SIP/CELLACT_GB_1-00000115",
    "state": "Ring",
    "caller": {
      "name": "ABC EFG",
      "number": "ZZXXXXXX"
    },
    "connected": {
      "name": "",
      "number": ""
    },
    "accountcode": "",
    "dialplan": {
      "context": "shadow_1",
      "exten": "0ZZXXXXXX",
      "priority": 49
    },
    "creationtime": "2018-05-09T10:08:05.716+0300",
    "language": "he"
  },
  "asterisk_id": "00:50:56:8a:56:f4",
  "application": "cgrates_auth"
}
##

REgards,
Yohai

**Comment by danbogos** [comment]
hi @YohaiAllouche 

Is there any chance you test also with an older version of asterisk? Maybe 13? Just to know if they have modified in between the way we can push data via ARI.

Ta,
DanB

**Comment by YohaiAllouche** [comment]
Hi Dan,

Yes I can, no problem.
I will check it and let you know the results.

Yohai

**Comment by YohaiAllouche** [comment]
Hi,

I have test it on 13:
Same problem asterisk flow don’t get the CGRMaxSessionTime value.
I can see that after Set command it is 0 in dump variables:
Variables:
CGRMaxSessionTime=0

When starting Stasis it is null
[May 10 13:37:51] DEBUG[5236] http.c: HTTP Request URI is /ari/channels/1525948671.877/variable?variable=CGRMaxSessionTime
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [httpstatus] len 10
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [phoneprov] len 9
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [amanager] len 8
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [arawman] len 7
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [manager] len 7
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [rawman] len 6
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [static] len 6
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [amxml] len 5
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [mxml] len 4
[May 10 13:37:51] DEBUG[5236] http.c: match request [ari/channels/1525948671.877/variable] with handler [ari] len 3
[May 10 13:37:51] DEBUG[5236] http.c: Match made with [ari]
[May 10 13:37:51] DEBUG[5236] res_ari.c: Finding handler for channels
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking applications
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking asterisk
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking bridges
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking channels
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Got it!
[May 10 13:37:51] DEBUG[5236] res_ari.c: Finding handler for 1525948671.877
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking create
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking channelId
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Got it!
[May 10 13:37:51] DEBUG[5236] res_ari.c: Finding handler for variable
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking continue
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking redirect
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking answer
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking ring
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking dtmf
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking mute
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking hold
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking moh
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking silence
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking play
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking record
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Checking variable
[May 10 13:37:51] DEBUG[5236] res_ari.c:   Got it!
[May 10 13:37:51] DEBUG[5236] http.c: HTTP discarding unused request body
[May 10 13:37:51] DEBUG[5236] http.c: HTTP keeping session open.  status_code:204
..
…
..

[May 10 13:37:56] DEBUG[5233][C-000000ec] pbx_variables.c: Result of 'CGRMaxSessionTime' is NULL
[May 10 13:37:56] DEBUG[5233][C-000000ec] pbx_variables.c: Result of 'value' is NULL
[May 10 13:37:56] DEBUG[5233][C-000000ec] pbx.c: Launching 'Verbose'
[May 10 13:37:56] VERBOSE[5233][C-000000ec] pbx.c: Executing [0557000363@shadow_1:52] Verbose("SIP/CELLACT_GB_1-00000145", "CGRMaxSessionTime: --- ") in new stack


Regards,
Yohai

**Comment by danbogos** [comment]
Great, many thanks, will take over from here. Most probably we don't set it in the way they expect the value.

DanB
