### ISSUE TITLE
RSRField as subset of filters objects

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1084]
Hello Dear CGRateS Team!

Will be nice having real filters in the processor templates.
Something like : 
`"field_filter":"*cgrReply>Error(^$);*cgrReply>MaxUsage(*gt(102400))"`

Thanks,
Michael

**Comment by Trial97** [comment]
This is available in filters(https://github.com/cgrates/cgrates/blob/master/data/conf/samples/diam_tutmysql/data.json#L62) for the field config
