### ISSUE TITLE
Starting cgrengine without stordb

### ISSUE THREAD

**Issue by ksrigo** [cgrates/cgrates#1117]
Hi Dan,

As discussed here: https://groups.google.com/forum/#!topic/cgrates/4LSdfHcLkVg

It would be nice to be able to start cgrengine in some cases without the need to have a storDB.

thx again
srigo

**Comment by danbogos** [comment]
The elegant solution for this should be using map as DataDB/StorDB. This will also help running CGRateS without any kind of database dependency.
That functionality is traced in #1118 

DanB

**Comment by danbogos** [comment]
Hi Srigo,

@TeoV has implemented this functionality in master. You should be able to start storDB with type "*internal" now.

Please test it and report back if any issue.

Thanks,
DanB

**Comment by ksrigo** [comment]
Hi Dan,

Thanks for this feature. I tested it using this config:

`{

// Real-time Online/Offline Charging System (OCS) for Telecom & ISP environments
// Copyright (C) ITsysCOM GmbH

// Added by Srigo on 14/06/18

"general": {
	"default_request_type": "*rated",
	"logger":"*stdout",                                                                             // controls the destination of logs <*syslog|*stdout>
	"log_level": 7,
	"rounding_decimals": 5,
	"poster_attempts": 3,
	"default_category": "call",
	"default_tenant": "v.ibrowse.com",
	"default_timezone": "UTC",
},

"stor_db": {                                                         // database used to store offline tariff plans and CDRs
      "db_type": "*internal",                                             // stor database type to use: <mongo|mysql|postgres>
},

"data_db": {								// database used to store runtime data (eg: accounts, cdr stats)
 	"db_type": "redis",						// data_db type: <redis|mongo>
 	"db_host": "127.0.0.1",					// data_db host address
 	"db_port": 6379, 						// data_db port to reach the database
 	"db_name": "10", 						// data_db database name to connect to
 	"db_user": "cgrates", 					// username to use when connecting to data_db
 	"db_password": "", 						// password to use when connecting to data_db
 	"load_history_size": 10,				// Number of records in the load history
 },

"listen": {
 	"http": "0.0.0.0:2080",				// HTTP listening address
},

"http": {
	"json_rpc_url": "/jsonrpc"
},

"rals": {
	"enabled": true,
},

"cdrs": {
	"enabled": true,						// start the CDR Server service:  <true|false>
	"store_cdrs": false,
	"pubsubs_conns": [],					// address where to reach the pubusb service, empty to disable pubsub functionality: <""|*internal|x.y.z.y:1234>
 	"attributes_conns": [],					// address where to reach the attribute service, empty to disable attributes functionality: <""|*internal|x.y.z.y:1234>
 	"users_conns": [],						// address where to reach the user service, empty to disable user profile functionality: <""|*internal|x.y.z.y:1234>
 	"aliases_conns": [],					// address where to reach the aliases service, empty to disable aliases functionality: <""|*internal|x.y.z.y:1234>
 	"cdrstats_conns": [],					// address where to reach the cdrstats service, empty to disable cdrstats functionality: <""|*internal|x.y.z.y:1234>
 	"thresholds_conns": [],					// address where to reach the thresholds service, empty to disable thresholds functionality: <""|*internal|x.y.z.y:1234>
 	"stats_conns": [],						// address where to reach the stat service, empty to disable stats functionality: <""|*internal|x.y.z.y:1234>
 	"online_cdr_exports":[test_file_csv"]
},


"cdrstats": {
	"enabled": false,						// starts the cdrstats service: <true|false>
},


"cdre": {
	"test_file_csv": {
		"export_format": "*file_csv",
		"export_path": "/tmp/toto",
		"synchronous": false,
		"attempts": 1,
		"field_separator": ",",
		"cdr_filter": "",
		"cost_multiply_factor": 1,
		"usage_multiply_factor": {
			"*any": 1									// multiply usage based on ToR field or *any for all
  		},
  		"header_fields": [],
		"content_fields": [								// template of the exported content fields
			{"tag": "CGRID", "type": "*composed", "value": "CGRID", "field_id": "CGRID"},
			{"tag":"RunID", "type": "*composed", "value": "RunID", "field_id": "RunID"},
			{"tag":"TOR", "type": "*composed", "value": "ToR", "field_id": "ToR"},
			{"tag":"OriginID", "type": "*composed", "value": "OriginID", "field_id": "OriginID"},
			{"tag":"OriginHost", "type": "*composed", "value": "OriginHost", "field_id": "OriginHost"},
			{"tag":"RequestType", "type": "*composed", "value": "RequestType", "field_id": "RequestType"},
			{"tag":"Direction", "type": "*composed", "value": "Direction", "field_id": "Direction"},
			{"tag":"Tenant", "type": "*composed", "value": "Tenant", "field_id": "Tenant"},
			{"tag":"Category", "type": "*composed", "value": "Category", "field_id": "Category"},
			{"tag":"Account", "type": "*composed", "value": "Account", "field_id": "Account"},
			{"tag":"Subject", "type": "*composed", "value": "Subject", "field_id": "Subject"},
			{"tag":"Destination", "type": "*composed", "value": "Destination", "field_id": "Destination"},
			{"tag":"SetupTime", "type": "*composed", "value": "SetupTime", "layout": "2006-01-02T15:04:05Z07:00", "field_id": "SetupTime"},
			{"tag":"AnswerTime", "type": "*composed", "value": "AnswerTime", "layout": "2006-01-02T15:04:05Z07:00", "field_id": "AnswerTime"},
			{"tag":"Usage", "type": "*composed", "value": "Usage", "field_id": "Usage"},
			{"tag":"Cost", "type": "*composed", "value": "Cost", "field_id": "Cost"},
			{"tag":"Room", "type": "*composed", "value": "room"},
		],
	}
},


"pubsubs": {
	"enabled": false,				// starts PubSub service: <true|false>.
},


"aliases": {
	"enabled": false,				// starts PubSub service: <true|false>.
},


"users": {
	"enabled": false,				// starts User service: <true|false>.
	"indexes": ["Uuid"],			// user profile field indexes
},


"sessions": {
	"enabled": true,
},


}
`
It's working great.

Now I want to use this feature on my production server? Will you release  a debian package soon or do I need to use the one I compiled now? Please guide me.

thx a lots.

Srigo

**Comment by danbogos** [comment]
Hey Srigo,

The new package should be available.

Thanks for your tests!

DanB

**Comment by Ekotto** [comment]
Hi Dan,

I'm really new to Opensips and CGRateS but i sincerly wish to integrate both systems in their recent versions for my company.
i would really appreciate if you could please give me some guides on what to do please. 

Thanks for the achievements so far

**Comment by arberkatellari** [comment]
Hello @Ekotto ,
If you are new to CGRateS, the best way to start is to read the [docs](https://cgrates.readthedocs.io/en/latest/index.html) along with [opensips](https://www.opensips.org/Documentation/Manuals) in your case. If you have any specific questions, feel free to ask them in our community at [google groups](https://groups.google.com/forum/#!forum/cgrates) .

P.S. It's better for us if you ask questions in our google groups and leave github issues for issues. This way, our community can benefit from our support.

Kind regards,
Arber!
