### ISSUE TITLE
queue for posting CDRs

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#1119]
When using cdrs i get this error:
 cgrates CGRateS <9832c1c> [22853]: <HTTPPoster> Posting to URL, : net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)>

It would be nice to implement queue for this:)

tnx
miha

**Comment by anthonysomerset** [comment]
seconding this issue - bumped into this the hard way and was scratching my head as to why it was saying some fields were blank yet clearly they were there in the request

i found my issue being that processing multiple CDR files simultaneously seemed to be causing it

had to adjust my input script to drop one file at a time then sleep long enough to process the largest file for now

**Comment by danbogos** [comment]
hey @anthonysomerset 

Any chance you can send us data to reproduce your issue? You can mask sensitive data inside.

The most important is that we both get the same results when applying the same content in.

Thanks,
DanB

**Comment by anthonysomerset** [comment]
if you have a way i can securely and privately send you some CDR's then i don't mind sending the originals because some of the larger ones have 1500 records or more for the hour so sanitizing that sensitive data could be tricky :)

**Comment by danbogos** [comment]
You can maybe password protect them inside a .zip archive and mail them to me directly?

DanB

**Comment by TeoV** [comment]
Should be resolved when updated the library for XML.
