### ISSUE TITLE
duplicate cdrs and call cost issue with SessionTerminate

### ISSUE THREAD

**Issue by aqsyounas** [cgrates/cgrates#1120]
Greetings, 

I am getting couple of issues when I trying to use default value of **"channel_sync_interval":"7s"**  with freeswitch.

First: Below Error
(Error 1062: Duplicate entry '7bada0f80bb0dad9362233234ac9ee42b83278af-*raw-075b3444-f140-41f3' for key 'cdrrun')
[2018-06-26 20:24:53]
2018/06/26 20:24:53 CGRateS <5af2049> [ERROR] <CDRS> Storing primary CDR {"CGRID":"7bada0f80bb0dad9362233234ac9ee42b83278af","RunID":"*raw","OrderID":0,"OriginHost":"127.0.0.1:8021","Source":"freeswitch_json","OriginID":"075b3444-f140-41f3-a6ee-67823137de88","ToR":"*voice","RequestType":"*prepaid","Tenant":"cgrates.org","Category":"call","Account":"1001","Subject":"1001","Destination":"1002","SetupTime":"2018-06-26T20:23:40-04:00","AnswerTime":"2018-06-26T20:23:40-04:00","Usage":73000000000,"ExtraFields":{},"ExtraInfo":"","Partial":false,"PreRated":false,"CostSource":"","Cost":-1,"CostDetails":null}, got error: Error 1062: Duplicate entry '7bada0f80bb0dad9362233234ac9ee42b83278af-*raw-075b3444-f140-41f3' for key 'cdrrun'
2018/06/26 20:24:53 CGRateS <5af2049> [ERROR] <CDRS> Errors when storing CDR entry: Error 1062: Duplicate entry '7bada0f80bb0dad9362233234ac9ee42b83278af-*raw-075b3444-f140-41f3' for key 'cdrrun'
2018/06/26 20:24:53 CGRateS <5af2049> [ERROR] <SessionS> SessionTerminate with no active sessions for cgrID: <7bada0f80bb0dad9362233234ac9ee42b83278af>
2018/06/26 20:24:53 CGRateS <5af2049> [ERROR] <FreeSWITCHAgent> Could not terminate session with event 075b3444-f140-41f3-a6ee-67823137de88, error: RALS_ERROR:SESSION_NOT_FOUND

Second: 
My call was incorrectly debited. Account was charged for the first minute when I have Rates.csv defined like below no matter how long the call was. 

#Id,ConnectFee,Rate,RateUnit,RateIncrement,GroupIntervalStart
RT_1CNT,0,1,60s,60s,0s

 i.e, when call lasted more than 3 minutes and less than 4 minute account was debited with 1 cent. But It should debit for 4 cents.
Look like cgrates was inserting cdr upon call answer with *default having cast 1 but was not updating it when call was hangup so call cost was always 1. 
 
According the @DanB this is new feature and was added few days back and should work fine.
cgrates.json file
[when_channel_sync_interval_was_7s_cgrates_json.txt](https://github.com/cgrates/cgrates/files/2141179/when_channel_sync_interval_was_7s_cgrates_json.txt)

Communication between session and cdrs
https://pastebin.com/uucS6ktN

cgrates startup logs and also the logs during the call start and end. 
https://pastebin.com/v7CeGeTS

As suggested by @DanB setting  https://github.com/cgrates/cgrates/blob/master/data/tutorials/fs_evsock/cgrates/etc/cgrates/cgrates.json#L84 to 0(zero) did resolve above errors for me. 

root@debian:/etc/cgrates# cgr-engine -version
CGRateS 0.9.1~rc8 git+00b64cc (2018-06-26T18:24:32+02:00)

Please let me know if you guys need anything further. Will love to help. 

Best Regards,

**Comment by TeoV** [comment]
Hi aqsyounas,
It would be very helpful if you can capture traffic between CGRateS and FreeSWITCH on port 8021 and sessions and cdrs on port 2012 after you add "channel_sync_interval":"7s".

Thanks
TeoV

**Comment by aqsyounas** [comment]
Here you go. 
Between Session and Cdrs:
https://pastebin.com/QMYHVj7w
Between Freeswitch and Cgrates:
https://pastebin.com/feBCuwYa

Please let me know if you need anything further. 

Thanks.

**Comment by TeoV** [comment]
Hi aqsyounas,
We found the problem. We think that the problem is the version of FreeSWITCH. 
Just from curiosity can you tell me what version of FreeSWITCH are you using? 
This is mine. 
freeswitch@teo> version
FreeSWITCH Version 1.6.20-37-987c9b9~64bit (-37-987c9b9 64bit)

Thanks,
TeoV

**Comment by aqsyounas** [comment]
I am using the same version. 
freeswitch@debian> version
FreeSWITCH Version 1.6.20-37-987c9b9~64bit (-37-987c9b9 64bit)

Thanks

**Comment by aqsyounas** [comment]
Just further info. 

When I have **"channel_sync_interval":"7s"** active_sessions gives an error. 
cgr> active_sessions
Error executing command: NOT_FOUND

But when I disable it(set it to 0(zero)). I can successfully execute active_sessions command. 
cgr> active_sessions
[
 {
  "CGRID": "894de43b208ea62b072a07420420e195fbd4cc81",
  "TOR": "*voice",
  "OriginID": "5d40516f-b03b-46ae-bdf2-907cb44e7a52",
  "CdrHost": "127.0.0.1:8021",
  "CdrSource": "*sessions",
  "ReqType": "*prepaid",
  "Tenant": "cgrates.org",
  "Category": "call",
  "Account": "1001",
  "Subject": "1001",
  "Destination": "1002",
  "SetupTime": "2018-06-26T23:28:41-04:00",
  "AnswerTime": "2018-06-26T23:28:42-04:00",
  "Usage": 5000000000,
  "ExtraFields": {
   "ACD": "0s",
   "Direction": "*out",
   "DisconnectCause": "",
   "FsConnID": "38c2c5de-d202-4f84-ae86-32c4bdf0c6ea",
   "PDD": "0s",
   "Supplier": ""
  },
  "SMId": "CGR-DA",
  "SMConnId": "",
  "RunID": "*default",
  "LoopIndex": 1,
  "DurationIndex": 60000000000,
  "MaxRate": 0,
  "MaxRateUnit": 0,
  "MaxCostSoFar": 1
 }
]

Could you tell me what might be issue with my Freeswitch?
I think events should be same. 
Thanks, 
Aqs

**Comment by TeoV** [comment]
Hi aqsyounas,
That's interesting. If you compare my capture with yours,  you will see that these are quite different.
https://pastebin.com/Xc4cK6Tv

T 2018/06/26 21:53:24.705087 127.0.0.1:50391 -> 127.0.0.1:8021 [AP]
api show channels
#
T 2018/06/26 21:53:24.705555 127.0.0.1:8021 -> 127.0.0.1:50391 [AP]
uuid,direction,created,created_epoch,name,state,cid_name,cid_num,ip_addr,dest,application,application_data,dialplan,context,read_codec,read_rate,read_bit_rate,write_codec,write_rate,write_bit_rate,secure,hostname,presence_id,presence_data,accountcode,callstate,callee_name,callee_num,callee_direction,**_call_uuid_**,sent_callee_name,sent_callee_num,initial_cid_name,initial_cid_num,initial_ip_addr,initial_dest,initial_dialplan,initial_context
28de90b7-9073-4920-987e-b6b1b5b9f94e,inbound,2018-06-26 21:53:21,1530064401,sofia/internal/1001@192.168.0.113,CS_EXECUTE,1001,1001,192.168.0.112,1002,playback,/opt/song.mp3,XML,default,PCMU,8000,64000,PCMU,8000,64000,,debian,1001@192.168.0.113,,1001,ACTIVE,,,,,,,1001,1001,192.168.0.112,1002,XML,default

In simple term call_uuid is empty and we take info from there from OriginID
https://github.com/cgrates/cgrates/blob/master/agents/fsagent.go#L400

The problem is now fixed .
Please update from master, after Dan accept the PR, rebuild CGRateS and test it.
After you test it, please confirm that everything are ok and close the issue.

Thanks
TeoV

**Comment by aqsyounas** [comment]
I think i know what went wrong. Actually, i was not bridging the call(call was not hitting other phone:1002) but media was being played instead of bridge at the local machine.  

Thinking it was not necessary to bridge(call) to other device. One might play media at the destination number on the server. Like call just hits my server and at desired destination number(1002 in above case). I just to play some IVR at destination numbers but still want to charge. So, it is basically one leg call. 

One leg call:
https://pastebin.com/tMhuzhy4

But if I use bridge dialplan like below. 
Two leg call. 
https://pastebin.com/uia8iJf8

So, i think **"api show channels"** is not the right way to sync calls. Because for bridged call it shows two channels(one inbound and other outbound for same one call) containing call_uuid. 

But for single call(on which user just want to play media) it show one channel with empty call_uuid.

I think it would be better if you use **"show calls"** and monitor **"uuid"** variable because it will show in both calls(one leg call and two leg call).

I highly appreciate the efforts you guys put into this. 

Best Regards, 
Aqs

**Comment by danbogos** [comment]
Hey Aqs,

Do u see anything wrong in show channels and monitoring uuid instead?

DanB

**Comment by aqsyounas** [comment]
That is fine too. :) 
"show calls" is just a bit simple(less data) nothing else. 

I will install the cgrates again on fresh machine once build is available. I will test it and report back. 
If everything is good. I will close this issue. 

Have a good day/evening. 

Thank You very much.

**Comment by danbogos** [comment]
Hey Aqs,

Please retest, I have rebuild the package for you.

Thanks,
DanB

**Comment by danbogos** [comment]
Hey Aqs,

Yes, since CGRateS bill the channel, it should work fine with the call terminating in FreeSWITCH and not being bridged outside.

DanB

PS: We will continue digging.

**Comment by TeoV** [comment]
Hey Aqs,
How did the update go?
If you can please post the version of CGRateS (cgr-engine -version)

Thanks,
TeoV

**Comment by TeoV** [comment]
Hey Aqs,
The problem is now fixed.
After you test it, please confirm that everything is ok and close the issue.

Thanks
TeoV

**Comment by aqsyounas** [comment]
Superb, Just tested it and issue is gone. :)
I will close it in few hours after further test.

Thank You very much. 
Aqs.

**Comment by aqsyounas** [comment]
ok Everything looks good. Closing it now. 

Thank You for such a awesome Software. 
Aqs
