### ISSUE TITLE
Stop indexing for *default:*any:*any filters

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1127]
Hello Dear CGRateS Team !
Following our troubleshooting session with Dan, we found that, all *lt or *gt like filters are indexed as *default:*any:*any. This causes the same index to grow fast which renders the service unstable and not really valid for production.
Please add an option in the configuration to enable *string to present as mandatory field for indexing an stop indexing to *default:*any:*any in case this option is enabled.

Thanks,
Michael

**Comment by TeoV** [comment]
Hi Michael,
Now we index only *string and *prefix and items who don't have a filter (*none).
Also, we have added an option in filter config => indexed_selected (https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L151).

Thanks,
TeoV
