### ISSUE TITLE
Feature request: Remove objects from dataDB

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1146]
Hello Dear CGRateS Team!
Instead of flushing db, or the new remove option of the cgr-loader, we would like to have more granular way of removing objects. Specified by their type, perhaps with some kind of filter.
For example, removing all thresholds, stats, and filters , leaving other stuff inside.
I see that, one could go and delete a corresponding namespace in datadb, but that seems wrong approach.

Other example would be , is to remove all thresholds where ID starts with "123123123_THD_TEST_".
That one, might come in handy for the feature requested here [#1061](https://github.com/cgrates/cgrates/issues/1061).
Just following some simple naming strategy , and using an Account as a pefix for object IDs , can be used later to remove all the relevant objects, when need to remove an Account and it's data in all the modules arise.

Thanks,
Michael

**Comment by Trial97** [comment]
Hi @muxalko,

More than -remove flag is not achievable in cgr-loader.
The best option is to open separate feature requests for each remove API.

Thanks,
Trial97
