### ISSUE TITLE
GetMaxUsage and InitiateSession not setting max_dialog time in OpenSips

### ISSUE THREAD

**Issue by stevehillin** [cgrates/cgrates#1150]
When using OpenSips with CGRates, OpenSips expects a return value from InitiateSession that OpenSips will use to set max_dialog timeout.  While GetMaxUsage is returning a correct value, InitiateSession is returning '-1', so OpenSips uses it's default timeout.

T 2018/07/13 09:43:42.026713 <OpenSips>:50636 -> <CGRates>:2012 [AP]
{ "method": "SMGenericV1.GetMaxUsage", "id": 804063321, "params": [ { "RequestType": "*pseudoprepaid", "Category": "OUTBOUND", "Destination": "<number>", "Account": "5181", "OriginID": "62571ac5042d5d3812b243f77b69d9f9@<PBX IP>:5060", "SetupTime": "1531493022" } ] }
#
T 2018/07/13 09:43:42.033686 <CGRates>:2012 -> <OpenSips>:50636 [AP]
{"id":804063321,"result":30000,"error":null}

##
T 2018/07/13 09:43:52.124112 <OpenSips>:57315 -> <CGRates>:2012 [AP]
{ "method": "SMGenericV1.InitiateSession", "id": 1489157879, "params": [ { "RequestType": "*pseudoprepaid", "Category": "OUTBOUND", "Destination": "<number>", "Account": "5181", "OriginID": "62571ac5042d5d3812b243f77b69d9f9@<PBX IP>:5060", "DialogID": 2025337485, "DialogEntry": 2239, "SetupTime": "1531493022", "AnswerTime": "1531493032" } ] }
#
T 2018/07/13 09:43:52.126962 <CGRates>:2012 -> <OpenSips>:57315 [AP]
{"id":1489157879,"result":-1,"error":null}

**Comment by danbogos** [comment]
Hey Steve,

Sorry for the delay, quite some prios and vacation time here ;).
This feature should be available in master as well as the latest package you can get from http://cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb.

Please let me know if any issues.

Thanks,
DanB

**Comment by danbogos** [comment]
Hey Steve,

Was wondering if you managed to test the fix?

Thanks,
DanB
