### ISSUE TITLE
Pubsub disable 

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1152]
Hello Dear CGRateS Team!
For some reason, cgr-engine wouldn't start when disabling the pubsub, even though, there are no reference to it in any modules.

Sending my configs in private.
Thanks,
Michael

**Comment by danbogos** [comment]
hey Michael,

For some reason I cannot figure out where you sent the configs for replicating the issue with PubSub. Can you please send them again (or better, open an issue in private repo and attach them there).

Thanks,
Dan

**Comment by TeoV** [comment]
Stale issue.
