### ISSUE TITLE
timings: same destination prefix with different tags makes CGRateS crash

### ISSUE THREAD

**Issue by cruzccl** [cgrates/cgrates#1153]
Hi CGRateS team,

We are having some issues when using timings to assign different rates to calls depending on the time they are established. We are not sure if we are using CGRateS incorrectly or if this may be a bug.

We have this minimal configuration running in CGRateS (version e3083471):

- Destinations.csv:
```
DST_34,+34
DST_34_DUP,+34
```
Same prefix, different tag, but fulfilling [database unique](https://github.com/cgrates/cgrates/blob/d829b17745e511001a6fae26f1919096bcace2f3/data/storage/mysql/create_tariffplan_tables.sql#L35). The reason behind this prefix duplication was a design decision we made for making CGRateS integration easier. We haven't experienced any problem until now.

- Rates.csv:
```
RT_10CNT,0.2,0.1,60s,60s,0s
RT_20CNT,0.4,0.2,60s,60s,0s
```
2 different rates.

- DestinationRates.csv:
```
DR_34_10CNT,DST_34,RT_10CNT,*up,4,0,
DR_34_DUP_20CNT,DST_34_DUP,RT_20CNT,*up,4,0,
```
2 different destination-rates to relate previous items.

- Timings.csv:
```
AFTERNOON,*any,*any,*any,*any,12:00:00
```
1 timing for calls after 12:00.

- RatingPlans.csv:
```
RP_GENERIC,DR_34_10CNT,*any,10
RP_GENERIC,DR_34_DUP_20CNT,AFTERNOON,20
```
One rating plan to achieve this:
- Calls to +34 prefix before 12:00, get rated by RT_10CNT (through DR_34_10CNT).
- Calls to +34 prefix after 12:00, get rated by RT_20CNT (through DR_34_DUP_20CNT).

- RatingProfiles.csv:
```
*out,cgrates.org,call,*any,2014-01-14T00:00:00Z,RP_GENERIC,,
```
One rating profile using previous rating plan.

- AccounActions.csv:
```
cgrates.org,1001,,,,
```
One account/subject in default tenant.

With this config, invoking this command causes segfault:
```
cgr-console 'cost Tenant="cgrates.org" Subject="1001" Category="call" AnswerTime="2015-03-10T08:00:00Z" Destination="+34676000000" Usage="60s"'
```

The reason behind this segfault seems to be in [GetRatingPlansForPrefix](https://github.com/cgrates/cgrates/blob/2f7b77f3a14d2f3b4c4e3a06f9f9a4abf4301e0f/engine/ratingprofile.go#L154):
- It detects two different destination tags, so it does not consider them 2 complementary destination-rates and evaluates them separately ordered by weight (the higher, first).

- That causes DR_34_DUP_20CNT been selected first, that is not capable to rate a call made at 8:00 and causes the crash.

Using two different destination tags with the same destination prefix is not supported and [database unique](https://github.com/cgrates/cgrates/blob/d829b17745e511001a6fae26f1919096bcace2f3/data/storage/mysql/create_tariffplan_tables.sql#L35) should be updated to avoid this or timings logic needs a patch to support them?

Sorry for the length of the issue and thank you very much for your time and your awesome project :)

**Comment by danbogos** [comment]
Hey @cruzccl ,

Thanks for nice words on project.

The issue you are seeing is due to the fact that we match destination before time. 
Due to that, you should have each destination covered in complete timing (either *any  or duplicated with different start time).
In order to fix your issue try adding something like:
`RP_GENERIC,DR_34_DUP_20CNT,*any,10`
Not sure I understand why would you duplicate your destination but if you think it works for you, I have no conceptual issue with that. The only thing which CGRateS expects is that you define them in the way it expects.

Hope this helps.

DanB

**Comment by cruzccl** [comment]
Hi @danbogos,

I know it is quite weird to have same prefixes with diferent destination tags, but that made CGRateS integration easier in our project and didn't cause any trouble until we have tried to add timing support.

We always load data with _cgr-loader -validate_ flag and I have read the code in ratingplan.go that verified that RatingPlans were continuous ([function isContinous](https://github.com/cgrates/cgrates/blob/2f33e0bd6dff2167fbc865471ef34f34916d90f8/engine/ratingplan.go#L100)).

This function verifies this continuity mixing all the timings of all destination-rates involved in a rating plan, instead of verifying each destination-rate on its own.

I have modified this function ([you can see it here](https://gist.github.com/cruzccl/361add4e53e14beb7d422a77b76accfa#file-ratingplan-go-iscontinous)) so that a configuration (like mine) that would lead to a runtime-crash will be warned if the data is loaded with _-validate_ flag.

I can create a PR is you think that I have not misunderstood anything.

Thank you and regards,

**Comment by danbogos** [comment]
hey  @cruzccl 

Thanks, that function was left behind, war more like a plan than reality, so I cannot say much about using it or not since we are not for the moment. I can check your changes next week when I will be back in the office.

On the other hand, did u get a chance to test the changes I was recommending?

Ta,
DanB

**Comment by cruzccl** [comment]
Hi @danbogos,

Yes, with your suggested configuration you avoid the crash, but adding an additional _*any_ timing line for every different destination-rate in a rating plan shouldn't be always necessary, IMHO.

Imagine this configuration:

**DestinationRates:**
```
DR_CHEAP,DST_34,RT_10CNT,*up,4,0,
DR_EXPENSIVE,DST_34,RT_20CNT,*up,4,0,
```
**RatingPlan:**
```
RP_GENERIC,DR_EXPENSIVE,*any,20
RP_GENERIC,DR_CHEAP,AFTERNOON,30
```

**Timings:**
```
AFTERNOON,*any,*any,*any,*any,12:00:00
```

2 different but complementary destination-rates:

- Calls to DST_34 before 12:00 will be rated using DR_EXPENSIVE.
- Calls to DST_34 after 12:00 will be rated using DR_CHEAP.

Adding an additional line to RatingPlan with _*any_ timing would be possible, achieving the same results as long as weight is configured correctly:

**RatingPlan:**
```
RP_GENERIC,DR_EXPENSIVE,*any,20
RP_GENERIC,DR_CHEAP,AFTERNOON,30
RP_GENERIC,DR_CHEAP,*any,10
```

But that additional entry, IMHO, should not be necessary (and is quite misleading). In fact, in this case is not necessary as both DR_EXPENSIVE and DR_CHEAP define rate for just one (and common) destination (DST_34), but could be otherwise if DestinationRates was like these:

```
DR_CHEAP,DST_34,RT_10CNT,*up,4,0,
DR_EXPENSIVE,DST_34,RT_20CNT,*up,4,0,
DR_CHEAP,DST_35,RT_10CNT,*up,4,0,
``` 

That additional line would make CGRateS crash if a call to DST_35 is rated before noon.

To sum up:

- Different destination-rates can be complementary if they define rates for the same destinations.
- In those cases, adding an additional _*any_ line for each destination-rates is not necessary, only one of need would be enough.
- Current _isContinous_ function returns true whenever a _*any_ timing entry is found for any of the destination-rates involved, without checking if destination-rates are complementary.
- That logic may be changed to evaluate all destinations involved separately: if a destination cannot be rated all the time (all the weekdays, all times), it will warn. This will prevent runtime crashes warning about configurations with non-complementary destination-rates without the mandatory _*any_ line.


I send a PR with the changes I suggest, that just prevents those runtime errors if cgr-loader is called with _-validate_ flag.

Thank you very much for your time and sorry for the note length.

Regards,

**Comment by danbogos** [comment]
hey @cruzccl 

As explained in PR we need to stick to the idea of continuous destination cost definition. The issue you are facing started from a wrong design of your destination rates (duplicating them), hence it is hard for us to fix that since it does not fit the way we have designed rates from beginning.
As written in PR reply, our rating is pretty well tested and we don't want to risk affecting it's stability by inserting such changes in concepts. Will start working on a new rating hopefully in autumn and we could add this idea there.

Sorry for any inconvenience on your side.

DanB
