### ISSUE TITLE
cdr_stats: ASR metric stuck on 100%

### ISSUE THREAD

**Issue by cruzccl** [cgrates/cgrates#1165]
Hi CGRateS team,

I am having the same issue reported [here](https://groups.google.com/forum/#!topic/cgrates/v87ohArS_Fc) back in 2016. I have read the thread multiple times, but I don't understand where exactly I should not use AnswerTime.

I am using Kamailio evapi connector with CGR_AUTH_REQUEST, CGR_CALL_START and CGR_CALL_END events for established calls. For failed calls, CGrateS only receives CGR_AUTH_REQUEST and those calls do not seem to traverse CDR and CDR-STAT logic, so ASR is not decremented.

Should I notify CGrateS that the call it has CGR_AUTH_REQUEST-ed has failed? If so, which event should I use? Am I missing something? :thinking: 

Thank you very much and regards,

**Comment by danbogos** [comment]
Hey Carlos,

We have deprecated cdr_stats in favor of stats. Please try that and report
here if still issues.

Dan

Carlos Cruz Luengo <notifications@github.com> schrieb am Mi., 1. Aug. 2018,
12:16:

**Comment by cruzccl** [comment]
Hi @danbogos,

We are currently running a patched version of CGRateS based on version e3083471 and we would need some work to adapt those patches for the newest CGRateS version with all the recent changes related to stats. We have postponed that upgrade work for our next major release.

We only need basic ASR/ACD stats per carrier, is it not possible to achieve basic ASR with _old_ cdr_stats and Kamailio-evapi connector?

Our current implementation is:

- _tp_cdr_stats_ table:
```
tag,queue_length,metrics,subjects
cr1,0,ASR,cr1
cr1,0,ACD,cr1
```
Remaining fields, empty ('').

- _tp_rating_profiles.cdr_stat_queue_ids_ for used rating profile has 'cr1' value.

- _cgrates.json_ is updated too, enabling internal cdrstats.


With that configuration ACD value is updated accordingly for every established call, but ASR value is always 100. Debugging the code I see that the logic to generate cdr_stat entry is not traversed for failed calls.


I don't want to make you waste your time asking about a deprecated stuff, but I would highly appreciate if you could tell me whether ASR with Kamailio is not possible or if I am just missing some configuration point.


Thank you very much for your time.

Regards,

**Comment by danbogos** [comment]
Hi Carlos,

Try enforcing AnswerTime for your calls.

DanB

Carlos Cruz Luengo <notifications@github.com> schrieb am Mi., 1. Aug. 2018,
16:28:

**Comment by danbogos** [comment]
Carlos,

Sorry, I was on the way, that is the reason of short answers. 
In order not to have  ASR as successful (non answered calls) you should put AnswerTime as zero value (0001-01-01 00:00:00 +0000 UTC) or do not define it at all.

Hope this time helps you more.

DanB

**Comment by danbogos** [comment]
hey @cruzccl 

You can call SessionSv1.ProcessCDR API instead (for a failed call). You can then add any parameter you want.

DanB

**Comment by cruzccl** [comment]
Hi @danbogos,

Thanks for the idea. I tried with _CdrsV1.ProcessExternalCDR_ but everything ends in the same point: no CDR are generated for zero or non-existing AnswerTime calls and no ASR is calculated for them.

I have finally made a _temporary_ workaround:

- Call to CGR_CALL_END in _dialog:failed_ Kamailio route.

- Set cgr_answertime equal to cgr_setuptime.

- Set cgr_duration to 0.

This way failed call establishments generate same CDR entries than established calls, but with 0 duration (and 0 cost/price) and answerTime==setupTime.

To get ASR value updated for this kind of CDR entries, I have patched engine/stats_metrics.go file so that
```
!cdr.AnswerTime.IsZero()
```
comprobation is changed to
```
!(cdr.Usage == 0 && cdr.SetupTime == cdr.AnswerTime)
```

With this (temporary!) workaround ASR is updated accordingly and I finally get correct values for all my carriers :)

Thank you very much for you help, you can close this issue.

Regards,
