### ISSUE TITLE
GetAttributeProfileIds API is missing

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1166]
Hello Dear CGRateS Team!,

It would be nice to have GetAttributeProfileIds API method for retrieving all the AttributeProfiles.

Thanks,
Michael

**Comment by TeoV** [comment]
Hi Michael,
We have implemented it.
Please update from master and test it .

Thanks,
TeoV

**Comment by muxalko** [comment]
Working !
Thanks.
