### ISSUE TITLE
The action is not triggered on EventType:BalanceUpdate defined in Thresholds/Filters

### ISSUE THREAD

**Issue by tstrg** [cgrates/cgrates#1172]
The goal is to configure actions based on account BalanceUpdate. 

**How to reproduce the issue:**

Adjust the tutorial CSVs (https://github.com/cgrates/cgrates/tree/master/data/tariffplans/tutorial) in the following way:

**Filters.csv**
```
#Tenant[0],ID[1],FilterType[2],FilterFieldName[3],FilterFieldValues[4],ActivationInterval[5]
cgrates.org,FLTR_ACNT_BALANCE,*string,EventType,BalanceUpdate,2014-07-29T15:00:00Z
```

**Thresholds.csv**
```
#Tenant[0],Id[1],FilterIDs[2],ActivationInterval[3],MaxHits[4],MinHits[5],MinSleep[6],Blocker[7],Weight[8],ActionIDs[9],Async[10]
cgrates.org,THD_ACNT_BALANCE,FLTR_ACNT_BALANCE,2014-07-29T15:00:00Z,-1,1,1s,false,10,ACT_LOG_WARNING,false

```

**Load tariff plan and call AddBalance via API**

Request:
```
{
  "method":"ApierV1.AddBalance",
  "params":[
    {
"Tenant":"cgrates.org",
"Account":"1002",
      "BalanceType":"*monetary",
      "Value":0.1,
      "ExpiryTime":"",
      "RatingSubject":"",
      "DestinationId":"",
      "Weight":666,
      "SharedGroup":"",
      "Overwrite":false,
      "BalanceId":"data"
    }],
  "id":0
}
```

Ngrep result:
```
gives me the ngrep result:
root@841b62cecdc1:/# ngrep -t -W byline port 2012 -d lo
interface: lo (127.0.0.0/255.0.0.0)
filter: (ip or ip6) and ( port 2012 )
#
T 2018/08/12 13:01:00.200483 127.0.0.1:55796 -> 127.0.0.1:2012 [AP]
{"method":"PubSubV1.Publish","params":[{"ActionIds":"","EventName":"ACTION_TRIGGER_FIRED","Id":"","Uuid":""}],"id":267}

#
T 2018/08/12 13:01:00.200708 127.0.0.1:2012 -> 127.0.0.1:55796 [AP]
{"id":267,"result":"OK","error":null}
```

**Expected behavior:**
Correct matching with the filter FLTR_ACNT_BALANCE should trigger ActionId ACT_LOG_WARNING.

**CGRageS version:**
CGRateS 0.9.1~rc8 git+834f130 (2018-07-09T19:25:00+02:00)

**Link to the original topic:**
https://groups.google.com/forum/?nomobile=true#!topic/cgrates/PSEDI35I0yg

**Comment by tstrg** [comment]
The 1st contribution to the topic contains the used **config.json**
https://groups.google.com/forum/?nomobile=true#!topic/cgrates/PSEDI35I0yg

**Comment by TeoV** [comment]
Hi tstrg,
An observation for threshold : instead of async false change it to true something like this: 
```
#Tenant[0],Id[1],FilterIDs[2],ActivationInterval[3],MaxHits[4],MinHits[5],MinSleep[6],Blocker[7],Weight[8],ActionIDs[9],Async[10]
cgrates.org,THD_ACNT_BALANCE,FLTR_ACNT_BALANCE,2014-07-29T15:00:00Z,-1,1,1s,false,10,ACT_LOG_WARNING,true
```
Please test it.

Thanks
TeoV

**Comment by TeoV** [comment]
Hi @tstrg 
The package is ready :) 

Thanks,
TeoV

**Comment by TeoV** [comment]
Hi @tstrg 
If ProcessEvent is triggered then it is not part of this issue anymore.
Let's continue the discussion on google group so others can benefit out of the solution.

Thanks,
TeoV
