### ISSUE TITLE
Rounding issue in CDRs

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#118]
Hello,

I have created a set of rates for Canada to bill in 30 / 6 increments as below. 

Tag	|  ConnectFee	|  Rate  |  RateUnit  |  RateIncrement  |  GroupIntervalStart
------ |  ----------------  | -------  |  ------------  | --------------------  |  -------------------------
RT_Canada  |  0  |  0.006  |  60  |  30  |  0s
RT_Canada  |  0  |  0.006  |  60  |   6  |  30s

I seem to have an issue where the CDR Cost Details are being calculated incorrectly as details in the test calls as follows:

1) A call with duration of 32 secs which should have been billed at 0.003 for the first 30 secs then the next 2 secs should have been rounded up to 6 secs and billed at (0.006 / 10) * 1 (6 sec block) which would be 0.0006 and the total being 0.003 + 0.0006 = 0.0036.

2) A call with duration of 57 secs which should have billed for the full 60 secs at 0.006 since we are rounding up to 6 secs but instead it only billed the call at the cost of 0.003 which is only 30 secs.

3) Another call with duration of 75 secs which should have been billed at a cost of 60 secs (0.006) + 3 x 6 secs blocks at 0.0006 (0.0018) giving a total cost of the call 0.006 + 0.0018 = 0.0078 but instead the call was billed incorrectly at 0.006 only charging for one minute.

I can confirm that the correct amount is being deducted from the monetary balance but the CDR Cost Details are incorrect.

-rwxr-xr-x 1 root   root    14582192 Jul  9 11:00 cgr-engine
OS: Debian Wheezy
StorDB: Postgres 9.4.x

Best regards,

Errol

**Comment by ewsamuels** [comment]
Just to update the ticket, I did some testing with Postpaid accounts with DanB on IRC and the Postpaid accounts seem to work fine.  So the issue seems to be Prepaid for sure.

**Comment by rif** [comment]
Just pushed a possible fix for this issue.
Please test and post back your results.

-rif

**Comment by ewsamuels** [comment]
Hi rif,
You would need to generate the debian package for me.

Thanks

**Comment by rif** [comment]
Package generated.

**Comment by ewsamuels** [comment]
Hi rif,
Just tested and it seems the issue still remains.

For Postpaid calls there is no issue as per my last response.  However, with Prepaid calls the issue remains but looking at the TimeSpans for the CostDetails for the Prepaid call I can see only 1 TimeSpan rather than 2 as in the Postpaid CDR.  This might be helpful.

Regards,

Errol

**Comment by ewsamuels** [comment]
Hi rif, I can confirm that this issue has been fixed.
