### ISSUE TITLE
Incorrect stats in exported CDRs (nondeterministic)

### ISSUE THREAD

**Issue by chrisgis333** [cgrates/cgrates#1197]
When exporting CDRs via ExportCDRs function sometime statistics are not correctly computed.

It can be also seen in unit tests sometime:
--- FAIL: TestWriteCdrs (0.00s)
    cdrefwv_test.go:257: Unexpected total cost in the stats: 3.65001
    cdrefwv_test.go:260: Unexpected FirstOrderId 3
    cdrefwv_test.go:266: Unexpected TotalCost:  3.65001

**Comment by TeoV** [comment]
Hi @chrisgis333 
Can you please give some example of CDRs and what stats aren't correctly computed.

Thanks,
TeoV

**Comment by chrisgis333** [comment]
I found where bug is.
Will make pull request soon
