### ISSUE TITLE
Incorrect Usage storage and subsequent incorrect rating

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#1208]
this effectively is related to https://groups.google.com/forum/#!topic/cgrates/PzheNqY6W1Q

we are processing XML CDR's from Metaswitch which stores the timestamps as EPOCH/UNIX to ms resolution

we are correctly calculating the usage from the relevant fields (subtract connect from disconnect times) however it appears that it is being stored in the database as a raw seconds value rather than a nanoseconds value as alluded to in the other post
, 
i believe this is why the rating is failing to charge for more than 1 second of usage in our model of per second billing because its thinking every call is less than 1 second long, not sure if this is specific to the XML engine or not

**Comment by TeoV** [comment]
Hi @anthonysomerset 
Please add a sample and template.

Thanks,
TeoV
