### ISSUE TITLE
Add SetTPLcrRules API

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#123]
Hello DanB,

As per our discussion there is no API for setting and Activating LcrRules.  If you can add these it would be great.

Regards,
Errol

**Comment by ewsamuels** [comment]
Hi DanB,
I forgot to mention that there is no LoadLcrRules or RemLcrRules either.

Thanks
Errol

**Comment by rif** [comment]
Is this still an issue?

**Comment by ewsamuels** [comment]
Yes yes this is still an issue, I am getting this error "MANDATORY_IE_MISSING:[LcrRulesId]"}" but not sure what the LcrRulesId is because there is no mention of it in the documentation.

curl -X POST -H "Content-Type: application/json" -d '{"method": "ApierV1.SetTPLcrRules","params": [{"Category": "Priority", "Direction": "*out", "TPid": "Priority", "Rules": {"RPCategory": "Priority", "Weight": 10, "Strategy": "*static", "DestinationId": "*any", "ActivationTime": "2015-09-18T11:40:54Z", "StrategyParams": "voxbeam_premium;thinq_premium;highside_premium"}, "Account": "*any", "Tenant": "demo.cgrates.org", "Subject": "*any"}]}' http://localhost:2080/jsonrpc

{"id":null,"result":null,"error":"MANDATORY_IE_MISSING:[LcrRulesId]"}

**Comment by rif** [comment]
should be something like lcr.Direction:lcr.Tenant:lcr.Category:lcr.Account:lcr.Subject

**Comment by rif** [comment]
looking in master code there is no LcrRulesId for SetTPLcrRules, you must be using some old code

**Comment by rif** [comment]
I am wrong, it is mandatory, we just have to take it out

**Comment by ewsamuels** [comment]
I am using the Debian package from the 14th Sept!

**Comment by danbogos** [comment]
Hi Errol,

Please retest with the latest code.

Thanks,
Dan

**Comment by danbogos** [comment]
No follow-up since more than a week, will close the ticket, so feel free to open a new one if required.

DanB
