### ISSUE TITLE
Feature request: Environment variables in configs

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1237]
Hello Dear CGRateS Team!

That would be nice to have the ability to use environment variables inside configs.

Thanks,
Michael

**Comment by ghenry** [comment]
Hi Michael,
Would this be for use with things like Docker?
Thanks.

**Comment by ghenry** [comment]
Having a play after getting my cgrates build env all set up. Are you thinking something like:

"data_db": {
    "db_type": "redis",
    "db_host": "my-redis-host.com",
    "db_port": 6379,
    "db_name": "10",
    "db_password": "$DB_PASSWORD",
    "redis_sentinel": "$REDIS_SENTINEL"
  },

i.e. $config_key_word_in_upper_case then we just os.Getenv("DB_PASSWORD") etc.

**Comment by ghenry** [comment]
Or do you want the env vars to replace what ever is loaded from config, i.e. the cgrates.json has things set and you override it via export DB_PASSWORD=blah so you have a hardcoded default that you control in **your** config file?

**Comment by ghenry** [comment]
Actually the later option would be best (just in the ENV to override cgrates.json) like everyone else does:

https://github.com/killbill/killbill-cloud/tree/master/docker#environment-variables

so in our example you'd do something like:

export CGRATES_DATA_DB_DB_PASSWORD=blah

**Comment by muxalko** [comment]
Hello Henry!

I am not sure I completely understand the second option you mentioned: ".. env vars to replace what ever is loaded from config.."
 Did you mean, it will be hard coded to read values from env var if exists ?

I want to use this in docker/k8s environment, but what difference does that make ?
If I understand correctly, from cgr perspective it's just to read env var, disregarding, whether it is a real server or a container.

For me, the example of KillBill is exactly what I want to achieve, and it seems to me more like the [first](https://github.com/cgrates/cgrates/issues/1237#issuecomment-427148378) option.
for instance:

my docker has the following env variables defined :
```
"Env": [
                "REDIS_REPLICATION_MODE=master",
                "REDIS_PASSWORD=xxxx",
                "REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL",
                "REDIS_MASTER_SERVICE_PORT_REDIS=6379",
                "KUBERNETES_PORT=tcp://10.43.0.1:443",
                "KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443",
                "REDIS_SLAVE_SERVICE_PORT=6379",
                "REDIS_SLAVE_SERVICE_PORT_REDIS=6379",
                "REDIS_MASTER_PORT=tcp://10.43.199.253:6379",
             ---[ommited]---
              
```
mounted config includes only references to var name :
"data_db": {
"db_host": "my-redis-host.com",
"db_password": "$REDIS_PASSWORD", // or ${REDIS_PASSWORD} 
},

So, cgr-engine will read the value "xxx" out of env var REDIS_PASSWORD and use it.

There is another option, is to run a script, at docker startup, that will substitute the config values.
aka.
1. look for everything enclosed with ${...} ,
2. read the value between brackets , 
3. use it to retrieve env var value
4. replace in config

I think there should also be an option to use a shell script to echo the config evaluating the variables in format of ${...} - perhaps , the best option, as nothing need to be done on cgrates side.
Let me do my research and get back to you, before you spend time on this.

Thanks,
Michael

**Comment by muxalko** [comment]
Hi Gavin,
Sorry for the delay
We will go for the script substitution.

**Comment by Trial97** [comment]
Hello,

We added the feature with the pull request #1273 so you can test it.
The syntax for environment variable in configuration files is:
`*env:VarName` 
e.g. if `DB_USER` is a environment variable equal to `cgrates` the following: 
`"db_user": "*env:DB_USER",`
will be used as:
`"db_user": "cgrates",`

Thanks,
Trial97
