### ISSUE TITLE
Issue with + in a Destination suffix (+ converted to a space via http_agent)

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1257]
Hi all,

Have have an agent like so:

```
// Destination is 234/015:Global+
{"tag": "Destination", "field_id": "Destination", "type": "*composed",
     "value": "~*req.MCC;/;~*req.MNC;:;~*req.profile", "mandatory": true},
```

`Destinations.csv`:

`United Kingdom - Vodafone,234/015:Global+`

but it seems the + is missed off:

`{"method":"SessionSv1.AuthorizeEvent","params":[{"GetAttributes":true,"AuthorizeResources":false,"GetMaxUsage":true,"ProcessThresholds":false,"ProcessStats":false,"GetSuppliers":false,"SuppliersMaxCost":"","SuppliersIgnoreErrors":false,"Tenant":"surevoip","ID":"445e4d4","Context":null,"Time":"2018-10-20T20:27:59.923041529+01:00","Event":{"Account":"XXX","Category":"m_data","Destination":"234/015:Global ","OriginID":"145403699","RequestType":"*pseudoprepaid","SetupTime":"*now"},"Limit":null,"Offset":null,"SearchTerm":""}],"id":0}`

Error:

Destination 234/015:Global  not authorized for account: surevoip:XXX, subject: *out:surevoip:m_data:XXX

It gets loaded OK:
```

2018/10/20 20:13:31     United Kingdom - Vodafone : [234/015:Global+]
...
2018/10/20 20:13:31      234/015:Global+ : [United Kingdom - Vodafone]
```

URL contains:

`GET /my_endpoint?request_type=DataAUTH&CallID=145403680&MSISDN=XX&IMSI=XX&MCC=234&MNC=015&TotalCurrentByteLimit=1048576&AgentID=2774&SessionID=479344&GlobalMSISDN=XX&GlobalIMSI=XX&ICCID=XX&frombundle=false&profile=Global+ HTTP/1.1.`

It's the profile part in the end of above url (+) gets turned into ` `

**Comment by TeoV** [comment]
Hi Gavin,

I have tried your content via a generic URL decoder and it behaves in the same way as CGRateS (plus is decoded as space):
You can test it here:
https://meyerweb.com/eric/tools/dencoder/
Also, can u please post the complete ngrep of your HTTP request(all headers)?

Thanks, TeoV

**Comment by ghenry** [comment]
Hi TeoV,

The complete ngrep is there (the bit with the GET above).

There isn't a particular RFC that states the behaviour of + in a query like this. It should actually be encoded better on the client side. Some discussion:

https://stackoverflow.com/questions/1005676/urls-and-plus-signs

I would say it's incorrect to turn it into a space automatically. If you want a space in the param value it should be encoded as a space. A `+` symbol should be treated as a `+` symbol.

I think this is the better function to use:

https://golang.org/pkg/net/url/#PathUnescape

> PathUnescape is identical to QueryUnescape except that it does not unescape '+' to ' ' (space).

**Comment by ghenry** [comment]
Closing. Client side issue that won't be fixed. Will work around. Thanks!
