### ISSUE TITLE
Suppliers in multiple lcr_profiles

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#127]
Hi DanB,

Further to our discussion on IRC I wanted to properly explain why it is important to be able to use a supplier / supplier-pricelist in more than one lcr_profile.

Here a user has 3 suppliers with 5 supplier pricelists as follows:

Supplier1-Silver
Supplier1-Gold
Supplier1-Platinum
Supplier2-Premium
Supplier3-Premium

The user intends to create a lcr_profiles due to various customer requirements.

**lcr_profile1 -- *lowest_cost** (based on the highest quality pricelist from each supplier)
* Supplier1-Platinum
* Supplier2-Premium
* Supplier3-Premium

**lcr_profile2 -- *static**
* Supplier1-Gold
* Supplier3-Premium
* Supplier1-Platinum

**lcr_profile3 -- *highest_cost**
* Supplier1-Platinum
* Supplier2-Premium
* Supplier3-Premium

All three examples of these are perfectly legitimate real life scenarios why a supplier pricelist can be used in the more than one lcr_profile since a user can have different routing requirements based on their customer types.  This is standard industry practice, for example a Business customer may want the highest quality at all times where as a Residential customer may only care about the lowest_cost.

Let me know if this makes sense to you and how we can implement this.

Thanks

Errol

**Comment by danbogos** [comment]
Hi @ewsamuels,

I agree that all 3 examples are perfectly legitimate. All you need to do is use each case with different category and you will be able to do what you are trying to achieve.

Thx,
DanB

**Comment by DigiDaz** [comment]
In my scenario with my supplier we have three 'tiers': silver, gold and platinum.

The pricing to us varies greatly but so does the availability of the routes, for example silver has this attached, "is only suitable for customers running their own LCR and able to route advance". If the silver  fails, it is sometimes good to the try the gold tier, and maybe eventually even the platinum, where termination is guaranteed.

**Comment by danbogos** [comment]
Hi @DigiDaz ,

You should create 3 different lcr profiles and select them by call category inside LcrRules. Failover should be done outside of CGR (eg: 3 different GetLcr queries).

DanB
