### ISSUE TITLE
Environment variables in config

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1281]
Hello Dear CGRateS Team!

THANKS A LOT for [EnvVar feature](https://github.com/cgrates/cgrates/issues/1237) https://github.com/cgrates/cgrates/pull/1273!!!
Huge one (for me at least).

Unfortunately, something doesn't work ...
When trying the following:
```
  "diameter_agent": {
        "origin_host": "*env:HOSTNAME",
  }

```
diameter refuses to start due to :
`2018/11/03 15:27:52 Could not parse config: <invalid character '\x00' after object key:value pair>`

Where am I wrong?
My version is CGRateS 0.9.1~rc8 git+5fc02a5 (2018-11-02T04:22:28-04:00)

Please assist,

Thanks,
Michael

**Comment by Trial97** [comment]
Hello @muxalko ,
We have added the fixes for environment variables in configuration files. Please update from master and retest.

Thanks,
Trial97
