### ISSUE TITLE
<DiameterAgent> error: NOT_FOUND processing message: Credit-Control-Request (CCR)

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1291]
Hello Dear Support Team!

When trying to get non existent field, the diameter agent replies with :

`diameter      | 2018/11/07 14:10:50 CGRateS <9a4f655> [WARNING] <DiameterAgent> error: NOT_FOUND processing message: Credit-Control-Request (CCR)`

and the request is not processed, although mandatory field is set to false.
here is my field:
`{"tag": "Charging-Rule-Base-Name",             "field_id": "Charging-Rule-Base-Name",          "type": "*composed",     "value": "~*req.Service-Information.PS-Information.Charging-Rule-Base-Name",              "mandatory": false},`

IMHO, the message should be more informative and
The request should pass when field doesn't exist and it is not mandatory.

Please correct, 
Thanks,
Michael

**Comment by muxalko** [comment]
Hello Dan!
The same error appears also when rals replies with NOT_FOUND for example. 
For me that was missing charger entry.
It is a bit confusing. Isn't there a way to catch an error and reply back to diameter client, aka the "proper" way?
I am not able to match it with rsr field, and diameter is not replying in case of error, meaning client will wait until timeout.
Setting default NACK doesn't help in that case.
Any thoughts?

Thanks,
Michael

**Comment by danbogos** [comment]
As discussed, the error was coming from AVPs (was looking for MaxUsage when error was present).

Dan
