### ISSUE TITLE
Environment variables in configs

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1301]
Hello Dear CGRateS Team!

There is an issue with the new feature introduced in #1237 .
While trying to pass db port number, config parser is complaining:
`2018/11/12 13:19:57 Could not parse config: <json: cannot unmarshal string into Go struct field DbJsonCfg.Db_port of type int>`

my var looks like this `DATADB_PORT=8102`
and in config it looks like this `"db_port": "*env:DATADB_PORT"`

Please assist,
Thanks,
Michael

**Comment by Trial97** [comment]
Hello @muxalko ,
The field `"db_port"` is an integer.
Please remove the quotes which surrounds: `*env:DATADB_PORT`.
Something like this: `"db_port": *env:DATADB_PORT`
Here you have some example for different type of data : 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/multifiles/d.json 

Thanks,
Trial97

**Comment by muxalko** [comment]
Thanks !
