### ISSUE TITLE
Separate MaxUsage from each Charger

### ISSUE THREAD

**Issue by chrisgis333** [cgrates/cgrates#1302]
Initiate/UpdateSession returns MaxUsage which is minimum allowed
usage from all chargers.
https://github.com/cgrates/cgrates/blob/2583be9e32364d68ba06a64e0d4689d46bf29da0/sessions/sessions.go#L1025

However in my scenario I need separate usage from each Charger in
response.

Multiple-Services-Credit-Control [
     Granted-Service-Unit[
         CC-Total-Octets = MaxUsage(Charger1) = 100MB
     ]
     RatingGroup = RatingGroup(Charger1)
     ResultCode = 2001
]
Multiple-Services-Credit-Control [
     Granted-Service-Unit [
         CC-Total-Octets = MaxUsage(Charger2) = 200MB
     ]
     RatingGroup = RatingGroup(Charger2)
     ResultCode = 2001
]
Multiple-Services-Credit-Control [
     Granted-Service-Unit [
         CC-Total-Octets = MaxUsage(Charger3) = 0MB
     ]
     RatingGroup = RatingGroup(Charger3)
     ResultCode = 4012
]

This scenario is supported by diameter Credit Control specification.
It would be nice to support it also in CGRateS.

**Comment by danbogos** [comment]
Please see example here:
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/diamagent/dryrun.json#L42

DanB

**Comment by chrisgis333** [comment]
Thanks,
I will retest soon.
Looks like change in Merge function after all :)

**Comment by danbogos** [comment]
hey @chrisgis333 

Indeed, it involved Merge (although a bit more than that) but the reason we did not do it in first place was because we did not see a reason for the reply overloading. Now that we understand the need of treating multiple groups, it makes sense.

Good luck!

DanB
