### ISSUE TITLE
 The subfields cost and usage are empty in the Cost_Details field

### ISSUE THREAD

**Issue by RBuryak** [cgrates/cgrates#1304]
Hi!

The CDRs was loaded to CGRateS via API function named CdrsV1.ProcessExternalCDR.
Below are JSON request and answer for CdrsV1.ProcessExternalCDR.

The Request:
{
	"id": 0,
	"method": "CdrsV1.ProcessExternalCDR",
	"params": [{
			"RunID": "*raw",
			"OriginHost": "127.0.0.1",
			"Source": "source1_cdrs",
			"OriginID": "1535544186_4483319",
			"ToR": "*data",
			"RequestType": "*postpaid",
			"Tenant": "tenant1",
			"Category": "data",
			"Account": "xxx71111113",
			"Subject": "xxx71111113",
			"Destination": "",
			"SetupTime": "2018-10-28T12:03:06Z",
			"AnswerTime": "2018-10-28T12:05:21Z",
			"Usage": "102400",
			"ExtraFields": {
				"Cli": "xxx71111113",
				"roamingDestinationPattern": "Gprs_Mo_Roaming_MCCMNC_Zone2_Internet",
				"routeTag": "NULL",
				"roamingRatingPackRef": "Operator1MiniPP_Roaming"
			},
			"CostSource": "*cdrs",
			"Rated": false
		}
	]
}

The Answer:
{
	"id": 0,
	"result": "OK",
	"error": null
}

But in StorDB ( in the Cost_Details field)  the subfields Cost and Usage are empty (are equal "null").

But in oldest version of CGRateS these subfields was correct.

BR,
Roman

**Comment by Trial97** [comment]
Hello @RBuryak,
Please update the CGRateS and retest.

Thanks,
Trial97
