### ISSUE TITLE
POST to call_url/call_url_async to include more details

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1307]
Hi all,

When using ThresholdS (I don't think it's really related to that) and a filter to call an action with call_url*, the event is POST'd to the url, but you can't tell what event caused it. You could construct different URLs, but it would be great to have the ActionID/FilterID/ThresholdID or similar as extra data. See:

https://groups.google.com/d/msg/cgrates/4abheYrhqj4/fxURQN3jBQAJ (use case is to filter based on a balance value to let the customer know their data/sms/voice bundle is at XX% usage).

This is what comes in:

```
User-Agent:Go-http-client/1.1.
Content-Length:1830.
Content-Type:application/json.
Accept-Encoding:gzip.
.
{
   "ID":"surevoip:234189200172500",
   "BalanceMap":{
      "*data":[
         {
            "Uuid":"1c9244bb-127b-4a1a-ad7d-035befab92f5",
            "ID":"B_UK_MOBILE_DATA_500",
            "Value":524288000,
            "Directions":{
               "*out":true
            },
            "ExpirationDate":"0001-01-01T00:00:00Z",
            "Weight":10,
            "DestinationIDs":{
               "United Kingdom - O2 (UK) Limited":true,
               "United Kingdom - Orange PCS Ltd":true,
               "United Kingdom - T-Mobile (UK) Limited":true,
               "United Kingdom - Vodafone":true
            },
            "RatingSubject":"",
            "Categories":{
               "m_data":true
            },
            "SharedGroups":{

            },
            "Timings":null,
            "TimingIDs":{

            },
            "Disabled":false,
            "Factor":null,
            "Blocker":false
         }
      ],
      "*sms":[
         {
            "Uuid":"c9a9064f-ad7f-4358-8add-046aa29330da",
            "ID":"B_UK_SMS_500",
            "Value":498,
            "Directions":{
               "*out":true
            },
            "ExpirationDate":"0001-01-01T00:00:00Z",
            "Weight":10,
            "DestinationIDs":{
               "UK EE(T-Mobile) Mobile":true,
               "United Kingdom - O2 (UK) Limited":true,
               "United Kingdom - Orange PCS Ltd":true,
               "United Kingdom - T-Mobile (UK) Limited":true,
               "United Kingdom - Vodafone":true
            },
            "RatingSubject":"",
            "Categories":{
               "mo_sms":true
            },
            "SharedGroups":{

            },
            "Timings":null,
            "TimingIDs":{

            },
            "Disabled":false,
            "Factor":null,
            "Blocker":false
         }
      ],
      "*voice":[
         {
            "Uuid":"d2570560-a6f8-4ef1-b53a-5a6e7c6a783e",
            "ID":"B_UK_MOBILE_UK_LANDLINE_500",
            "Value":30000000000000,
            "Directions":{
               "*out":true
            },
            "ExpirationDate":"0001-01-01T00:00:00Z",
            "Weight":10,
            "DestinationIDs":{
               "UK 03 UK wide":true,
               "UK 3 Mobile":true,
               "UK EE(Orange) Mobile":true,
               "UK EE(T-Mobile) Mobile":true,
               "UK National":true,
               "UK O2 Mobile":true,
               "UK Vodafone Mobile":true,
               "United Kingdom - O2 (UK) Limited":true,
               "United Kingdom - Orange PCS Ltd":true,
               "United Kingdom - T-Mobile (UK) Limited":true,
               "United Kingdom - Vodafone":true
            },
            "RatingSubject":"",
            "Categories":{
               "mo_call":true
            },
            "SharedGroups":{

            },
            "Timings":null,
            "TimingIDs":{

            },
            "Disabled":false,
            "Factor":null,
            "Blocker":false
         }
      ]
   },
   "UnitCounters":null,
   "ActionTriggers":null,
   "AllowNegative":false,
   "Disabled":false
}
```

Thanks!

**Comment by TeoV** [comment]
Hi Gavin, 
We have checked this feature and right now we can not implement because the parameters for action are static. 
Will review it later, together with implementing the new ActionS.

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi TeoV,

Thanks. So either unique URLs (or params) to be used or AttributeS to add
additional information to the event?

Gavin.

**Comment by TeoV** [comment]
Hi Gavin,
Yes, these could be the only choices for now. 

Thanks,
TeoV

**Comment by ghenry** [comment]
Thanks!

**Comment by TeoV** [comment]
Hi Gavin,
In the meantime, we update the callurl, callurlasync and log actions to use extra data when they are executed from the threshold.
https://github.com/cgrates/cgrates/blob/master/engine/thresholds.go#L86

**Comment by ghenry** [comment]
Hi TeoV,

Can you explain or show me what this extra data is?

Thanks.

**Comment by danbogos** [comment]
Hi @ghenry 

Do u have any issue with the implementation or just questions around it?
If only questions, I would suggest we continue the discussion over the google group so we don't duplicate the efforts here also.

Thanks,
DanB

**Comment by ghenry** [comment]
Hi Dan,
I'm not sure what TeoV is referring to in https://github.com/cgrates/cgrates/issues/1307#issuecomment-445155618 but it sound like just the think to give more context about the POST.

**Comment by danbogos** [comment]
Hi Gavin,

What we have added was the original CGREvent matching the threshold (so you can identify the information within the received event). 

DanB

**Comment by ghenry** [comment]
Hi Dan,

OK, great. Can you explain that more with maybe an example? 

Thanks.

**Comment by danbogos** [comment]
Gavin,

Not sure what do u mean by example? Are you asking about how would the
event look like or?

DanB

Gavin Henry <notifications@github.com> schrieb am Mo., 29. Apr. 2019, 17:46:

**Comment by ghenry** [comment]
Hi Dan,

Yes, that's right. When an event is matched via a filter in ThresholdS it
just sends through the account info. The way you've described this suggests
there is more that can be POSTed to a URL?

Thanks.

**Comment by fcessi** [comment]
Hi dears, by this explanations i can't understand how to post a url when threashould  80% is occured?
please guide me step by step
threashould.csv ??
Actions.csv??
api example jason RPC??

**Comment by danbogos** [comment]
Hi @fcessi 

Since this is not really an issue, please post your question on our google group and will do our best to assist you there.

Thanks,
DanB

**Comment by Trial97** [comment]
This issue is obsolete, we are passing the event to the ThresholdS.
Enough information should be available there.

**Comment by ghenry** [comment]
@Trial97 is this POSTing more data than just the account info to an `*http_post` action? I don't think so.

**Comment by Trial97** [comment]
Hi @ghenry,

If the Threshold event has the "Account" field we will send the account in the HTTP body else we will send the event itself.
This inherited from the old code.
We will address this in the new subsystem we are working on - `ActionS`.

Thanks,
Trial97

**Comment by ghenry** [comment]
Thanks Trial97. Ah, I've put account *notempty for my filter, like so
*notempty,~*req.Account

If I leave that out, should I get just the event? We'd obviously like both
:-)

**Comment by devhossamali** [comment]
Hi @Trial97 is this case addressed in the new Actions subsystem it seems like i don't have much control on what to be delivered as (event data) the only thing comes back is the account payload which doesn't have much use in my case and there's no clear way of how to force it to ignore account payload, we need a common ground when it comes to event payload delivery
