### ISSUE TITLE
Regex in diameter request_processor fields

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1314]
Hello Dear CGRateS Team!
When I try to populate OriginID from Session-Id using regex grouping, the diameter fails with:
` [WARNING] <DiameterAgent> no request processor enabled, ignoring message Credit-Control-Request (CCR)`

Here is my Session-Id:  "`GatewayService-6-31-3.XXggsn.telecom.net;1542190753;303167174`"
and the rule I am trying to use
`{"tag": "OriginID",     "field_id": "OriginID",         "type": "*composed",    "value": "~*req.Session-Id:s/(\\d+);(\\d+)$/$1;$2/",      "mandatory": true},`

I want to take only the digits from the end, so the result will be 
OriginID = "1542190753;303167174"

Please assist,
Thanks,
Michael

**Comment by TeoV** [comment]
Hi Michael,
The problem here comes from the separator ( ";" is reserved for our RSR splitting).
Please open an issue regarding configurable RSRParser separator.

Thanks,
TeoV

**Comment by muxalko** [comment]
Thanks Teo!
Opened #1322.
