### ISSUE TITLE
*attribute as a mandatory substitution

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1315]
Hello Dan,
Just a reminder for using *attribute as a mandatory substitution.
In case attribute is not found, it is not replied to diameter, so is allowing to pass.

Please fix.
Thanks,
Michael

**Comment by muxalko** [comment]
Hello Guys,
Just wondering, for the cases when I want to check if there was no attribute found, and perhaps allow the call.
Will the correct way be to use  filters: ["*rsr::~*cgrep.Attributes.xxx(^$)"], where xxx is the field being substituted.
Or just to check the field value directly, aka filters: ["*rsr::~*cgrep.xxx(^$)"] ?

I am confused by this Attributes between *cgrep and the actual field.


Thanks,
Michael

**Comment by danbogos** [comment]
Hi Michael,

In case of no attribute is found and you want to allow the call, don't do anything (that is the default behavior).

DanB
