### ISSUE TITLE
Configurable RSRParser separator

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1322]
Hello Dear CGRateS Team!
Please add an option to configure RSRParser separator. 
Needed for use cases as explained here https://github.com/cgrates/cgrates/issues/1314.

Thanks,
Michael

**Comment by TeoV** [comment]
Hello Michael,

This feature is available in master.
https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L53

Thanks,
TeoV
