### ISSUE TITLE
Feature request: test DerivedChargers through cgr-console

### ISSUE THREAD

**Issue by ccppprogrammer** [cgrates/cgrates#1337]
Because DerivedChargers is handled by session managers we can't test it by using cgr-console.
It would be useful to have possibility to test DerivedChargers through cgr-console, for example like we can test cost.

**Comment by TeoV** [comment]
Hi @ccppprogrammer,

Old DerivedChargers was replaced by ChargerService (ChargerS).
https://github.com/cgrates/cgrates/blob/master/console/chargers_for_event.go#L28
https://github.com/cgrates/cgrates/blob/master/console/chargers_process_event.go#L30

Thanks,
TeoV
