### ISSUE TITLE
Duplicate OriginID protection 

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1338]
Hi all,

For some reason we get two identical CDRs from our vendor and the second fails due to pg pk issues, which is expected. I'd like to handle this elegantly before it hits PostgreSQL.

Do I have any options?

Thanks.

**Comment by TeoV** [comment]
Hi Gavin,

Is still this issue active?
If not can you please close it.

Thanks,
TeoV

**Comment by TeoV** [comment]
Hi @ghenry,

Now we composed the CGRID from OriginID and OriginHost and as UniqueKey in databases, we use CGRID and RunID.

Thanks,
TeoV

**Comment by ghenry** [comment]
Nice! Any new breaking changes for an upgrade?
