### ISSUE TITLE
reply fields are not grouped properly

### ISSUE THREAD

**Issue by Razhan13** [cgrates/cgrates#1343]
Hello,

I wanna have an FUI inside the same MSCC.
with this config

      {"tag": "CCATemplate", "type": "*template", "value": "*cca"},
      {"tag": "ResultCode",  "filters": ["*rsr::~*cgrep.Error(!^$)"], "field_id": "Result-Code", "type": 
        "*constant", "value": "5030", "blocker": true},
      {"tag": "GrantedUnits", "type": "*variable",
        //"filters": ["*gt:*cgrep.MaxUsage{*duration_nanoseconds}:0"],
        "field_id": "Multiple-Services-Credit-Control.Granted-Service-Unit.CC-Total-Octets",
        "value": "~*cgrep.MaxUsage{*duration_nanoseconds&*multiply:1048576&*round}", "mandatory": 
      true},
       {"tag": "RatingGroup", "type": "*constant",
        "field_id": "Multiple-Services-Credit-Control.Rating-Group",
        "value": "999"},
       {"tag": "ServiceIdentifier", "type": "*constant",
        "field_id": "Multiple-Services-Credit-Control.Service-Identifier",
        "value": "999"},
       {"tag": "ValidityTime", "type": "*constant", "field_id": "Multiple-Services-Credit-Control.Validity- 
         Time", "value": "600"},
      {"tag": "FinalUnits", "type": "*variable", "field_id": "Multiple-Services-Credit-Control.Final-Unit- 
          Indication.Final-Unit-Action","value": "1"},
      {"tag": "RedirectAddressType", "type": "*constant", "field_id": "Multiple-Services-Credit- 
          Control.Final-Unit-Indication.Redirect-Server.Redirect-Address-Type", "value": "2"},
      {"tag": "RedirectServerAddress", "type": "*constant","field_id": "Multiple-Services-Credit- 
          Control.Final-Unit-Indication.Redirect-Server.Redirect-Server-Address", "value": 
          "http://172.10.88.88/"},
       {"tag": "ResultCode", "type": "*constant",
        "field_id": "Multiple-Services-Credit-Control.Result-Code",
        "value": "2001"},

FUI is a grouped AVP, Both FUA and Redirect-Server should be inside the one FUI and that FUI inside the original MSCC.
but as you can see there is three MSCC.

     AVP: Multiple-Services-Credit-Control(456) l=80 f=-M-
        AVP Code: 456 Multiple-Services-Credit-Control
        AVP Flags: 0x40, Mandatory: Set
        AVP Length: 80
        Multiple-Services-Credit-Control: 000001af40000018000001a5400000100000000000200000...
            AVP: Granted-Service-Unit(431) l=24 f=-M-
            AVP: Rating-Group(432) l=12 f=-M- val=999
            AVP: Service-Identifier(439) l=12 f=-M- val=999
            AVP: Validity-Time(448) l=12 f=-M- val=600
            AVP: Result-Code(268) l=12 f=-M- val=DIAMETER_SUCCESS (2001)
    AVP: Multiple-Services-Credit-Control(456) l=28 f=-M-
        AVP Code: 456 Multiple-Services-Credit-Control
        AVP Flags: 0x40, Mandatory: Set
        AVP Length: 28
        Multiple-Services-Credit-Control: 000001ae40000014000001c14000000c00000001
            AVP: Final-Unit-Indication(430) l=20 f=-M-
                AVP Code: 430 Final-Unit-Indication
                AVP Flags: 0x40, Mandatory: Set
                AVP Length: 20
                Final-Unit-Indication: 000001c14000000c00000001
                    AVP: Final-Unit-Action(449) l=12 f=-M- val=REDIRECT (1)
    AVP: Multiple-Services-Credit-Control(456) l=72 f=-M-
        AVP Code: 456 Multiple-Services-Credit-Control
        AVP Flags: 0x40, Mandatory: Set
        AVP Length: 72
        Multiple-Services-Credit-Control: 000001ae40000040000001b240000038000001b14000000c...
            AVP: Final-Unit-Indication(430) l=64 f=-M-
                AVP Code: 430 Final-Unit-Indication
                AVP Flags: 0x40, Mandatory: Set
                AVP Length: 64
                Final-Unit-Indication: 000001b240000038000001b14000000c00000002000001b3...
                    AVP: Redirect-Server(434) l=56 f=-M-
                        AVP Code: 434 Redirect-Server
                        AVP Flags: 0x40, Mandatory: Set
                        AVP Length: 56
                        Redirect-Server: 000001b14000000c00000002000001b34000002368747470...
                            AVP: Redirect-Address-Type(433) l=12 f=-M- val=URL (2)
                            AVP: Redirect-Server-Address(435) l=35 f=-M- val=http://172.10.88.88

they should be under the same branch

**Comment by TeoV** [comment]
Hi Razhan13,

This should be fixed in master. 
Please update and retest.

Thanks,
TeoV
