### ISSUE TITLE
REQUEST: ability to fully specify the order of Diameter reply fields

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#1358]
this is a follow on from https://groups.google.com/forum/#!topic/cgrates/69LbTgN02Ss

our switch vendor (metaswitch) currently requires the AVP's in diameter CCR replies to be in a specific order - specifically they need the SessionId to be before the result code

please can support be coded in to return the fields in an order specified in the config file or via some defined template in order to support the required ordering

**Comment by anthonysomerset** [comment]
added notes:

Based on RFC4006 section 3.2 Credit-Control-Answer (CCA) message format is:
<Credit-Control-Answer> ::= < Diameter Header: 272, PXY >
< Session-Id >
{ Result-Code }
{ Origin-Host }
{ Origin-Realm }
{ Auth-Application-Id }
{ CC-Request-Type }
{ CC-Request-Number }
[ User-Name ]
[ CC-Session-Failover ]
[ CC-Sub-Session-Id ]
[ Acct-Multi-Session-Id ]
[ Origin-State-Id ]
[ Event-Timestamp ]
[ Granted-Service-Unit ]
*[ Multiple-Services-Credit-Control ]
[ Cost-Information]
[ Final-Unit-Indication ]
[ Check-Balance-Result ]
[ Credit-Control-Failure-Handling ]
[ Direct-Debiting-Failure-Handling ]
[ Validity-Time]
*[ Redirect-Host]
[ Redirect-Host-Usage ]
[ Redirect-Max-Cache-Time ]
*[ Proxy-Info ]
*[ Route-Record ]
*[ Failed-AVP ]
*[ AVP ]

**Comment by danbogos** [comment]
Good for people following RFCs ;)

**Comment by anthonysomerset** [comment]
FYI current master works with Initial Request events

still getting incorrect order on terminate events (Result Code coming first when it should come after session id)

**Comment by danbogos** [comment]
hi @anthonysomerset 

I am not sure it is fixed, we are still working with the guy who wrote the diameter library to see the best approach since result code is hardcoded as first AVP in the request.

DanB

**Comment by danbogos** [comment]
sorry @anthonysomerset , @TeoV has corrected me. We have patched in the code the result-code so it should work like you confirmed.
DanB
