### ISSUE TITLE
tp_rating_profiles.activation_time varchar(24) to short for RFC3339

### ISSUE THREAD

**Issue by hampsterx** [cgrates/cgrates#1360]
hi there,

Attempting to store RFC3339 value via `SetTPRatingProfile` results in truncation. EG

```
2018-12-21T11:46:17+00:0
```

Resulting in

```
cannot parse activation time from 2018-12-21T11:46:17+00:0
```
Fiddling manually..
```
alter table tp_rating_profiles modify column activation_time varchar(26);
```

Resolves the error

> RFC 3339 is mostly a profile of ISO 8601, but is actually inconsistent with it in borrowing the "-00:00" timezone specification from RFC 2822 - https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats

Oh the joy. Cheers~

**Comment by TeoV** [comment]
Hi hampsterx,

This should be fixed in master.
Please update and retest.

Thanks,
TeoV
