### ISSUE TITLE
 Empty balances on a newly created account 

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1367]
Hi,

Would like to check why balances aren't created on account `surevoip:234189200172500`. After loading, I see:

```
cgr> accounts Tenant="surevoip" AccountIds=["234189200172500"] 
[
 {
  "ID": "surevoip:234189200172500",
  "BalanceMap": null,
  "UnitCounters": null,
  "ActionTriggers": null,
  "AllowNegative": false,
  "Disabled": false
 }
]
```

but I am not loading `DestinationRates.csv  Rates.csv  RatingPlans.csv  RatingProfiles.csv` at the same time. I don't think this should affect building the BalanceMap though?
[no_balances_created.zip](https://github.com/cgrates/cgrates/files/2723498/no_balances_created.zip)

Thanks.

**Comment by ghenry** [comment]
Works. I found a bug when using -to_stordb in the my Actions.csv had dup Ids. Hadn't tried cgr-loader since that fix. All is good. I think that was it.

**Comment by danbogos** [comment]
Hi Gavin,

Thanks for reporting. Please update also google groups thread. 

DanB
