### ISSUE TITLE
XML to Json configuration

### ISSUE THREAD

**Issue by KuikenArjan** [cgrates/cgrates#137]
We want to transform the current configuration in XML to the new format in Json.

XML:
\<field name="Cost" type="cdrfield" value="cost" filter="~mediation_runid:s/^(?:default|default_cnl)//:s/^(partner|partner_cnl)$/filtered/" mandatory="true"/\>

How can we achieve the same result in the JSON code.

**Comment by danbogos** [comment]
Hi @KuikenArjan 

In the rc6 you do not longer have the derived charging in the .cfg (nor .json) but all defined in your DerivedChargers.csv (or APIs). Will send you privately the api calls which you need.

DanB
