### ISSUE TITLE
GetTPResourceIDs makes CGRateS panic instead of return error

### ISSUE THREAD

**Issue by TayyabTalha** [cgrates/cgrates#1386]
Hi, 
I have updated cgrates and using following version
`
cgr-engine --version
`

> CGRateS 0.9.1~rc8 git+4e45f56 (2019-01-15T05:15:34-05:00)

I'm using following docker image as base image

> Debian GNU/Linux 9 \n \l

When I try to call following apier cgr-engine is getting crashed
`curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetTPResourceIDs","params":[{"TPid":"tpt12"}]}' http://cgrates:2080/jsonrpc | python -m json.tool`

Here is response I got as result

> curl: (52) Empty reply from server

Here are logs for panic

> panic: reflect: call of reflect.Value.FieldByName on ptr Value
> 
> goroutine 142 [running]:
> reflect.flag.mustBe(0x196, 0x19)
>         /usr/local/go/src/reflect/value.go:207 +0xb4
> reflect.Value.FieldByName(0xfd8aa0, 0xc0005b82f0, 0x196, 0x115b3f5, 0x4, 0x196, 0x0, 0xc000130700)
>         /usr/local/go/src/reflect/value.go:865 +0x4c
> github.com/cgrates/cgrates/utils.MissingStructFields(0xf34d80, 0xc0005b82f0, 0xc0005c0b20, 0x1, 0x1, 0x70e76d, 0xc0005c0b50, 0x40d8ff)
>         /root/Projects/Proj1/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/utils/struct.go:33 +0x18f
> github.com/cgrates/cgrates/apier/v1.(*ApierV1).GetTPResourceIDs(0xc000234070, 0xc000672d80, 0xc00044ee00, 0x0, 0x0)
>         /root/Projects/Proj1/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/tpresources.go:60 +0xb6
> reflect.Value.call(0xc0002b6d20, 0xc00015e168, 0x13, 0x115b201, 0x4, 0xc0005c0f18, 0x3, 0x3, 0xc0003fe300, 0xec93eb, ...)
>         /usr/local/go/src/reflect/value.go:447 +0x454
> reflect.Value.Call(0xc0002b6d20, 0xc00015e168, 0x13, 0xc00045df18, 0x3, 0x3, 0x7f7d12361c60, 0xc00045df28, 0x40e188)
>         /usr/local/go/src/reflect/value.go:308 +0xa4
> net/rpc.(*service).call(0xc0003fe180, 0xc00017a000, 0xc0002169e0, 0xc000216a00, 0xc0003e6580, 0xc00044ece0, 0xfd8aa0, 0xc000672d80, 0x16, 0xf3e300, ...)
>         /usr/local/go/src/net/rpc/server.go:384 +0x14e
> created by net/rpc.(*Server).ServeCodec
>         /usr/local/go/src/net/rpc/server.go:481 +0x47e
> 

Thanks
Regards,
Tayyab Talha

**Comment by danbogos** [comment]
Hi @TayyabTalha 

Please retest with master and report back.

Thanks,
DanB

**Comment by TayyabTalha** [comment]
Hi @danbogos 
I'm not able to reproduce this issue with following version 

> CGRateS 0.9.1~rc8 git+e02eda5 (2019-02-13T17:02:23+02:00)

You can close this issue
Thanks
Regards,
Tayyab Talha
