### ISSUE TITLE
CGRATES Crash on APIER RemoveThresholdProfile/RemoveSupplierProfile

### ISSUE THREAD

**Issue by TayyabTalha** [cgrates/cgrates#1390]
Hi, Cgrates crash is you try to delete any of supplier/RemoveThresholdProfile via APIER if SupplierProfile/ThresholdProfile is not in datadb(already deleted/Not inserted). Here is example
> curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.RemoveThresholdProfile","params":[{"Tenant":"cgrates.org","ID":"SPL_AQL"}]}' http://cgrates:2080/jsonrpc | python -m json.tool
> No JSON object could be decoded

Here is panic

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc19ca7]
> 
> goroutine 192 [running]:
> github.com/cgrates/cgrates/engine.(*DataManager).RemoveThresholdProfile(0xc0003f3080, 0xc00032ab90, 0xb, 0xc00032aba0, 0x7, 0x0, 0x0, 0x1, 0xc0001dc570, 0x0)
>         /root/Projects/Proj1/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/datamanager.go:479 +0x2d7
> github.com/cgrates/cgrates/apier/v1.(*ApierV1).RemoveThresholdProfile(0xc00056a230, 0xc00001b380, 0xc0005eb390, 0x0, 0x0)
>         /root/Projects/Proj1/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/thresholds.go:109 +0xd7
> reflect.Value.call(0xc00036ade0, 0xc000270600, 0x13, 0x115b201, 0x4, 0xc00007ff18, 0x3, 0x3, 0xc0003b8940, 0x0, ...)
>         /usr/local/go/src/reflect/value.go:447 +0x454
> reflect.Value.Call(0xc00036ade0, 0xc000270600, 0x13, 0xc000466f18, 0x3, 0x3, 0x0, 0x0, 0x0)
>         /usr/local/go/src/reflect/value.go:308 +0xa4
> net/rpc.(*service).call(0xc0003b8600, 0xc000180000, 0xc00032aac0, 0xc00032aad0, 0xc000365e00, 0xc0001021c0, 0xfdb8c0, 0xc00001b380, 0x16, 0xf64440, ...)
>         /usr/local/go/src/net/rpc/server.go:384 +0x14e
> created by net/rpc.(*Server).ServeCodec
>         /usr/local/go/src/net/rpc/server.go:481 +0x47e

**Comment by danbogos** [comment]
Hi @TayyabTalha 

Do u still see this issue present in the master?

Thanks,
DanB

**Comment by TayyabTalha** [comment]
Hi @danbogos 
I'm not able to reproduce this issue with following version 

> CGRateS 0.9.1~rc8 git+e02eda5 (2019-02-13T17:02:23+02:00)

You can close this issue
Thanks
Regards,
Tayyab Talha
