### ISSUE TITLE
Latest "amqp_aws" publishes CDRs to Amazon MQ with a message with some strange binary chars at start

### ISSUE THREAD

**Issue by asnaseer-resilient** [cgrates/cgrates#1391]
We have been using the latest "**amqp_aws**" exporter to publish our CDRs to Amazon MQ. When we examine the message in the Amazon MQ Web Console we noticed that it has some binary characters at the start:

> Su� �{"Account":"HSBdanC001@resilientplc","AnswerTime":"2019-01-22T09:53:56Z","CGRID":"df3b8d67ad99b7f9c4ddd2c04df5ea34269c4ccf","CLI":"443397807668","Category":"inbound_03","Cost":"-1.00000","CostDetails":"null","Destination":"442073067607","Direction":"","OriginHost":"","OriginID":"5bf2be2a-de56-4898-afdf-ce30c385c006:1","RequestType":"*postpaid","RunID":"*raw","ServiceCategory":"Received","SetupTime":"2019-01-22T09:53:55Z","Tenant":"resilientplc","ToR":"*voice","Usage":"1m0s"}

We wrote a simple javascript consumer (using the **@stomp/stompjs** library) to read the message off the queue and skipped all the initial binary characters but found that the message seems to be chopped at the end.

As an example, when we read a queued message we found it contained a binary message body which comes back as a **Uint8Array** containing:

> [0,
> 83,
> 117,
> 239,
> 191,
> 189,
> 0,
> 0,
> 1,
> 239,
> 191,
> 189,
> 123,
> ...,
> 58,
> 34,
> 49,
> 109]

We skipped the first 12 characters and then read the rest of this array starting from value **123** (which is the open brace character **{**) to the end of the array and got:

> {"Account":"HSBdanC001@resilientplc","AnswerTime":"2019-01-22T09:53:56Z","CGRID":"df3b8d67ad99b7f9c4ddd2c04df5ea34269c4ccf","CLI":"443397807668","Category":"inbound_03","Cost":"-1.00000","CostDetails":"null","Destination":"442073067607","Direction":"","OriginHost":"","OriginID":"5bf2be2a-de56-4898-afdf-ce30c385c006:1","RequestType":"*postpaid","RunID":"*raw","ServiceCategory":"Received","SetupTime":"2019-01-22T09:53:55Z","Tenant":"resilientplc","ToR":"*voice","Usage":"1m

So it looks like it is not returning the end of the message - i.e. it is missing the **0s"}** characters.

We wrote a quick test using the stomp library to queue our own message and this seems to queue correctly (i.e. with no strange binary characters at the start) and we were also able to dequeue it correctly.

Any ideas on what is going wrong here?

**Comment by Trial97** [comment]
Hello @asnaseer-resilient ,

Can we still use the test account for today?

Thanks,
Trial97

**Comment by Trial97** [comment]
Hello @asnaseer-resilient ,

The binary characters at the start are the AMQP constructor for the message described in : 
https://www.amqp.org/sites/amqp.org/files/amqp.pdf
After some research we found that the library you are using reads the messages with STOMP  not with AMQP and hence the incompatibilities when reading. 

Thanks,
Trial97

**Comment by danbogos** [comment]
Hi @asnaseer-resilient 

Since the issue proved not to be CGRateS related, will close here. Please re-open if you find anything not normal regarding our AMQP (or SQS) implementations.

Thanks,
DanB
