### ISSUE TITLE
ApierV1.GetLcr

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#142]
Hi DanB,

I have 3 Tariff Plans defined and configured as follows:

thinq_premium -- USA and Canada only Tariff Plan with 360 rows
voxbeam_premium -- Complete A-Z Tariff Plan with 73054 rows
voxbeam_direct -- Complete A-Z Tariff  Plan with 73054 rows

All three (3) are configured in the same lcr_profile called "default_route" and I am able to get results for USA destination numbers using ApierV1.GetLcr without issues.
```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"premium_lcr","Account":"1482229879","Subject":"1482229879","Destination":"19173331111","StartTime":"2015-08-06T23:20:28Z","Duration":"60"}]}' http://localhost:2080/jsonrpc```

**then I get this result back which is correct.**

```{"id":null,"result":{"DestinationId":"*any","RPCategory":"premium_lcr","Strategy":"*lowest_cost","Suppliers":[{"Supplier":"thinq_premium","Cost":0.0065,"QOS":null},{"Supplier":"voxbeam_premium","Cost":0.0081,"QOS":null},{"Supplier":"voxbeam_direct","Cost":0.0085,"QOS":null}]},"error":null}``

**Now, I try to query an international number for example:**

```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"premium_lcr","Account":"1482229879","Subject":"1482229879","Destination":"4411383000783","StartTime":"2015-08-06T23:20:28Z","Duration":"60"}]}' http://localhost:2080/jsonrpc```

**and I get this error:**

```{"id":null,"result":null,"error":"SERVER_ERROR:LCR_COMPUTE_ERRORS"}```

**If I use GetCallCost to query the Supplier I get the correct rate so I know for sure the rates are loaded correctly.**

If I remove the supplier Thinq from the LCR Profiles and delete the Redis key it works fine.  I have been pulling my hair out all day with this and I am able to replicate on another server so suspecting its a bug.

CGRATES Version: cgrates_0.9.1~rc7_amd64.deb dated 3rd August 2015.

``redis-cli -n 10 keys lcr_*```
1) "lcr_*out:cgrates.org:priority:*any:*any"
2) "lcr_*out:cgrates.org:premium_lcr:*any:*any"

If you need any more info please let me know.

Thanks,

Errol

**Comment by danbogos** [comment]
Hi @ewsamuels,

Can you please paste your LCR rules here? 
Also the reason you are getting LCR errors (not at all at bug if you ask me) could be you misconfiguring something.

Thanks,
DanB

PS: Will modify your title since I think it is misleading in this case since we don't know we have a bug and moreover we label the bugs using bug label once it is proven.

**Comment by ewsamuels** [comment]
Let me know if this is good for you seen github doesn't accept .csv files.

![lcr](https://cloud.githubusercontent.com/assets/5496519/9144263/b14f02e0-3d43-11e5-8902-612cf2c1fa9e.png)

**Comment by ewsamuels** [comment]
Hi DanB,

```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"default_route","Account":"6889101058","Subject":"6889101058","Destination":"441138300783","StartTime":"2015-08-07T22:20:00.0000Z","Duration":"60"}]}' http://localhost:2080/jsonrpc```
{"id":null,"result":null,"error":"SERVER_ERROR:LCR_COMPUTE_ERRORS"}

The syslog gives the clue to the issue and it is exactly what I suspected.

```Aug  7 20:56:48 demo CGRateS[8854]: error getting cost for key <*out:cgrates.org:default_route:thinq_premium>: Could not determine rating plans for call
Aug  7 20:56:48 demo CGRateS[8854]: LCR_ERROR: supplier <*out:cgrates.org:default_route:thinq_premium>, error <Could not determine rating plans for call>```

This is correct that the supplier "thinq_premium" will be able to route the destination "441138300783" because it only supports USA and Canada and not international destinations.  This is typical in a real world scenario.

What I believe should happen is that if a supplier is unable to determine the rating plan for a call cgrates should just skip it and move on to the next supplier in the list.  So if an LCR Profile has 10 suppliers in it and only 4 of them is able to match a particular destination then the LCR should be calculated based on those 4 suppliers.

Best regards,

Errol

**Comment by danbogos** [comment]
This is the subject of the new feature to ignore the suppliers with errors in the configuration, so not at all a bug.

DanB

**Comment by ewsamuels** [comment]
DanB,
I am not sure if you understood what I was trying to explain.  There is no error in my supplier configuration whatsoever. The LCR for calls to the USA calculates correctly since all three of the suppliers support USA prefixes / destination.  

Only two of the three suppliers support ALL A-Z destinations.  What I am saying is that CGRateS when CGRateS is calculating the LCR it needs to bypass / ignore a suppliers that does not support a particular destination rather than give an error.

If this is not clear I would have to show you the actual Ratesheets so you can see it clearly.

Regards,

Errol

**Comment by danbogos** [comment]
Hey @ewsamuels,

I think you have misunderstood me. The error is the fact that you don't have rates defined for your destination. It is impossible to tell whether you have done it on purpose (taken destination out of list) or simply forgot to define it - so an error. We consider that a tariff plan has a-z destinations defined so missing destination is an error in your tariff plan.

DanB

**Comment by ewsamuels** [comment]
DanB,

Ok there is definitely a misunderstanding between the two of us.  So I will explain via the attached screenshot.

![lcr_example](https://cloud.githubusercontent.com/assets/5496519/9163838/0db33ab4-3f43-11e5-9349-fe1feb5a72a5.png)

Notice we have 3 suppliers and all three of these suppliers support calls to the United_States with prefix 1917.
If I made an API call to GetLcr I will get back the following response.
````{"id":null,"result":{"DestinationId":"*any","RPCategory":"premium_lcr","Strategy":"*lowest_cost","Suppliers":[{"Supplier":"thinq_premium","Cost":0.004,"QOS":null},{"Supplier":"voxbeam_premium","Cost":0.0081,"QOS":null},{"Supplier":"voxbeam_direct","Cost":0.0085,"QOS":null}]},"error":null},,,

This is 100% correct and no problem here.
Now I also want to make a call to United_Kingdom_Mobile_O2 but my supplier thinq doesn't support calls to the United_Kingdom_Mobile_O2 destination where as the other two do.  

So when I make the API call, I get the error:
````{"id":null,"result":null,"error":"SERVER_ERROR:LCR_COMPUTE_ERRORS"}````

In my opinion this logic is not 100% correct because since thinq doesn't have a destination or a rate for a particular destination it should just be ignored and the LCR calculated between Voxbeam_Premium and Voxbeam_Direct since both of these suppliers can complete calls to the United_Kingdom_Mobile_o2.

This is a typical real world scenario that I am giving.  Not all carriers will support ALL the A-Z Destinations some Carriers may only specialize in certain destinations but there is no reason why they shouldn't be put in an LCR to compete for a destination where they maybe cheaper than another supplier.

I hope this makes sense to you now.

Regards,

Errol

**Comment by danbogos** [comment]
Hi @ewsamuels,

For the sake of completion, will repeat the information we have discussed over IRC.

We need to have complete tariff plans matched in order to be able to calculate costs. That implies having things like destination, time, rating subject and so on matched on each time span we use to calculate costs on. Any missing information out of it for us is an error even if you are trying to enforce the rule that if destination is missing, should be not big deal since you wanted it to be missing. For us missing destination says you should have not routed the call to that lcr profile in first place.

Anyway, planning to add a new flag, IgnoreErros to the GetLcr API call which should make the query work in the way you are trying to do.

DanB
