### ISSUE TITLE
Get RatingProfiles by RatingPlanId from DataDB

### ISSUE THREAD

**Issue by pustovoytenko** [cgrates/cgrates#1424]
Hi,

Please add API method that retrieves RatingProfiles by RatingPlanId from DataDB.

Thanks

**Comment by danbogos** [comment]
Hi @pustovoytenko 

Unfortunately it is not possible to do this since we need to maintain additional indexes for this.
I recommend you managing the mapping outside of CGRateS and use the standard GetRatingProfile once you have the ID from your own mapping.

DanB
