### ISSUE TITLE
Feature request: pass only dynamic arguments into filters gt/gtr/lt/lte

### ISSUE THREAD

**Issue by szpodpora** [cgrates/cgrates#1426]
It would be good to have possibility to use two dynamic values in filters gt/gte/lt/lte. 
TO-BE example:
	"filters":	["*lte:*cgrep.MaxUsage:*cgreq.Usage"],

Current implementation allows to pass one dynamic (1st argument) and one constant (2nd argument, number) 
AS-IS example
	"filters":	["*lte:*cgrep.MaxUsage:0s"],

Best regards,
Szymon

**Comment by Trial97** [comment]
Hi @szpodpora ,

This feature should be available in master.
Here is an example:
`*lte:~*cgrep.MaxUsage:~*cgreq.Usage` 
`*lte:~*cgrep.MaxUsage:0s`

Thanks,
Trial97
