### ISSUE TITLE
Exposing a debug URL for profiling

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1427]
Hi all,

I see we load net/http/pprof in engine. It would be good to have a config setting to expose a debug URL so you can profile CGRateS within a Container env like:

https://bruinsslot.jp/post/profiling-golang-docker/

Thanks.

**Comment by danbogos** [comment]
hey  @ghenry 

Please hold since we would need to do some modifications again before ready to test.

Thanks,
DanB
