### ISSUE TITLE
Balance History Tracking

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#143]
Hi Guys,

I been experiencing some strange issues with customer prepaid balances over the past weeks / months as follows:

1) I made a topup of $25 then maybe 20 mins later I added another topup for $143.777.  I confirmed 100% the correct total in the customers account. I would check the customer's account the next day and see that the $100+ just vanishes from his account.  I know that it was not used in calls because this customer uses only about $50 in call credit per week and his CDRs also confirms this.

2) The next issue I have is that we would try to topup a prepaid during the day using the API we would get back the usual response to say that the account was topped up and there were no errors.  However, when we check the account to confirm the new balance its still the same.  This is an intermittent issue but it happens very often especially during peak times when traffic is on the system.

Not sure if these issues were fixed in the August 3rd and 6th packages but the system is using the package from late July.

Also, I would like to suggest implementing some sort of Audit Trail for Balances in StoreDB where we can track debits and credits of accounts since when there are issues we have no recourse whatsoever.  This would prove to be invaluable if the Redis Accounting Data was lost for whatever reason.

Best regards,

Errol

**Comment by danbogos** [comment]
Hey Errol,

This issue should have been fixed on 3rd of August, so available in any package after that.

Regarding logging of the account activity, that would be quite some load on the storDb so we don't want to go there. We are planning introducing of the new database for that purpose but no idea when it will be it's turn for implementation.

In the mean time what I suggest for the balance activity logging would be a pubsub client on your side which will monitor balance changes and do the archiving which you are after.

DanB
