### ISSUE TITLE
ApierV1.GetAttributeProfileIDs Bug

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#1431]
Dear Team,

I just came across with ApierV1.GetAttributeProfileIDs and saw that the result disappears _**the first character**_ of the Tenant. I am using the latest master code : cgrates_0.9.1~rc8+20190220+00302d2

In the example below I am setting : "Tenant":"**a**bcd_voiceland.global" and the Result of GetAttributeProfileIDs is : "bcd_voiceland.global:ATTR_1234567890_SESSIONAUTH_3"
So the result of GetAttributeProfileIDs misses the "a" character of the Tenant!

Example :

Set SetAttributeProfile Request:
{
  "id":"0",
  "method":"ApierV1.SetAttributeProfile",
  "params":[
    {
      "Tenant":"abcd_voiceland.global",
      "ID":"ATTR_1234567890_SESSIONAUTH_3",
      "Contexts":["*sessions","*cdrs"],
      "FilterIDs":["*string:Account:101"],
      "Attributes":[
          {
            "FieldName":"Category1",
            "Initial": "*any",
            "Substitute":[
              {
                "name":"test",
                "Rules":"RULE1",
                "AllFiltersMatch": true
              }
            ],
            "Append":false
          }
  ],
      "Blocker":false,
      "Weight":10
    }
  ]
}

GetAttributeProfileIDs Request:
{
  "id":"0",
  "method":"ApierV1.GetAttributeProfileIDs",
  "params":[
  
  ]
}

result:
{
    "id": "0",
    "result": [
         "bcd_voiceland.global:ATTR_1234567890_SESSIONAUTH_3"      <------------- misses "**a**" from tenant
    ],
    "error": null
}

Thank you

Vasilios Tzanoudakis

**Comment by Trial97** [comment]
Hello @vtzan ,

This problem should be fix in master.
Please update and retest. 

Thanks
Trial97

**Comment by vtzan** [comment]
Dear @Trial97,

Problem fixed! Thank you for your fast response.

Best Regards

Vasilios Tzanoudakis
