### ISSUE TITLE
ApierV1.GetLcr StartTime issue

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#144]
Hello Guys,

I upload the LcrRules.csv and made note of the server time below before making queries.  I call made several calls to the API using different StartTimes all of them are times in the future but for some strange reason only the only the 3rd attempt with StartTime that's at least 1 hour ahead of the server time seems to work.  Any ideas?

**Server Time:** Sun Aug  9 05:57:10 UTC 2015

````curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"default_route","Account":"6889101058","Subject":"6889101058","Destination":"17862240000","StartTime":"2015-08-09T06:20:00.0000Z","Duration":"60"}]}' http://localhost:2080/jsonrpc````

{"id":null,"result":null,"error":"NOT_FOUND"}

```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"default_route","Account":"6889101058","Subject":"6889101058","Destination":"17862240000","StartTime":"2015-08-09T06:45:00.0000Z","Duration":"60"}]}' http://localhost:2080/jsonrpc````

{"id":null,"result":null,"error":"NOT_FOUND"}

````curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"default_route","Account":"6889101058","Subject":"6889101058","Destination":"17862240000","StartTime":"2015-08-09T07:00:00.0000Z","Duration":"60"}]}' http://localhost:2080/jsonrpc````

{"id":null,"result":{"DestinationId":"*any","RPCategory":"default_route","Strategy":"*lowest_cost","Suppliers":[{"Supplier":"thinq_premium","Cost":0.0065,"QOS":null},{"Supplier":"voxbeam_premium","Cost":0.0081,"QOS":null},{"Supplier":"voxbeam_direct","Cost":0.0085,"QOS":null}]},"error":null}cgrates.org

Regards,

Errol

**Comment by danbogos** [comment]
Hey Errol,

Can u maybe show us your full lcr rules? There are chances you have overlapping. Setting time in the future it should be no issue (actually that is how we have planned using it).

DanB

**Comment by ewsamuels** [comment]
Hi DanB,
OK this one I believe I resolved.  It seems the LcrRules was 1 hour ahead for some strange reason.

Thanks
