### ISSUE TITLE
Performance: Add ability to run each diameter message in separate goroutine

### ISSUE THREAD

**Issue by chrisgis333** [cgrates/cgrates#1447]
Diameter agent processes each tcp connection in paralell.
However messages inside each connection are processed one by one 
(sequential)
Read -> Process -> Send Response -> Read Next -> Process -> Send
Response
Processing diameter messages in separate goroutines should improve performance.

My dirty change works quite well for me allowing to increase performance from 300 tps to 1500 tps with this little change.

```
 	dSM := sm.New(settings)
 
-	dSM.HandleFunc("ALL", da.handleMessage) // route all commands to one dispatcher
+	dSM.HandleFunc("ALL", da.handleMessageAsync) // route all commands to one dispatcher
 	go func() {
 		for err := range dSM.ErrorReports() {
```

```
+
+func (da *DiameterAgent) handleMessageAsync(c diam.Conn, m *diam.Message) {
+	go da.handleMessage(c, m)
+}
+
 // handleALL is the handler of all messages coming in via Diameter
 func (da *DiameterAgent) handleMessage(c diam.Conn, m *diam.Message) {
 	start := time.Now()
```

**Comment by danbogos** [comment]
hi @chrisgis333 

Please add this into a PR so we can integrate it into master.

Thanks,
DanB

**Comment by danbogos** [comment]
@chrisgis333 

Ended up doing it myself so it can catch some more intensive testing in our testing workshop.

Thanks for this!

DanB

**Comment by chrisgis333** [comment]
@danbogos 
No problem.
Hope to contribute more in the future.
I am making extensive performance testing for my deployment now. So if sth come up, I will let You know.
