### ISSUE TITLE
Add warning for missing BalanceType when using balance_remove

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1473]
balance_remove Tenant="surevoip" Account="XXXX" BalanceUuid="62651e3d-3d09-4d6a-a1c9-74b85eeff4d5"

doesn't complain and returns "OK", but does nothing.

Thanks.

**Comment by Trial97** [comment]
Hi Gavin,

We investigated the issue and found out that the reason why balance_remove only returns  "OK" is because as default the BalanceType it has the value:"*monetary". 

Thanks,
Trial97

**Comment by ghenry** [comment]
Ah, OK. Well I think in this case the Uuid was for a different balance type. But glad it's corrected. Thank you!
