### ISSUE TITLE
Topup via AddBalance not always correct

### ISSUE THREAD

**Issue by ibstelix** [cgrates/cgrates#1475]
CGRateS 0.9.1~rc8 git+4835ba2 (2019-03-04T20:49:33+01:00)

1. Create Account
{
  "method": "ApierV2.SetAccount",
  "params": [
    {
      "Tenant": "cgrates.org",
      "Account": "999999",
      "ActionPlansOverwrite": true,
      "ActionTriggerOverwrite": true,
      "AllowNegative": false,
      "Disabled": false,
      "ReloadScheduler": true
    }
  ],
  "id": "d2df89ad-1fcc-43b5-a77b-8cb2499cfd3d"
}
2. Create Balance: 
{
  "method": "ApierV2.AddBalance",
  "params": [
    {
      "Tenant": "cgrates.org",
      "Account": "999999",
      "BalanceType": "*monetary",
      "BalanceID": "National_Calls",
      "Value": 50, <--------------------------- 50 !
      "Weight": 0,
      "Overwrite": true,
      "Blocker": false,
      "Disabled": false,
      "Cdrlog": true
    }
  ],
  "id": "d7700a32-d671-4167-bbdd-e581e51c6804"
}
3. RESULT:
{
  "error": null,
  "id": "dbe107cd-912e-4f79-93d1-092aaa48a984",
  "result": {
    "ID": "cgrates.org:999999",
    "BalanceMap": {
      "*monetary": [
        {
          "Uuid": "a908de19-a5a8-4f10-96ec-140873571274",
          "ID": "National_Calls",
          "Value": 49, <--------------------------- 49 Why !?
          "ExpirationDate": "0001-01-01T00:00:00+00:00",
          "Weight": 0,
          "DestinationIDs": "{}",
          "RatingSubject": "",
          "Categories": "{}",
          "SharedGroups": "{}",
          "TimingIDs": "{}",
          "Disabled": false,
          "Blocker": false
        }
      ]
    },
    "UnitCounters": null,
    "ActionTriggers": null,
    "AllowNegative": false,
    "Disabled": false
  }
}

**Comment by TeoV** [comment]
Hi Ibrahima,

We tried to reproduce this issue but without success.
When we verified the account we get the correct value ( we checked also the cdr from cdrlog if it has the correct value ): 
```
{
  "ID": "cgrates.org:999999",
  "BalanceMap": {
   "*monetary": [
    {
     "Uuid": "8e4cff56-f226-4b3f-a883-f5a405b32386",
     "ID": "National_Calls",
     "Value": 50,
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ]
  },
  "UnitCounters": null,
  "ActionTriggers": null,
  "AllowNegative": false,
  "Disabled": false
 }
```
Please make sure that you use the latest version of CGRateS. 
I will close this issue.

Thanks,
TeoV
