### ISSUE TITLE
 <CDRs> error: not convertible processing CDR event .... with ChargerS 

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1479]
Hi all,

Not changed anything our side apart from the latest master deb and seeing:

`<CDRs> error: not convertible processing CDR event &{Tenant:surevoip ID:70ef79c Time:2019-03-26 13:39:00.558931883 +0000 UTC Event:map[CLI:XXXX HasRecording:no OriginID:146288407 <snip> OriginHost:10.255.0.2 SetupTime:2019-03-26T13:37:33 ToR:*voice Usage:4s]} with ChargerS`

Since going on to version:

cgr> status
{
 "ActiveGoroutines": 69,
 "Footprint": "70.9MiB",
 "GoVersion": "go1.11.4",
 "MemoryUsage": "21.4MiB",
 "NodeID": "xxxx.suretec.net",
 "RunningSince": "Mon Mar 25 17:03:23 UTC 2019",
 "Version": "CGRateS 0.9.1~rc8 git+a6363e0 (2019-03-24T14:47:49+01:00)"
}

**Comment by danbogos** [comment]
Hi Gavin,

Have updated yesterday the sources with a possible fix, but that did not get into the .deb package. Please update now since I have generated a new package.

If issue still there should still help since we have added a more descriptive log.

Thanks,
DanB

**Comment by ghenry** [comment]
Hi Dan,

Great thanks! Looking forward to when your deb repo comes out and we can
fix to a certain version when deploying.

Gavin.
