### ISSUE TITLE
SM-Asterisk development

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#148]
Through this we should be able to cover all 4 charging modes which CGRateS supports: *prepaid, *postpaid, *pseudoprepaid and *rated. 

We need our own Asterisk AMI (v2) and will target Asterisk support starting with version 11.

DanB

**Comment by mdarii** [comment]
Hi, any update on that feature?

**Comment by danbogos** [comment]
Work in progress, should be test-able end of September.


DanB
