### ISSUE TITLE
Kernel Panic with 85998bf

### ISSUE THREAD

**Issue by stevehillin** [cgrates/cgrates#1488]
Opensips 2.3.6

Here is the panic:
:Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8bb3d]
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: goroutine 29 [running]:
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCv1InitiateSession(0xc00023e9a0, 0x0, 0x0, 0xc000569ab0, 0x0, 0x0, 0x0)
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:1917 +0xf0d
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCV1InitiateSession(0xc00023e9a0, 0x0, 0x0, 0xc000550d20, 0xc00034c2f8, 0xc0002bdb58, 0x414c15)
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:2539 +0x195
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: github.com/cgrates/cgrates/apier/v1.(*SMGenericV1).InitiateSession(0xc0006d2e70, 0xc000550d20, 0xc00034c2f8, 0x0, 0x0)
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/smg.go:44 +0x4a
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: reflect.Value.call(0xc000086d80, 0xc0006d2eb0, 0x13, 0x128ae2f, 0x4, 0xc0002bdf18, 0x3, 0x3, 0xc0002986c0, 0x11e2980, ...)
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/usr/local/go/src/reflect/value.go:447 +0x454
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: reflect.Value.Call(0xc000086d80, 0xc0006d2eb0, 0x13, 0xc000469718, 0x3, 0x3, 0x7f6de3804458, 0xc000469728, 0x40e1a8)
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/usr/local/go/src/reflect/value.go:308 +0xa4
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: net/rpc.(*service).call(0xc000299c00, 0xc000166000, 0xc00034c0f0, 0xc00034c110, 0xc0006c1e80, 0xc00025d680, 0x10e5a40, 0xc0000b80e0, 0x195, 0x104d280, ...)
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/usr/local/go/src/net/rpc/server.go:384 +0x14e
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: created by net/rpc.(*Server).ServeCodec
Mar 28 00:29:49 vtonebilling2 cgr-engine[29589]: #011/usr/local/go/src/net/rpc/server.go:481 +0x47e
Mar 28 00:29:49 vtonebilling2 systemd[1]: cgrates.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 28 00:29:49 vtonebilling2 systemd[1]: cgrates.service: Unit entered failed state.
Mar 28 00:29:49 vtonebilling2 systemd[1]: cgrates.service: Failed with result 'exit-code'.
Mar 28 00:29:49 vtonebilling2 systemd[1]: cgrates.service: Service hold-off time over, scheduling restart.
Mar 28 00:29:49 vtonebilling2 systemd[1]: Stopped Control CGRateS - carrier grade real-time charging system.
Mar 28 00:29:49 vtonebilling2 systemd[1]: Started Control CGRateS - carrier grade real-time charging system.
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting CGRateS Session service.
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <ServiceManager> Starting CGRateS Scheduler.
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting CGRateS CDRS service.
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <CDRC> No enabled CDRC clients
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting Attribute service
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: WARNING: missing TLS certificate/key file!
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: WARNING: missing TLS certificate/key file!
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: WARNING: missing TLS certificate/key file!
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <HTTP> enabling handler for JSON-RPC
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <HTTP> enabling handler for WebSocket connections
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <HTTP> start listening at <:2080>
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting ChargerS
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting CGRateS JSON server at <:2012>.
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting CGRateS GOB server at <:2013>.
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Registering CDRS HTTP Handlers.
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Registering CDRS RPC service.
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "Call" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "RegisterHandlersToServer" has 2 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCV1GetMaxUsage" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCV1InitiateSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCV1ProcessCDR" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCV1TerminateSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCV1UpdateSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "Handlers" has 1 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCPing" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1AuthorizeEvent" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1AuthorizeEventWithDigest" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1ForceDisconnect" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1GetActiveSessions" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1GetActiveSessionsCount" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1GetPassiveSessions" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1GetPassiveSessionsCount" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1InitiateSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1InitiateSessionWithDigest" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1ProcessCDR" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1ProcessEvent" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1RegisterInternalBiJSONConn" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1ReplicateSessions" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1SetPassiveSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1SyncSessions" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1TerminateSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "BiRPCv1UpdateSession" has 4 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 cgr-engine[29699]: 2019/03/28 00:29:49 rpc.Register: method "Handlers" has 1 input parameters; needs exactly three
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: Starting CGRateS BiJSON server at <127.0.0.1:2014>
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <Scheduler> processing 175 action plans
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <Scheduler> queued 175 action plans
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <Scheduler> Scheduler queue length: 175
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <Scheduler> Action: ACT_TOPUP_RST_APCGeek
Mar 28 00:29:49 vtonebilling2 CGRateS <cgrates2> [29699]: <Scheduler> Time to next action (ACT_TOPUP_RST_APCGeek): 23h30m10.370263368s

The request (redacted)
{ "method": "SMGenericV1.InitiateSession", "id": 904292344, "params": [ { "RequestType": "*rated", "Account": "Customer1", "Category": "INBOUND", "Destination": "12810000000", "OriginID": "1011525039-0-3253264298@64.136.173.226", "DialogID": 1715036899, "DialogEntry": 1882, "SetupTime": "1553750988", "AnswerTime": "1553750989" } ] }

cgr-console status
{
 "ActiveGoroutines": 22,
 "Footprint": "69.4MiB",
 "GoVersion": "go1.11.4",
 "MemoryUsage": "4.4MiB",
 "NodeID": "cgrates2",
 "RunningSince": "Thu Mar 28 00:25:06 CDT 2019",
 "Version": "CGRateS 0.9.1~rc8 git+85998bf (2019-03-13T14:32:52+02:00)"
}

**Comment by danbogos** [comment]
hey  @stevehillin 

Any chance you can reproduce the panic on the latest master?

Ta,
DanB

**Comment by stevehillin** [comment]
I just pulled down the lastest .deb (b2cd78a) and I will test off-hours against this.

Thanks,
Steve

**Comment by stevehillin** [comment]
Still panicked:

{
 "ActiveGoroutines": 26,
 "Footprint": "69.2MiB",
 "GoVersion": "go1.11.4",
 "MemoryUsage": "4.1MiB",
 "NodeID": "cgrates2",
 "RunningSince": "Mon Apr  1 01:49:46 CDT 2019",
 "Version": "CGRateS 0.9.1~rc8 git+b2cd78a (2019-03-26T18:41:52+02:00)"
}

Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: panic: runtime error: invalid memory address or nil pointer dereference
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe9f955]
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: goroutine 1050 [running]:
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCv1InitiateSession(0xc000402580, 0x0, 0x0, 0xc0009e7ab0, 0x0, 0x0, 0x0)
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:1922 +0xf05
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCV1InitiateSession(0xc000402580, 0x0, 0x0, 0xc0004f9bc0, 0xc000958240, 0xc0008f2b58, 0x414c15)
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessions/sessions.go:2606 +0x195
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: github.com/cgrates/cgrates/apier/v1.(*SMGenericV1).InitiateSession(0xc00000ea88, 0xc0004f9bc0, 0xc000958240, 0x0, 0x0)
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/smg.go:44 +0x4a
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: reflect.Value.call(0xc0000baa80, 0xc00000eac8, 0x13, 0x12aed8f, 0x4, 0xc0008f2f18, 0x3, 0x3, 0xc00044dc40, 0x1204fe0, ...)
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/usr/local/go/src/reflect/value.go:447 +0x454
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: reflect.Value.Call(0xc0000baa80, 0xc00000eac8, 0x13, 0xc0008dc718, 0x3, 0x3, 0x7f153eddaf70, 0xc0008dc728, 0xc001283400)
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/usr/local/go/src/reflect/value.go:308 +0xa4
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: net/rpc.(*service).call(0xc00044c900, 0xc000186000, 0xc000ae60c8, 0xc000ae60e0, 0xc00018ac00, 0xc000aba240, 0x1105000, 0xc001164000, 0x195, 0x106a8a0, ...)
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/usr/local/go/src/net/rpc/server.go:384 +0x14e
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: created by net/rpc.(*Server).ServeCodec
Apr  1 01:47:44 vtonebilling2 cgr-engine[31992]: #011/usr/local/go/src/net/rpc/server.go:481 +0x47e
Apr  1 01:47:44 vtonebilling2 systemd[1]: cgrates.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr  1 01:47:44 vtonebilling2 systemd[1]: cgrates.service: Unit entered failed state.
Apr  1 01:47:44 vtonebilling2 systemd[1]: cgrates.service: Failed with result 'exit-code'.
Apr  1 01:47:44 vtonebilling2 systemd[1]: cgrates.service: Service hold-off time over, scheduling restart.
Apr  1 01:47:44 vtonebilling2 systemd[1]: Stopped Control CGRateS - carrier grade real-time charging system.
Apr  1 01:47:44 vtonebilling2 systemd[1]: Started Control CGRateS - carrier grade real-time charging system.
Apr  1 01:47:44 vtonebilling2 cgr-engine[19679]: No versions defined: please backup cgrates data and run : <cgr-migrator -migrate=*set_versions>

**Comment by danbogos** [comment]
hey Steve,

Can you please attach also the ngrep towards SessionS?

Thanks,
DanB

**Comment by danbogos** [comment]
hey Steve,

In case you have missed, can u add also ngrep towards SessionS?

Thanks,
DanB

**Comment by stevehillin** [comment]
Dan,
Yes, I'm going to, just been pretty busy this week.  I'll try to get to you
today.

Thanks,
Steve

**Comment by danbogos** [comment]
Closing the issue due to inactivity.
