### ISSUE TITLE
Wrong balance deduction

### ISSUE THREAD

**Issue by m00zi** [cgrates/cgrates#1502]
Hi,

CGRates version:

`CGRateS 0.9.1~rc8 git+5910d3a (2018-12-17T08:35:22-05:00)`

recently I've noticed that some users usage is abnormal, let say the remaining data = 1000  means 1GB and the usage value is = 100 (mean 100MB) so the balance value should become 900 (mean 900 MB left) after 100MB deduction, but for some session the calculation result is wrong, I don't know why this is happening, is there anything related to Core network or CGRateS configuration ?

**here is the MongoDB query to check the balance deduction statistics :**

 
```
db.sessions_costs.find(
        {
            "costdetails.accountsummary.id": "123456789"
        }, 
        {
            "usage": 1, 
            "costdetails.starttime": 1,
            "costdetails.accountsummary.balancesummaries.value": 1, 
            "_id": 0
        }
    ).sort({"costdetails.starttime": -1}).pretty()


and here is the result:

{
	"usage" : NumberLong(116),
	"costdetails" : {
		"starttime" : ISODate("2019-03-30T13:27:49Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 59
				}
			]
		}
	}
}
```

**So here is the wrong calculation**
(The last balance value was = 7744 and the usage after that was 825 mean (7744 - 825) = 6919 , while the value become 175 instead)

```
{
	"usage" : NumberLong(825),
	"costdetails" : {
		"starttime" : ISODate("2019-03-28T19:24:35Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 175
				}
			]
		}
	}
}
{
	"usage" : NumberLong(37),
	"costdetails" : {
		"starttime" : ISODate("2019-03-28T12:11:51Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 7744
				}
			]
		}
	}
}
{
	"usage" : NumberLong(1362),
	"costdetails" : {
		"starttime" : ISODate("2019-03-27T14:38:58Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 7831
				}
			]
		}
	}
}
{
	"usage" : NumberLong(560),
	"costdetails" : {
		"starttime" : ISODate("2019-03-26T14:34:29Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 9193
				}
			]
		}
	}
}
{
	"usage" : NumberLong(1029),
	"costdetails" : {
		"starttime" : ISODate("2019-03-25T17:39:26Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 9753
				}
			]
		}
	}
}
{
	"usage" : NumberLong(394),
	"costdetails" : {
		"starttime" : ISODate("2019-03-25T14:04:09Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 10782
				}
			]
		}
	}
}
{
	"usage" : NumberLong(253),
	"costdetails" : {
		"starttime" : ISODate("2019-03-24T14:24:06Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 11176
				}
			]
		}
	}
}
{
	"usage" : NumberLong(722),
	"costdetails" : {
		"starttime" : ISODate("2019-03-23T13:11:08Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 11429
				}
			]
		}
	}
}
{
	"usage" : NumberLong(888),
	"costdetails" : {
		"starttime" : ISODate("2019-03-22T09:31:49Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 12151
				}
			]
		}
	}
}
{
	"usage" : NumberLong(563),
	"costdetails" : {
		"starttime" : ISODate("2019-03-21T17:12:52Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 13039
				}
			]
		}
	}
}
{
	"usage" : NumberLong(133),
	"costdetails" : {
		"starttime" : ISODate("2019-03-19T14:36:05Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 14659
				}
			]
		}
	}
}
{
	"usage" : NumberLong(395),
	"costdetails" : {
		"starttime" : ISODate("2019-03-18T16:55:05Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 14792
				}
			]
		}
	}
}
{
	"usage" : NumberLong(121),
	"costdetails" : {
		"starttime" : ISODate("2019-03-18T12:51:35Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 15187
				}
			]
		}
	}
}
{
	"usage" : NumberLong(143),
	"costdetails" : {
		"starttime" : ISODate("2019-03-17T17:33:13Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 15308
				}
			]
		}
	}
}
{
	"usage" : NumberLong(16),
	"costdetails" : {
		"starttime" : ISODate("2019-03-17T17:23:19Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 15451
				}
			]
		}
	}
}
{
	"usage" : NumberLong(0),
	"costdetails" : {
		"starttime" : ISODate("2019-03-17T17:23:02Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 15467
				}
			]
		}
	}
}
{
	"usage" : NumberLong(15),
	"costdetails" : {
		"starttime" : ISODate("2019-03-17T16:39:23Z"),
		"accountsummary" : {
			"balancesummaries" : [
				{
					"value" : 15467
				}
			]
		}
	}
}

```

**Comment by TeoV** [comment]
Hi @m00zi,

Please add here a full CDR, because the description is not enough for us to figure it out where the issue can be.

Thanks,
TeoV

**Comment by m00zi** [comment]
Hello TeoV, 

please find the attached usage details for a user with USER ID: **11004060**, 

check the _id (`5ca3074898fbe03865ebf624`) the remaining value at (`2019-04-01T20:45:39Z`) was => **6329 MB**
in the next transaction in _id `5ca321b698fbe03865ec0d58` user usage was `0MB` (`"usage" : NumberLong(0)`) but the value become => `3179`
which is for `0MB` usage CGRate deduct `3150MB`

[11004060_usage.txt](https://github.com/cgrates/cgrates/files/3083244/11004060_usage.txt)

**Comment by TeoV** [comment]
Hi @m00zi 

We have analyzed your CDRs. Indeed it's strange how the value has changed. 
First:  This problem with Usage was fixed in master.
Second: Do you operate on the account outside of CDR ( do a manual debit, topup, etc...) or do you have multiple RALs which do multiple debits for the same account?
Can you please describe your setup: how do you use CGRateS, together with what software, etc...?

Thanks,
TeoV

**Comment by m00zi** [comment]
Hi, no we don't have any other app or external operation on accounts, we have CGRates only, and the setup is very basic, the user will do recharge and we are updating via balance_set, but before balance_set we are retrieving the old balance, and then + with new balance and then balance_set

**Comment by TeoV** [comment]
Hi @m00zi,

When you do balance_set please do it with cdr ( you have a parameter cdrlog. Put this on true and send us the cdrs so we can check if the balance changed during the call ). 

Thanks,
TeoV

**Comment by m00zi** [comment]
sorry, I didn't get you, would you please elaborate more?

**Comment by TeoV** [comment]
Hi @m00zi, 

When you do a balance operation you can generate a CDR for that operation. 
For example, if you do a balance_set and you have cdrlog parameter on true CGRateS will create a CDR for that. In the CDR you will find information regarding the amount that was added, the source, etc... It's like a normal CDR.
This can help us to check if the balance is changing during the call or what happens with the account. 

Thanks,
TeoV

**Comment by m00zi** [comment]
Hi TeoV, 

You mean in `cgrates.json` I can add this parameter? if so :

1- Do you have a sample of cgrates.json including this option?
2- Do I need to restart the cgreates service after adding this option?

thanks 
m00zi

**Comment by TeoV** [comment]
Hi @m00zi,

No, you don't have to do anything in your config. 
If you do balance_set from cgr-console there you have a parameter **Cdrlog**. 
```
teo@debian:~$ cgr-console 
Welcome to CGRateS console!
Type `help` for a list of commands

cgr> help balance_set

	Usage: balance_set Tenant="" Account="" BalanceType="*monetary" BalanceUUID=null BalanceID=null Directions=null Value=null ExpiryTime=null RatingSubject=null Categories=null DestinationIds=null TimingIds=null Weight=null SharedGroups=null Blocker=null Disabled=null Cdrlog=null ExtraData=null 
```
If you do balance_set by sending an API to the engine you have the same parameter .
Now if you set this on true it will generate a CDR for your balance operation.
Hope now all is clear.

Thanks,
TeoV

**Comment by m00zi** [comment]
Hello TeoV, 

Here I am sending these parameters to CGRates endpoint: 

 ```
      Account: "11004060",
      BalanceType: "*data",
      BalanceId: "basic",
      Value: 1000,
      ExpiryTime: expiration_time,
      Directions: "*out",
      Weight: 10,
      Cdrlog: true,
```

shall I add the `Cdrlog: true` and make it like the below one:

 ```
      Account: "11004060",
      BalanceType: "*data",
      BalanceId: "basic",
      Value: 1000,
      ExpiryTime: expiration_time,
      Directions: "*out",
      Weight: 10,
      Cdrlog: true,
```

and then what is the next ? what should I track and expect? and depending on the output what should I do?

**Comment by TeoV** [comment]
Hi @m00zi,

After that, you should verify if the topup/topup_reset operations are done correctly ( topup the amount that you expected ).

Thanks,
TeoV

**Comment by TeoV** [comment]
Hi @m00zi,

Any news about this issue? 

Thanks,
TeoV
