### ISSUE TITLE
cgr-console deletion/remove protection

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1514]
Hi,

For any of the commands that end in _rem, I'd like there to be a protection prompt of "Are you sure? y/n" or similar.
I just wiped out tons of RatingProfiles by accident.

Thanks.

**Comment by ghenry** [comment]
I did this to get help:

`cgr> ratingprofile_rem`

and then a scary OK appeared which wiped out all my RatingProfiles.

**Comment by ghenry** [comment]
Would it be possible to have protection on all _rem commands or was it only this one that just went ahead and removed everything?

**Comment by danbogos** [comment]
hi Gavin,

We hope only this one should be with issues. If you find any other, please report here and will treat it separately.

Thanks,
DanB

**Comment by ghenry** [comment]
Understood.
