### ISSUE TITLE
Contribution guide ?

### ISSUE THREAD

**Issue by okandas** [cgrates/cgrates#1518]
Would like to contirbute to this open source project but there is no guide as to how to go about it.

**Comment by danbogos** [comment]
Hi @okandas 

If you are asking about technical details on how to contribute, github makes it pretty simple. You should just sign [contributors](https://github.com/cgrates/cgrates/blob/master/CONTRIBUTORS.md) file and send us your PR with the desired changes to the code. Not sure if that is what you are asking.

Thanks,
DanB

**Comment by okandas** [comment]
@danbogos it is and thought you had a specific way of making a PR. Thanks
