### ISSUE TITLE
DiameterAgent not using the second SessionS when having multiple SessionS in sessions_conns

### ISSUE THREAD

**Issue by mortchm** [cgrates/cgrates#1523]
Hi,

here is my config

[cgrates-multi-sessions.tar.gz](https://github.com/cgrates/cgrates/files/3081087/cgrates-multi-sessions.tar.gz)

when the two sessions_server are up, i get an answer to ccr but when i kill the first SessionS, then i see no request to the second SessionS and there is no answer to ccr

here is the version, i use:

`
# cgr-engine -version
CGRateS 0.9.1~rc8 git+39f9d5f (2019-04-05T20:15:16+02:00)
`
Thanks

Michael

**Comment by Trial97** [comment]
Hi @mortchm,

We observed that in your diameter configuration file you did not set the number of reconnects.
By default it's value is -1(https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L46) so it will try to reconnect to the first connection until it can send the request.
Please set  "reconnects" in your configuration files with a value other than -1 and retest.

Thanks,
Trial97

**Comment by mortchm** [comment]
Hi,

thanks a lot, it works
