### ISSUE TITLE
Feature Request: cgr-exporter

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1529]
Export all or specific services back to csv.

**Comment by ghenry** [comment]
Can I help with this?

**Comment by danbogos** [comment]
Hey @ghenry 

Sure, do u mean by writing the code or?

Thanks,
DanB

**Comment by ghenry** [comment]
Yeah :) I'll give it a shot!

**Comment by danbogos** [comment]
K, once you have it implemented, please send us a PR and we will check.

DanB

**Comment by ghenry** [comment]
Hi Dan,

Quick question, in cgr-migrator.go there is a lot of similar config loading code:

https://github.com/cgrates/cgrates/blob/master/cmd/cgr-loader/cgr-loader.go#L116

and

https://github.com/cgrates/cgrates/blob/master/cmd/cgr-migrator/cgr-migrator.go#L139

rather than me just have another place (e.g. `cgr-exporter.go`) in `cmd` namespace that duplicates this, did you have any plans to move this into `utils` namespace or other ideas?

Maybe move https://github.com/cgrates/cgrates/blob/master/cmd/cgr-loader/cgr-loader.go#L107 into `utils` and use that in migrator and loader?

Thanks.

**Comment by TeoV** [comment]
Hi @ghenry,

If you want you can open a separate issue and we will try to unify them.

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi TeoV,

I was thinking last night before falling asleep of something better.

How about merging `cgr-migrator` and `cgr-loader` to create `cdr-data`?

Then we have:

```
cgr-data -migrate
cgr-data -import
cgr-data -export
```

No need to for a new utils addition. Or one step further and merge `cgr-console` too to create a brand new:

```
cgr-client 
cgr-client -import-data
cgr-client -export-data
cgr-client -migrate-data
```

This would save a ton of duplicate work. A lot of users use `cgr-console` in scripts so calling it `cgr-client` might make more sense.

To retain backwards compatibility you can create symlinks from your packages and you can exhibit different behaviour if needed based on that. That's what we do in the OpenLDAP projects. He's a simple example:

```
~/go/src/diffname $ cat diffname.go 
 package main

 import (
    "os"
    "fmt"
 )

 func main() {
    fmt.Fprintf(os.Stderr, "your own program name is %s \n", os.Args[0])

 }

~/go/src/diffname $ ./diffname 
your own program name is ./diffname 

~/go/src/diffname $ ll
total 1976
drwxr-xr-x 2 ghenry ghenry    4096 Feb 24 11:33 ./
drwxr-xr-x 6 ghenry ghenry    4096 Feb 24 11:33 ../
-rwxr-xr-x 1 ghenry ghenry 2010095 Feb 24 11:33 diffname*
-rw-r--r-- 1 ghenry ghenry     140 Feb 24 11:33 diffname.go
lrwxrwxrwx 1 ghenry ghenry       8 Feb 24 11:33 gavin -> diffname*

~/go/src/diffname $ ./gavin 
your own program name is ./gavin 
```

Just in case you hadn't guessed above :-)

Thoughts?

Thanks.

**Comment by TeoV** [comment]
Hi Gavin,

Each binary does a limited number of tasks.
The import and export will be done from cgr-engine.
Cgr-migrator cannot be combined because it needs connection to datadb and stordb and does migration tasks.
Cgr-console, from our point, is ok it doesn't need renaming.

Thanks,
TeoV

**Comment by ghenry** [comment]
Thanks for the info. Looks like I don't need to do anything then.

**Comment by ghenry** [comment]
Hi @TeoV ,

Looks like you have this ability already?

https://github.com/cgrates/cgrates/blob/v0.10.0/engine/tpexporter.go
https://github.com/cgrates/cgrates/blob/master/engine/tpexporter.go

That's all I was looking for. A way to export to CSV exactly what you imported via CSV.

https://godoc.org/github.com/cgrates/cgrates/apier/v1#APIerSv1.ExportCdrsToZipString
https://godoc.org/github.com/cgrates/cgrates/apier/v1#APIerSv1.ExportTPToFolder

for 5 years now. Why didn't you say or why didn't I notice! :-)

**Comment by TeoV** [comment]
Hi @ghenry,

ExportTPToFolder is used to export the tariff plan from StorDB back to file.
Regarding ExportCdrsToZipString export the cdrs to a zip.

Thanks,
TeoV

**Comment by ghenry** [comment]
https://godoc.org/github.com/cgrates/cgrates/apier/v1#APIerSv1.ExportTPToFolder dies a full backup of all your original csv data. That's what I wanted. It will miss somethings though that aren't in a tp of course. Will have a play
