### ISSUE TITLE
Cgrates  fsagent crashing INVALIDARGUMENT

### ISSUE THREAD

**Issue by Durihub10** [cgrates/cgrates#1531]
Hi 
Cgrates is crashing with below error :

 "Version": "CGRateS 0.9.1~rc8 git+74ef3c8 (2019-04-20T14:37:58+02:00)"

extract from freeswitch socket

api uuid_setvar fcaed9bc-a1b8-44be-bd42-64e9fc802e1a cgr_notify RALS_ERROR:NO_ACTIVE_SESSION

Panic error in cgrates log :
_

- Apr 21 10:21:32 host1 cgr-engine: panic: runtime error: invalid memory address or nil pointer dereference
- Apr 21 10:21:32 host1 cgr-engine: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10390d4]
- Apr 21 10:21:32 host1 cgr-engine: goroutine 2561 [running]:
- Apr 21 10:21:32 host1 cgr-engine: github.com/cgrates/cgrates/agents.(*FSsessions).disconnectSession(0xc000446c80, 0x0, 0x0, 0xc0008417c3, 0x24, 0x0, 0x0, 0x140f506, 0x13, 0xc000601730, ...)
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/agents/fsagent.go:322 +0x154
- Apr 21 10:21:32 host1 cgr-engine: github.com/cgrates/cgrates/agents.(*FSsessions).V1DisconnectSession(0xc000446c80, 0xc0009074a0, 0x140f506, 0x13, 0xc0006016d0, 0x0, 0x0)
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/agents/fsagent.go:381 +0x215
- Apr 21 10:21:32 host1 cgr-engine: reflect.Value.call(0x1345a80, 0xc000446c80, 0xe13, 0x13fbd31, 0x4, 0xc00047dd40, 0x2, 0x2, 0xc00037c8f0, 0x13, ...)
- Apr 21 10:21:32 host1 cgr-engine: /usr/lib/golang/src/reflect/value.go:447 +0x461
- Apr 21 10:21:32 host1 cgr-engine: reflect.Value.Call(0x1345a80, 0xc000446c80, 0xe13, 0xc00047dd40, 0x2, 0x2, 0xc000446c80, 0xe13, 0x2)
- Apr 21 10:21:32 host1 cgr-engine: /usr/lib/golang/src/reflect/value.go:308 +0xa4
- Apr 21 10:21:32 host1 cgr-engine: github.com/cgrates/cgrates/utils.RPCCall(0x1345a80, 0xc000446c80, 0x141a47e, 0x1c, 0x12aa1a0, 0xc000312420, 0x11bf6a0, 0xc0006016d0, 0xc000312420, 0xc000312420)
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/utils/coreutils.go:843 +0x361
- Apr 21 10:21:32 host1 cgr-engine: github.com/cgrates/cgrates/agents.(*FSsessions).Call(0xc000446c80, 0x141a47e, 0x1c, 0x12aa1a0, 0xc000312420, 0x11bf6a0, 0xc0006016d0, 0xc0004e2bb8, 0xc0003dd70c)
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/agents/fsagent.go:374 +0x80
- Apr 21 10:21:32 host1 cgr-engine: github.com/cgrates/cgrates/sessions.(*SessionS).disconnectSession(0xc000209340, 0xc0003640a0, 0x140f506, 0x13, 0xc00030fc01, 0x3)
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/sessions/sessions.go:679 +0x22b
- Apr 21 10:21:32 host1 cgr-engine: github.com/cgrates/cgrates/sessions.(*SessionS).debitLoopSession.func1(0xc0003640a0, 0x0, 0xc000209340)
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/sessions/sessions.go:546 +0x13a
- Apr 21 10:21:32 host1 cgr-engine: created by github.com/cgrates/cgrates/sessions.(*SessionS).debitLoopSession
- Apr 21 10:21:32 host1 cgr-engine: /cgrates/go/src/github.com/cgrates/cgrates/sessions/sessions.go:541 +0x227
- Apr 21 10:21:32 host1 systemd: cgrates.service: main process exited, code=exited, status=2/INVALIDARGUMENT

_

**Comment by danbogos** [comment]
Hi @Durihub10 

Please provide the following:
 * Your cgrates.json configuration
 * After configuring the components to reach each other on :2012 and transport *json, capture the traffic between them with ngrep (ngrep -t -W byline port 2012 -d any)
 * Traffic capture between CGRateS and FreeSWITCH (ngrep on port 8021)
 * Syslog entries before the panic.


Ta,
DanB

**Comment by kmuchinenyika** [comment]
Hi @danbogos 

I am also facing a very similar issue:

My cgrates configuration file, :
[cgrates_config.txt](https://github.com/cgrates/cgrates/files/3113747/cgrates_config.txt)

The ngrep -t -W byline port 2012 -d any: on cgrates port, about 2 minutes before panic
[cgrates_panic.txt](https://github.com/cgrates/cgrates/files/3113750/cgrates_panic.txt)

The ngrep on freeswitch port 8021, about 2 minutes before the panic:
[freeswitch_panic.txt](https://github.com/cgrates/cgrates/files/3113752/freeswitch_panic.txt)

The syslog entries before and during the panic:
[syslog_panic.txt](https://github.com/cgrates/cgrates/files/3113753/syslog_panic.txt)

**Comment by danbogos** [comment]
hi  @kmuchinenyika 

Please post here also your config version.

Thanks,
DanB

**Comment by kmuchinenyika** [comment]
hi @danbogos 

Config version: "Version": "CGRateS 0.9.1~rc8 git+74ef3c8

**Comment by Durihub10** [comment]
Hi ,
I still have below error , try  upgrading  to last commit " CGRateS 0.9.1~rc8 git+f6a9ec0 (2019-04-26T15:59:02+02:00)"

Syslog Error is 

Apr 29 08:03:47 shagi cgr-engine: panic: runtime error: invalid memory address or nil pointer dereference
Apr 29 08:03:47 shagi cgr-engine: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1039734]
Apr 29 08:03:47 shagi cgr-engine: goroutine 879 [running]:
Apr 29 08:03:47 shagi cgr-engine: github.com/cgrates/cgrates/agents.(*FSsessions).disconnectSession(0xc00057a1c0, 0x0, 0x0, 0xc0009757c5, 0x24, 0x0, 0x0, 0x141136d, 0x13, 0xc0005fe070, ...)
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/agents/fsagent.go:322 +0x154
Apr 29 08:03:47 shagi cgr-engine: github.com/cgrates/cgrates/agents.(*FSsessions).V1DisconnectSession(0xc00057a1c0, 0xc00012a0f0, 0x141136d, 0x13, 0xc0005fe000, 0x0, 0x0)
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/agents/fsagent.go:381 +0x215
Apr 29 08:03:47 shagi cgr-engine: reflect.Value.call(0x13478c0, 0xc00057a1c0, 0xe13, 0x13fdb71, 0x4, 0xc00013ed40, 0x2, 0x2, 0xc0006b2018, 0x13, ...)
Apr 29 08:03:47 shagi cgr-engine: /usr/lib/golang/src/reflect/value.go:447 +0x461
Apr 29 08:03:47 shagi cgr-engine: reflect.Value.Call(0x13478c0, 0xc00057a1c0, 0xe13, 0xc00013ed40, 0x2, 0x2, 0xc00057a1c0, 0xe13, 0x2)
Apr 29 08:03:47 shagi cgr-engine: /usr/lib/golang/src/reflect/value.go:308 +0xa4
Apr 29 08:03:47 shagi cgr-engine: github.com/cgrates/cgrates/utils.RPCCall(0x13478c0, 0xc00057a1c0, 0x141c32b, 0x1c, 0x12ac0a0, 0xc000218000, 0x11c1600, 0xc0005fe000, 0xc000218000, 0xc000218000)
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/utils/coreutils.go:843 +0x361
Apr 29 08:03:47 shagi cgr-engine: github.com/cgrates/cgrates/agents.(*FSsessions).Call(0xc00057a1c0, 0x141c32b, 0x1c, 0x12ac0a0, 0xc000218000, 0x11c1600, 0xc0005fe000, 0xc0005ef4b8, 0xc00047370c)
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/agents/fsagent.go:374 +0x80
Apr 29 08:03:47 shagi cgr-engine: github.com/cgrates/cgrates/sessions.(*SessionS).disconnectSession(0xc00019f4a0, 0xc000324fa0, 0x141136d, 0x13, 0xc000473701, 0x3)
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/sessions/sessions.go:679 +0x22b
Apr 29 08:03:47 shagi cgr-engine: github.com/cgrates/cgrates/sessions.(*SessionS).debitLoopSession.func1(0xc000324fa0, 0xb2d05e00, 0xc00019f4a0)
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/sessions/sessions.go:546 +0x13a
Apr 29 08:03:47 shagi cgr-engine: created by github.com/cgrates/cgrates/sessions.(*SessionS).debitLoopSession
Apr 29 08:03:47 shagi cgr-engine: /root/go/src/github.com/cgrates/cgrates/sessions/sessions.go:541 +0x227
Apr 29 08:03:47 shagi systemd: cgrates.service: main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by danbogos** [comment]
Hi @Durihub10 

Is the panic happening always, or randomly?

Thanks,
DanB

**Comment by Durihub10** [comment]
Hi Dan ,

It’s random but almost frequent

Thanx
