### ISSUE TITLE
cgr-loader context deadline exceeded

### ISSUE THREAD

**Issue by aqsyounas** [cgrates/cgrates#1532]
I am trying to upload my tarrifplans from mongo database(stor_db) to redis(data_db) using cgr-loader. i am using below command for that. 

 cgr-loader -verbose -stordb_host="localhost" -stordb_name="cgrates" -stordb_passwd="CGRateS.org" -stordb_port="27017" -stordb_type="*mongo" -stordb_user="cgrates" -from_stordb   -tpid="1" -config_path="/etc/cgrates/"

But this command gives below error. 

`2019/04/21 09:15:45 context deadline exceeded`

Sometimes, i get below error. 
`2019/04/21 09:13:26 connection(localhost:27017[-2]) failed to write: context deadline exceeded`

I have tried setting `query_timeout` to some bigger value as suggested by Dan for both data_db and store_db, but i see no effect. 

Mongo version

`MongoDB shell version v4.0.9
git version: fc525e2d9b0e4bceff5c2201457e564362909765
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: debian92
    distarch: x86_64
    target_arch: x86_64`

I am attaching to this thread the mongo collections dump files, cgrates.json file that can be used along with above cgr-loader command to reproduce the issue. 

[cgrates.zip](https://github.com/cgrates/cgrates/files/3101574/cgrates.zip)

**Comment by aqsyounas** [comment]
Forgot to mention cgrates version. 
`CGRateS 0.9.1~rc8 git+6b61917 (2019-04-18T20:09:51+02:00)`
 and discussion thread. 

https://groups.google.com/forum/#!topic/cgrates/Pvc-xLW-Yb8

**Comment by ryan-netizen** [comment]
Hi, 

Looks like i am getting this exact error on master. 
```
cgr> status
{
 "ActiveGoroutines": 48,
 "GoVersion": "go1.14",
 "MemoryUsage": "5.4MiB",
 "NodeID": "04cefdd",
 "RunningSince": "Mon Nov 23 06:32:36 UTC 2020",
 "Version": "CGRateS@v0.11.0~dev-20201119133434-920b304a6f94"
}
```
No matter what value i have for `query_timeout` in config.

```
"stor_db": {                                                            // database used to store offline tariff plans and CDRs
        "db_type": "*mongo",                                    // stor database type to use: <*mongo|*mysql|*postgres|*internal>
        "db_host": "127.0.0.1",                                 // the host to connect to
        "db_port": 27017,                                               // the port to reach the stor_db
        "db_name": "cgrates",                                   // stor database name
        "db_user": "cgrates",                                   // username to use when connecting to stor_db
        "db_password": "CGRateS.org",                                           // password to use when connecting to stor_db
        "query_timeout":"2000s",
},
```
The loader seems to be completely ignoring it and giving me context deadline error at around 10 seconds while reading data from `tp_destination_rates` collection. 

```
time cgr-loader -stordb_type="*mongo" -stordb_port="27017" -config_path="/etc/cgrates/" -from_stordb -tpid="1" -verbose
2020/11/23 06:43:53 context deadline exceeded

real    0m11.022s
user    0m13.726s
sys     0m0.512s
```

Should i open a separate issue or provide more details?

Really appreciate your great work.

Ryan

**Comment by ryan-netizen** [comment]
please, ignore  my earlier message. 
i have been using old config param with master. After adjusting config according to master it seems to be working. 

Now i have it like below. 

```
"stor_db": {                                                            // database used to store offline tariff plans and CDRs
        "db_type": "*mongo",                                    // stor database type to use: <*mongo|*mysql|*postgres|*internal>
        "db_host": "127.0.0.1",                                 // the host to connect to
        "db_port": 27017,                                               // the port to reach the stor_db
        "db_name": "cgrates",                                   // stor database name
        "db_user": "cgrates",                                   // username to use when connecting to stor_db
        "db_password": "CGRateS.org",                                           // password to use when connecting to stor_db
        "opts": {
                "max_open_conns": 100,                                  // maximum database connections opened, not applying for mongo
                "max_idle_conns": 10,                                   // maximum database connections idle, not applying for mongo
                "conn_max_lifetime": 0,                                 // maximum amount of time in seconds a connection may be reused (0 for unlimited), not applying for mongo
                "query_timeout":"300s",
        },
},
```

Thanks again for your efforts.  

Ryan
