### ISSUE TITLE
 Could not connect to Scheduler: UNSUPPORTED_CODEC 

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1534]
Please see:

https://groups.google.com/d/msg/cgrates/KzUPpGSFEWo/wpRyj9dEAQAJ

Transport error.

**Comment by TeoV** [comment]
Hi @ghenry,

This should be fixed in master : 
https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L736

Thanks,
TeoV
