### ISSUE TITLE
can't find service SMGenericV2.InitiateSession

### ISSUE THREAD

**Issue by negbie** [cgrates/cgrates#1540]
Dear CGRateS Team,

I'm trying to create a CGRateS output for heplify-server. I've looked through the rpc calls and found this one handy https://github.com/cgrates/cgrates/blob/master/utils/consts.go#L861
But it seems it got removed. Trying it with following code:

type CGREvent struct {
	ID      string
	Tenant  string
	Time    *time.Time // event time
	Event   map[string]interface{}
}
.....
....
....
		usage := time.Duration(1*time.Minute + 30*time.Second)
		smgEv := &CGREvent{
			ID: "idididididid123",
			Event: map[string]interface{}{
				"EventName":   "TEST_EVENT",
				"ToR":         "*voice",
				"OriginID":    "123456",
				"Direction":   "*out", // "*in"
				"Account":     "1001",
				"Subject":     "1001",
				"Destination": "1002",
				"Category":    "call",
				"Tenant":      "cgrates.org",
				"RequestType": "*prepaid", // "*postpaid"
				"SetupTime":   pkt.Timestamp,
				"AnswerTime":  pkt.Timestamp,
				"Usage":       usage,
			},
		}
		var maxUsage float64
		if err := c.rpcClient.Call("SMGenericV2.InitiateSession", smgEv, &maxUsage); err != nil {
			logp.Warn("%v", err)
		}

gives me "can't find service SMGenericV2.InitiateSession". I cannot find any reference in the code to it either so I think it got removed?

Trying more or less the same rpc call with "v1":
c.rpcClient.Call("SMGenericV1.InitiateSession", smgEv, &maxUsage)

Let's cgr-engine panic with:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf02cb5]

goroutine 45 [running]:
github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCv1InitiateSession(0xc0004d6420, 0x176c9e0, 0xc00017a000, 0xc0005c1b50, 0x0, 0x0, 0x0)
	/home/eugen/go/src/github.com/cgrates/cgrates/sessions/sessions.go:1990 +0x995
github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCV1InitiateSession(0xc0004d6420, 0x176c9e0, 0xc00017a000, 0xc0004a3bf0, 0xc0000b4760, 0xc000452c00, 0x415305)
	/home/eugen/go/src/github.com/cgrates/cgrates/sessions/sessions.go:2713 +0x191
github.com/cgrates/cgrates/apier/v1.(*SMGenericV1).BiRPCV1InitiateSession(...)
	/home/eugen/go/src/github.com/cgrates/cgrates/apier/v1/smgbirpc.go:45
reflect.Value.call(0x1251bc0, 0xc000333710, 0x13, 0x13fec11, 0x4, 0xc000452f48, 0x3, 0x3, 0x119d320, 0xc0001e16a8, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1251bc0, 0xc000333710, 0x13, 0xc0001e1748, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2.(*Client).handleRequest(0xc00017a000, 0x1, 0xc0003f8200, 0x1b, 0xc00013a480, 0x123c460, 0xc0003ec150, 0x195)
	/home/eugen/go/src/github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2/client.go:131 +0x1c4
created by github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2.(*Client).readRequest
	/home/eugen/go/src/github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2/client.go:181 +0x235

**Comment by negbie** [comment]
Which rpc call would you recommend for a sip capture server written in Go to talk with cdr-engine?

**Comment by negbie** [comment]
I saw Dan's presentation at opensips summit 2019 talking about fraud prevention with CGRateS and thought it would be cool feed cdr-engine from a sip capture server with events to achieve that.

**Comment by negbie** [comment]
Does it even makes sense in this case to work with sessions or would it be better to use ProcessCDR?

**Comment by negbie** [comment]
Sorry for the noise again. Still going through the docs and code I've found ThresholdSv1.ProcessEvent. Is it possible to just use that rpc call and enable only thresholds inside cgrates.json? So that the user just needs to import his Thresholds.csv and Filters.csv?

**Comment by negbie** [comment]
Ok calling ThresholdSv1.ProcessEvent with adjusted Thresholds.csv and Filters.csv seems to do something but would you suggest it using only thresholdS?

T 127.0.0.1:46974 -> 127.0.0.1:2012 [AP] #40
  {"method":"ThresholdSv1.ProcessEvent","params":[{"ThresholdIDs":null,"ID":"TestSessionsVoiceVoiceRefund","Event":{"Account":"1001","AnswerTime":"2019-05-05T19:58:12.593958+02:00","Category":"call","D
  estination":"1003","OriginID":"123452","RequestType":"*prepaid","SetupTime":"2019-05-05T19:58:12.593958+02:00","Subject":"1001","Tenant":"cgrates.org","ToR":"*voice","Usage":90000000000},"Tenant":"cg
  rates.org","Time":"2019-05-05T19:58:12.594537326+02:00"}],"id":4}.                                                                                                                                     
#
T 127.0.0.1:2012 -> 127.0.0.1:46974 [AP] #41
  {"id":4,"result":["THD_ACNT_1001"],"error":null}.

**Comment by TeoV** [comment]
Hi @negbie 

Please make sure that you use the latest version of CGRateS ( cgr-engine -version) because we tried to follow the trace of panic and the line doesn't match with the version from the master.
Regarding your other questions, please send them in separate threads to our google group, so the community can also benefit out of solutions given

Thanks,
TeoV

**Comment by negbie** [comment]
Hi @TeoV,
ok thanks. I will do that.
