### ISSUE TITLE
Feature Request: Export rated Cdrs via https

### ISSUE THREAD

**Issue by scharles-resilient** [cgrates/cgrates#1547]
Hi, 
We'd like to request a feature to export rated cdrs to AWS SQS through HTTPS (rather than HTTP).

The current configuration also specifies the AWS IAM credentials (key and secret key) in the export path. We would like to remove the need to specify this as our EC2 instance will be setup to have correct permissions to post to SQS.

Thanks,
Swetha

**Comment by Trial97** [comment]
Hi @scharles-resilient,
The library should handle the connection so all you  need to do is to specify a correct https endpoint.
Also if you do not specify the AWS IAM credentials in the export_path it will try to take them from in this order:

1.  Environment variables.
2.  Shared credentials 
3.  If your application is running on an Amazon EC2 instance, IAM role for Amazon EC2.

Thanks,
Trial97

**Comment by Trial97** [comment]
Hi @scharles-resilient ,

Can we consider this issue closed?

Thanks,
Trial97

**Comment by scharles-resilient** [comment]
Yes - thank you!
