### ISSUE TITLE
Unable to POST JSON RPC requests to CGRateS

### ISSUE THREAD

**Issue by asnaseer-resilient** [cgrates/cgrates#1548]
I manually created an EC2 instance via the AWS console and then did the following from VSCode Terminal (I have used 1.2.3.4 as the redacted IP address of this instance):
> scp -r -i cgrates.pem cgrates.json admin@1.2.3.4:/tmp/
> scp -r -i cgrates.pem sqsexporter.json admin@1.2.3.4:/tmp/
> ssh -i cgrates.pem admin@1.2.3.4
> sudo apt-get install telnet
> sudo apt-get install ngrep
> cd /tmp
> wget http://www.cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb
> sudo dpkg -i cgrates_0.9.1~rc8_amd64.deb
> sudo systemctl stop cgrates
> sudo rm -rf /etc/cgrates
> mkdir ~/cgretc
> sudo ln -s ~/cgretc /etc/cgrates
> cd ~/cgretc
> mv /tmp/cgrates.json .
> mv /tmp/sqsexporter.json .
> sudo systemctl start cgrates
> sudo systemctl status cgrates
> sudo netstat -tulpn
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      497/sshd            
tcp6       0      0 :::22                   :::*                    LISTEN      497/sshd            
udp        0      0 127.0.0.1:323           0.0.0.0:*                           494/chronyd         
udp        0      0 0.0.0.0:68              0.0.0.0:*                           295/dhclient        
udp6       0      0 ::1:323                 :::*                                494/chronyd         
udp6       0      0 fe80::62:fbff:feef::546 :::*                                363/dhclient 
```

I then connected to the EC2 that we created we Dan when he was training us and ran netstat on that as follows:
> ssh -i cgrates.pem admin@5.6.7.8
> sudo netstat -tulpn
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      11102/sshd          
tcp        0      0 127.0.0.1:2012          0.0.0.0:*               LISTEN      19752/cgr-engine    
tcp        0      0 127.0.0.1:2013          0.0.0.0:*               LISTEN      19752/cgr-engine    
tcp6       0      0 :::22                   :::*                    LISTEN      11102/sshd          
tcp6       0      0 :::2080                 :::*                    LISTEN      19752/cgr-engine    
udp        0      0 127.0.0.1:323           0.0.0.0:*                           503/chronyd         
udp        0      0 0.0.0.0:68              0.0.0.0:*                           295/dhclient        
udp6       0      0 ::1:323                 :::*                                503/chronyd         
udp6       0      0 fe80::497:6bff:fe95:546 :::*                                357/dhclient   
```

This instance is also listening on ports *2012*, *2013* and *2080*. We believe this is why we cannot POST any JSON RPC requests to the new CGRateS EC2 instance (as we POST to http://1.2.3.4:2080/jsonrpc).

If we look at the syslog after restarting CGRateS we see:
```
May  8 15:04:04 ip-10-177-241-223 systemd[1]: Stopping Control CGRateS - carrier grade real-time charging system...
May  8 15:05:05 ip-10-177-241-223 dhclient[363]: XMT: Solicit on eth0, interval 112500ms.
May  8 15:05:35 ip-10-177-241-223 systemd[1]: cgrates.service: State 'stop-sigterm' timed out. Killing.
May  8 15:05:35 ip-10-177-241-223 systemd[1]: cgrates.service: Killing process 966 (cgr-engine) with signal SIGKILL.
May  8 15:05:35 ip-10-177-241-223 systemd[1]: cgrates.service: Main process exited, code=killed, status=9/KILL
May  8 15:05:35 ip-10-177-241-223 systemd[1]: Stopped Control CGRateS - carrier grade real-time charging system.
May  8 15:05:35 ip-10-177-241-223 systemd[1]: cgrates.service: Unit entered failed state.
May  8 15:05:35 ip-10-177-241-223 systemd[1]: cgrates.service: Failed with result 'timeout'.
May  8 15:05:35 ip-10-177-241-223 systemd[1]: Started Control CGRateS - carrier grade real-time charging system.
```

We cannot work out why these ports are not being listened to on our new installation.

I can supply a copy of the *cgrates.json* and *sqsexporter.json* that we used in the manually configured EC2 instance if required.

**NOTE**:
- New instance has version CGRateS 0.9.1~rc8 git+6b61917 (2019-04-18T20:09:51+02:00)
- Dan installed instance has version CGRateS 0.9.1~rc8 git+4835ba2 (2019-03-04T20:49:33+01:00)

**Comment by asnaseer-resilient** [comment]
Some more information on this issue:
Running `cgr-console status` on Dan's instance gives:
```
{
 "ActiveGoroutines": 28,
 "Footprint": "68.4MiB",
 "MemoryUsage": "3.1MiB",
 "NodeID": "762b120",
 "RunningSince": "Tue Mar  5 13:58:14 UTC 2019",
 "Version": "CGRateS 0.9.1~rc8 git+4835ba2 (2019-03-04T20:49:33+01:00)"
}
```
and on our new instance it fails and lists all the valid parameters for this command followed by:
```
2019/05/09 07:07:47 Could not connect to server 127.0.0.1:2012
```

**Comment by asnaseer-resilient** [comment]
More information:
We tried removing the new version of CGRateS and installing the same version that Dan had installed but still get the same errors.

**Comment by anthonysomerset** [comment]
the error refers to the rpc_json interface rather than the HTTP interface - it would appear that your config is causing a failure to start or something

can you fully stop the service then paste the output of the command:
`cgr-engine -config_path /etc/cgrates -logger "*stdout"`
it might give you some other errors, also confirm the config of your listen config block if you have one present
