### ISSUE TITLE
Can't target certain ~CostDetails Rating fields

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#1549]
I'm running on current master and when i have the following CDRE config:

```
	"cdre": {
		"RatedOutput": {
			"export_format": "*file_csv",
			"export_path": "/tmp/cdrs",
			"filters" :["*string:~RunID:*default"],
			"content_fields": [
				 {"tag": "CGRID", "type": "*composed", "value": "~CGRID"},
				 {"tag":"RunID", "type": "*composed", "value": "~RunID"},
				 {"tag":"TOR", "type": "*composed", "value": "~ToR"},
				 {"tag":"OriginID", "type": "*composed", "value": "~OriginID"},
				 {"tag":"RequestType", "type": "*composed", "value": "~RequestType"},
				 {"tag":"Tenant", "type": "*composed", "value": "~Tenant"},
				 {"tag":"Category", "type": "*composed", "value": "~Category"},
				 {"tag":"Account", "type": "*composed", "value": "~Account"},
				 {"tag":"Subject", "type": "*composed", "value": "~Subject"},
				 {"tag":"Destination", "type": "*composed", "value": "~Destination"},
				 {"tag":"SetupTime", "type": "*composed", "value": "~SetupTime", "layout": "2006-01-02T15:04:05Z07:00"},
				 {"tag":"AnswerTime", "type": "*composed", "value": "~AnswerTime", "layout": "2006-01-02T15:04:05Z07:00"},
				 {"tag":"Usage", "type": "*composed", "value": "~Usage{*duration_seconds}"},
				 {"tag":"Cost", "type": "*composed", "value": "~Cost", "rounding_decimals": 4},
				 {"tag":"ReleaseCode", "type": "*composed", "value": "~ReleaseCode"},
				 {"tag":"CallType", "type": "*composed", "value": "~CallType"},
				 {"tag":"RatePlanID", "type": "*composed", "value": "~CostDetails.RatingFilters.RatingPlanID"},
				 {"tag":"DestinationPrefix", "type": "*composed", "value": "~CostDetails.RatingFilters.DestinationPrefix"},
				 {"tag":"DestinationID", "type": "*composed", "value": "~CostDetails.RatingFilters.DestinationID"},
			],
		},
	},
```

When i try to export the CDR's it succeeds but the last 3 fields are empty always, here is an example content of cost_details from the DB for an example call (formatted to protect the innocent) - https://gist.github.com/anthonysomerset/f6b0f3ec571d5cb735a6dd8eee0d0486

i specifcally note that there are ID references in the RatingFilters path that relate to other elements within the cost_details - and they are different per call for obvious reasons

it would be great to identify a way to access this data accordingly for export

**Comment by TeoV** [comment]
Hi @anthonysomerset 

 You have two choices about how you can access fields from RatingFilters : 
1) If you know the unique key, which is improbable because it's unique and we generate it each time you can take the fields with the following formula: ~CostDetails.RatingFilters.3d99c91.RatingPlanID
2) With Regex rules: if you use ~CostDetails.RatingFilters you will get the whole RatingFilters as JSON string and from there you can extract what data you need. 

Thanks,
TeoV

**Comment by anthonysomerset** [comment]
Hi @TeoV putting this here to keep the thread

I'm trying to take Option 2 here:

My Regex appears to not be matching or has no data:

```
 {"field_id":"RatePlanID", "type": "*composed", "value": "~CostDetails.RatingFilters:s/RatingPlanID\"\\s?\\:\\s?\"([^\"]*)\".*/$1/"},
{"field_id":"DestinationPrefix", "type": "*composed", "value": "~CostDetails.RatingFilters"},
```
i also tried grabbing the field with no regex and I'm just getting empty arrays `"{}"` rather than any data in both cases

**Comment by anthonysomerset** [comment]
so i may have spoken too soon

seems for a properly rated call where the category is "call" the data is coming out, but for my "intrabg" category call, despite having same data in the CDR record in the stor_db not coming through

**Comment by anthonysomerset** [comment]
so i did speak too soon
this only happens for unanswered calls and inspecting the raw CDR record in the DB shows that the RatingFilters is not populated at all which does makes sense as there is nothing to rate - at this point i don't believe this is a bug at this time, so will re-close this
