### ISSUE TITLE
Adding OriginHost as part of UniqueKey for CDR

### ISSUE THREAD

**Issue by EfelinNovak** [cgrates/cgrates#1552]
Hi,

when generating CDRs from two different IPs (different OriginHost), the cgrid in CDRs stays the same. I'd like to push one call from two Kamailios, the call goes through. Now the second call of cdr_http fails as there is a UNIQUE on cdrs table (UNIQUE(cgrid, run_id, origin_id)).

Should the generation of cgrid or a UNIQUE on the cdrs table be changed?

This issue comes from a group: https://groups.google.com/d/msg/cgrates/jh6Bp5q0pTs/kzgv29DPCwAJ

Thanks

Efelin

**Comment by anthonysomerset** [comment]
cgrID is generated from the origin_id and origin host:
https://github.com/cgrates/cgrates/blob/master/engine/cdr.go#L140

so if you have different origin_hosts and the field is properly mapped then the cgrid should be different each time

**Comment by EfelinNovak** [comment]
Hi Anotony,

thanks for the reply. How to map fields in HTTP API?

When I call:
```
curl -X POST --noproxy "*" -d "ToR=*voice&OriginID=Friday1&OriginHost=192.168.1.2&Source=curl_kamailio&RequestType=postpaid&Category=inbound_call&Tenant=t&Account=&Subject=&Destination=4412345&SetupTime=1555882070&AnswerTime=1555882091&Usage=3589s&CostSource=&from=83520400&carrier_out_id=888&carrier_out_name=asdasda" http://192.168.1.3:2080/cdr_http
curl -X POST --noproxy "*" -d "ToR=*voice&OriginID=Friday1&OriginHost=192.168.1.3&Source=curl_kamailio&RequestType=postpaid&Category=inbound_call&Tenant=t&Account=&Subject=&Destination=4412345&SetupTime=1555882070&AnswerTime=1555882091&Usage=3589s&CostSource=&from=83520400&carrier_out_id=888&carrier_out_name=asdasda" http://192.168.1.3:2080/cdr_http
```

I get following cdrs:

id | cgrid | run_id | origin_host | source | origin_id | tor | request_type | ...
------------ | -------------| ------------ | -------------| ------------ | -------------| ------------ | ------------- | -----
1430604 | 6ff66daec88e9b344e1362a868810a3820c87f5d | *raw | 192.168.1.3 | curl_kamailio | Friday1 | *voice | postpaid | ...
1431574 | 6ff66daec88e9b344e1362a868810a3820c87f5d | *raw | 192.168.1.2 | curl_kamailio | Friday1 | *voice | postpaid | ...

The Origin host is different, however the cgrid is the same (please note, that getting such CDRs is possible only when UNIQUE in cdrs table is modified.)

Thanks

Efelin

**Comment by Yenkee** [comment]
Hi Thanks, I can confirm it works.
