### ISSUE TITLE
Can't compare usage to a number in Diameter

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#1558]
I have the following config in my DiameterAgent Terminate Template:

```
        {
          "tag": "Usage",
          "field_id": "Usage",
          "type": "*cc_usage",
          "mandatory": true,
          "value": "~*req.CC-Request-Number;~*req.Multiple-Services-Credit-Control.Used-Service-Unit.CC-Time:s/(.*)/${1}s/;30s"
        },
        {
          "tag": "AnswerTime",
          "field_id": "AnswerTime",
          "filters": [
            "*gt:~*cgrareq.Usage:0"
          ],
          "type": "*difference",
          "value": "~*req.Event-Timestamp;~*cgrareq.Usage",
          "mandatory": true
        },
```

but we get the following error: `<DiameterAgent> error: incomparable processing message:`

if we take the filter out it works fine but the answer time is injected even if the call is unanswered

**Comment by TeoV** [comment]
Hi Anthony,

In our case, this filter works. We will investigate this, until then please use this as an alternative filter.
*rsr::~*cgrareq.Usage{*duration_nanoseconds}(>0)"

Thanks,
TeoV

**Comment by anthonysomerset** [comment]
OK thanks

Tried this but getting errors like this:

` <DiameterAgent> error: time: invalid duration [{"Path":["Usage"],"Data":0,"Config":{"Tag":"Usage","Type":"*cc_usage","FieldId":"Usage","Filters":null,"Value":[{"Rules":"~*req.CC-Request-Number","AllFiltersMatch":true},{"Rules":"~*req.Multiple-Services-Credit-Control.Used-Service-Unit.CC-Time:s/(.*)/${1}s/","AllFiltersMatch":true},{"Rules":"30s","AllFiltersMatch":true}],"Width":0,"Strip":"","Padding":"","Mandatory":true,"AttributeID":"","NewBranch":false,"Timezone":"","Blocker":false,"BreakOnSuccess":false,"HandlerId":"","Layout":"","CostShiftDigits":0,"RoundingDecimals":0,"MaskDestID":"","MaskLen":0}}]`

`<DiameterAgent> error: time: invalid duration [{"Path":["Usage"],"Data":3000000000,"Config":{"Tag":"Usage","Type":"*cc_usage","FieldId":"Usage","Filters":null,"Value":[{"Rules":"~*req.CC-Request-Number","AllFiltersMatch":true},{"Rules":"~*req.Multiple-Services-Credit-Control.Used-Service-Unit.CC-Time:s/(.*)/${1}s/","AllFiltersMatch":true},{"Rules":"30s","AllFiltersMatch":true}],"Width":0,"Strip":"","Padding":"","Mandatory":true,"AttributeID":"","NewBranch":false,"Timezone":"","Blocker":false,"BreakOnSuccess":false,"HandlerId":"","Layout":"","CostShiftDigits":0,"RoundingDecimals":0,"MaskDestID":"","MaskLen":0}}]`

**Comment by TeoV** [comment]
Hi @anthonysomerset 

That's very strange because we have tests for this and it works. 
Here is our template 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/diamagent/voice.json#L88
And here is the test and as you can see usage is calculated correctly without error
https://github.com/cgrates/cgrates/blob/master/agents/diam_it_test.go#L687
Can you please capture the DiameterRequest and send us so we can analyze it? 

Thanks,
TeoV

**Comment by anthonysomerset** [comment]
confirmed fixed thanks
