### ISSUE TITLE
WARNING: Could not find CallCostLog for cgrid

### ISSUE THREAD

**Issue by negbie** [cgrates/cgrates#1562]
I get the mentioned warning plus a panic

2019/05/19 18:22:09 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *raw, originID: 123452 originHost: , will recalculate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd987f1]

goroutine 84 [running]:
github.com/cgrates/cgrates/engine.(*CDRServer).attrSProcessEvent(0xc000342b40, 0xc0003e5090, 0x9559dc9697db04e5, 0x73a863)
	/home/eugen/go/src/github.com/cgrates/cgrates/engine/cdrs.go:334 +0x131
github.com/cgrates/cgrates/engine.(*CDRServer).attrStoExpThdStat(0xc000342b40, 0xc0003e5090, 0x101000101, 0x1, 0x1)
	/home/eugen/go/src/github.com/cgrates/cgrates/engine/cdrs.go:244 +0x31d
github.com/cgrates/cgrates/engine.(*CDRServer).V1ProcessEvent(0xc000342b40, 0xc000100150, 0xc00034c450, 0x0, 0x0)
	/home/eugen/go/src/github.com/cgrates/cgrates/engine/cdrs.go:611 +0x3b9
github.com/cgrates/cgrates/apier/v1.(*CDRsV1).ProcessEvent(0xc000010d80, 0xc000100150, 0xc00034c450, 0x0, 0x0)
	/home/eugen/go/src/github.com/cgrates/cgrates/apier/v1/cdrs.go:99 +0x42
reflect.Value.call(0xc0004599e0, 0xc000010da8, 0x13, 0x1406831, 0x4, 0xc00059ff18, 0x3, 0x3, 0xc000436540, 0x1357780, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc0004599e0, 0xc000010da8, 0x13, 0xc000017718, 0x3, 0x3, 0x7efc803734b8, 0xc000017728, 0x40df68)
	/usr/local/go/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc000429e40, 0xc0000ac280, 0xc000584858, 0xc000584860, 0xc0002b8b80, 0xc000434420, 0x134f2c0, 0xc000100150, 0x16, 0x11c9880, ...)
	/usr/local/go/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:481 +0x42b

Is something wrong with my config? https://github.com/negbie/heplify-server/blob/master/example/cgrates.json

This is the codeblock which sends the request: https://github.com/negbie/heplify-server/blob/master/cdr/cgrates.go

Ngrep output:
#
T 127.0.0.1:52804 -> 127.0.0.1:2012 [AP] #53
  {"method":"CDRsV1.ProcessEvent","params":[{"Tenant":"cgrates.org","ID":"","Time":null,"Event":{"Account":"1001","AnswerTime":"2019-05-19T18:22:02.172312+02:00","Category":"call","Destination":"1003",
  "OriginID":"123452","RequestType":"*prepaid","Source":"192.168.1.1","Subject":"1001","Tenant":"cgrates.org","Usage":3058288000},"AttributeS":true,"RALs":true,"ChargerS":true,"Store":null,"Export":nul
  l,"ThresholdS":true,"StatS":true}],"id":0}.                                                                                                                                                            
######
T 127.0.0.1:52798 -> 127.0.0.1:2012 [AP] #59
  {"method":"ThresholdSv1.ProcessEvent","params":[{"ThresholdIDs":null,"Tenant":"cgrates.org","ID":"ca2ef3b5-089e-452f-a8a5-ae26d2a16928","Time":null,"Event":{"Account":"1001","BalanceID":"","EventSour
  ce":"AccountS","EventType":"BalanceUpdate","Units":9.8}}],"id":0}.                                                                                                                                     
##
T 127.0.0.1:2012 -> 127.0.0.1:52798 [AP] #61
  {"id":0,"result":null,"error":"NOT_FOUND"}.

#cgr-engine -version
CGRateS 0.9.1~rc8 git+a98907b (2019-05-17T16:40:46+03:00)

**Comment by negbie** [comment]
I guess something must be wrong with my config because I do this:
https://github.com/cgrates/cgrates/blob/8626e90cf3ac66050c618f9aa67e35e56e00d7d5/general_tests/cdrs_it_test.go#L616

Is it because of the heave "*internal" store usage?

**Comment by negbie** [comment]
When I turn off attributeS and thresholdS I see this from cgr-engine:

2019/05/19 18:47:39 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *raw, originID: 123452 originHost: , will recalculate
2019/05/19 18:47:46 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *raw, originID: 123452 originHost: , will recalculate
2019/05/19 18:47:46 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *default, originID: 123452 originHost: , will recalculate
2019/05/19 18:47:46 CGRateS <heplify-cgrates> [WARNING] <CDRs> error: NOT_IMPLEMENTED processing CDR event &{CGREvent:0xc00015a310 ArgDispatcher:<nil>} with ChargerS
2019/05/19 18:47:53 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *default, originID: 123452 originHost: , will recalculate
2019/05/19 18:47:53 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *raw, originID: 123452 originHost: , will recalculate
2019/05/19 18:47:53 CGRateS <heplify-cgrates> [WARNING] <CDRs> error: NOT_IMPLEMENTED processing CDR event &{CGREvent:0xc000150000 ArgDispatcher:<nil>} with ChargerS
2019/05/19 18:48:00 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *default, originID: 123452 originHost: , will recalculate
2019/05/19 18:48:00 CGRateS <heplify-cgrates> [WARNING] <Cdrs> WARNING: Could not find CallCostLog for cgrid: 72571665d1184a5889ec08a1ea4c6345b35634f0, source: *sessions, runid: *raw, originID: 123452 originHost: , will recalculate


Ngrep output:

###
T 127.0.0.1:56100 -> 127.0.0.1:2012 [AP] #90
  {"method":"ThresholdSv1.ProcessEvent","params":[{"ThresholdIDs":null,"Tenant":"cgrates.org","ID":"766e39d5-5fba-4471-bf00-a17d9513517b","Time":null,"Event":{"Account":"1001","BalanceID":"","EventSour
  ce":"AccountS","EventType":"BalanceUpdate","Units":9.28}}],"id":9}.                                                                                                                                    
#
T 127.0.0.1:2012 -> 127.0.0.1:56100 [AP] #91
  {"id":9,"result":null,"error":"NOT_FOUND"}.                                                                                                                                                            
##
T 127.0.0.1:56100 -> 127.0.0.1:2012 [AP] #93
  {"method":"ThresholdSv1.ProcessEvent","params":[{"ThresholdIDs":null,"Tenant":"cgrates.org","ID":"65ada846-8869-4330-bbe5-6b9ef0f4de0a","Time":null,"Event":{"Account":"1001","BalanceID":"","EventSour
  ce":"AccountS","EventType":"BalanceUpdate","Units":9.24}}],"id":10}.                                                                                                                                   
#
T 127.0.0.1:2012 -> 127.0.0.1:56100 [AP] #94
  {"id":10,"result":null,"error":"NOT_FOUND"}.                                                                                                                                                           
#
T 127.0.0.1:2012 -> 127.0.0.1:56202 [AP] #95
  {"id":5,"result":"OK","error":null}.                                                                                                                                                                   
#
T 127.0.0.1:56202 -> 127.0.0.1:2012 [AP] #96
  {"method":"CDRsV1.ProcessEvent","params":[{"Tenant":"cgrates.org","ID":"","Time":null,"Event":{"Account":"1001","AnswerTime":"2019-05-19T18:47:40.880063+02:00","Category":"call","Destination":"1003",
  "OriginID":"123452","RequestType":"*prepaid","Source":"192.168.1.1","Subject":"1001","Tenant":"cgrates.org","Usage":6377523000},"AttributeS":false,"RALs":true,"ChargerS":true,"Store":true,"Export":fa
  lse,"ThresholdS":false,"StatS":true}],"id":6}.                                                                                                                                                         
#####
T 127.0.0.1:56100 -> 127.0.0.1:2012 [AP] #101
  {"method":"ThresholdSv1.ProcessEvent","params":[{"ThresholdIDs":null,"Tenant":"cgrates.org","ID":"53385f7b-4532-400b-9fd8-d12a189faed4","Time":null,"Event":{"Account":"1001","BalanceID":"","EventSour
  ce":"AccountS","EventType":"BalanceUpdate","Units":9.2}}],"id":11}.                                                                                                                                    
#
T 127.0.0.1:2012 -> 127.0.0.1:56100 [AP] #102
  {"id":11,"result":null,"error":"NOT_FOUND"}.                                                                                                                                                           
##
T 127.0.0.1:56100 -> 127.0.0.1:2012 [AP] #104
  {"method":"ThresholdSv1.ProcessEvent","params":[{"ThresholdIDs":null,"Tenant":"cgrates.org","ID":"a0910e30-5a5f-4268-9c4d-01b475bb3a1b","Time":null,"Event":{"Account":"1001","BalanceID":"","EventSour
  ce":"AccountS","EventType":"BalanceUpdate","Units":9.13}}],"id":12}.                                                                                                                                   
#
T 127.0.0.1:2012 -> 127.0.0.1:56100 [AP] #105
  {"id":12,"result":null,"error":"NOT_FOUND"}.                                                                                                                                                           
#
T 127.0.0.1:2012 -> 127.0.0.1:56202 [AP] #106
  {"id":6,"result":"OK","error":null}.

**Comment by TeoV** [comment]
Hi @negbie,

According to your capture : 
T 127.0.0.1:52804 -> 127.0.0.1:2012 [AP] #53
{"method":"CDRsV1.ProcessEvent","params":[{"Tenant":"cgrates.org","ID":"","Time":null,"Event":{"Account":"1001","AnswerTime":"2019-05-19T18:22:02.172312+02:00","Category":"call","Destination":"1003",
"OriginID":"123452","RequestType":"*prepaid","Source":"192.168.1.1","Subject":"1001","Tenant":"cgrates.org","Usage":3058288000},**"AttributeS":true,**"RALs":true,"ChargerS":true,"Store":null,"Export":nul
l,"ThresholdS":true,"StatS":true}],"id":0}.
In your request you active AttributeS process, but in your config, you don't have a connection from cdrs to attributes : 
https://github.com/negbie/heplify-server/blob/master/example/cgrates.json#L64-L77

The solutions are the following : 
1) When you send the cdr and you don't need the " attributeS process " you should put the AttriuteS flag on false: https://godoc.org/github.com/cgrates/cgrates/engine#ArgV1ProcessEvent
OR
2) In case that you need " attributeS process " add a connection from cdr to attributes and everything should be fine.

Regarding Warnings: this is because you use *internal as stor_db. This wasn't meant to replace the functionality of a "normal stor_db" ( MySQL for example ) 
Another problem is that you send the cdr with RequestType : *prepaid, but without a cost. When we receive a cdr with RequestType *prepaid we expected to have a cost.

Thanks,
TeoV

**Comment by negbie** [comment]
@TeoV Thank you! I will change that and setup mysql for further tests. I thought I can just use internal for everything to test things out.
