### ISSUE TITLE
Rated CDR does not contain answer time

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#1564]
Since some point approx from 15th to 17th May (last known good commit- https://github.com/cgrates/cgrates/commit/486504a64d30ceeed12c8e031501610862877fc2 )  our rated cdr's have had empty answer times but the raw CDR did have:

example CDR rows (actual phone numbers sanitised):

```
6b31a8651fc45a4c2046b88ab17ec179d75c3dc4,*raw,*voice,0gQAAC8WAAACBAAALxYAALugRsAoCMFua4TWFxoKVk8g1ACHt6ldoFAcSgDvNeKo47PcrB43CKN/Kr87JlE2Eg--@10.170.248.200,*prepaid,voice.lab.liquidtelecom.net,call,2711XXXXXXX,2711XXXXXXX,2776XXXXXXX,2019-05-21T12:25:41Z,2019-05-21T12:25:46Z,23s,-1.00000
6b31a8651fc45a4c2046b88ab17ec179d75c3dc4,*default,*voice,0gQAAC8WAAACBAAALxYAALugRsAoCMFua4TWFxoKVk8g1ACHt6ldoFAcSgDvNeKo47PcrB43CKN/Kr87JlE2Eg--@10.170.248.200,*prepaid,voice.lab.liquidtelecom.net,call,2711XXXXXXX,2711XXXXXXX,2776XXXXXXX,2019-05-21T12:25:41Z,0001-01-01T00:00:00Z,23s,7.37540
```

**Comment by TeoV** [comment]
Hi @anthonysomerset,

Can you please put the communication on *json between DiameterAgent -> SessionS -> CDRs and send us the requests.
Also, add additional data if is needed to reproduce this and if you have sensitive data please send these on email.

Thanks,
TeoV

**Comment by anthonysomerset** [comment]
Sent into Dan via Mail :)

**Comment by TeoV** [comment]
Hi @anthonysomerset,

We noticed that you don't have in InitiateSession AnswerTime.
Can you please try to add it into your template? 
We only initiate the event once due to derive charging.

Thanks,
TeoV

**Comment by anthonysomerset** [comment]
so this might be by our design..

If we put AnswerTime into the Initiate Diameter event - we can't do no answer time for ASR stats because all calls will appear to have been "answered" or am I getting the wrong end of things here?

We are trying to only calculate the answer time at the end of the call in the terminate event if such a call was actually answered (Usage > 0s) - is there a better way to do this? i wonder if theres a way to "reset" the answer time to empty if the usage = 0s ?

**Comment by anthonysomerset** [comment]
So adding the answer time in the init event does indeed "solve" this issue however:

as per attached CDRs - see the 0s call has an answer time when it really should be empty

```
cd4eed1a82a7d31cd7696e89261aaf14ee61fbef,*default,*voice,0gQAAC8WAAACBAAALxYAAJa3JQj9/NuOjWS2345YlbJK0g/Usyqlm3ffqeFwCzd0LRcgCO0xAc7re7DP4lvxWw--@10.170.248.200,*prepaid,voice.lab.liquidtelecom.net,call,27110XXXXXX,27110XXXXXX,2773XXXXXXX,2019-05-22T12:31:30Z,2019-05-22T12:31:30Z,8s,2.56540
cd4eed1a82a7d31cd7696e89261aaf14ee61fbef,*raw,*voice,0gQAAC8WAAACBAAALxYAAJa3JQj9/NuOjWS2345YlbJK0g/Usyqlm3ffqeFwCzd0LRcgCO0xAc7re7DP4lvxWw--@10.170.248.200,*prepaid,voice.lab.liquidtelecom.net,call,27110XXXXXX,27110XXXXXX,2773XXXXXXX,2019-05-22T12:31:30Z,2019-05-22T12:31:35Z,8s,-1.00000
34046f1329091d66502e2d4b6f8b2809b99b43d8,*default,*voice,0gQAAC8WAAACBAAALxYAAOaD1pIy3rr7rlF2ywg5sqWBRPOfg919ZHGeDNo1kL8KDUPGBG6W5E2QpW1cKLXn5Q--@10.170.248.200,*prepaid,voice.lab.liquidtelecom.net,call,27110XXXXXX,27110XXXXXX,2773XXXXXXX,2019-05-22T12:31:14Z,2019-05-22T12:31:14Z,0s,3.52740
34046f1329091d66502e2d4b6f8b2809b99b43d8,*raw,*voice,0gQAAC8WAAACBAAALxYAAOaD1pIy3rr7rlF2ywg5sqWBRPOfg919ZHGeDNo1kL8KDUPGBG6W5E2QpW1cKLXn5Q--@10.170.248.200,*prepaid,voice.lab.liquidtelecom.net,call,27110XXXXXX,27110XXXXXX,2773XXXXXXX,2019-05-22T12:31:14Z,2019-05-22T12:31:14Z,0s,-1.00000
```

**Comment by TeoV** [comment]
Hi @anthonysomerset,

We pushed a change that allows you to modify answer Time in TerminateSession.
Please update from the master and retest and tell us how it goes.

Thanks,
TeoV

**Comment by anthonysomerset** [comment]
i see its still pending under https://github.com/cgrates/cgrates/pull/1569

how do we go about modifying the answer time to be null if usage is null?

**Comment by TeoV** [comment]
Hi @anthonysomerset,

With this update, you can remove AnswerTime from InitSession template.
Now If you don't send an AnswerTime in InitSession, but you send one in TerminateSession the final Answer will be the one from TerminateSession.
Hope now all is clear.

Thanks,
TeoV
