### ISSUE TITLE
panic: fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by chrisgis333** [cgrates/cgrates#1577]
https://github.com/cgrates/cgrates/blob/120060d95fd3eac80e488cede36279059ee3a76f/engine/action.go#L752

In this line cgrates is using global map without protection on concurrent access.
It generates panic if two actions are executed at once.

**Comment by TeoV** [comment]
Hi @chrisgis333,

I don't think this is a problem because we only read from the map; we don't write in it.
Have you faced this problem ( panic the CGRateS because of this)? 

Thanks,
TeoV

**Comment by chrisgis333** [comment]
Panic is in mapstructure.Decode

in, out := params.InParam, params.OutParam
	//utils.Logger.Info("Params: " + utils.ToJSON(req.Params))
	//p, err := utils.FromMapStringInterfaceValue(req.Params, in)
mapstructure.Decode(req.Params, in)

it uses in params which is not deepcopied

**Comment by TeoV** [comment]
Hi @chrisgis333,

Sorry for forgetting this issue.
If not too late can you please attach here some data to reproduce the problem?

Thanks,
TeoV
