### ISSUE TITLE
Kamevapi problem in kubernetes

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#1594]
When running cgrates in a kubernetes pod I get the following when sending data through kamevapi:

kamevapi:21:12:24  Attempting connect to Kamailio at: kamailio-evapi:8448
kamevapi:21:12:24  Successfully connected to kamailio-evapi:8448!
panic: interface conversion: interface {} is nil, not string

goroutine 144 [running]:
github.com/cgrates/cgrates/agents.(*KamailioAgent).onCgrAuth(0xc00048f580, 0xc0001c00e0, 0xd2, 0xd2, 0xc0005ea000, 0x24)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/agents/kamagent.go:127 +0x10ae
github.com/cgrates/cgrates/agents.(*KamailioAgent).onCgrAuth-fm(0xc0001c00e0, 0xd2, 0xd2, 0xc0005ea000, 0x24)
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/agents/kamagent.go:68 +0x5c
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi.(*KamEvapi).dispatchEvent
        /home/dan/go/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/kamevapi/kamevapi.go:117 +0xe6

**Comment by danbogos** [comment]
Hey @DigiDaz 

This issue was fixed in master but forgot to create package. Please upgrade and retest.

Thanks,
DanB
