### ISSUE TITLE
UserS functionality from package shared into own object

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#163]
Right now we share the UserS functionality for all components.

While this is simple in implementation, it has the disadvantage of not being scalable over different servers (eg: for partitioning).
Would be beneficial to be able to specify the user service connection in each component (eg: rater separately from cdrs).

DanB

**Comment by danbogos** [comment]
Same valid for: HistoryS, PubSubS, Aliases.

Will open separate issues once we decide about the go.

DanB

**Comment by rif** [comment]
added individual service parameters to cdrs server
