### ISSUE TITLE
Filter on Events for finding balance used to cover event cost

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1632]
As per:

https://groups.google.com/forum/#!searchin/cgrates/balance$20gavin%7Csort:date/cgrates/VMpW-pZAukM/l5nfjT_aBgAJ

I'd like a way to determine what balance was used to cover the cost of the event. For my use case I am only interested if the following balance was used to cover this event cost:

```
   "*monetary": [
    {
     "Uuid": "aabd70f2-a56e-4963-a21e-68bcf8913223",
     "ID": "B_MONETARY_POSTPAID",
     "Value": 50,
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 20,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ],
```

I'd like a way to filter on `"ID": "B_MONETARY_POSTPAID"` and export that CDR into a new location/db/filesystem/API etc.

Make sense? Currently a CDR stored in Pg has tons of information in JSON that doesn't not make this easy, if at all possible.

Thanks,
Gavin.

**Comment by danbogos** [comment]
As discussed, the idea should be adding a filter to exporter which goes into EventCost path.

**Comment by TeoV** [comment]
Hi @ghenry 

You can access fields from CostDetails from CDR very easily. For example, If you want to access AccountID from AccountSummary from CostDetails simply use: "~CostDetails.AccountSummary.AccountID" like in this example : 
https://github.com/cgrates/cgrates/blob/master/engine/cdr_test.go#L280
Regarding filters, they can be applied at the whole template https://github.com/cgrates/cgrates/blob/master/data/conf/samples/cdrewithfilter/cgrates.json#L51
( in this example if the cdr will have Source: test2 they will be exported ) 

Thanks,
TeoV

**Comment by ghenry** [comment]
Brilliant, thanks. Where can I read up on options for `export_format` if I didn't want these as CSV, but POSTed to an API or into say storDB?

**Comment by ghenry** [comment]
Nevermind, I see it now:

https://github.com/cgrates/cgrates/search?q=export_format&unscoped_q=export_format

I could also now set up a filter and use within `ThresholdS` and send to an API now too? But `cdre` would be better?

Thanks.

**Comment by ghenry** [comment]
Or read the example :-) https://github.com/cgrates/cgrates/blob/616b16c8d4cd588bc3e1d3b618da9f6485104fc9/data/conf/cgrates/cgrates.json

**Comment by ghenry** [comment]
I could use this to receive the POST?

https://github.com/cgrates/cgrates/blob/master/data/conf/samples/cdrsv2psql/cdrsv2psql.json

**Comment by ghenry** [comment]
Could we get a new deb built? Thanks!

**Comment by ghenry** [comment]
Hi,

I'm not sure how to filter from this CostDetails as I can see with my eyes that UUID cd192f3a was used (B_MONETARY_POSTPAID), but I want a generic filter to match the ID name, not a UUID:

```
"CostDetails":{
   "AccountSummary":{
      "AllowNegative":false,
      "BalanceSummaries":[
         {
            "Disabled":false,
            "ID":"B_UK_MOBILE_UK_LANDLINE_5000",
            "Type":"*voice",
            "UUID":"b69a12b5-72dc-4d64-8428-ffd82ced1b3b",
            "Value":292688000000000.06
         },
         {
            "Disabled":false,
            "ID":"B_UK_MOBILE_DATA_5000",
            "Type":"*data",
            "UUID":"1b093788-9c2c-4448-b123-2e02510ab90a",
            "Value":4540326230
         },
         {
            "Disabled":false,
            "ID":"B_UK_SMS_5000",
            "Type":"*sms",
            "UUID":"d9ca5d42-8505-4827-b63b-ff01e8b2ee0e",
            "Value":4987
         },
         {
            "Disabled":false,
            "ID":"B_MONETARY_POSTPAID",
            "Type":"*monetary",
            "UUID":"cd192f3a-587d-4b02-bdf3-9be602747f4",
            "Value":36.876
         }
      ],
      "Disabled":false,
      "ID":"229199",
      "Tenant":"surevoip"
   },
   "Accounting":{
      "c3264e2":{
         "AccountID":"surevoip:229199",
         "BalanceUUID":"cd192f3a-587d-4b02-bdf3-f9be602747f4",
         "ExtraChargeID":"",
         "RatingID":"",
         "Units":0.0787
      }
   },
   "CGRID":"62249d33cd0188878b02ac472a4e01e55c65a778",
   "Charges":[
      {
         "CompressFactor":1,
         "Increments":[
            {
               "AccountingID":"c3264e2",
               "CompressFactor":1,
               "Cost":0.0787,
               "Usage":30000000000
            }
         ],
         "RatingID":"64819b2"
      }
   ],
   "Cost":0.0787,
   "Rates":{
      "73c0ab2":[
         {
            "GroupIntervalStart":0,
            "RateIncrement":30000000000,
            "RateUnit":60000000000,
            "Value":0.1574
         },
         {
            "GroupIntervalStart":30000000000,
            "RateIncrement":1000000000,
            "RateUnit":60000000000,
            "Value":0.1574
         }
      ]
   },
   "Rating":{
      "64819b2":{
         "ConnectFee":0,
         "MaxCost":40,
         "MaxCostStrategy":"*disconnect",
         "RatesID":"73c0ab2",
         "RatingFiltersID":"41e089c",
         "RoundingDecimals":4,
         "RoundingMethod":"*up",
         "TimingID":"3eccc5e"
      }
   },
   "RatingFilters":{
      "41e089c":{
         "DestinationID":"DST_UK_Freephone",
         "DestinationPrefix":"44800",
         "RatingPlanID":"RP_MO_CALL_UK_Mobile_Vodafone_GBRVF",
         "Subject":"*out:surevoip:mo_call_UK_Mobile_Vodafone_GBRVF:*any"
      }
   },
   "RunID":"*default",
   "StartTime":"2019-08-20T20:34:46Z",
   "Timings":{
      "3eccc5e":{
         "MonthDays":[

         ],
         "Months":[

         ],
         "StartTime":"00:00:00",
         "WeekDays":[

         ],
         "Years":[

         ]
      }
   },
   "Usage":30000000000
}
```

Thanks.
