### ISSUE TITLE
Breaking change with commit b9d89ed: "Agents: changing continue_on_success to continue" 

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1636]
Hi all,

There was no notification of this change to the mailing list and it also seems inconsistent with the other systems:

https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L258

continue_on_success does make more sense than just "continue" too. I'd vote to revert it.

Thanks.

**Comment by danbogos** [comment]
Hey Gavin,

"continue" looks simpler in our view (same logic as in go for loop). This was the reason we have done the change. The other is longer to write and we want to keep the templates as simple as possible.

Thanks,
DanB
