### ISSUE TITLE
cgr-* does not read from /etc/cgrates/cgrates.json

### ISSUE THREAD

**Issue by esfandiaryfard** [cgrates/cgrates#1651]
each time I want to use cgr-* it returns me error related to wrong config and it seems cgrates does not read from /etc/cgrates/cgrates.json and I need to pass it with -config_path
is it the only solution?

**Comment by Trial97** [comment]
Hi @esfandiaryfard,

This doesn't look like a CGRateS issue.
If you have questions about this project please ask them on google groups:
https://groups.google.com/forum/#!forum/cgrates 

Thanks,
Trial97
