### ISSUE TITLE
GetKeysForPrefix in big redis environment blocks database

### ISSUE THREAD

**Issue by chrisgis333** [cgrates/cgrates#1658]
Using KEYS in production environment is not recommended.
KEYS time complexity is O(n)

_"Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. "_

In my database with 50 mln+ accounts GetKeysForPrefix blocks redis database for over 15 seconds.

https://github.com/cgrates/cgrates/blob/008e67c1436467e92c4a2642f4c97534d28d49e4/engine/storage_redis.go#L346

**Comment by Trial97** [comment]
Hi @chrisgis333,

We use this only for management purposes, not for real-time tasks.
Do you see it used somewhere in such a manner that it could impact the speed of real-time tasks?

Thanks,
Trial97

**Comment by chrisgis333** [comment]
At every Scheduler initialization

https://github.com/cgrates/cgrates/blob/6a647f1e6be9d0c30f4d869ccd173edc4cbb59e7/scheduler/scheduler.go#L153

**Comment by chrisgis333** [comment]
And that limits normal CgrateS functionality.
- All Get<>Ids e.g GetAttributeProfileIDs can't be run on prod.
- Prechache flag need's to be false on prod
- filters indexed_selects needs to be true on prod

**Comment by Trial97** [comment]
Hi @chrisgis333, 

This should be partially fixed in master:
We indexed ActionPlans using an additional set in Redis so the scheduler initialization and reload should be much faster.  
The rest of the APIs are for administration and we cannot do much about them unfortunately.

Thanks,
Trial97
