### ISSUE TITLE
Session Manager Clarification

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#166]
Hi Dan,

I have 3 remote FS servers that I would like to connect to my main CGRateS installation and I would like some clarification on how to achieve this correctly.

Basically the 3 FS servers have the following IPs for example.

Server1: 10.10.10.1  
Server2: 10.10.10.2   
Server3: 10.10.10.3 

FreeSwitch and CGRateS is installed on all 3 of the remote FS servers and each of the 3 is running the following config and cgrates is started.
````
"sm_freeswitch": {
            "enabled": true,
            "rater": "10.10.10.10:2013",
            "cdrs": "10.10.10.10:2080",                                    
//      "reconnects": 5,
//      "create_cdr": false,
//      "cdr_extra_fields": [],
//      "debit_interval": "10s",
//      "min_call_duration": "0s",
//      "max_call_duration": "3h",
//      "min_dur_low_balance": "5s",
//      "low_balance_ann_file": "",
//      "empty_balance_context": "",
//      "empty_balance_ann_file": "",
//  "subscribe_park": true,
//          "channel_sync_interval": "5m",
//          "connections":[
//                  {"server1": “127.0.0.1:8021”, "password": “ClueCon”, "reconnects": 5}
````
1) Is my configuration above correct?

2) Server0 is being used as the main CGRateS Server. How do I configure Server0 to listen to the 3 Session Managers?

In Server0, the main CGRateS server I configured the sm_freeswitch sections as below but CGrateS would not start.
````
    "sm_freeswitch": {
            "enabled": true,
            "rater": "internal",
            "cdrs": "internal",                                    
    //      "reconnects": 5,
    //      "create_cdr": false,
    //      "cdr_extra_fields": [],
    //      "debit_interval": "10s",
    //      "min_call_duration": "0s",
    //      "max_call_duration": "3h",
    //      "min_dur_low_balance": "5s",
    //      "low_balance_ann_file": "",
    //      "empty_balance_context": "",
    //      "empty_balance_ann_file": "",
    //  "subscribe_park": true,
            "channel_sync_interval": "5m",
            "connections":[
                    {"server1": “10.10.10.10:8021”, "password": “ClueCon”, "reconnects": 5}
                    {"server2": “10.10.10.1:8021”, "password": “ClueCon”, "reconnects": 5}
                    {"server3": “10.10.10.2:8021”, "password": “ClueCon”, "reconnects": 5}
                    {"server4": “10.10.10.3:8021”, "password": “ClueCon”, "reconnects": 5}
````
So I am not clear as to want is to be done with this.  Any assistance would be much appreciated.

Regards,

esamuels

**Comment by danbogos** [comment]
Hi @ewsamuels,

We use github for issues/feature requests. 

In order for the community to benefit out of our support, please direct your messages to the mailing list where they are automatically published to all subscribed users and where can be monitored more properly.

Thanks for understanding.

DanB

PS: Google group here: https://groups.google.com/forum/#!forum/cgrates
