### ISSUE TITLE
Debug logging facility 

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#169]
We need a way to specify debug logging.
Since full CGRateS debugging could become useless and complex, we could specify a concept of "debugging profiles". These should be defined in configuration and enabled through the code.

Eg, in cgrates.json we could specify something like:

```
debug=["cdr_processing", "rater_auth", "sm_freeswitch_session"]
```

These flags could be kept into an internal map and accessed through the code something like:

```
if _,hasFlag := debugFlags["cdr_processing"]; hasFlag {
    engine.Logger.Debug("CDR Received ...")
}
```

DanB

**Comment by danbogos** [comment]
Another idea for efficiency should be declaring log levels as integers (eg: with iota) and doing bitwise operations in the code logic.

DanB

**Comment by ghenry** [comment]
Any more thoughts on this? Whilst testing things it would be great to know why your rate and destination isn't found via cgr-console cost etc.

**Comment by danbogos** [comment]
@ghenry, since we have other ways of troubleshooting (ngrep for API calls, logs inside), we did not further think about debug. Could work something out a bit later but the basics of troubleshooting should be already covered by tracing APIs and logs.

DanB

**Comment by ghenry** [comment]
Hi @danbogos 

That does work great, but I mean something that exposes internals with things like debug/trace levels to see what functions get calls, what checks are run and found etc. I suppose that would be more for the dev side though.

Gavin.

**Comment by danbogos** [comment]
@ghenry 

I understand it will be good to have such facility but the question is whether is bringing enough benefits to worth loosing computing performance for standard requests.

DanB

**Comment by ghenry** [comment]
@danbogos 
This would be analogous to FreeSWITCH and `fs_ctl loglevel` - https://freeswitch.org/confluence/display/FREESWITCH/Troubleshooting+Debugging which then switches on different types of function tracing and print statements etc.

Same with OpenLDAP and any other Open Source project or daemon. I'm not looking for anything clever here, just the normal thing an admin would want to see :-)

https://www.openldap.org/doc/admin24/slapdconfig.html#Configuration%20File%20Directives (loglevel)

Thanks!

**Comment by ghenry** [comment]
Performance wise. Well, you're only adjusting the loglevel to learn more info about an issue you may have or some other debug reason and you'd know there'd be a hit switching the level up higher. Operations wise you'd do that debugging in the lab or during a maintenance window or similar.

Don't get me wrong, ngrepping API traffic and logs are great, but this is to get at what's happening when your API query is doing something in order to return the result which in the long run helps users not create so much support noise for the project.

**Comment by danbogos** [comment]
@ghenry 

Yes and no. Each log will be an extra switch/if where you decide to display or not that log. Depending on the amount of logging you add, you could end up with quite some decisions.

DanB

**Comment by Trial97** [comment]
Since we added AnalyzerS we decided not to implement this on master.

**Comment by Jajcus** [comment]
> Since we added AnalyzerS we decided not to implement this on master.

How does this help? CGrateS logging is still quite useless (no way to see what is happening there) and there seems to be no documentation for this AnalyzerS thing…

Proper logging is a very needed feature for anyone who wants to deploy CGrateS, especially when the documentation is so lacking. If opensips can have extensive logging (e.g. loglevel=9) which even show what string processing is being done, I don't understand why CGrateS, when configured so, cannot show exactly how messages are passed between services and what actually caused a specific NOT_FOUND error.
