### ISSUE TITLE
ApierV1.AddBalance vs ApierV2.GetAccounts different variable names

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#1690]
Dear Team,

When Using ApierV1.AddBalance & ApierV2.GetAccounts we saw that following variable names are different when setting them(ApierV1.AddBalance) and different when getting them(ApierV2.GetAccounts). It would would be nice to have same values for both of them.

**ApierV1.AddBalance -------------------------->ApierV2.GetAccount**
BalanceUUID -------------------------------------->Uuid
BalanceID------------------------------------------->ID
ExpiryTime------------------------------------------>ExpirationDate
DestinationI**d**s------------------------------------->DestinationI**D**s
TimingI**d**s------------------------------------------->TimingI**D**s

thank you.
Vasilios Tzanoudakis

**Comment by Trial97** [comment]
We are closing the issue as obsolete. 
Please reopen if needed.
