### ISSUE TITLE
ApierV1.GetActionPlanIDs - rpc: can't find method

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#1693]
Dear Team,

I am trying to use [ApierV1.GetActionPlanIDs](https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.GetActionPlanIDs) on latest master

```
{
    "method": "ApierV1.GetActionPlanIDs",
    "params": [
        {
            "Tenant": "XXXX"
            
        }
    ]
}
```
But the result is :
```
{
    "id": null,
    "result": null,
    "error": "rpc: can't find method ApierV1.GetActionPlanIDs"
}
```

Is this feature implemented?

thank you in advance
Best Regards
Vasilios Tzanoudakis

**Comment by TeoV** [comment]
Hi Vasilios,

Please attach the config.

Thanks,
TeoV

**Comment by vtzan** [comment]
Dear TeoV,

Thank you for your response.
Here is the config: https://pastebin.com/u4hiRq4e

Best Regards
Vasilios Tzanoudakis

**Comment by TeoV** [comment]
Hi Vasilios,

We just tested this and it works.
```
T 2019/09/23 06:28:34.100315 127.0.0.1:58082 -> 127.0.0.1:2012 [AP]
{"method":"ApierV1.GetActionPlanIDs","params":[{"Tenant":"cgrates.org","Limit":null,"Offset":null}],"id":10}

T 2019/09/23 06:28:34.101029 127.0.0.1:2012 -> 127.0.0.1:58082 [AP]
{"id":10,"result":["AP_PACKAGE_10"],"error":null}
```
The error said that in your engine the RALs didn't start.
Please check if RALs started by sendind a ping: 
```
T 2019/09/23 06:34:07.891946 127.0.0.1:58184 -> 127.0.0.1:2012 [AP]
{"method":"RALsV1.Ping","params":[{}],"id":0}

T 2019/09/23 06:34:07.892430 127.0.0.1:2012 -> 127.0.0.1:58184 [AP]
{"id":0,"result":"Pong","error":null}
```

Thanks,
TeoV

**Comment by vtzan** [comment]
Dear TeoV,

Strange! Rals ping responded with Pong without problem.
Here is what CGRateS Shows after startup after installing latest current pkg --> https://pastebin.com/52MFwa1D

Do you see something there?

Thank you in advance
Vasilios Tzanoudakis

**Comment by TeoV** [comment]
Hi Vasilios,

Please check with this API if RALs is enabled in your cgr-engine : 
```
T 2019/09/24 14:01:14.243926 127.0.0.1:44498 -> 127.0.0.1:2012 [AP]
{"method":"ConfigSv1.GetJSONSection","params":[{"APIKey":null,"RouteID":null,"Tenant":"","Section":"rals"}],"id":0}

T 2019/09/24 14:01:14.244266 127.0.0.1:2012 -> 127.0.0.1:44498 [AP]
{"id":0,"result":{"RALsBalanceRatingSubject":{"*any":"*zero1ns","*data":"*zero1ns","*generic":"*zero1ns","*monetary":"*zero1ns","*sms":"*zero1ns","*voice":"*zero1s"},"RALsEnabled":true,"RALsMaxComputedUsage":{"*any":680400000000000,"*data":107374182400,"*sms":10000,"*voice":259200000000000},"RALsMaxIncrements":1000000,"RALsStatSConns":[],"RALsThresholdSConns":[],"RemoveExpired":true,"RpSubjectPrefixMatching":false},"error":null}
```
You should see "RALsEnabled":true.

Thanks,
TeoV

**Comment by vtzan** [comment]
Problem Solved! We found out with @danbogos that I had an older version on the machine I was testing. Thank you all for support on this!!!
