### ISSUE TITLE
Issue retrieving CDRs

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#171]
Hi Guys,
I seems to be getting the errors below when I try to retrieve CDRs from a certain machine.

Type "help", "copyright", "credits" or "license" for more information.
>> from json_client import CGRConnector as A
>> conn = A()
Connecting to cgr-engine...
>> cdrs = conn.call('ApierV2.GetCdrs',{})
('ERROR: ', <type 'exceptions.ValueError'>, ValueError('Unterminated string starting at: line 1 column 43760 (char 43759)',))
Connecting to cgr-engine...

>> cdrs = conn.call('ApierV2.GetCdrs',{})
('ERROR: ', <type 'exceptions.ValueError'>, ValueError('Extra data: line 1 column 4 - line 3 column 1 (char 3 - 7329534)',))

Connecting to cgr-engine...
>> cdrs = conn.call('ApierV2.GetCdrs',{'AnswerTimeStart':'2015-09-09T00:00:00Z', 'AnswerTimeEnd':'2015-09-10T00:00:00Z'})
('ERROR: ', <type 'exceptions.ValueError'>, ValueError('Extra data: line 1 column 4 - line 3 column 1 (char 3 - 4131560)',))
Connecting to cgr-engine...
>>

but I am able to see the CDRs on port 2012 when I run ngrep and the CDRs have all these backslashes "\".  

```T 2015/09/10 02:11:58.291361 127.0.0.1:2012 -> 127.0.0.1:55534 [AP]
ll,\"CompressFactor\":31}],\"MatchedSubject\":\"*out:sbc.cgrates.com.au:customer:*any\",\"MatchedPrefix\":\"61401\",\"MatchedDestId\":\"Australia_Mobile\",\"RatingPlanId\":\"RP_CUSTOMER\"}]}","Rated":false}......<snipped>````

I am using the package dated 1st Sept.
There are no errors in syslog or in cgrates.strace

Any ideas?

Regards,

Errol

**Comment by danbogos** [comment]
Hi Errol,

Since you are becoming the answer over network, this does look to be CGRateS issue but connector one. Will need to check it there.

Thanks,
DanB

**Comment by ewsamuels** [comment]
Hi DanB,
Please forgive my ignorance but I don't understand what you mean by "Since you are becoming the answer over network".

Regards,
Errol

**Comment by danbogos** [comment]
Hi Errol

You mentioned seeing data coming over network.

DanB
Am 10.09.2015 09:45 schrieb "Errol Samuels" <notifications@github.com>:

**Comment by ewsamuels** [comment]
Hi DanB,
I had an idea to try a different way using curl this time.
So I tried these two API calls:

```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV2.GetCdrs","params":[{}]}' http://localhost:2080/jsonrpc```

```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetCdrs","params":[{}]}' http://localhost:2080/jsonrpc```

With both of these API calls I am getting the CDRs and there are no errors.  So maybe like you said there is an issue with the JSON client.

However in the CDRs just like the ones on Ngrep I am seeing these "/" backslashes in the CDRs.  Maybe there are for escaping characters?  Is that normal to have them?

Regards,

Errol

**Comment by danbogos** [comment]
Hi Errol

Yes the // can be escape chars.

DanB
Am 10.09.2015 13:16 schrieb "Errol Samuels" <notifications@github.com>:

**Comment by danbogos** [comment]
Hi Errol,

Since this issue is not cgrates related I will close it for now so we don't get false alarms on this channel.

DanB

**Comment by ewsamuels** [comment]
DanB,
The issue seemed to have been related to the json_client.py that I got from rif sometime ago.   We have stopped using it now and the problem has gone away!

esamuels

**Comment by danbogos** [comment]
Hi Errol,

If you need to still do it via python (eg: from your django app), there are a number of different other python implementations which you can choose from. I suggest checking the list here:
https://en.wikipedia.org/wiki/JSON-RPC#Implementations for python.

DanB
