### ISSUE TITLE
Ability to set sslmode for postgres connections in config

### ISSUE THREAD

**Issue by mahummon** [cgrates/cgrates#1715]
First off, thank you to all the contributors for an amazing project. 

I'm currently participating in a wonderful training class from the cgrates team when I ran in to an issue trying to use a managed postgres cluster from digitalocean for my `stor_db`.

When running 

```
cgr-migrator -config_path=/etc/cgrates -exec="*set_versions"
```

I get the following error

```
2019/10/17 11:25:09 pq: no pg_hba.conf entry for host "x.x.x.x", user "cgrates", database "cgrates", SSL off
```

@danbogos kindly pointed me to the following line where the connection string is being built

https://github.com/cgrates/cgrates/blob/master/engine/storage_postgres.go#L31

Digitalocean requires `sslmode=require`. It would be great if `sslmode` could be set in config.

-Matt

**Comment by Trial97** [comment]
Hi @mahummon,

This feature should be added in master, please update and test it.

Thanks,
Trial97
