### ISSUE TITLE
[Feature] Add support for RemoveRatingPlans

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#1729]
Dear Team,

Currently I can't find a way to remove RatingPlans from DataDB. It would be nice feature to have an apier e.g. `RemoveRatingPlans` to remove a RatingPlans from live DB.

Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Thank you guys @danbogos @adragusin !!!! We really appreciate this.

Best Regards
Vasilios Tzanoudakis

**Comment by adragusin** [comment]
Hi @vtzan 

You're welcome, 

Best regards,
adragusin
