### ISSUE TITLE
GetResourceProfileIDs and GetChargerProfileIDs from apier v1 replaces two characters with empty string

### ISSUE THREAD

**Issue by mehrdadep** [cgrates/cgrates#1732]
When using `ApierV1.GetChargerProfileIDs`or `ApierV1.GetResourceProfileIDs` the first two charachters of Tenant will replace with ''.
This is the results from APIs:

```
{
  "id": "1231231",
  "result": [
    "2.16.0.73:ResGroup1",
    ".104.118.63:ResGroup1"
  ],
  "error": null
}
```

This is the expected results:
```
{
  "id": "1231231",
  "result": [
    "172.16.0.73:ResGroup1",
    "77.104.118.63:ResGroup1"
  ],
  "error": null
}
```
version of CGRateS:` CGRateS 0.9.1~rc8 git+f183a53 `

**Comment by adragusin** [comment]
Hi @mehrdadep,
Please update to master and retest.  
Thanks,
adragusin
