### ISSUE TITLE
GetMaxUsage returning -1

### ISSUE THREAD

**Issue by stevehillin** [cgrates/cgrates#1733]
Opening per Dan's request:
T 2019/11/05 10:50:22.160177 10.247.110.9:49529 -> 10.247.110.11:2014 [AP]
{ "method": "SessionSv1.InitiateSession", "id": 1140194175, "params": [ { "GetMaxUsage": true, "Event": { "RequestType": "*rated", "Category": "INBOUND_TOLLFREE", "Destination": "1844xxxxxxx", "Account": "XXXX", "OriginID": "1550092719_134200648@<ip>", "DialogID": 293531910, "DialogEntry": 1963, "SetupTime": "1572972588", "AnswerTime": "1572972588" }, "InitSession": true } ] }
#
T 2019/11/05 10:50:22.160431 127.0.0.1:56184 -> 127.0.0.1:2012 [AP]
{"method":"ChargerSv1.ProcessEvent","params":[{"Tenant":"xxxx.com","ID":"faf77d1","Time":null,"Event":{"Account":"XXXX","AnswerTime":"1572972588","CGRID":"44111bc3d95f727d77c8b2b0dddbe9cae1cbc2b3","Category":"INBOUND_TOLLFREE","Destination":"1844xxxxxxx","DialogEntry":1963,"DialogID":293531910,"OriginID":"1550092719_134200648@<ip>","RequestType":"*rated","SetupTime":"1572972588"}}],"id":2}

#
T 2019/11/05 10:50:22.161075 127.0.0.1:2012 -> 127.0.0.1:56184 [AP]
{"id":2,"result":[{"ChargerSProfile":"XXXX","AttributeSProfiles":null,"AlteredFields":null,"CGREvent":{"Tenant":"xxxx.com","ID":"faf77d1","Time":null,"Event":{"Account":"XXXX","AnswerTime":"1572972588","CGRID":"44111bc3d95f727d77c8b2b0dddbe9cae1cbc2b3","Category":"INBOUND_TOLLFREE","Destination":"1844xxxxxxx","DialogEntry":1963,"DialogID":293531910,"OriginID":"1550092719_134200648@<ip>","RequestType":"*rated","RunID":"*default","SetupTime":"1572972588"}}}],"error":null}

##
T 2019/11/05 10:50:22.161192 10.247.110.11:2014 -> 10.247.110.9:49529 [AP]
{"id":1140194175,"result":{"Attributes":null,"ResourceAllocation":null,"MaxUsage":-1,"ThresholdIDs":null,"StatQueueIDs":null},"error":null}

**Comment by danbogos** [comment]
Should be fixed in master. Please retest and report here if issues.

Thanks,
DanB
