### ISSUE TITLE
New apt repository?

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1752]
Hi all,

I see http://www.cgrates.org/tmp_pkg/ is now empty. I presume this is the latest way:

https://cgrates.readthedocs.io/en/latest/installation.html

Congrats btw! Great work on getting to this.

Gavin.

**Comment by TeoV** [comment]
Hi @ghenry,

Now the process is fully automated ( congrats to ansible ). 
Old tmp_pkg is history.

Thanks,
TeoV

**Comment by ghenry** [comment]
Thanks. You mean the generating of the debs etc?

**Comment by TeoV** [comment]
Hi @ghenry,

Yes, the generating process and the indexing of old packages.

Thanks,
TeoV
