### ISSUE TITLE
ActionTrigers to be used in SetAccount API

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#176]
Right now the way to set action triggers is with cgr-loader or individual SetActionTriggers API calls. This is not very robust in case of adding users via SetAccount API when used in conjunction with commercial packages. 
To solve this issue we should attach ActionTriggers also via SetAccount.
For that we need also to store ActionTriggers on load time into tp_db.

DanB

**Comment by danbogos** [comment]
Can we maybe add ActionTriggers into cache as well, in order to be consistent with the rest of the data?

DanB

**Comment by rif** [comment]
Decided to leave them out of cache (consistent with action plans)
