### ISSUE TITLE
Feature Request: Count of all items for APIs that include lists

### ISSUE THREAD

**Issue by mehrdadep** [cgrates/cgrates#1774]
CGRateS have pagination using limit and offset. we need to know the count of all items to make a useful limit offset pagination system. So each API that returns a list of items should return count of all items somehow.

For example `ApierV2.GetAccounts` can have `ApierV2.GetAccountsCount` that returns count of all accounts. here is a list of requested APIs

1. `ApierV2.GetAccountsCount`
2. `ApierV2.GetActionsCount`
3. `CDRsV2.GetCDRsCount`
4. `ApierV1.GetAttributeProfileIDsCount`
5. `ApierV1.GetThresholdProfileIDsCount` 

here is the link of related [Google Groups Topic](https://groups.google.com/forum/#!topic/cgrates/xDV7-B5STpY)

**Comment by adragusin** [comment]
Hi @mehrdadep,

The following APIs are now implemented: 

1. ApierV2.GetAccountsCount
https://godoc.org/github.com/cgrates/cgrates/apier/v2#APIerSv2.GetAccountsCount
2. ApierV2.GetActionsCount
https://godoc.org/github.com/cgrates/cgrates/apier/v2#APIerSv2.GetActionsCount
3. CDRsV2.GetCDRsCount
https://godoc.org/github.com/cgrates/cgrates/apier/v1#CDRsV1.GetCDRsCount
4. APIerSv1.GetAttributeProfileIDsCount
https://godoc.org/github.com/cgrates/cgrates/apier/v1#APIerSv1.GetAttributeProfileIDsCount
5. APIerSv1.GetThresholdProfileIDsCount
https://godoc.org/github.com/cgrates/cgrates/apier/v1#APIerSv1.GetThresholdProfileIDsCount

Thanks, 
adragusin

**Comment by mehrdadep** [comment]
Great, keep up the good work
