### ISSUE TITLE
Bug: CGRateS crashes in case of sending a null argument to the API

### ISSUE THREAD

**Issue by mehrdadep** [cgrates/cgrates#1778]
After calling CDRsV2.GetCDRs with empty params, CGR crashes 
```
{
 "jsonrpc": "2.0",
 "method": "CDRsV2.GetCDRs",
 "params": [
 {

 }
 ],
 "id": 12345545
}
```

**Comment by Trial97** [comment]
Hi @mehrdadep,

This should be solved on latest master, please update and retest.

Thanks,
Trial97
