### ISSUE TITLE
CGRateS don't iterate correctly over csv files in cdrc

### ISSUE THREAD

**Issue by mintos5** [cgrates/cgrates#1779]
### Description

In our workflow, we are importing cdrs from multiple csv files and we are using "run_delay": 3 to create consecutive runs (not using inotify). CGRateS is not processing all files in the folder during one consecutive run.
#### Reproduction

We created 3 files at the same time. After run_delay time CGRateS will start to process these files. Problem is that CGRateS is three times processing the last file. 

### Possible Solutions

I found the problem in cdrc/cdrc.go. To be precise here:https://github.com/cgrates/cgrates/blob/master/cdrc/cdrc.go#L157
Fixing it like this:
```diff
        filesInDir, _ := ioutil.ReadDir(self.dfltCdrcCfg.CDRInPath)
        for _, file := range filesInDir {
                if self.dfltCdrcCfg.CdrFormat != utils.MetaFScsv || path.Ext(file.Name()) != ".csv" {
-                       go func() { //Enable async processing here
+                       go func(file os.FileInfo) { //Enable async processing here
                                if err := self.processFile(path.Join(self.dfltCdrcCfg.CDRInPath, file.Name())); err != nil {
                                        utils.Logger.Err(fmt.Sprintf("Processing file %s, error: %s", file, err.Error()))
                                }
-                       }()
+                       }(file)
                }
        }
        return nil
```

### Additional Information
The explanation why these changes are needed:
https://stackoverflow.com/questions/21822527/why-golang-dont-iterate-correctly-in-my-for-loop-with-range

```
 CGRateS 0.9.1~rc8 git+87af8cd
```

**Comment by TeoV** [comment]
Hi @mintos5,

Please open a Pull Request for this change and we will be happy to review it.

Thanks,
TeoV

**Comment by TeoV** [comment]
Hi @mintos5,

We integrated your pull request ( https://github.com/cgrates/cgrates/pull/1782 ) 

Thanks,
TeoV
