### ISSUE TITLE
cgr-migrator -exec=*filters

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1787]
Gives me:

`2019/11/28 14:47:43 NOT_FOUND`

**Comment by TeoV** [comment]
Hi Gavin,

Can you please capture the communications between the CGRateS and the DataDB and send it to us so we can see what gives out NOT_FOUND?

Thanks,
TeoV

**Comment by ghenry** [comment]
Ah, I think it's our redis not speaking to each other. Closing.

**Comment by ghenry** [comment]
redis is all correct:
```
T 2019/11/28 19:16:10.393579 185.xx:33824 -> 185.xx:26379 [AP]
*3.
$8.
SENTINEL.
$6.
MASTER.
$6.
master.

##
T 2019/11/28 19:16:10.394152 185.xx:26379 -> 185.xx:33824 [AP]
*40.
$4.
name.
$6.
master.
$2.
ip.
$13.
185.xx.
$4.
port.
$4.
6379.
$5.
runid.
$40.
267460ed208dd91f36c407a4697f55cf4758ad9a.
$5.
flags.
$6.
master.
$21.
link-pending-commands.
$1.
```

but still getting:

```
cgr-migrator -verbose -datadb_type=redis -datadb_host="xxx:26379;xxx:26380;xxx:26381" -datadb_name=10 -datadb_passwd=xxx -redis_sentinel=master -stordb_host="xx" -stordb_passwd="xxx" -stordb_type="*postgres" -stordb_name="cgrates" -stordb_port="5432" -exec=*filters 
2019/11/28 19:16:10 NOT_FOUND
```

**Comment by TeoV** [comment]
Hi Gavin,

Please update from the master and attach the Redis communication as requested above.

Thanks,
TeoV

**Comment by ghenry** [comment]
Will be upgrading soon.

**Comment by danbogos** [comment]
Hey @ghenry 

Since there was not much activity, will close the issue for now. Please reopen it once you can confirm that the issue persists.

Thanks,
DanB

**Comment by ghenry** [comment]
I think there's a better error message now, but it's the same thing?

https://groups.google.com/forum/#!topic/cgrates/Wbb14RDKw74
