### ISSUE TITLE
Lcr Incorrect results

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#180]
Hi Guys,

We seem to have an issue with the LCR picking the longest match rate for a destination.
If I run this API call:
```curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"vb_direct","Account":"9840952636","Subject":"9840952636","Destination":"447783855111","StartTime":"2015-09-16T23:15:00Z","Duration":"60"}]}' http://localhost:2080/jsonrpc```

**The result is:**
{"id":null,"result":{"DestinationId":"*any","RPCategory":"vb_direct","Strategy":"*lowest_cost","Suppliers":[{"Supplier":"voxbeam_direct","Cost":0.0955,"QOS":null}]},"error":null}

Here it is returning the shortest match which is actually the most expensive.  

```curl -X POST -H "Content-Type: application/json" -d '{"method":"Responder.GetCost","params":[{"Direction":"*out","Category":"vb_direct","Tenant":"cgrates.org","Subject":"voxbeam_direct","Account":"9840952636","Destination":"447783855111","TimeStart":"2015-09-16T22:00:00Z","TimeEnd":"2015-09-16T22:01:00Z"}]}' http://localhost:2080/jsonrpc```

**Also GetCost finds the correct MatchedDestId but the rate is incorrect and I suspect its the same with the LCR.  The rate return is for 0.0955 for United_Kingdom_Mobile rather than 0.0079 which is for United_Kingdom_Mobile_O2**
{"id":null,"result":{"Direction":"*out","Category":"vb_direct","Tenant":"cgrates.org","Subject":"voxbeam_direct","Account":"9840952636","Destination":"447783855111","TOR":"*voice","Cost":0.0955,"Timespans":[{"TimeStart":"2015-09-16T22:00:00Z","TimeEnd":"2015-09-16T22:01:00Z","Cost":0.0955,"RateInterval":{"Timing":{"Years":[],"Months":[],"MonthDays":[],"WeekDays":[],"StartTime":"00:00:00","EndTime":""},"Rating":{"ConnectFee":0,"RoundingMethod":"*middle","RoundingDecimals":5,"MaxCost":0,"MaxCostStrategy":"0","Rates":[{"GroupIntervalStart":0,"Value":0.0955,"RateIncrement":1000000000,"RateUnit":60000000000}]},"Weight":10},"DurationIndex":60000000000,"Increments":null,"MatchedSubject":"*out:cgrates.org:vb_direct:voxbeam_direct","MatchedPrefix":"447783","MatchedDestId":"United_Kingdom_Mobile_O2","RatingPlanId":"RP_VOXBEAM_DIRECT"}]},"error":null}

I have attached two screenshot so you can see the rates.

![uk_mobile_o2](https://cloud.githubusercontent.com/assets/5496519/9912395/4eff77b6-5c9f-11e5-939e-92b71db301f6.png)
![uk_mobile](https://cloud.githubusercontent.com/assets/5496519/9912398/53c9e18c-5c9f-11e5-885c-f507d23915a4.png)

Regards,

Errol

**Comment by danbogos** [comment]
Hi Errol,

Please confirm whether the issue was false alarm/fixed.

Thanks,
Dan

**Comment by ewsamuels** [comment]
Seems to work in the latest package as of today 22nd Sept.
