### ISSUE TITLE
attributes_process_event on version CGRateS 0.9.1~rc8 git+7d27cff (2019-11-10T16:15:03+01:00)

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1808]
```cgr> attributes_process_event Tenant="surevoip" Context="*any" Event={"Account":"XXXX"} Error executing command: NOT_FOUND```

**Comment by Trial97** [comment]
Hi Gavin,

Your context is wrong.

Thanks,
Trial97

**Comment by ghenry** [comment]
What should it be?

**Comment by Trial97** [comment]
Hi @ghenry,

You should use the same context as you have configured in your AttributeProfile.

Thanks,
Trial97

**Comment by ghenry** [comment]
Ah yes. Working. Apologies.
