### ISSUE TITLE
FREE minutes is being charged a ConnectFee

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#181]
Hello Guys,
We have a created a package with X number of FREE minutes.  This package is associated with a Tariff Plan which has a Rate and ConnectFee configured with the intention that when the user exceeds his FREE minutes calls will get charged at the rate as well as the connectFee defined in the Tariff Plan.

The calls are working correctly meaning the FREE minutes are not being charged but the calls are being charged the ConnectFee which should not happen since these are FREE minutes.  This ConnectFee charge should only come into play once the customer exceeds their FREE minutes allowance.

"*voice*out": [
        {
           "Uuid": "3606e224-2a77-40e0-90a5-a27c35c7c442",
          "Id": "",
         "Value": 30000,
          "ExpirationDate": "0001-01-01T00:00:00Z",
          "Weight": 10,
           "DestinationIds": "United_Kingdom_Fixed, United_Kingdom_Mobile",
          "RatingSubject": "",
           "Category": "",
          "SharedGroup": "",
           "Timings": null,
          "TimingIDs": ""
         }
       ]
This is what the balance looks like.
Let me know if you need more info.

Regards,

Errol

**Comment by rif** [comment]
Hi Errol, I would need a callcost info structure for a such a call (that was charged from the free minute balance and an extra wrong connect fee from a money balance).

**Comment by rif** [comment]
Found the reason why the balance was not seleted: DestinationIds value format is wrong.

It should be "United_Kingdom_Fixed;United_Kingdom_Mobile" with semicolon and no space.

Please try after this change and report your results.

**Comment by ewsamuels** [comment]
I am still in the process of testing this.  Please don't close!

**Comment by danbogos** [comment]
Last update 12 days ago. Please reopen if any issue

DanB
