### ISSUE TITLE
freeswitch agent empty_balance_context  not working on zero balance

### ISSUE THREAD

**Issue by babakyakhchali** [cgrates/cgrates#1812]
Hi
Trying to use empty_balance_context  in freeswitch agent to send zero balance calls to a context and do something with these calls. As configuration file shows setting empty_balance_context   to the name of the context should work, setting empty_balance_context   to a context like "nocharge" in cgrates.json works only if account balance reaches zero during a call, but if a call is started when account blanace is already zero, just after answer I see these logs in freeswitch console:

2019-12-10 12:37:20.389338 [NOTICE] switch_ivr.c:2238 Transfer sofia/internal/1001@192.168.205.135:5060 to nocharge[XML@default]
2019-12-10 12:37:20.389338 [ERR] switch_core_state_machine.c:276 Dialplan [nocharge] not found, skipping
2019-12-10 12:37:20.389338 [INFO] switch_core_state_machine.c:312 No Route, Aborting

and this results a loop in cgrates which logs these repeatedly:

Dec 10 12:37:20 debian CGRateS <cdcb9f7> [46025]: <FreeSWITCHAgent> error: -ERR No such channel! when attempting to disconnect channelID: 575517da-6595-43e2-8b1a-e42ebe3415c7 over connIdx: 0
Dec 10 12:37:20 debian CGRateS <cdcb9f7> [46025]: <SessionS> could not command disconnect session: 5433db21c350f38ff30787a1ee0e37a07e6a4586, error: -ERR No such channel!
Dec 10 12:37:20 debian CGRateS <cdcb9f7> [46025]: <FreeSWITCHAgent> error: -ERR No such channel! when attempting to disconnect channelID: 575517da-6595-43e2-8b1a-e42ebe3415c7 over connIdx: 0
Dec 10 12:37:20 debian CGRateS <cdcb9f7> [46025]: <SessionS> could not command disconnect session: 5433db21c350f38ff30787a1ee0e37a07e6a4586, error: -ERR No such channel!

I read through source and it seems problem starts in this line:
https://github.com/cgrates/cgrates/blob/2558d55607bad1d930f747ae4639caa29928e596/agents/fsagent.go#L335
when redirectNr is empty and the api call arguments are created incorrectly

this is a sample api call event:
RECV EVENT
Event-Name: API
Core-UUID: edde1e58-ba75-4a91-b048-f186b59c872d
FreeSWITCH-Hostname: debian
FreeSWITCH-Switchname: debian
FreeSWITCH-IPv4: 192.168.205.135
FreeSWITCH-IPv6: ::1
Event-Date-Local: 2019-12-10 12:55:19
Event-Date-GMT: Tue, 10 Dec 2019 09:25:19 GMT
Event-Date-Timestamp: 1575969919149382
Event-Calling-File: switch_loadable_module.c
Event-Calling-Function: switch_api_execute
Event-Calling-Line-Number: 2992
Event-Sequence: 858819
API-Command: uuid_transfer
API-Command-Argument: 8ce4136e-0c36-47c7-b7fb-1504f789597e  XML nocharge

as you can see there is no destination number in arguments so freeswitch consideres "nocharge" as context dialplan name which is invalid

I attached full fs log to this issue
thanks

[cgrfslg.txt](https://github.com/cgrates/cgrates/files/3944061/cgrfslg.txt)

**Comment by Trial97** [comment]
Hi @babakyakhchali,

We only handle the context switch we disconnect the session.
If you want to switch the context on authorize/initialize event by editing your `dialplan.xml` during park application to switch the context when receiving from us the `INSUFFICIENT_CREDIT` error.

Thanks,
Trial97
