### ISSUE TITLE
SERVER_ERROR: REPLY_TIMEOUT while charging

### ISSUE THREAD

**Issue by Barak-Cellact** [cgrates/cgrates#1846]
Hi CGRateS team,

Occasionally when charging SMS's (using SMGenericV2.ChargeEvent API), we start receiving "SERVER_ERROR: REPLY_TIMEOUT" errors and are forced to restart the service in order to recover the system.

I'm able to simulate it with 3 concurrent requests, which are sent immediately after a clean restart.

Attached our config + example tp.

[cgrates.txt](https://github.com/cgrates/cgrates/files/4027269/cgrates.txt)
[tp_destination_rate.txt](https://github.com/cgrates/cgrates/files/4027271/tp_destination_rate.txt)
[tp_rating_plan.txt](https://github.com/cgrates/cgrates/files/4027272/tp_rating_plan.txt)
[tp_rating_profile.txt](https://github.com/cgrates/cgrates/files/4027274/tp_rating_profile.txt)

**Comment by Barak-Cellact** [comment]
Our version: CGRateS 0.9.1~rc8 git+07bca27 (2018-05-16T15:24:15+02:00)

**Comment by danbogos** [comment]
Hi @Barak-Cellact 

Can you please upgrade and test with the master version? There are chances that we have fixed your issue in between.
You can find installation instructions [here](https://cgrates.readthedocs.io/en/latest/installation.html)

Thanks,
DanB
