### ISSUE TITLE
ExtraFields in CDRs

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1877]
Hello Dear CGRateS Team!
In the older versions of CGRateS, I had my ExtraFields added to CDR in TerminateSession. Now it is omitted in CDR , only if sent with InitiateSession first. 
For us, CallInformationInfoRequestReport comes at the end of a call, and I have my values only at termination call state.
Please could you explain what would be the correct way of adding ExtraField values ?
Or, it's something that shouldn't be like that ?

Link to the topic for traces https://groups.google.com/d/topic/cgrates/P0UosrErw9M/discussion

Thanks in advance, 
Michael

**Comment by Trial97** [comment]
Hi @muxalko,

We updated the master with a new setting `alterable_fields` for SessionS configuration(https://github.com/Trial97/cgrates/blob/session_update/config/config_defaults.go#L422).
This is used to specify SessionS which fields can be overwritten by the incoming event.
Please populate the `alterable_fields` in your config and retest.

Thanks,
Trial97

**Comment by muxalko** [comment]
It is working !
Thanks a lot.
