### ISSUE TITLE
ApierV1.RemoveRatingProfile not removing the correct key

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#194]
Hello guys,

It would appear that ApierV1.RemoveRatingProfile is not removing the correct key instead it is removing all the keys with the same category. For example I had the following keys:

1) "rpf_*out:cgrates.org:priority:voxbeam_direct"
2) "rpf_*out:cgrates.org:call_cgrt_plat:*any"
3) "rpf_*out:cgrates.org:did_inbound:*any"
4) "rpf_*out:cgrates.org:call_cgrt_prem:*any"
5) "rpf_*out:cgrates.org:priority:voxbeam_premium"
6) "rpf_*out:cgrates.org:cgrt_premium:*any"

Then made the following API call:

curl -X POST -H "Content-Type: application/json" -d  '{"method": "ApierV1.RemoveRatingProfile", "params": [{"Category": "priority", "Subject ": "voxbeam_direct", "Direction": "*out", "Tenant": "demo.cgrtbilling.org"}]}'  http://localhost:2080/jsonrpc
{"id":null,"result":"OK","error":null}

Which was meant only to remove the 1st key: 
1) "rpf_*out:cgrates.org:priority:voxbeam_direct"

but instead it removed both keys with the category priority so I ended up with:

1) "rpf_*out:cgrates.org:call_cgrt_plat:*any"
2) "rpf_*out:cgrates.org:did_inbound:*any"
3) "rpf_*out:cgrates.org:call_cgrt_prem:*any"
4) "rpf_*out:cgrates.org:cgrt_premium:*any"

Regards,

Errol

**Comment by rif** [comment]
You have an extra space after Subject attribute in your curl json so the subject value is not mapped on the structure field. See  "Subject "
                                                   ^
Please close after confirmation.

**Comment by ewsamuels** [comment]
Hi rif,
You have the eyes of an eagle...well spotted!
Thanks

**Comment by danbogos** [comment]
-1 on @ewsamuels ring of trust. :)

DanB
