### ISSUE TITLE
UnitCounters - Counters per day and week

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#199]
Today we can only have counters per day or week (depending on reset time).
Need a mechanism to be able to count more than one average for a balance (eg: when defining thresholdId).

DanB

**Comment by ewsamuels** [comment]
As per my IRC chat I think counters for day, month and year would better as especially for Accounting purposes.

With this info you can have daily, month_to_date / current_month and year_to_date / current_year totals much easier to access than doing it a more long winded way.

Regards,

Errol

**Comment by rif** [comment]
latest build updates all counters matching event or balance. Multiple triggers can be added with the same filters and they can be reseted at various periods of time.
