### ISSUE TITLE
Bad path value in default config ers->readers->fields->path

### ISSUE THREAD

**Issue by mintos5** [cgrates/cgrates#1994]
Hi CGRateS team, after upgrading to a stable v0.10 version we have found a problem with default config and documentation for ERS service.
The path value is like this:
https://github.com/cgrates/cgrates/blob/646f9a33cdb416d93ace97121dc463bbdf16e195/data/conf/cgrates/cgrates.json#L299
It is missing ***cgreq.** or similar which is needed.
I found correct config in data/conf/samples (I think used for testing)
https://github.com/cgrates/cgrates/blob/646f9a33cdb416d93ace97121dc463bbdf16e195/data/conf/samples/ers_postgres/cgrates.json#L118

Please update the default config and documentation. Thank You

**Comment by danbogos** [comment]
Should be fixed in master.
