### ISSUE TITLE
attributes.go problem with utils.MetaTenant and attributes with filters

### ISSUE THREAD

**Issue by mintos5** [cgrates/cgrates#1995]
Hi CGRateS team. After playing with v0.10 We found a small problem with attributes service.

We have attributes that use varied attribute_filters. One of the same attributes is changing Tenant with  **utils.MetaTenant** in its path.
The problem occurs after calling this section of code:
https://github.com/cgrates/cgrates/blob/646f9a33cdb416d93ace97121dc463bbdf16e195/engine/attributes.go#L261-L278
We have changed the tenant that is great but we have other attributes that use filters and they need to be applied.

Attributes.go continues execution to this line:
https://github.com/cgrates/cgrates/blob/646f9a33cdb416d93ace97121dc463bbdf16e195/engine/attributes.go#L177
Problem is the **args.Tenant** is changed to the new value. So attributes.go can not find the filters used by the attributes.

We found a workaround for this:
```diff
+       tenantFix := args.Tenant
        evNm := config.NewNavigableMap(map[string]interface{}{utils.MetaReq: rply.CGREvent.Event})
        for _, attribute := range attrPrf.Attributes {
                //in case that we have filter for attribute send them to FilterS to be processed
                if len(attribute.FilterIDs) != 0 {
-                       if pass, err := alS.filterS.Pass(args.Tenant, attribute.FilterIDs,
+                       if pass, err := alS.filterS.Pass(tenantFix, attribute.FilterIDs,
```
We know this is not a common problem but it will be nice if you can look at it. Thanks

**Comment by TeoV** [comment]
Hi @mintos5,

This part of the code works as expected. We had one user that required your scenario ( change the tenant for an event and have attributes that match new tenant).
What you can you are to set the priority of Attributes ( what attributes to be executed first ) by setting the weight ( the one with the highest weight will be executed first ).
We will consider this issue closed.

Thanks,
TeoV

**Comment by mintos5** [comment]
Hi @TeoV,
I was not totally clear. We are using just **one** **AttributeProfile**. This AttributeProfile has multiple **Attributes**. One of this Attributes changes Tenant. Other attributes change different things and use **FilterIDs**. 

If I understand correctly You can set priority just for **AttributeProfiles** and not for Attributes connected to AttributeProfiles. And I am not sure in what order this Attributes are executed.

I am sorry but we can not use your suggestion. Can You look at the problem one more time and open this issue again.

Thanks

**Comment by TeoV** [comment]
Hi @mintos5,

Attribute profile has a slice of Attributes ( it means that the order is kept ). Please modify the order or attributes and put the attribute that changes the tenant to be the last.

Thanks,
TeoV

**Comment by mintos5** [comment]
Hi @TeoV,
thanks for a quick reply. We are loading TarrifData from the Postgres database, the order is dependant by the pk column in the table tp_attributes? In other words, during the import, the attributes are sorted by the pk column?

If that is case everything is ok. And Thank you for clarification.

**Comment by TeoV** [comment]
Hi @mintos5,

We took the default order coming from Postgres.

Thanks,
TeoV
