### ISSUE TITLE
Timed Balances

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#2]
A useful feature when you want to specify something like: "User has 1000 minutes in weekends". 
The timed part should be seen as a filter which only activates specific balance during some time interval.

Dan

**Comment by danbogos** [comment]
Should be available in the latest master.

DanB

**Comment by ezgektor** [comment]
Hello, @danbogos 

Sorry for writing to the closed ticket, but maybe there is more info about this feature and how it can be used? I've tried to create a balance (AddBalance and SetBalance) with providing TimingIDs parameter, but looks like it is ignored and balances can be used any time. I've also created predefined Actions (SetActions) and tried to execute them to init new balance. It also has field TimingIDs, but it looks like it is still ignored.

If it is possible, can you, please, give any advice how to bind balances to concrete time when it can be used?

Thank you.

**Comment by danbogos** [comment]
hey @ezgektor,

What version of CGR are you using?

DanB

**Comment by ezgektor** [comment]
Hi @danbogos 

It is from late 2016.

**Comment by danbogos** [comment]
@ezgektor,

It is hard for us to troubleshoot on versions other than master.
If you can, please upgrade (or use a separate VM for tests), and let me know how it goes.

DanB

**Comment by ezgektor** [comment]
@danbogos,

thank you for your help. As soon, as I'll have any news after testing, I'll let you know.
