### ISSUE TITLE
High CPU consumption after update to stable version

### ISSUE THREAD

**Issue by alexwildix** [cgrates/cgrates#2041]
Hi all,

according to https://groups.google.com/forum/?pli=1#!topic/cgrates/nE_CIOArIwg need to investigate issue with high CPU consumption after upgrade to stable release. We have collect communication logs with CGRates for investigation
[radis_ngrep.txt.zip](https://github.com/cgrates/cgrates/files/4358777/radis_ngrep.txt.zip)
Please let me know if you need any additional info.
Thanks.

**Comment by TeoV** [comment]
Hi @alexwildix,

Please do the followings : 
1.Isolate the processes ( all should communicate via JSON-RPC ) 
2. Do CPU profiling at the process that does CPU spikes ( you can do this by populating the cpuprof_dir parameter when starting CGRateS https://github.com/cgrates/cgrates/blob/master/cmd/cgr-engine/cgr-engine.go#L50 ) 
3. Each service should run in its own process ( i.e: sessions independent from rals and cdrs and so on ) 

Thanks,
TeoV

**Comment by alexwildix** [comment]
Hi @TeoV ,
i tried to start CGRates with cgr-engine --log_level=7 --logger=*stdout --cpuprof_dir /, but file cpu.prof is empty. What i am doing wrong?

**Comment by alexwildix** [comment]
Hi @TeoV , the most load for CPU caused by redis due to requests from CGRates to them, please see screenshot attached. I will appreciate if you will check ngrep examples of communication and will find the reason of high redis load.
Thanks.
![image](https://user-images.githubusercontent.com/62422876/78764560-66c9b200-798f-11ea-95ee-228811a43366.png)
[ngrep_2080_2012.txt](https://github.com/cgrates/cgrates/files/4449349/ngrep_2080_2012.txt)
[ngrep_6379_2080_2012.txt](https://github.com/cgrates/cgrates/files/4449353/ngrep_6379_2080_2012.txt)

**Comment by TeoV** [comment]
Hi @alexwildix,

Regarding Redis high CPU consumption we found in your ngrep that you do a query for destination and reverse destination (start at line 5517 and ending somewhere at line 120000)  which returns a lot of them which indicate that you have unoptimized tariff plans.

First, you should so some optimization by compacting them and after that, you can use preaching ( if you don't use it ).

In the end, we don't see any issue with CGRateS here 

Thanks,
TeoV

**Comment by alexwildix** [comment]
Thanks a lot for your help.
