### ISSUE TITLE
cgr-loader: Could not reload cache: unexpected EOF

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#2075]
Process:

```
cgr-loader -config_path=../rals-v0.10.0 
2020/04/06 19:45:25 Could not reload cache: unexpected EOF

cgr-console -version
CGRateS@v0.10.0

~/rates$ cgr-console -server xxx:2022 -tls
Welcome to CGRateS console!
Type `help` for a list of commands

cgr> cache_reload
"OK"

cgr> status
{
 "ActiveGoroutines": 48,
 "GoVersion": "go1.13",
 "MemoryUsage": "316.9MiB",
 "NodeID": "xxx",
 "RunningSince": "Sun Mar 15 01:20:10 UTC 2020",
 "Version": "CGRateS@v0.10.1~dev-20200305141418-1bef8e48de92"
}
```

All works, but this `EOF` error(?).

Thanks.

**Comment by TeoV** [comment]
Hi Gavin,

Can you please attach the full log of EOF?

Thanks,
TeoV

**Comment by ghenry** [comment]
full log in what format? Thanks.

**Comment by TeoV** [comment]
Hi Gavin,

This panic comes with additions information ( reason of panic e.g. nil pointer, concurrent problem, etc...) and at what line in code happens.
Can you attach that information, please? 


Thanks,
TeoV

**Comment by ghenry** [comment]
Hi Teofil,

That's all the info I have on the console and logs. Data all gets loaded.

Thanks.

On Tue, 7 Apr 2020 at 12:43, Teofil Voivozeanu <notifications@github.com> wrote:
>
> Hi Gavin,
>
> This panic comes with additions information ( reason of panic e.g. nil pointer, concurrent problem, etc...) and at what line in code happens.
> Can you attach that information, please?
>
> Thanks,
> TeoV
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

**Comment by ghenry** [comment]
Hi TeoV,

There is no panic. This is all you see:

```
cgr-loader -config_path=../rals-v0.10.0 
2020/04/01 23:36:51 Could not reload cache: unexpected EOF
```

There's not the usual summary of what was loaded etc. after it completes. The EOF is all you have see. I can run this again any time with an ngrep or something. What do you need?

Thanks.

**Comment by TeoV** [comment]
Hi Gavin,

Please start the engine in a separate terminal with -logger=*stdout parameter and try to load again.
The engine will close and you should see the reason ( in your case the panic and the details )

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi TeoV,

Our engine lives in a Docker Swarm, so it's probably getting restarted
instantly if there is a crash. We have that all logged in ELK anyway.
Will check there.

Thanks.

**Comment by ghenry** [comment]
Hi again,

I'll reload rates tonight and then check the logs as they are too old now.

Thanks.

**Comment by ghenry** [comment]
So two issues:

1. I was using a config_path that had config to the rals to be on the localhost, which is incorrect. Data was still getting into the right places though. Crash shows:

```
Apr  7 19:56:05  cgr-engine[15143]: panic: runtime error: invalid memory address or nil pointer dereference
Apr  7 19:56:05  cgr-engine[15143]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x102665d]
Apr  7 19:56:05  cgr-engine[15143]: goroutine 101 [running]:
Apr  7 19:56:05  cgr-engine[15143]: github.com/cgrates/cgrates/engine.(*DataManager).CacheDataFromDB(0x0, 0x1770e3d, 0x4, 0x0, 0x0, 0x0, 0x203001, 0x0, 0x0)
Apr  7 19:56:05  cgr-engine[15143]: #011/home/dan/go/src/github.com/cgrates/cgrates/engine/datamanager.go:201 +0x245d
Apr  7 19:56:05  cgr-engine[15143]: github.com/cgrates/cgrates/engine.(*CacheS).reloadCache(0xc00079a180, 0x1770e3d, 0x4, 0x0, 0x0, 0x0)
Apr  7 19:56:05  cgr-engine[15143]: #011/home/dan/go/src/github.com/cgrates/cgrates/engine/caches.go:202 +0xcd
Apr  7 19:56:05  cgr-engine[15143]: github.com/cgrates/cgrates/engine.(*CacheS).V1ReloadCache(0xc00079a180, 0xc0002ff860, 0x0, 0x0, 0xc000726220, 0xc0007264a0, 0xc00000e0a0, 0xc00000e0e0, 0xc00000e1c0, 0xc00000e760, ...)
Apr  7 19:56:05  cgr-engine[15143]: #011/home/dan/go/src/github.com/cgrates/cgrates/engine/caches.go:253 +0x32f
Apr  7 19:56:05  cgr-engine[15143]: github.com/cgrates/cgrates/apier/v1.(*CacheSv1).ReloadCache(0xc0007db0b0, 0xc0002ff860, 0x0, 0x0, 0xc000726220, 0xc0007264a0, 0xc00000e0a0, 0xc00000e0e0, 0xc00000e1c0, 0xc00000e760, ...)
Apr  7 19:56:05  cgr-engine[15143]: #011/home/dan/go/src/caches_address=dckr-01.psg.uk.suretec.net:2012github.com/cgrates/cgrates/apier/v1/caches.go:104 +0x73
Apr  7 19:56:05  cgr-engine[15143]: reflect.Value.call(0xc000609020, 0xc0007db220, 0x13, 0x1770651, 0x4, 0xc000074f18, 0x3, 0x3, 0x0, 0x0, ...)
Apr  7 19:56:05  cgr-engine[15143]: #011/usr/local/go/src/reflect/value.go:460 +0x5f6
Apr  7 19:56:05  cgr-engine[15143]: reflect.Value.Call(0xc000609020, 0xc0007db220, 0x13, 0xc0007a3f18, 0x3, 0x3, 0x0, 0x0, 0x0)
Apr  7 19:56:05  cgr-engine[15143]: #011/usr/local/go/src/reflect/value.go:321 +0xb4
Apr  7 19:56:05  cgr-engine[15143]: net/rpc.(*service).call(0xc0006f4600, 0xc00013c000, 0xc000722000, 0xc000722020, 0xc00071aa80, 0xc0007260a0, 0x15f0b40, 0xc00044e1a0, 0x199, 0x1477900, ...)
Apr  7 19:56:05  cgr-engine[15143]: #011/usr/local/go/src/net/rpc/server.go:377 +0x16f
Apr  7 19:56:05  cgr-engine[15143]: created by net/rpc.(*Server).ServeCodec
Apr  7 19:56:05  cgr-engine[15143]: #011/usr/local/go/src/net/rpc/server.go:474 +0x42b
```

Also a local cgr-engine was running for a FS Agent. I think this can be closed due to user error. Apologies. Running cgr-loader with correct config and caches setting all works:

```
2020/04/07 20:26:46 Rebuilding reverse destinations
2020/04/07 20:29:32 Reloading cache
2020/04/07 20:29:32 Clearing indexes
```

**Comment by TeoV** [comment]
Hi Gavin,

Can you please attach the config in the form that produced the panic?

Thanks,
TeoV

**Comment by ghenry** [comment]
Hi TeoV,

Can do, but it's our FS agent config. Because I didn't set the cache
server, cgr-loader tried to reload cache on the cgr-engine for FS
agent on the box I was running it on. Still want it?

Thanks.

On Wed, 8 Apr 2020 at 15:55, Teofil Voivozeanu <notifications@github.com> wrote:
>
> Hi Gavin,
>
> Can you please attach the config in the form that produced the panic?
>
> Thanks,
> TeoV
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

**Comment by TeoV** [comment]
Hi Gavin,

Yes, please.

Thanks,
TeoV

**Comment by ghenry** [comment]
This is our Ansible jenga template:

```
{
  "general": {
    "node_id": "{{ inventory_hostname }}",
    "default_tenant": "surevoip"
  },
  "freeswitch_agent": {
    "enabled": true,
    "event_socket_conns": [
      {"address": "127.0.0.1:8021", "password": "{{ freeswitch.es_password }}", "reconnects": -1, "alias": "{{ inventory_hostname }}"}
    ],
    "sessions_conns": ["*internal"],
    "create_cdr": true
  },
  "rpc_conns": {
    "rals_suretec": {
      "strategy": "*first",
      "conns": [
        //{"address": "{{ rals.location }}:{{ rals.rpc_json_tls_port }}", "tls": true, "transport": "*json"}
        {"address": "{{ rals.location }}:{{ rals.rpc_json_port }}", "transport": "*json"}
      ]
    }
  },
  "sessions": {
    "enabled": true,
    "chargers_conns": ["rals_suretec"],
    "rals_conns": ["rals_suretec"],
    "cdrs_conns": ["rals_suretec"],
    "attributes_conns": ["rals_suretec"],
    "thresholds_conns": ["rals_suretec"],
    "resources_conns": ["rals_suretec"],
    "suppliers_conns": ["rals_suretec"],
    "stats_conns": ["rals_suretec"],
    "debit_interval": "5s", // interval to perform debits on.
    "channel_sync_interval": "7s",
    "min_call_duration": "60s", // only authorize calls with allowed duration higher than this
    "max_call_duration": "8h"  // maximum call duration a prepaid call can last
  }
}
```

I note on start up of cgr-engine I'm seeing:

```
Apr  8 17:43:17 xxx CGRateS <xxx> [9338]: <CoreS> starting version <CGRateS@v0.10.0><go1.13>
Apr  8 17:43:17 xxx CGRateS <xxx> [9338]: Could not configure dataDb: dial tcp 127.0.0.1:6379: connect: connection refused. Some SessionS APIs will not work

```
