### ISSUE TITLE
balance_set bug on v0.10.0 console - MANDATORY_IE_MISSING: [BalanceID or BalanceUUID]

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#2090]
```
cgr> balance_set Tenant="surevoip" BalanceID="B_MONETARY_PREPAID" Account="XXXX" BalanceType="*monetary" Weight=10 Value=50
Error executing command: MANDATORY_IE_MISSING: [BalanceID or BalanceUUID]

cgr> status
{
 "ActiveGoroutines": 49,
 "GoVersion": "go1.13",
 "MemoryUsage": "200.0MiB",
 "NodeID": "xxx",
 "RunningSince": "Tue Apr 14 08:58:56 UTC 2020",
 "Version": "CGRateS@v0.10.1~dev-20200305141418-1bef8e48de92"
}

~$ cgr-console -version
CGRateS@v0.10.0

```

Tab complete doesn't actually prompt for BalanceID either like it used to?

**Comment by ghenry** [comment]
balance_add works. Maybe because there is no existing balance? I have used balance_add, but still same issue with balance_set running after this.

**Comment by danbogos** [comment]
@ghenry 

This is not a bug but misuse of the command.

DanB

**Comment by ghenry** [comment]
As per: https://groups.google.com/g/cgrates/c/eTX5nopK6tM/m/oHjS6329BwAJ

The cgr-console docs need updating to show this new method.
