### ISSUE TITLE
TP_Rates column alteration request

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#216]
Hey DanB,

In the tariff plan tables the schema for tp_rates is set to NUMERIC(7,4) for the connect_fee and the rate columns which for Postgres means 3 digits and 4 decimal places which is fine 90% of the time but this is causing issues with countries like Vietnam where a rate can be 1000.00000 VND which is the equivalent of 4.4 cents USD! So 1.00 USD =  22,533.19 VND.

Also the other reason I am suggesting to use 5 decimal places is because this is more or less the standard in Wholesale business models.  Most Carriers use 5 decimal places.

So here is my suggestion for Postgres

alter table tp_rates alter column connect_fee TYPE NUMERIC(12,5)
alter table tp_rates alter column rate TYPE NUMERIC(12,5)
alter table tp_destination_rates max_cost NUMERIC(12,5)

This would allow 7 digits + 5 decimal places in Postgres i.e 1234567.12345
Regards,
Errol

**Comment by danbogos** [comment]
hey @ewsamuels,

Do u mind modifying the columns in the way you need them and do a pull request? Please do it for both postgres/mysql and we will review it.

You can find the files here:
https://github.com/cgrates/cgrates/tree/master/data/storage/postgres
https://github.com/cgrates/cgrates/tree/master/data/storage/mysql


Ta,
DanB

PS: Don't forget to sign the contributors agreement please.
