### ISSUE TITLE
Feature Request: Asterisk agent support for empty_balance_context and empty_balance_ann_file

### ISSUE THREAD

**Issue by mehrdadep** [cgrates/cgrates#2170]
Hi all,

There are some options in FreeSwitch agent to play a playback or go to another context when low or empty balance detected. It would nice for Asterisk agent to have this feature.

```
// "freeswitch_agent": {
// 	"enabled": false,						// starts the FreeSWITCH agent: <true|false>
// 	"sessions_conns": ["*internal"],
// 	"subscribe_park": true,					// subscribe via fsock to receive park events
// 	"create_cdr": false,					// creates CDR out of events and sends them to CDRS component
// 	"extra_fields": [],						// extra fields to store in auth/CDRs when creating them
// 	//"min_dur_low_balance": "5s",			// threshold which will trigger low balance warnings for prepaid calls (needs to be lower than debit_interval)
// 	//"low_balance_ann_file": "",			// file to be played when low balance is reached for prepaid calls
// 	"empty_balance_context": "",			// if defined, prepaid calls will be transferred to this context on empty balance
// 	"empty_balance_ann_file": "",			// file to be played before disconnecting prepaid calls on empty balance (applies only if no context defined)
// 	"max_wait_connection": "2s",			// maximum duration to wait for a connection to be retrieved from the pool
// 	"event_socket_conns":[					// instantiate connections to multiple FreeSWITCH servers
// 		{"address": "127.0.0.1:8021", "password": "ClueCon", "reconnects": 5,"alias":""}
// 	],
// },
```

```
// "asterisk_agent": {
// 	"enabled": false,						// starts the Asterisk agent: <true|false>
// 	"sessions_conns": ["*internal"],
// 	"create_cdr": false,					// create CDR out of events and sends it to CDRS component
// 	"asterisk_conns":[						// instantiate connections to multiple Asterisk servers
// 		{"address": "127.0.0.1:8088", "user": "cgrates", "password": "CGRateS.org", "connect_attempts": 3,"reconnects": 5}
// 	],
// },
```

**Comment by Trial97** [comment]
Hi @mehrdadep,

We do this in Freeswitch by using the playback application and redirect using the redirect application.
How can we achieve all of that using Asterisk?

Thanks,
Trial97

**Comment by mehrdadep** [comment]
Hi @Trial97 ,

I don't think playing a playback before soft hang up in Asterisk is an option but maybe we could have the option to choose between hanging up or going to a custom context in dial plan, is that possible?

Many thanks,
MehrdadEP

**Comment by Trial97** [comment]
Hi @mehrdadep,

Yes is possible, but what commands need to be send to Asterisk in order to change the context?

Thanks,
Trial97

**Comment by mehrdadep** [comment]
@Trial97 maybe we could use `continue` method from `ARI`:
[continueInDialplan](https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Channels+REST+API#Asterisk16ChannelsRESTAPI-continueInDialplan): POST /channels/{channelId}/continue
Exit application; continue execution in the dialplan.

**Comment by mehrdadep** [comment]
Hi all,
any updates on this?
Thanks

**Comment by danbogos** [comment]
Nope.

Mehrdad Esmaeilpour <notifications@github.com> schrieb am Sa., 11. Juli
2020, 08:52:

**Comment by Trial97** [comment]
Hi @mehrdadep,

We investigated a few leads about this but we got to a dead-end every time.
At the time we need to play the file we are outside `Stasis` and inside the `Dial` application.
Unfortunately, we can not find a mechanism similar to the FreeSWITCH(`sched_transfer`) that will allow us to play the file or switch the context after we exited the  `Stasis` application.
Did we miss anything?

Thanks,
Trial97

**Comment by mehrdadep** [comment]
Hi @Trial97 
We've also tried multiple solutions that leads to nowhere. Finally we've decided to handle these kind of scenario's in another layer without Asterisk. Thank you for putting your time and effort into this. I'm closing this request.
Many thanks,
MEP
