### ISSUE TITLE
The GPG keys listed for the "CGRateS" repository are already installed but they are not correct for this package

### ISSUE THREAD

**Issue by voztovoice** [cgrates/cgrates#2182]
Hello,
this happens on CentOS 7.8 desde repository.
CGrates version:

0.11.0~dev-20200519191301+1f86b2852

Regards

**Comment by TeoV** [comment]
Hi @voztovoice,

Probably you have an older key for the package.
Please try to update it manually ( http://yum.cgrates.org/yum.cgrates.org.gpg.key ) and retest ( https://unix.stackexchange.com/questions/136170/the-gpg-keys-listed-for-the-atomicrocketturtle-com-repository-are-already-ins ) 

Thanks,
TeoV

**Comment by voztovoice** [comment]
Same result on all servers where I try:
[cgrates]
name=CGRateS
baseurl=http://yum.cgrates.org/yum/nightly/
enabled=1
gpgcheck=1
gpgkey=http://yum.cgrates.org/yum.cgrates.org.gpg.key

Downloading packages:
warning: /var/cache/yum/x86_64/7/cgrates/packages/cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 72789b6f: NOKEY======-   ] 8.8 MB/s |  54 MB  00:00:00 ETA
Public key for cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm is not installed
cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm                                                                                                                               |  56 MB  00:00:04
Retrieving key from http://yum.cgrates.org/yum.cgrates.org.gpg.key
Importing GPG key 0xD18FDC16:
 Userid     : "CGRateS <cgrates@itsyscom.com>"
 Fingerprint: 2d64 7c9b 5815 8b53 07f2 6bbf 3d0e d2b3 d18f dc16
 From       : http://yum.cgrates.org/yum.cgrates.org.gpg.key
Is this ok [y/N]: y


Public key for cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm is not installed


 Failing package is: cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64
 GPG Keys are configured as: http://yum.cgrates.org/yum.cgrates.org.gpg.key

**Comment by TeoV** [comment]
Hi @voztovoice,

Please try to clean the cache first (sudo yum clear all ) and after retest.

Thanks,
TeoV

**Comment by voztovoice** [comment]
Same Result:
yum clean all
Loaded plugins: fastestmirror
Cleaning repos: base centos-gluster5 centos-gluster6 cgrates epel extras irontec updates
Cleaning up list of fastest mirrors
Other repos take up 42 M of disk space (use --verbose for details)

then
yum install cgrates
Downloading packages:
warning: /var/cache/yum/x86_64/7/cgrates/packages/cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 72789b6f: NOKEY======-   ] 9.0 MB/s |  54 MB  00:00:00 ETA
Public key for cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm is not installed
cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64.rpm                                                                                                                               |  56 MB  00:00:04
Retrieving key from http://yum.cgrates.org/yum.cgrates.org.gpg.key


The GPG keys listed for the "CGRateS" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: cgrates-0.11.0~dev-20200525101206+27c1e7288.x86_64
 GPG Keys are configured as: http://yum.cgrates.org/yum.cgrates.org.gpg.key

**Comment by TeoV** [comment]
Hi @voztovoice,

I just tested now on a centos 8.1 and it worked.
I think you still have cached the old key because the message said explicitly " 
The GPG keys listed for the "CGRateS" repository are already installed but they are not correct for this package. "
Unfortunately, we cannot be responsible for keys management.
In the past, we have changed the key and most probably you have the old one.

Thanks,
TeoV

**Comment by voztovoice** [comment]
Hi
Is the first time I install CGRates on this server and made the same test on another server with the same result so I don't know which is the problem.
Regards

**Comment by TeoV** [comment]
Hi @voztovoice,

Can you please tell us on what OS are you trying to install it and how?
Also, can you add the exact steps?

Thanks,
TeoV

**Comment by voztovoice** [comment]
Hello,
in a server where never installed cgrates (CentOS 7.8):

sudo tee -a /etc/yum.repos.d/cgrates.repo > /dev/null <<EOT
[cgrates]
name=CGRateS
baseurl=http://yum.cgrates.org/yum/nightly/
enabled=1
gpgcheck=1
gpgkey=http://yum.cgrates.org/yum.cgrates.org.gpg.key
EOT

yum update

yum install cgrates

Resolving Dependencies
--> Running transaction check
---> Package cgrates.x86_64 0:0.11.0~dev-20200526101524+27c1e7288 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================
 Package                                   Arch                                     Version                                                                 Repository                                 Size
============================================================================================================================================================================================================
Installing:
 cgrates                                   x86_64                                   0.11.0~dev-20200526101524+27c1e7288                                     cgrates                                    48 M

Transaction Summary
============================================================================================================================================================================================================
Install  1 Package

Total download size: 48 M
Installed size: 177 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/cgrates/packages/cgrates-0.11.0~dev-20200526101524+27c1e7288.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 72789b6f: NOKEY==========] 7.9 MB/s |  48 MB  00:00:00 ETA
Public key for cgrates-0.11.0~dev-20200526101524+27c1e7288.x86_64.rpm is not installed
cgrates-0.11.0~dev-20200526101524+27c1e7288.x86_64.rpm                                                                                                                               |  48 MB  00:00:03
Retrieving key from http://yum.cgrates.org/yum.cgrates.org.gpg.key
Importing GPG key 0xD18FDC16:
 Userid     : "CGRateS <cgrates@itsyscom.com>"
 Fingerprint: 2d64 7c9b 5815 8b53 07f2 6bbf 3d0e d2b3 d18f dc16
 From       : http://yum.cgrates.org/yum.cgrates.org.gpg.key
Is this ok [y/N]: y


Public key for cgrates-0.11.0~dev-20200526101524+27c1e7288.x86_64.rpm is not installed


 Failing package is: cgrates-0.11.0~dev-20200526101524+27c1e7288.x86_64
 GPG Keys are configured as: http://yum.cgrates.org/yum.cgrates.org.gpg.key

Thank you
Regards

**Comment by TeoV** [comment]
Hi @voztovoice,

Can you do me a favour and try on a fresh CentOS 8.1.
I just tested today and in my case, it worked without errors.

Thanks,
TeoV

**Comment by voztovoice** [comment]
Hello,
On  CentOS 8.1 no problem. Works like a charm
Regards

**Comment by TeoV** [comment]
Hi @voztovoice,

I tested on CentOS7.8 and indeed is not working.
I'm not an expert on RedHat but after some checking, I found that that a lot of people have this problem with different repositories and the conclusion was some different version of gpg doesn't communicate well.
There are two solutions:
1) Install the current package from our pkg server 
( sudo rpm -i http://pkg.cgrates.org/rpm/nightly/cgrates_current.rpm ) 
2) If you install CGRateS with yum add --nogpgcheck
( sudo yum --nogpgcheck install cgrates ) 

Thanks,
TeoV

**Comment by voztovoice** [comment]
Thank you
