### ISSUE TITLE
ERs should take content from .csv files by column name

### ISSUE THREAD

**Issue by nunovieira** [cgrates/cgrates#2194]
ERs takes content from CSV files by column index, but it would be more straightforward to take content by column name. 
If we have a CSV like:
```
id,name,time,something
1,some user,10:50,hello
```
would be nice to configure ers fields like `"value": "~*req.time"`, instead of `"value": "~*req.2"`.
Of course, the first line (headers) would be ignored.

**Comment by nunovieira** [comment]
Will this only be available in a future v0.11?

**Comment by Trial97** [comment]
Hi @nunovieira,

Unfortunately, we are not allowed to add new features on v0.10.

Thanks,
Trial97
