### ISSUE TITLE
Redis library update and support for redis cluster 

### ISSUE THREAD

**Issue by tumpanaios** [cgrates/cgrates#2207]
Opened an issue to track the update of the redis library used to https://github.com/mediocregopher/radix .

**Comment by gedia** [comment]
To elaborate a little, this regards support for native redis cluster functionality. AFAIK, this mostly entails discovering other redis nodes (if not configured explicitly in the config file), and honouring MOVED responses.

It seems that there is support for this in both the deprecated radix.v2 and the newer radix.
