### ISSUE TITLE
Cassandra database support as StorDb

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#221]
As first stage we should support Cassandra as complete StorDb implementation.

**Comment by andamasov** [comment]
Hello, once it´s stabilized it will be nice to test with scyllaDB - https://github.com/scylladb/scylla

**Comment by rif** [comment]
I tested today scylla and it did not work using https://github.com/gocql/gocql.

For the moment I don't know any way to connect to scylladb from go (I am sure the support will be there as scylla matures).

**Comment by rif** [comment]
As we are looking for a database to be able to store tariffplan data as well as cdrs it seems that cassandra is not the best option for our use case.

So far the searching of the cdrs using all fields as filter would require many extra pseudo index cf to be maintained and potential expensive array intersection to be processed real time.

The best option so far seems to be mongo so I will close this ticket and open one for mongo instead.
