### ISSUE TITLE
SetTPLcrRule Question!

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#223]
Hi DanB,
I am not reporting any bug its just a question to clarify something! We are setting LcrRules using the API call below.

```{"params": [{"Category": "priority", "Direction": "*out", "TPid": "priority", "Rules": [{"RPCategory": "priority", "Weight": 10.0, "Strategy": "*static", "DestinationId": "*any", "ActivationTime": "2015-09-30T17:40:04Z", "StrategyParams": "voxbeam_premium;voxbeam_direct"}], "Account": "*any", "Tenant": "cgrates.org", "Subject": "*any"}], "method": "ApierV1.SetTPLcrRule"}```

Notice this is the order we are setting --> "voxbeam_premium;voxbeam_direct" then to test we use this to check the LCR.

```{"params": [{"Category": "priority", "Direction": "*out", "IgnoreErrors": true, "StartTime": "2015-09-30T18:41:00Z", "Duration": "60", "Destination": "19173001321", "Account": "6889101058", "Tenant": "cgrates.org", "Subject": "6889101058"}], "method": "ApierV1.GetLcr"}```

and these are the results we get back

{"id":null,"result":{"DestinationId":"*any","RPCategory":"priority","Strategy":"*static","Suppliers":[{"Supplier":"voxbeam_direct","Cost":0.0083,"QOS":null},{"Supplier":"voxbeam_premium","Cost":0.0081,"QOS":null}]},"error":null}

Isn't the result supposed to be returned in the same order in which it was set with SetTPLcrRule meaning 1) voxbeam_premium 2) voxbeam_direct ?

Regards,

Errol

**Comment by cgrates** [comment]
Hey Errol

As diacussed in the past also, please use mailing list for questions and
keep the github issue numbers for real issues.

Ta,
DanB.
Am 30.09.2015 20:03 schrieb "Errol Samuels" <notifications@github.com>:
