### ISSUE TITLE
TTL for replicated sessions

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#2248]
Hello Dear CGRateS Team!
When the session TTL is taking place and closing a stale session, it doesn't close it's replica.
I am using CGRateS@v0.9.1~rc8-20200121173609-1b1f00da01e4
Not yet tested with newer version, perhaps that was fixed already

Counting sessions on the master node:
{
  "method":"SessionSv1.GetActiveSessionsCount",
  "params":[
  {
    "Tenant": "golant",
    "Filters": [
      "*string:Category:data"
    ]
    }
],
"id":0
}
{
    "id": 0,
    "result": 4019,
    "error": null
}

Counting sessions on the backup node:
{
  "method":"SessionSv1.GetPassiveSessionsCount",
  "params":[
  {
    "Tenant": "golant",
    "Filters": [
      "*string:Category:data"
    ]
    }
],
"id":0
}
{
    "id": 0,
    "result": 633821,
    "error": null
}

Thanks,
BR,

**Comment by TeoV** [comment]
Hi @muxalko,

This is fixed in v0.10. We will close this issue and if any problem appears fell free to open it again.

Thanks,
TeoV
