### ISSUE TITLE
Feature Request: Ability to use different configurable policies for topup_reset action plans.

### ISSUE THREAD

**Issue by u35tpus** [cgrates/cgrates#2255]
Currently CGRateS rolls over action plans according to the following Golang sample:
https://play.golang.org/p/zIFMw25pbl_E

That is, in edge case like 31 Mar, the next billing date will be 1 May.

It would be nice to have it configurable, e.g. in our project, our algorithm to execute next topup_reset  is as below:

Lets say billing day is D1 (D1=1..31), current billing month is M1 (M1=1..12)

```

Lets say your billing day is D1 (D1=1..31), current billing month is M1 (M1=1..12) - D1:M1
1) Try to add 1 month to the billing day D1. Have new billing date candidate D2:M2 where D2=D1 initially.
2) If D2 exists in M2, then D2:M2 is your billing date for this period.
3) If D2 does not exist in M2, then decrement D2 until D2:M2 is a real date.


```

So, for  31 Mar the following will be sequence of dates:
31 Mar, 30 Apr, 31 May,  30 June, 31 July, 31 Aug, 30 Sept, 31  Oct, 30 Nov, 31 Dec

**Comment by u35tpus** [comment]
I see this ticket is closed. Was it implemented?

**Comment by cgrates** [comment]
@u35tpus,


Yes, there is a new timingid which you can use: *monthly_estimated


DanB

PS: we close the tickets with commits, you should have been informed 
when we did it.

**Comment by coredigger** [comment]
@cgrates 

Hi! To update action plan we are using API: APIerSv1.SetActionPlan: 
https://godoc.org/github.com/cgrates/cgrates/apier/v1#APIerSv1.SetActionPlan

But there is no timingid property there. Is it possible to have such functionality in APIerSv1.SetActionPlan?
