### ISSUE TITLE
HTTP request with Invalid JSON in body hangs the request 

### ISSUE THREAD

**Issue by Yitzchok** [cgrates/cgrates#2280]
Making an HTTP request with invalid JSON (the actual JSON content is invalid like missing a closing tag, comma, and the like) in the payload will cause the request to hang.

This should return right away with 400 Bad Request or something like that.

**Comment by danbogos** [comment]
Hi @Yitzchok 

Unfortunately there is not much we can do here since this is the standard way Go handles JSON-RPC. I guess the right approach here is to make sure you don't send invalid JSON from your client.
With using standard libraries for JSON-RPC it is almost impossible to break it.

DanB
