### ISSUE TITLE
Action execution for non-existing account

### ISSUE THREAD

**Issue by ezgektor** [cgrates/cgrates#233]
Hello. I tried to use API method "ApierV1.ExecuteAction" for an account, which doesn't exist and received repsponse "OK" after such try. As for me, it looks like a bug.
So, can you, please, explain if it is normal behavior or it is a bug? 

Here is a log(first i checked if account exists and after that executed action for it):

interface: eth0 (172.16.43.0/255.255.255.0)
filter: (ip or ip6) and ( port 2012 )
###
T 2015/10/07 18:53:14.971100 10.46.13.118:53973 -> 172.16.43.101:2012 [A]
......
#
T 2015/10/07 18:53:14.971357 10.46.13.118:53973 -> 172.16.43.101:2012 [AP]
{"params": [{"Direction": "\*out", "Account": "42", "Tenant": "tenant.tenant"}], "id": 1, "method": "ApierV1.GetAccount"}
##
T 2015/10/07 18:53:14.972283 172.16.43.101:2012 -> 10.46.13.118:53973 [AP]
{"id":1,"result":null,"error":"Redis Error: Key \`ubl_\*out:tenant.tenant:42\` does not exist"}

#
T 2015/10/07 18:53:14.978544 10.46.13.118:53973 -> 172.16.43.101:2012 [AF]
......
##
T 2015/10/07 18:53:14.979655 10.46.13.118:53973 -> 172.16.43.101:2012 [A]
......
###
T 2015/10/07 18:53:27.739278 10.46.13.118:53974 -> 172.16.43.101:2012 [A]
......
#
T 2015/10/07 18:53:27.739489 10.46.13.118:53974 -> 172.16.43.101:2012 [AP]
{"params": [{"Direction": "\*out", "ActionsId": "1_EUR", "Account": "42", "Tenant": "tenant.tenant"}], "id": 1, "method": "ApierV1.ExecuteAction"}
##
T 2015/10/07 18:53:27.740677 172.16.43.101:2012 -> 10.46.13.118:53974 [AP]
{"id":1,"result":"OK","error":null}

#
T 2015/10/07 18:53:27.745968 10.46.13.118:53974 -> 172.16.43.101:2012 [AF]
......
##
T 2015/10/07 18:53:27.747109 10.46.13.118:53974 -> 172.16.43.101:2012 [A]
......

**Comment by danbogos** [comment]
Hi @ezgektor 

It depends on what your action is doing. In case of the account does not exist for a top-up, we automatically create it behind the scene. Was your account not created after executing the actions on it?

DanB

**Comment by ezgektor** [comment]
Hello. It wasn't created.

**Comment by rif** [comment]
@ezgektor you are right, now we should return NOT_FOUND error

**Comment by rif** [comment]
Actually I'm going to close this, feel free to reopen if you see any issues on this.
