### ISSUE TITLE
CGRateS continues crash - Fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by playingbogart** [cgrates/cgrates#2372]
CGrateS v0.10 and up to latest cgrates_0.10.2~dev+20200831101928+3289a59a4 with kamailio agent crashes in production environment repeatedly under load (>100 simultaneous calls).
When I disabled *resources everything seems working without crash - tested for 3 days.
See full log in attachment.

Please let me know if additional info needed.
[cgrates-crash_20200901_154645.log](https://github.com/cgrates/cgrates/files/5181105/cgrates-crash_20200901_154645.log)

Thanks.

**Comment by mortchm** [comment]
Hi,

it's interesting, i just saw the same things in production on my cgrates that handle data sessions, look

```
# grep "fatal error"  cgrates-diameter-smg-stderr.log
fatal error: concurrent map iteration and map write
fatal error: concurrent map writes
fatal error: concurrent map read and map write
fatal error: concurrent map writes
fatal error: concurrent map writes

```
from what i see, it's happening every 5 days i don't know why, i have attached the log of the latest crash 3 days ago
[cgrates-crash_20200904.log](https://github.com/cgrates/cgrates/files/5183320/cgrates-crash_20200904.log)

but it's not happening on my cgrates instance for RaL, diameter and voice only for the data sessions if it can helps

`~# cgr-engine -version
CGRateS@v0.10.1
`

**Comment by Trial97** [comment]
Hi @playingbogart, @mortchm,

This panics should be solved in the latest v0.10 please update and retest.

Thanks,
Trial97

**Comment by mortchm** [comment]
Hi, i have updated a week ago to CGRateS@v0.10.2~dev-20200928083433-225492cfe519 and so far no crash :)

Thanks

**Comment by danbogos** [comment]
@mortchm 

Thanks for reporting!

DanB

**Comment by sangameshwp** [comment]
root@localhost cgrates]# cgr-engine -version
CGRateS@v0.11.0~dev-20220309095920-f0adf870a3e9

This version still has this issue.

fatal error: concurrent map iteration and map write
