### ISSUE TITLE
Populating tables for RALs module

### ISSUE THREAD

**Issue by Shkiperon** [cgrates/cgrates#2379]
Hello.
In https://cgrates.readthedocs.io/en/latest/rals.html#rating you have some logic description of the fields in tables, but I can't understand how to use it for populating tables with my data. My StorDB is PostgreSQL
Example - Destination
I think it is about the `tp_destinations` table (maybe I'm wrong but I have no other ideas for this). In docs you have description for ID field (i think you mean `tpid` field because it could be multiple IDs with same name) and Destination field (i think it is about `prefix` field).
When I try to insert one row with this two parameters - SQL client give me an error, because another field `tag` must be populated too, but I have no idea what this field about and how populating of this can affects the CGRates system and RALs module.

Do you have some kind of tutorial or another docs about populating of tables for RALs module?

**Comment by danbogos** [comment]
Hi @Shkiperon 

Please direct your questions regarding CGRateS to our discussion group here:

https://groups.google.com/u/2/g/cgrates

We use github only for issues reporting and feature requests.

Thanks!

DanB
