### ISSUE TITLE
API for changing the Weight of a Balance

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#240]
Hello DanB,
I would like to request an API for changing the weight of a balance.  There are many scenarios that I can think of where this would be useful for example:

1) In cases where Balances were created using Weight of 0 due to lack of understanding
2) Where we may need to change the priority of a balance due to a change in business logic etc
3) Adds lots more flexibilty to the ability to manage balances.

Thank you

esamuels

**Comment by danbogos** [comment]
Part of the new SetBalance API

**Comment by danbogos** [comment]
This issue should be fixed now with new SetBalance API.

DanB
