### ISSUE TITLE
[Feature] Redis library TLS transport

### ISSUE THREAD

**Issue by volga629-1** [cgrates/cgrates#2435]
Hello Everyone,
Since redis version 6.0 supports native TLS transport.  
Can you please enable TLS support for redis connection.

**Comment by volga629-1** [comment]
Thank you for prompt fixes, I will test soon.

**Comment by volga629-1** [comment]
I am trying build against master branch and it failing on some dependencies.

```
go: github.com/elastic/go-elasticsearch@v0.0.0: reading github.com/elastic/go-elasticsearch/go.mod at revision v0.0.0: unknown revision v0.0.0
go: github.com/elastic/go-elasticsearch@v0.0.0: reading github.com/elastic/go-elasticsearch/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by volga629-1** [comment]
@TeoV   is possible back port patch to v0.10.2 ?

**Comment by TeoV** [comment]
Hi @volga629-1 

For me, this looks like a version go problem ( go version installed )
We tested with the go version 1.15.2 and worked as expected. Please make sure you have at least go 1.15 and clean the cache.
Branch v0.10 is only for bug fixing and since this is a feature request we cannot add it there.

Thanks,
TeoV

**Comment by volga629-1** [comment]
Thank you for reply @TeoV  I tried test  redis TLS with go version 15.3
and getting io timeout. Is possible get better visibility why ?
I am trying connect to azure redis 

azure connection string 

```
cache-nd1.redis.cache.windows.net:6380,password=,ssl=True,abortConnect=False
```
```
[root@voice-accnt ~]# cgr-migrator -verbose -config_path=/etc/cgrates -exec=*set_versions
2020/10/18 03:06:28 read tcp 10.30.0.9:57458->10.30.0.5:6380: i/o timeout
```

**Comment by volga629-1** [comment]
Hello @TeoV  
I tested with go version 15.3 and  tls connections works as expected right now.
I was be able run migration command to populate initial data.
Tank you for all work and  great project.

Command with allow populate with all SSL options for stor and cache
```
cgr-migrator -verbose -config_path=/etc/cgrates -exec="*set_versions"

```
