### ISSUE TITLE
Issues with balaces, units are added not deducted

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#2450]
HI

we have notice strange issue with balances (all). After a while it happens that cgrates is not deducting any more (still something in balance) but it starts to add units to balance.

It is very strange, basically I do not know when it happens and why. Version is latest.

I it hard to debug when it happens as it is just random. Also I noticed that memory is always at 95% ("top") for cgrates, if i restart it it drops to normal but then is starts to rise again (like cgrates is not releasing it). We did not have this issues with previous versions.

1. OK

{"CGRID":"b865482311317abf817922e5cf89587859133add","RunID":"*default","StartTime":"2020-10-14T14:08:16+02:00","Usage":33008,"Cost":0,"Charges":[{"RatingID":"374f480","Increments":[{"Usage":1,"Cost":0,"AccountingID":"4e89038","CompressFactor":33008}],"CompressFactor":1}],"AccountSummary":{"Tenant":"xxx-mobil","ID":"xxxxxx","BalanceSummaries":[{"UUID":"80c8d970-a45a-4e26-9232-cc0280556fea","ID":"PREMIUM-DATA","Type":"*data","Value":45597.18046,"Disabled":false},{"UUID":"7de4c4bb-379e-4e40-aba2-461d6a9c7787","ID":"*default","Type":"*monetary","Value":-0.19,"Disabled":false}],"AllowNegative":false,"Disabled":false},"Rating":{"374f480":{"ConnectFee":0,"RoundingMethod":"","RoundingDecimals":0,"MaxCost":0,"MaxCostStrategy":"","TimingID":"","RatesID":"f36ee2f","RatingFiltersID":"0d60236"}},"Accounting":{"4e89038":{"AccountID":"softnet-mobil: xxxxxx  ","BalanceUUID":"80c8d970-a45a-4e26-9232-cc0280556fea","RatingID":"","Units":0.00098,"ExtraChargeID":"*none"}},"RatingFilters":{"0d60236":{"DestinationID":"DST_SLO","DestinationPrefix":"386","RatingPlanID":"*none","Subject":"80c8d970-a45a-4e26-9232-cc0280556fea"}},"Rates":{"f36ee2f":[{"GroupIntervalStart":0,"Value":0,"RateIncrement":1,"RateUnit":1}]},"Timings":{}}

2. next cost_details which is not ok.

{"CGRID":"cc0b302d3e241ecd454cd54b06085c36a80290e5","RunID":"*default","StartTime":"2020-10-16T06:38:58+02:00","Usage":1844,"Cost":0,"Charges":[{"RatingID":"d825276","Increments":[{"Usage":1,"Cost":0,"AccountingID":"2b6bdf5","CompressFactor":1844}],"CompressFactor":1}],"AccountSummary":{"Tenant":"xxx-mobil","ID":"xxxxxx  ","BalanceSummaries":[{"UUID":"80c8d970-a45a-4e26-9232-cc0280556fea","ID":"PREMIUM-DATA","Type":"*data","Value":58194.01456,"Disabled":false},{"UUID":"7de4c4bb-379e-4e40-aba2-461d6a9c7787","ID":"*default","Type":"*monetary","Value":-0.19,"Disabled":false}],"AllowNegative":false,"Disabled":false},"Rating":{"d825276":{"ConnectFee":0,"RoundingMethod":"","RoundingDecimals":0,"MaxCost":0,"MaxCostStrategy":"","TimingID":"","RatesID":"57e1b3d","RatingFiltersID":"a348ac3"}},"Accounting":{"2b6bdf5":{"AccountID":"softnet-mobil: xxxxxx  ","BalanceUUID":"80c8d970-a45a-4e26-9232-cc0280556fea","RatingID":"","Units":0.00098,"ExtraChargeID":"*none"}},"RatingFilters":{"a348ac3":{"DestinationID":"DST_SLO","DestinationPrefix":"386","RatingPlanID":"*none","Subject":"80c8d970-a45a-4e26-9232-cc0280556fea"}},"Rates":{"57e1b3d":[{"GroupIntervalStart":0,"Value":0,"RateIncrement":1,"RateUnit":1}]},"Timings":{}}

I should mention that this started to happens to all accounts not just this one. So accounts have wrong balances.

**Comment by Trial97** [comment]
Hi @miha-,

Please post the output of the following command: `cgr-engine -version`.
Because we already have tests related to this please describe step by step how to reproduce this:
- What is the source of the CDRs
- How do you top-up the balances for your account? Because the increments from CostDetails looks ok there may be some top-up actions executed on your account

Related to the memory we already had a similar [issue](https://github.com/cgrates/cgrates/issues/1629) and have concluded that we release the memory but the system needs to also mark it as free.

Thanks,
Trial97

**Comment by miha-** [comment]
Hello 

source is csv files, we are reading it via ers.

We do not do any top-up, we only renew balances every month, to get their balaces back.
We are doing this as shown bellow:

Timings.csv:RENEW,*any,*any,1,*any,00:00:00
ActionPlans.csv:TELEMETRIJA_1000SMS,TELEMETRIJA_1000SMS,RENEW,10
ActionPlans.csv:TELEMETRIJA_1000SMS,TELEMETRIJA_1000SMS,*asap,10
Actions.csv:TELEMETRIJA_1000SMS,*topup_reset,"{""*sms"":1.0, ""*mms"": 1.0}",,TELEMETRIJA_1000SMS,*generic,slo-sms-mms;EU-sms-mms,DST_SLO;!DST_SLO_NOT_ALLOWED,,,*unlimited,,1000,10,false,false,10
Actions.csv:TELEMETRIJA_1000SMS,*topup_reset,,,*default,*monetary,,,,,*unlimited,,0,10,false,false,10


br
Miha

**Comment by Trial97** [comment]
Hi @miha-,

In order to further debug this, we added the initial value of the balance in AccountSummary.
Please update to the latest master, retest, and post two consecutive CDRs of the same Account.

Thanks,
Trial97

**Comment by miha-** [comment]
OK, give me pls some time. Now is new month, balances are renewed and lets see if this hapaned again or this happened only when i have imported all cdrs.

I will send you everything together.

**Comment by Trial97** [comment]
Hi @miha-,

We will close this issue due to inactivity.
Please feel free to reopen this issue but because we could not reproduce it, please post two consecutive CDRs of the same Account generated using the latest master.

Thanks,
Trial97
