### ISSUE TITLE
[Feature Request] Stats: Reset stats metrics at mid-night

### ISSUE THREAD

**Issue by ryan-netizen** [cgrates/cgrates#2472]
It would be nice to a reset param inside stats component so, stats can be reset at given time?

Use case: I would like to know how much someone has spent on a single day and then my stats gets reset at mid-night. 

TTL field does not seem to fit alone for that use case. 

So, something like ttl=-1 with another param `reset` taking time?

Thanks for the amazing work. !

**Comment by ryan-netizen** [comment]
Wow this was really fast. Thank you guys.
When the new build be available for this feature, because i don't see at listed below

`http://pkg.cgrates.org/deb/nightly/`

**Comment by danbogos** [comment]
hey @ryan-netizen 

You should have a new package built.

Have a nice weekend!

Dan

**Comment by ryan-netizen** [comment]
@danbogos thank you very much. !
I will test and ask in group if help needed.

**Comment by ryan-netizen** [comment]
@danbogos @Trial97  so i check the master and it looks to me that `*reset_stat_queue` flushes the stats from memory. But if you have stored flag set to true and you flush stats queue and restart cgrates before the stored interval hits(So cgrates can store the flushed value to database). Cgrates will take values from storage(database) and continues from there. 

Would be better if we can flush stats from both, memory and storage, if later one was set. 

Also wanted to know what internal we have in place to store stats into database? Is it per minutes or every 30 seconds?

Thanks for effort you guys are putting into this, highly appreciated. 

Ryan
