### ISSUE TITLE
SessionS high-availability

### ISSUE THREAD

**Issue by michal-sejc** [cgrates/cgrates#2485]
Hello, we're having problems with session server high-availability. We have a main and a backup kamailio server with master and slave SessionS. Everything is interconnected. Normally the traffic goes only through the main kamailio and master SessionS.
Now here is the problem, if I shut down the slave kamailio through which no traffic is routed, active sessions on the master SessionS will be dropped (although the main kamailio is unaffected and the calls still go through). Restarting either SessionS doesn’t help. Only Starting up the backup kamailio and then restarting both SessionS does.

Why do the active sessions drop to zero? 

I have attached both cgrates’ configs. Which parts of the kamailio configs do you need? Could I send them to you privately ? They contain business logic that we wouldn’t want disclosed.

Michal

[cgrates.zip](https://github.com/cgrates/cgrates/files/5547382/cgrates.zip)

**Comment by Trial97** [comment]
Hi @michal-sejc,

The Kamailio master should be connected only to the SessionS master and the Kamailio slave only to the SessionS slave.
This will assure that when one Kamailio fails only the connected SessionS will be affected.
Please update your config using a single Kamailio connection per SessionS and retest.

Thanks,
Trial97
