### ISSUE TITLE
Stats: SERVER_ERROR: an inserted document is too large 

### ISSUE THREAD

**Issue by ryan-netizen** [cgrates/cgrates#2530]
Greetings Team, 

I see you if you run `APIerSv1.LoadTariffPlanFromStorDb` while you are using `stats` with stored param to `true`, you might encounter below error in case you have big stats data.  

```
T 127.0.0.1:54196 -> 127.0.0.1:2012 [AP] #5
{"method":"APIerSv1.LoadTariffPlanFromStorDb","params":[{"TPid":"1","DryRun":false,"Validate":true,"Opts":null,"Caching":null}],"id":10}


T 127.0.0.1:2012 -> 127.0.0.1:54196 [AP] #11
{"id":10,"result":null,"error":"SERVER_ERROR: an inserted document is too large"}
```

By looking over the internet i see it might be due to some document size increasing beyond 16MB which is the limit set by mongodb. 

Why i am sure this happens due to stats, because after flushing the stats with action `*reset_stat_queue` i was able to reload the tariff plan just fine. 

```
cgr> load_tp_from_stordb TPid="1" DryRun=false Validate=true Opts=null Caching=null
"OK"
```

Can we somehow exclude stats metrics(data) from getting reloaded or exclude them from tariffplan reload? 

I see if you have zero stats, reload command executes really quickly. So, excluding stats metric(data) from reload would be great. 

Or May be by using [gridfs](https://docs.mongodb.com/manual/core/gridfs/) we can over come this?

But you guys know better, just giving my 5 cents above. 

Thanks again for your hard work. 

```
cgr>
cgr> status
{
 "ActiveGoroutines": 55,
 "GoVersion": "go1.14",
 "MemoryUsage": "5.8MiB",
 "NodeID": "b6db2c5",
 "RunningSince": "Wed Dec  2 10:29:10 UTC 2020",
 "Version": "CGRateS@v0.11.0~dev-20201119133434-920b304a6f94"
}
```

Ryan

**Comment by Trial97** [comment]
Hi @ryan-netizen,

This is happenning because when we load the data we update the Stats Queues by removing the obsolete queues and adding the new ones.
We can't exclude the Stats Queue update from the data loading as it may result in Stats which does not match the profiles.
Because of this, we recommend using the `store_uncompressed_limit` [config](https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L595) to compress all the metrics that exceed that limit.

Thanks,
Trial97

**Comment by ryan-netizen** [comment]
@Trial97 thanks for taking time to check this. 

May i know what value can I set for that `config` param when i don't know how many stats are exceeding the limit?
Can i set this to `-1` and let the cgrates adjust things automatically for me?

Thanks again. 
Ryan

**Comment by Trial97** [comment]
Hi @ryan-netizen,

You can set the limit to `50`  but depending on how you defined your stats you can adjust this value.
Also, we can't determine if the queue should compress or not.

Thanks,
Trial97

**Comment by ryan-netizen** [comment]
@Trial97 well thank you. 

I will try that option and get back to you the very next day. 

Ryan

**Comment by ryan-netizen** [comment]
I am going to close this issue since this does not look like an issue but configuration problem. 
I will ask in group if help needed.
