### ISSUE TITLE
DebitUsage and ProcessExternalCdr methods lead to double charging

### ISSUE THREAD

**Issue by ezgektor** [cgrates/cgrates#256]
Hello.

We have integrated SMS Gateway with CGRateS and found some strange behavior.
We have constructed the next API calls flow (and it was implemented on SMS Gateway side):
1. ApierV2.GetMaxUsage - to check authorization for sending sms;
2. ApierV2.DebitUsage - to charge a customer;
3. CdrsV2.ProcessExternalCdr - to upload cdr.

But every time we send an SMS, customer charged twice.

**Comment by Trial97** [comment]
Hi @ezgektor ,

The right approach is to use APIs in SessionSv1 not directly ApierV2.DebitUsage.
Please reopen if needed.

Thanks,
Trial97
