### ISSUE TITLE
ers import crash

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#2571]
Hello

when trying to import cdrs from csv on latest version i get bellow error:
With the same config on preveios version this does not happen.

root@debian:~# ngrep -pq -W byline port 2012 -d any
interface: any
filter: ( port 2012 ) and (ip || ip6)

T 127.0.0.1:56390 -> 127.0.0.1:2012 [AP] #4
{"method":"SessionSv1.ProcessMessage","params":[{"GetAttributes":true,"AllocateResources":false,"Debit":false,"ForceDuration":false,"ProcessThresholds":false,"ProcessStats":false,"GetRoutes":false,"RoutesMaxCost":"","RoutesIgnoreErrors":false,"AttributeIDs":null,"ThresholdIDs":null,"StatIDs":null,"Opts":{},"Tenant":"test-mobil","ID":"0cb73d7","Time":"2020-12-24T08:12:46.425863646+01:00","Event":{"Account":"1231231321","AnswerTime":"22.12.2020 08:45:48","Category":"slo-voice","Destination":"1231231321","Direction":"*out","OriginID":"041619304_0301000102E5070310DFD0_MO","RequestType":"*postpaid","SetupTime":"22.12.2020 08:45:48","Subject":"1231231321","Tenant":"test-mobil","ToR":"*voice","Usage":"135s"},"Limit":null,"Offset":null}],"id":0}

T 127.0.0.1:56390 -> 127.0.0.1:2012 [AP] #6
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"Context":"*sessions","ProcessRuns":null,"Opts":{"*subsys":"*sessions"},"Tenant":"test-mobil","ID":"0cb73d7","Time":"2020-12-24T08:12:46.425863646+01:00","Event":{"Account":"1231231321","AnswerTime":"22.12.2020 08:45:48","Category":"slo-voice","Destination":"1231231321","Direction":"*out","OriginID":"041619304_0301000102E5070310DFD0_MO","RequestType":"*postpaid","SetupTime":"22.12.2020 08:45:48","Subject":"1231231321","Tenant":"test-mobil","ToR":"*voice","Usage":"135s"}}],"id":1}

T 127.0.0.1:2012 -> 127.0.0.1:56390 [AP] #8
{"id":1,"result":{"MatchedProfiles":["12312313212"],"AlteredFields":["*req.Category"],"Opts":{"*subsys":"*sessions"},"Tenant":"test-mobil","ID":"0cb73d7","Time":"2020-12-24T08:12:46.425863646+01:00","Event":{"Account":"1231231321","AnswerTime":"22.12.2020 08:45:48","Category":"slo-voice-neomejeno","Destination":"1231231321","Direction":"*out","OriginID":"041619304_0301000102E5070310DFD0_MO","RequestType":"*postpaid","SetupTime":"22.12.2020 08:45:48","Subject":"1231231321","Tenant":"test-mobil","ToR":"*voice","Usage":"135s"}},"error":null}

^Croot@debian:~# cat /var/log/cgrates/CGRateS.log
Dec 24 08:12:46 debian CGRateS <4a82b26> [17752]: <ERs> parsing </usr/local/cdrs/CCI_SLO_112/Obracun-5934-20201222085710>
Dec 24 08:12:46 debian CGRateS <4a82b26> [17752]: <ERs> parsing </usr/local/cdrs/CCI_SLO_VOICE_OUT/Obracun-5934-20201222085710>
Dec 24 08:12:46 debian CGRateS <4a82b26> [17752]: <ERs> LOG, reader: <Voice_slo>, message: {#012 "Tenant": "test-mobil",#012 "ID": "0cb73d7",#012 "Time": "2020-12-24T08:12:46.425863646+01:00",#012 "Event": {#012  "Account": "1231231321",#012  "AnswerTime": "22.12.2020 08:45:48",#012  "Category": "slo-voice",#012  "Destination": "1231231321",#012  "Direction": "*out",#012  "OriginID": "041619304_0301000102E5070310DFD0_MO",#012  "RequestType": "*postpaid",#012  "SetupTime": "22.12.2020 08:45:48",#012  "Subject": "1231231321",#012  "Tenant": "test-mobil",#012  "ToR": "*voice",#012  "Usage": "135s"#012 }#012}
Dec 24 08:12:46 debian CGRateS <4a82b26> [17752]: ERs finished processing file </usr/local/cdrs/CCI_SLO_112/Obracun-5934-20201222085710>. Total records processed: 127, events posted: 0, run duration: 6.134869ms
Dec 24 08:12:46 debian cgr-engine[17752]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 24 08:12:46 debian cgr-engine[17752]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x162d443]
Dec 24 08:12:46 debian cgr-engine[17752]: goroutine 143710 [running]:
Dec 24 08:12:46 debian cgr-engine[17752]: github.com/cgrates/cgrates/analyzers.(*AnalyzerServerCodec).WriteResponse(0xc0001052d0, 0xc000f964b0, 0x1be2800, 0xc000462b70, 0xc000462b70, 0x16)
Dec 24 08:12:46 debian cgr-engine[17752]: #011/root/go/src/github.com/cgrates/cgrates/analyzers/codec.go:76 +0x123
Dec 24 08:12:46 debian cgr-engine[17752]: net/rpc.(*Server).sendResponse(0xc00007a190, 0xc000613880, 0xc00059cda0, 0x1be2800, 0xc000462b70, 0x23f72c0, 0xc0001052d0, 0x0, 0x0)
Dec 24 08:12:46 debian cgr-engine[17752]: #011/usr/local/go/src/net/rpc/server.go:353 +0xe7
Dec 24 08:12:46 debian cgr-engine[17752]: net/rpc.(*service).call(0xc000505980, 0xc00007a190, 0xc000613880, 0xc000613890, 0xc000ab0a80, 0xc00059cda0, 0x1d948e0, 0xc0005ece00, 0x16, 0x1be2800, ...)
Dec 24 08:12:46 debian cgr-engine[17752]: #011/usr/local/go/src/net/rpc/server.go:384 +0x27d
Dec 24 08:12:46 debian cgr-engine[17752]: created by net/rpc.(*Server).ServeCodec
Dec 24 08:12:46 debian cgr-engine[17752]: #011/usr/local/go/src/net/rpc/server.go:474 +0x445
Dec 24 08:12:47 debian CGRateS <7e38bbb> [18447]: <CoreS> starting version <CGRateS@v0.11.0~dev-20201221154535-8fa22d732ef9><go1.15>
Dec 24 08:12:47 debian CGRateS <7e38bbb> [18447]: <CoreS> starting <CoreS> subsystem

cgr-console --version
CGRateS@v0.11.0~dev-20201221154535-8fa22d732ef9

**Comment by danbogos** [comment]
hi  @miha- 

Please attach here also your configuration.

Thanks!

**Comment by miha-** [comment]
Hello Dan

here is my json config. Sorry for waiting so long.


br
miha
[cgrates.txt](https://github.com/cgrates/cgrates/files/5765011/cgrates.txt)

**Comment by danbogos** [comment]
Hi @miha- 

I can see that you have "analysers" enabled in your configuration. May I know what is this used for?

Ta,
DanB

**Comment by miha-** [comment]
Hallo @danbogos 

i have set it to "false". We were not using them.

br
miha

**Comment by danbogos** [comment]
hi @miha- 

Does the panic still occur after disabling analyzers?

DanB

**Comment by miha-** [comment]
@danbogos i tried and it seems that it does not. I will do some tests today as I need also to change something, so i will have to import a lot of cdrs. I will get back to you to have right answer for you :)

**Comment by miha-** [comment]
@danbogos it seems that it is ok now.

**Comment by Trial97** [comment]
Hi @miha-,

We pushed a possible fix for this in the latest master.
Please re-enable the analyzers service and try to reproduce this again.

Thanks,
Trial97

**Comment by miha-** [comment]
ok, thank you

________________________________

**Comment by Trial97** [comment]
Hi @miha-,

Any feedback on this?

Thanks,
Trial97

**Comment by miha-** [comment]
Hello

it seems that after putting it on false there are no issues any more with crashes.

**Comment by Trial97** [comment]
Hi @miha-,

Please review this [comment](https://github.com/cgrates/cgrates/issues/2571#issuecomment-759289418) where we requested to enable the analyzers( putting it on true) and retest.
We requested to put this on true in order to determine if we fixed the panic mention in the first commit.
Please try to reproduce this panic with the latest master and the analyzers on true.

Thanks,
Trial97
