### ISSUE TITLE
SERVER_ERROR: pq: relation \"tp_account_profiles\" does not exist

### ISSUE THREAD

**Issue by max-konin** [cgrates/cgrates#2573]
Hi

When I try to upload a tariff plan via `ApierV1.LoadTariffPlanFromStorDb` (storedb is PG) I get `SERVER_ERROR: pq: relation \"tp_account_profiles\" does not exist`. But I unable to find this relation in https://github.com/cgrates/cgrates/blob/master/data/storage/postgres/create_tariffplan_tables.sql

**Comment by danbogos** [comment]
hi @max-konin 

Please make sure your cgr-engine version matches the schema version. In this case you have pointed us to a "master" SQL schema, hence your engine must be also be compiled from master.

DanB

**Comment by danbogos** [comment]
Sorry, I just realized that we did not add the necessary schema in the mysql/postgres. Please give me some time and I will add it.

Thanks,
DanB
