### ISSUE TITLE
Actions with *unlimited ExpiryTime convert to limited ones

### ISSUE THREAD

**Issue by ezgektor** [cgrates/cgrates#261]
Hello.

I've created two Actions:
1. Voice topup with expiry date of 2015-10-31T23:59:59Z;
2. Voice topup with unlimited expiry date.

Also i created new account without balances.

I executed first action for it and it works well and add new balance with the number of defined seconds in the action and defined expiry date.

After that i execute the second one and it just adds seconds (defined in it) to the balance with expiry date of 2015-10-31T23:59:59Z, but the action has unlimited expiry date. So it limits validity after actions is executed.

What is the right way to avoid such situations?

**Comment by rif** [comment]
Hi @ezgektor  we analyzed this issue and it's on our short TODO list. It is an issue about specifying balance filters so the second topup will know that it is a balance without expiration date you want to topup not that you don't care about the expiration date. 

It's an internal issue and we hope to solve it soon.

However a possible workaround is to assign different BalanceWeight to the two balances, in this way the second topup will no longer find a matching balance and will create a new one.
Different weights will also ensure the debit order which is something that it's usually desired (having the same weight will produce a random selection for each particular debit).

**Comment by rif** [comment]
Your initial case should work now. Just make sure you use *unlimited for the second action expiry date.
