### ISSUE TITLE
send warning before call drops

### ISSUE THREAD

**Issue by emdwaem** [cgrates/cgrates#27]
We need ability to send/play msg during call if user is running out of balance. it may be settings : 
warning_msg = "some_name_of_voice_msg"  - play msg at channel from freeswitch sounds 
warning_msg_time = 30s - if user have 30s to end of the call , play sound warning msg 
warning_script = "/usr/local/launch_script.pl UUID"  - optional script that will be launched when hit 30s to end of that call

**Comment by danbogos** [comment]
@emdwaem: can u confirm that this issue was fixed?

DanB

**Comment by danbogos** [comment]
No follow up, works for me.

DanB
