### ISSUE TITLE
SM Panic - close of a closed channel

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#271]
As reported by Iwada:
``
panic: close of closed channel

goroutine 30 [running]:
github.com/cgrates/cgrates/sessionmanager.(*Session).Close(0xc821cb97a0, 0x7ff3b8d7e128, 0xc8218e2150, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/session.go:117 +0x49
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).SyncSessions(0xc8201e4180, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:410 +0xcf1
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect.func2(0xc8201e4180)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:89 +0x39
created by github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:92 +0x82d
``

**Comment by iwada** [comment]
@danbogos Please any update on this?

**Comment by danbogos** [comment]
Hi @iwada,

Sorry not yet.

DanB

**Comment by iwada** [comment]
Thanks @danbogos , 
I assume these changes are in the the latest RC8 tmp package. Would do the upgrade,test and report back.
