### ISSUE TITLE
Copy packaging for another project

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#2864]
Hi all,

I'm looking to do a PR for hydra and wondered if you mind me copying your packaging files and modifying them?

https://github.com/ory/hydra/issues/2487

Thanks.

**Comment by danbogos** [comment]
hey @ghenry 

Sure, no issue about copying them, however please maintain copyright (many of these files were contributed to us also and we are obliged by contributors agreement to keep copyright - independent on the license you will use the files with).

Cheers,
Dan

**Comment by ghenry** [comment]
Thanks. I only see this which is yours - https://github.com/cgrates/cgrates/blob/master/packages/debian/copyright

**Comment by danbogos** [comment]
OK, keeping the copyright only on me should suffice since even if a conflict will raise I will be obliged to disclose the full copyright (which I do through publishing the full list of contributors here: https://github.com/cgrates/cgrates/blob/master/CONTRIBUTORS.md).

DanB
