### ISSUE TITLE
cgrates crashes

### ISSUE THREAD

**Issue by asteriskauto** [cgrates/cgrates#2865]
Hi. Sometimes cgrates crashes. Ican see this error in the logs. can someone help?

Apr 22 14:51:17 localhost CGRateS <CGRAsterisk> [2297]: <AsteriskAgent> failed disconnecting channel <1619103077.12731>, err: Delete "http://flypost.leadzvon.ru:8088/ari/channels/1619103077.12731": dial tcp: lookup flypost.leadzvon.ru: too many open files
Apr 22 14:51:17 localhost cgr-engine[2297]: 2021/04/22 14:51:17 http: Accept error: accept tcp 172.18.0.1:2080: accept4: too many open files; retrying in 1s
Apr 22 14:51:18 localhost cgr-engine[2297]: 2021/04/22 14:51:18 http: Accept error: accept tcp 172.18.0.1:2080: accept4: too many open files; retrying in 1s
Apr 22 14:51:19 localhost cgr-engine[2297]: 2021/04/22 14:51:19 http: Accept error: accept tcp 172.18.0.1:2080: accept4: too many open files; retrying in 1s

cgrates is on Ubuntu 18.04.5 LTS
2 cores
2 gb memory

using with asterisk agent

**Comment by porosnicuadrian** [comment]
Hi @asteriskauto 

Can you tell me what verison of cgrates are you using? And also, how many setups/second do you have in your asterisk configuration?

Thanks, 
@porosnicuadrian

**Comment by asteriskauto** [comment]
Hi @porosnicuadrian 

1. root@localhost:~# cgr-console --version
CGRateS@v0.11.0~dev-20201223123054-007240bd732f

2. it's 10-20 cps, asterisk in not really loaded, it's for tests now

**Comment by maks1m45** [comment]
Hi @porosnicuadrian is there progress on the task? we stopped working

**Comment by porosnicuadrian** [comment]
Hi @asteriskauto 

No progress for the moment. Will update here when there will be any.

Thanks 
@porosnicuadrian
