### ISSUE TITLE
<Cdrs> WARNING: Could not find CallCostLog 

### ISSUE THREAD

**Issue by iwada** [cgrates/cgrates#290]
I am getting "<Cdrs> WARNING: Could not find CallCostLog for cgrid: e7e61a663d97793debb76f6fa3b305ac8b74569f, source: SMR, runid: *default, will recalculate" ONLY for calls that are not answered(having duration <=0)

However,For Answered calls, I don't notice that warning, everything Works as expected. 

sm_freeswitch accesses CDRS directly. 

Snippets of relevant portions of  my cgrates.json
``` json
"rater": {
        "enabled": true,                                                 
},

"cdrs": {
        "enabled": true,                                                
        "rater": "internal",                                                                    
},

"sm_freeswitch": {
        "enabled": true,                                
        "rater": "internal",                   
        "cdrs": "internal",                            
       
        
},

Running latest build of RC8

**Comment by danbogos** [comment]
Hi @iwada,

Have pushed a fix for this. Please retest and carefully review costs for both connected and unanswered calls and confirm.

Ta,
DanB

**Comment by iwada** [comment]
@danbogos , I guess on this, i'll have to build from Source.
 Once i do that, would be reverting back. Thank You

**Comment by danbogos** [comment]
@iwada 

to speed up the process on your side, I have created packages here:
http://www.cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb

DanB

**Comment by iwada** [comment]
@danbogos , 
That saved me a lot. 
Tested. I don't see the warning again
 Answered and unanswered calls are billed as expected. 
All Good. Thank You!

**Comment by danbogos** [comment]
Great,

Have a good one!

DanB
