### ISSUE TITLE
ENUM DNS interface on LCR subsystem

### ISSUE THREAD

**Issue by ovi82** [cgrates/cgrates#291]
Hi,

I have a feature request regarding the LCR subsystem.
It would be nice if the information can be retrieved using ENUM / DNS.

**Comment by danbogos** [comment]
Hi @ovi82,

Can you describe a bit more your request here? Are you talking about 
querying ENUM for numbers and then have them rated for specific supplier or?

Thanks,
DanB

**Comment by ovi82** [comment]
Hi DanB,

I'm interested in the following scenario:

-Send a ENUM DNS request towards CGR for a specific number
-Receive a list of operators as result to route the number to, optionally with cost information.

**Comment by Trial97** [comment]
This is already on the latest master
