### ISSUE TITLE
Missing tenant for automatic cache reloads.

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#2928]
Dear Team,

I am using CGRateS v0.10 and following the discussion here --> https://groups.google.com/g/cgrates/c/-ZHMOOIafDM
with @Trial97 I am opening this issue to also populate Tenant for automatic cache reloads which will fix `NOT_FOUND` issue on the dispatcher engine. 

Thank you in advance for your support
Vasilios Tzanoudakis

**Comment by Trial97** [comment]
Hi @vtzan,

This should be fixed on the latest v0.10 branch.

Thanks,
Trial97
