### ISSUE TITLE
Inconsistence in account IDs

### ISSUE THREAD

**Issue by tomec-martin** [cgrates/cgrates#294]
When creating balance through Apierv1_AddBalance, the ID for created account is in form:
`:<tenant>:<account ID>` (e.g. ":cgrates.org:123456")
When creating through cgr-console - ballance_set, the ID for created account is with Direction:
`<direction>:<tenant>:<account ID>` (e.g. "*out:cgrates.org:123456")

Can I specify direction in Apierv1_AddBalance, or it is a bug?

**Comment by danbogos** [comment]
Hi @tomec-martin,

Please retest master, using package provided here: http://www.cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb.

We have considerably modified the account id part in master. During upgrade if you need to keep the old accounts, it is recommendable that you follow the procedure described here:
https://groups.google.com/forum/#!topic/cgrates/WicbtU45FGA

DanB
