### ISSUE TITLE
cache_age removed

### ISSUE THREAD

**Issue by tomec-martin** [cgrates/cgrates#295]
This commit removed API function GetCachedItemAge:
https://github.com/cgrates/cgrates/commit/06e4004c5175aafdec10a128a45609dd3e689849

But in cgr-console it is still used:
cgr> cache_age
Error executing command: rpc: can't find method ApierV1.GetCachedItemAge

Is there any replacement of cache_age, or the function shouldn´t be removed?

**Comment by danbogos** [comment]
Hi @tomec-martin 

We have also removed the console command in a later stage (in master), but missing just in your downloaded package which is now 3 days old.

DanB
