### ISSUE TITLE
loss  of "AccountActionTriggers"

### ISSUE THREAD

**Issue by simon-af** [cgrates/cgrates#297]
Hello
For my customers,if I subcribe a new ActionTriggersId and new ActionPlanId using web service SetAccount, curent AccountActionTriggers of these customers are lost.
Is it normal?
Thanks

Simon B

**Comment by danbogos** [comment]
@rif is this issue fixed?

**Comment by rif** [comment]
this is the issue about merging vs overwriting existing data on change

**Comment by cgrates** [comment]
Ok still there?
Ta
DanB
Am 31.12.2015 12:53 schrieb "Radu Ioan Fericean" <notifications@github.com>:

**Comment by rif** [comment]
ApierV2.SetAccount has a slightly different attribute and has the option to no longer overwrite action triggers (or action plans).

New attribute structure:
type AttrSetAccount struct {
	Tenant                            string
	Account                          string
	ActionPlanIds                 []string
	ActionPlansOverwrite     bool
	ActionTriggersIds           []string
	ActionTriggerOverwrite  bool
	AllowNegative                bool
	Disabled                         bool
	ReloadScheduler        bool
}

The two flags ActionPlansOverwrite and ActionTriggerOverwrite switch between overwrite/append modes.
