### ISSUE TITLE
Rerates API only run at 1 connection at mysql

### ISSUE THREAD

**Issue by KuikenArjan** [cgrates/cgrates#298]
When we call the rpc.call("CdrsV1.RateCdrs",{"RerateErrors":True}) the rerates run at only 1 mysql connection. This results in rerating with nearly 1 rerate per second.

Due to this behaviour rerates takes quite long if you have a lot of rerating to do.

Can you please investigate.

**Comment by danbogos** [comment]
Hi @KuikenArjan 

I have just tested and the connections are dynamically allocated based on needs (eg: I can see a dynamic number of ports from where the MySQL requests are being generated for a single RateCdrs API call).

There must be something else in your setup causing this.

DanB
