### ISSUE TITLE
[v0.10]Cache_conns for Rals not working

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#3046]
Dear Team,

I am using latest v0.10 --> CGRateS@v0.10.3~dev-20210607111152-a92bcc0ce103
and I have implemented the following setup : 

![cgrates-z1](https://user-images.githubusercontent.com/1777931/122037780-98cd7400-cddd-11eb-81ed-5296eccf0c3d.png)

The problem is that Rals1 doesn't sent out account/balance updates for cache_conns
which I would like to use to update Account Balance on CGRateS InstanceS closely to OpenSIPS(ApierV1 Instance on graph for example)

Here is the Rals config --> https://pastebin.com/JzfyjBa3

Am I doing something wrong here or there is some kind of bug? Is this the wrong path for what I want to achieve?

Thank you in advance for your support
Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
Hi @vtzan 

The connection from rals to cache will not allow you to get an account or balance updated because accounts are not caching, so that's why you did not receive any updates. This connection between this two will be removed soon.

Thanks, 
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian,

Thank you very much for your reply. 
Could you please tell me the recommended way to update accounts from rals instance to the CGRateS sessions instance that is near OpenSIPs which has its own DB? 

thank you in advance
Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
Hi @vtzan 

If you are looking for data replication between different databases, you can use our built-in replication. You can find examples here:https://github.com/cgrates/cgrates/blob/master/data/conf/samples/replication/internal/cgrates.json#L15-L63

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian,

Thank you for your reply.
Ok understood. I tested that and Its working great that way. 
I was confused with the rals cache conns part and I though that this was the proper way but now its clear.

Best Regards
Vasilios Tzanoudakis
