### ISSUE TITLE
Crash when trying to integrate with Opensips

### ISSUE THREAD

**Issue by axyi** [cgrates/cgrates#3061]
Good day!

Faced the fact that Cgr-engine crashes when interacting with OpenSips. The error occurs with approximately 30 CPS and 240 concurrent sessions. Reproduced stably.

Cgrates version: CGRateS@v0.11.0~dev-20210615141345-0ca0750b3e41
Configuration: https://pastebin.com/8rJkrQcv

Opensips version: opensips 3.1.2 (x86_64 / linux)
Configuration: https://pastebin.com/LeXMcnds

Stack trace of the error on the link below.
https://pastebin.com/XMyLNzBv

I did not see the rules for the design of topics, I apologize in advance if I did not indicate something.

Thank you in advance!

**Comment by Trial97** [comment]
Hi @axyi,

We pushed a possible fix regarding this in the latest master.
Please update and retest.

Thanks,
Trial97

**Comment by Trial97** [comment]
Hi @axyi,

Please feel free to reopen this if you can reproduce it with the latest master.

Thanks,
Trial97
