### ISSUE TITLE
crash with 10 cps

### ISSUE THREAD

**Issue by FengZStrong** [cgrates/cgrates#310]
Hi,

I make load test with 10 cps,then CGRateS crashed.
The following is log message:
2015/12/02 17:51:12 http: panic serving 192.168.133.154:55423: runtime error: invalid memory address or nil pointer dereference
goroutine 121577 [running]:
net/http.(*conn).serve.func1(0xc820fdc6e0, 0x7f34153c4670, 0xc82006cd90)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
database/sql.(*Tx).Rollback(0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1149 +0x28
github.com/jinzhu/gorm.(*DB).Rollback(0xc8209c14a0, 0xdd8580)
        /home/byron/GOPATH/src/github.com/jinzhu/gorm/main.go:360 +0x8d
github.com/cgrates/cgrates/engine.(*SQLStorage).SetCdr(0xc8200944d0, 0xc82013a820, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/storage_sql.go:626 +0x746
github.com/cgrates/cgrates/engine.(*CdrServer).processCdr(0xc820466310, 0xc82013a820, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:206 +0x3c8
github.com/cgrates/cgrates/engine.fsCdrHandler(0x7f34153e3408, 0xc820fdc8f0, 0xc821911880)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:63 +0x2ab
net/http.HandlerFunc.ServeHTTP(0x115dd10, 0x7f34153e3408, 0xc820fdc8f0, 0xc821911880)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820065050, 0x7f34153e3408, 0xc820fdc8f0, 0xc821911880)
        /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820018ae0, 0x7f34153e3408, 0xc820fdc8f0, 0xc821911880)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820fdc6e0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6

(Error 1040: Too many connections)

**Comment by andamasov** [comment]
not sure if this is a case,
but I guess you have a bottleneck at MySQL, increase max connections 

 It will be nice to have correct behaviour(maybe write all to files as an emergency option if store DB for some reason is down)

**Comment by danbogos** [comment]
Hi @FengZStrong 

Please limit the maximum open connection to the one which suits best for your db and try again. You can find them here:
https://github.com/cgrates/cgrates/blob/master/data/conf/cgrates/cgrates.json#L62

DanB

**Comment by danbogos** [comment]
Hi @FengZStrong 

Have opened a dedicated issue for your first crash here - #322, and since the issue with mysql connections is gone, I am closing this one.

DanB
