### ISSUE TITLE
Crash under load with evapi

### ISSUE THREAD

**Issue by KeithMilner** [cgrates/cgrates#311]
When used with evapi communicating with Kamailio (v4.3.4) and CGRates (0.9.1~rc8) CGRateS will crash silently. Sometimes this occurs after what looks like memory corruption as it seems to lose knowledge of configured accounts.

In the example, a sustained call load was generated between two SIPp testers across Kamailio (see attached diagram). At 25 cps the test successfully completed 10,000 calls. At 30cps CGRateS died during the test. Notes that CGRateS was not restarted or reloaded between these two test runs so it is possible that the crash was due to the cumulative effect of the two test runs. It may also be related to CPU load as it appears to occur at a lower call rate when run on a smaller instance.

From an initial analysis by DanB, this appears to be related to the "internal locker".

See https://groups.google.com/d/msg/cgrates/-NRj6dikzcs/fJLy8ZlWCQAJ for discussion, including strace file.

![lab setup 1](https://cloud.githubusercontent.com/assets/16083553/11529207/6ee2d584-98e3-11e5-8659-9662cb9f32e8.png)

**Comment by KeithMilner** [comment]
I have just repeated the test using a freshly restarted CGRateS instance. All other variables are the same. This test completed with no issues, which might point to this being  a volume based issue, rather than a call rate issue.

[10k calls test result.txt](https://github.com/cgrates/cgrates/files/49685/10k.calls.test.result.txt)

**Comment by cgrates** [comment]
Hey Keith,

Interesting, still will need to check/fix that crash since it should not 
happen no matter what.

I would be curious what are your results when using MongoDB instead of 
MySQL. Do u have time to check that?

DanB

**Comment by KeithMilner** [comment]
MongoDB seems to give better performance for me. At 30cps the test ran smoothly (I have yet to check it will perform several iterations). At 50 cps I started to have issues again.

**Comment by cgrates** [comment]
Issues but not crashes right?

DanB

**Comment by KeithMilner** [comment]
Correct. No crashes so far.

On Wed, 2 Dec 2015 at 15:24 cgrates <notifications@github.com> wrote:

> Issues but not crashes right?
>
> DanB
>
> On 02.12.2015 16:18, KeithMilner wrote:
> >
> > MongoDB seems to give better performance for me. At 30cps the test ran
> > smoothly (I have yet to check it will perform several iterations). At
> > 50 cps I started to have issues again.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cgrates/cgrates/issues/311#issuecomment-161329698>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrates/cgrates/issues/311#issuecomment-161331191>.
>

-- 
-- 
Conecto, LLC | Conecto Comunicaciones S.A. de C.V.
2220 125th Street NW Rice MN 56367 *USA*
1 Berkeley Street Mayfair London W1J 8DJ, *UK* 
Andrés Bello 10, Mexico City, 11560 *Mexico*

**Comment by danbogos** [comment]
@KeithMilner 

Will close this issue and have created a separate one for the original issue to follow it up there (#322).

DanB
