### ISSUE TITLE
Rating issue, export error, timespans truncated

### ISSUE THREAD

**Issue by voxbit1** [cgrates/cgrates#314]
This issue is based on the discussion in the forum at ref: https://groups.google.com/forum/#!topic/cgrates/Wt6MWcORygw

The conclusion of that discussion was that cgrates ought to compress the data during the call.

Hi I just tried to export some cdrs and got an error:
cgr-console 'cdrs_export CdrFormat="csv" ExportDir="/tmp"'

Error executing command: JSON unmarshal callcost error for cgrid: bc970b021cdd0abd916d41c61eec390e3c583748, runid: *default, error: unexpected end of JSON input

Looking into cdr_details I can see that the 'timespans' text field for that call truncated at 64k...the mysql text field limit.

The call was correctly billing against a voice minutes balance, and cgrates was configured such that sm_kamailio had a debit_interval=10seconds.

It seems that the cost-details timespans field is appended every 10 seconds with the latest details ... and runs out of space after 14 minutes of call duration.

It seems therefore that if debit_interval = 10sec then billing stops working when call duration exceeds about 14 minutes.

I have set debit_interval to 60 seconds as a work around for the time being.

A sample (first minute)
[cgrates-compress-bug.txt](https://github.com/cgrates/cgrates/files/53726/cgrates-compress-bug.txt)
 of a call log which filled the 64k in 14 minutes is attached.

**Comment by danbogos** [comment]
To clear out, the issue is that the callcost data becomes too large. We have discussed it internally and we  should compress the data, same as we do today for rating increments.

DanB
