### ISSUE TITLE
MaxChannels per destination

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#317]
Since we have all the information, it should be trivial to add channel limits per destination, useful in a number of commercial offerings.

DanB

**Comment by KeithMilner** [comment]
I agree this would be useful.

**Comment by iwada** [comment]
I agree too

**Comment by danbogos** [comment]
Some more ideas on the design after we have analyzed it internally.

 * There should be a new subsystem handling this limiting (eg: resourcelimiter).
 * The resource counters should follow the cdrstats implementation, one event could update more than one counter.
 * Within the configuration of profiles we should have the following:
 ** ResourceID (subject).
 ** Category (filter).
 ** StartTime of the limiting (eg: different resource allocation between peak and offpeak).
 ** ActivationTime of the limit profile.
* The counters should have ttl configurable by requests (eg: if no hangup received for a call, we still expire the counter so it does not remain stale forever).

DanB

**Comment by danbogos** [comment]
Some more ideas:
 * integrate it with callstats (so we can state stuff like: give him 5 channels if termination has enough capacity, 3 if less). This should follow the LCR implementation if possible.

DanB
