### ISSUE TITLE
Issue with ApierV1.GetAccount

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#32]
Hello Dan,

As per our chat on IRC I am adding this ticket as requested.

I came across an issue not sure if it is CGRates intended but when we use the GetBalance API we are getting two elements returned as below and I am not sure why. 

>>> response = connection.call("ApierV2.GetAccount",{"Tenant":"sbc.mydomain.com","Account":"2651797610","Direction":"*out"})
>>> response
{u'UnitCounters': [{u'Direction': u'*out', u'Balances': [{u'Category': u'', u'Uuid': u'', u'Weight': 0, u'RatingSubject': u'', u'Value': 0.03770999999999994, u'DestinationId': u'', u'ExpirationDate': u'0001-01-01T00:00:00Z', u'SharedGroup': u''}], u'BalanceType': u'*monetary'}], u'BalanceMap': {u'*monetary*out': [{u'Category': u'', u'Uuid': u'bcb34776-76e0-481c-afd8-77d79999e7f1', u'Weight': 0, u'RatingSubject': u'', u'Value': 0, u'DestinationId': u'*any', u'ExpirationDate': u'0001-01-01T00:00:00Z', u'SharedGroup': u''}, {u'Category': u'', u'Uuid': u'f808a4d4-af00-4a12-b7c7-b9565705b0e5', u'Weight': 10, u'RatingSubject': u'', u'Value': 10.71229, u'DestinationId': u'*any', u'ExpirationDate': u'0001-01-01T00:00:00Z', u'SharedGroup': u''}]}, u'AllowNegative': False, u'ActionTriggers': None, u'Disabled': False, u'Id': u'*out:sbc.mydomain.com:2651797610'}

CGRateS: cgrates_0.9.1-rc6_amd64.deb	(4th Dec and also tested on latest 18th Dec)
Database: PostgreSQL 9.4

I suspected there was an issue with the weight which was initially set to 10 so as a test I added a test I set the weight to 0 and added balance of 3 and that seems to work fine as you can see from the result below.  So is it better to add balances with weight set to 0 or is that dependent on something else? 

>>> connection.call("ApierV2.GetAccount",{"Tenant":"sbc.mydomain.com","Account":"2651797610","Direction":"*out"})
{u'UnitCounters': [{u'Direction': u'*out', u'Balances': [{u'Category': u'', u'Uuid': u'', u'Weight': 0, u'RatingSubject': u'', u'Value': 0.03770999999999994, u'DestinationId': u'', u'ExpirationDate': u'0001-01-01T00:00:00Z', u'SharedGroup': u''}], u'BalanceType': u'*monetary'}], u'BalanceMap': {u'*monetary*out': [{u'Category': u'', u'Uuid': u'bcb34776-76e0-481c-afd8-77d79999e7f1', u'Weight': 0, u'RatingSubject': u'', u'Value': 3, u'DestinationId': u'*any', u'ExpirationDate': u'0001-01-01T00:00:00Z', u'SharedGroup': u''}, {u'Category': u'', u'Uuid': u'f808a4d4-af00-4a12-b7c7-b9565705b0e5', u'Weight': 10, u'RatingSubject': u'', u'Value': 10.71229, u'DestinationId': u'*any', u'ExpirationDate': u'0001-01-01T00:00:00Z', u'SharedGroup': u''}]}, u'AllowNegative': False, u'ActionTriggers': None, u'Disabled': False, u'Id': u'*out:sbc.mydomain.com:2651797610'}

Please note that we are not using CSV files but pushing the data into StorDB via API and then using ApierV1.LoadDestination, ApierV1.LoadRatingPlan and ApierV1.LoadRatingProfile to move the data from StorDB to DataDB.

Attached are a couple of images of my tp_actions and tp_action_plans.

![tp_actions](https://cloud.githubusercontent.com/assets/5496519/5587744/b7b09d6a-90eb-11e4-979a-2a26a96c0924.png)
![tp_action_plans](https://cloud.githubusercontent.com/assets/5496519/5587745/c23c399c-90eb-11e4-845d-fd63a64e7987.png)

regards,

Errol

**Comment by danbogos** [comment]
Hi Errol,

After investigating it turned out that CGRateS behaves.

Whenever you create an account, there will be a default balance attached. This is needed for the case of consuming and no other matching balance found (eg: you have only minutes to UK and you are calling US).

If you only want to see one balance, you will need to top up the default balance (with weight 0), so the one with weight 10 will not longer be created.

Please let me know if clear enough.

DanB

**Comment by ewsamuels** [comment]
OK Thanks for the explanation.
