### ISSUE TITLE
Guard bad map state

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#322]
In some extreme load cases we could spot the following panic:

```
fatal error: bad map state

goroutine 708551 [running]:
runtime.throw(0xfa8d60, 0xd)
        /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc838d12b38 sp=0xc838d12b20
runtime.evacuate(0xca4ea0, 0xc8204c8750, 0xd98)
        /usr/local/go/src/runtime/hashmap.go:825 +0x3b1 fp=0xc838d12bf8 sp=0xc838d12b38
runtime.growWork(0xca4ea0, 0xc8204c8750, 0x78f5)
        /usr/local/go/src/runtime/hashmap.go:795 +0x83 fp=0xc838d12c18 sp=0xc838d12bf8
runtime.mapassign1(0xca4ea0, 0xc8204c8750, 0xc838d12d70, 0xc838d12d28)
        /usr/local/go/src/runtime/hashmap.go:433 +0x176 fp=0xc838d12cc0 sp=0xc838d12c18
github.com/cgrates/cgrates/engine.(*GuardianLock).Guard(0xc820194310, 0xc832131590, 0x77359400, 0xc838d12e98, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/guardian.go:44 +0x1db fp=0xc838d12e30 sp=0xc838d12cc0
github.com/cgrates/cgrates/sessionmanager.(*Sessions).removeSession(0xc82096c660, 0xc8219d8120, 0x7f3486fd28b8, 0xc832131560, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/sessionmanager/sessions.go:87 +0x197 fp=0xc838d12ed8 sp=0xc838d12e30
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).onChannelHangupComplete(0xc8200142d0, 0x7f3486fd28b8, 0xc832131560)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:216 +0x130 fp=0xc838d12f40 sp=0xc838d12ed8
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).createHandlers.func2(0xc83569c780, 0x259, 0xc82096c6c0, 0x24)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:66 +0x76 fp=0xc838d12f90 sp=0xc838d12f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc838d12f98 sp=0xc838d12f90
created by github.com/cgrates/fsock.(*FSock).dispatchEvent
        /home/byron/GOPATH/src/github.com/cgrates/fsock/fsock.go:387 +0x401
```

**Comment by danbogos** [comment]
Should be fixed in the master.

DanB

**Comment by MarcVoIP** [comment]
The same happens on recent master branch of cgrates. 

Load test with 60CPS lasts for 4 minutes and then cgrates crashes. 
Freeswitch + cgrates + redis + MariaDB on a single host, 32GB ram, 8 cores Xeon CPU.

30CPS test crashes cgrates after 15 minutes

CPU usage is at around 60% for all the proceses. 
Attached is the stack trace. 

[Issue322_bad_map_state.txt](https://github.com/cgrates/cgrates/files/124374/Issue322_bad_map_state.txt)

**Comment by rif** [comment]
@MarcVoIP Can you reproduce this again with go 1.6 since they added some feature to detect similar cases. Maybe with this go version it will be more informative.

Here is the excerpt of 1.6 release notes:
The runtime has added lightweight, best-effort detection of concurrent misuse of maps. As always, if one goroutine is writing to a map, no other goroutine should be reading or writing the map concurrently. If the runtime detects this condition, it prints a diagnosis and crashes the program. The best way to find out more about the problem is to run it under the race detector, which will more reliably identify the race and give more detail.

**Comment by MarcVoIP** [comment]
So far no luck in reproducing the issue on better servers and with separate database and Freeswitch nodes. Cgrates performs well even with 160CPS (new call setups per second). I will continue the test and report in case of any further issues. 

Still using   go1.5.3 linux/amd64 and master cgrates trunk

**Comment by danbogos** [comment]
Thanks for report @MarcVoIP. Will close the issue for now, so feel free to reopen if issue coming back.

DanB
