### ISSUE TITLE
Action: *add_balance

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#324]
We need to specify: add new balance even if there is one with the same characteristics.
There are common offerings telling: create a balance monthly and make it's units expire in 2 months.

DanB

**Comment by rif** [comment]
You can use one of the *topup, *topup_reset actions or newly added *set_balance putting anything (not an existing uuid) in the BalanceUuid field. In this way none of the existing balances will match and a new one will be added with the specified fields.

We don't care what you put in the uuid field as a new unique one will be generated anyway.
