### ISSUE TITLE
cgrates crashes if using wrong config in ERS

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#3270]
so i followed the docs which were incorrect (PR #3269 )

and my cgrates bailed with a crash when attempting to process a CDR - example cdr, config and error - https://gist.github.com/anthonysomerset/0e98fc1a5bd5a639b2804c2283aea47e

@Trial97 asked that we create an issue against this as cgrates should not crash in this scenario as discussed in https://groups.google.com/g/cgrates/c/j73XdM-2Tpk

**Comment by ionutboangiu** [comment]
The sanity check added in commit https://github.com/cgrates/cgrates/commit/6c41ebe0de5a11a7a7552239e5233c983813e465 prevents this from happening anymore.
