### ISSUE TITLE
FeatureRequest - Balance Operations on the *voice balance should accept time units in the value field

### ISSUE THREAD

**Issue by anthonysomerset** [cgrates/cgrates#3274]
Initial chat took place here https://groups.google.com/g/cgrates/c/f_b7JrnjnfQ

We are implementing voice bundles and while going through sample tarrif plans e.g https://github.com/cgrates/cgrates/tree/master/data/tariffplans/oldtutorial i noted that the Actions can reset a *voice balance in a time unit of say 120s

```
TOPUP_120_DST1003,*topup_reset,,,,*voice,,DST_1003,,,*unlimited,,120s,20,false,false,10
```

i tried doing an equivilent Set balance event via API assuming this unit metric would work but i get 

e.g.
```
{
  "method": "ApierV1.SetBalance",
  "params": [
    {
      "Tenant": "voice.lab.liquidtelecom.net",
      "Account": "27110XXXX98",
      "BalanceType": "*voice",
      "Balance": {
        "ID": "SMARTVOICE",
        "Value": "120s",
        "Weight": 25,
        "DestinationIDs": "LAB_LOCAL"
      }
    }
  ],
  "id": 13
}
```

I get following error:

```
{
  "id": 13,
  "result": null,
  "error": "strconv.ParseFloat: parsing \"120s\": invalid syntax"
}
```

It would be much more human friendly if the provisioning calls would also support balance operations where time suffixes are processed the same as an Action gets handled otherwise assume default handling value as nano seconds

**Comment by ionutboangiu** [comment]
Implemented in commit: 24cce1425
