### ISSUE TITLE
Dropped calls when rate_increment and group_interval_start set to 6

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#33]
Hello,

I uploaded my A-Z rates and I was able to make calls to any international destination that I called however I noticed that whenever I made a call to the USA the call would drop as soon as it was answered.  

There were no errors in the Freeswitch or CGRates logs but what I did realize was that all the international destinations I was calling the rate_increment and group_interval_start were both set to 1 whereas for the USA both the rate_increment and group_interval_start were both set to 6.  

I set both the rate_increment and group_interval_start were both set to 1 and was able to make calls to the USA then I set them back to 6 and the calls dropped again. 

#### GET CALL COST with rate_increment and group_interval_start set to 6
 cgr-console 'cost Direction="*out" Category="call" Tenant="sbc.mydomain.com" Subject="2651797610" Account="2651797610" Destination="19173001321" TimeStart="2014-12-31T14:00:00Z" TimeEnd="2014-12-31T14:05:00Z"'
{
 "Direction": "*out",
 "Category": "call",
 "Tenant": "sbc.mydomain.com",
 "Subject": "322181565",
 "Account": "322181565",
 "Destination": "19123001321",
 "TOR": "*voice",
 "Cost": 6e+09,
 "Timespans": [
  {
   "TimeStart": "2014-12-31T14:00:00Z",
   "TimeEnd": "2014-12-31T14:00:06Z",
   "Cost": 6e+09,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0,
     "RoundingMethod": "*middle",
     "RoundingDecimals": 5,
     "Rates": [
      {
       "GroupIntervalStart": 6000000000,
       "Value": 0,
       "RateIncrement": 6000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 6000000000,
   "Increments": null,
   "MatchedSubject": "*out:sbc.mydomain.com:call:*any",
   "MatchedPrefix": "1912",
   "MatchedDestId": "United_States"
  },
  {
   "TimeStart": "2014-12-31T14:00:06Z",
   "TimeEnd": "2014-12-31T14:05:00Z",
   "Cost": 0,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0,
     "RoundingMethod": "*middle",
     "RoundingDecimals": 5,
     "Rates": [
      {
       "GroupIntervalStart": 6000000000,
       "Value": 0,
       "RateIncrement": 6000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 300000000000,
   "Increments": null,
   "MatchedSubject": "*out:sbc.mydomain.com:call:*any",
   "MatchedPrefix": "1912",
   "MatchedDestId": "United_States"
  }
 ]
}
#### GET CALL COST with rate_increment and group_interval_start set to 1
root@sbc:~# cgr-console 'cost Direction="*out" Category="call" Tenant="sbc.mydomain.com" Subject="322181565" Account="322181565" Destination="19123001321" TimeStart="2014-12-31T14:00:00Z" TimeEnd="2014-12-31T14:05:00Z"'
{
 "Direction": "*out",
 "Category": "call",
 "Tenant": "sbc.mydomain.com",
 "Subject": "322181565",
 "Account": "322181565",
 "Destination": "19123001321",
 "TOR": "*voice",
 "Cost": 1e+09,
 "Timespans": [
  {
   "TimeStart": "2014-12-31T14:00:00Z",
   "TimeEnd": "2014-12-31T14:00:01Z",
   "Cost": 1e+09,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0,
     "RoundingMethod": "*middle",
     "RoundingDecimals": 5,
     "Rates": [
      {
       "GroupIntervalStart": 1000000000,
       "Value": 0,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 1000000000,
   "Increments": null,
   "MatchedSubject": "*out:sbc.mydomain.com:call:*any",
   "MatchedPrefix": "1912",
   "MatchedDestId": "United_States"
  },
  {
   "TimeStart": "2014-12-31T14:00:01Z",
   "TimeEnd": "2014-12-31T14:05:00Z",
   "Cost": 0,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0,
     "RoundingMethod": "*middle",
     "RoundingDecimals": 5,
     "Rates": [
      {
       "GroupIntervalStart": 1000000000,
       "Value": 0,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 300000000000,
   "Increments": null,
   "MatchedSubject": "*out:sbc.mydomain.com:call:*any",
   "MatchedPrefix": "1912",
   "MatchedDestId": "United_States"
  }
 ]
}
![tp_rates](https://cloud.githubusercontent.com/assets/5496519/5588044/dce73c9c-90f5-11e4-8eee-fb63667db4b8.png)

![tp_rating_plan](https://cloud.githubusercontent.com/assets/5496519/5588055/2ae49fb6-90f6-11e4-9801-4a9b85b2807d.png)

![tp_rating_profile](https://cloud.githubusercontent.com/assets/5496519/5588062/821cb2d2-90f6-11e4-81c8-e0ad30d3a325.png)

I trust someone would be able to make some sense from this.

Happy New Year to ALL!

regards,

Errol

**Comment by cgrates** [comment]
Hi Errol,

Happy New Year to you too!

The reason you get session disconnect is due to tariff plan error you 
have inserted in your Rates.csv. If you set GroupIntervalStart to 6 the 
rater will not have a rate for the beginning of the interval (1-6) hence 
dropping the call. If you want to have the first 6 seconds of a call 
free, you need to still define a GroupIntervalStart 0 with a 
corresponding rate of 0. If you want to charge all but in increments of 
6 seconds, you need to define GroupIntervalStart to 0 and RateIncrement 
to 6.

Let me know if clear enough.

DanB

**Comment by ewsamuels** [comment]
Hi DanB,
I tested with a rate of 0.015 and defining GroupIntervalStart to 0 and RateIncrement to 6 and it works as expected.

Thanks
Errol
