### ISSUE TITLE
API for trigger management

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#330]
We should improve trigger management for the cases:
 * We want to manage a group of triggers on an account (eg: remove group of triggers with id). This group of triggers will match the one loaded via ActionTriggers.csv
 * We want to remove/reset specific on an account (eg: remove/reset trigger with id).

DanB

**Comment by rif** [comment]
Added SetActionTriggers, RemoveActionTriggers and ResetActionTriggers APIs. Tests pending.
