### ISSUE TITLE
Wrong detection of Timing

### ISSUE THREAD

**Issue by tomec-martin** [cgrates/cgrates#338]
We have pricelist with peak and offpeak price, but for call at 2015-12-11T09:07:27Z (which is peak) I have got 2 diferent prices. When I try 2 minutes call in cgr-console:

cost Direction="*out" Category="call" Tenant="cgrates.org" Subject="P11585T28864" Account="P326215734" Destination="+420848000868" TimeStart="2015-12-11T09:05:27Z" TimeEnd="2015-12-11T09:07:27Z" FallbackSubject="" TOR=""

I have got result where first minute is offpeak and second minute is peak:
{
"Direction": "*out",
"Category": "call",
"Tenant": "cgrates.org",
"Subject": "P11585T28864",
"Account": "P326215734",
"Destination": "+420848000868",
"TOR": "*voice",
"Cost": 214,
"Timespans": [
  {
   "TimeStart": "2015-12-11T09:05:27Z",
   "TimeEnd": "2015-12-11T09:06:27Z",
   "Cost": 85,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      0
     ],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0,
     "RoundingMethod": "*up",
     "RoundingDecimals": 5,
     "MaxCost": 0,
     "MaxCostStrategy": "",
     "Rates": [
      {
       "GroupIntervalStart": 0,
       "Value": 85,
       "RateIncrement": 60000000000,
       "RateUnit": 60000000000
      },
      {
       "GroupIntervalStart": 60000000000,
       "Value": 85,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 60000000000,
   "Increments": null,
   "MatchedSubject": "*out:cgrates.org:call:P11585T28864",
   "MatchedPrefix": "+420848",
   "MatchedDestId": "350_Bila_linka_848_TREE0",
   "RatingPlanId": "5775"
  },
  {
   "TimeStart": "2015-12-11T09:06:27Z",
   "TimeEnd": "2015-12-11T09:07:27Z",
   "Cost": 129,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [
      1,
      2,
      3,
      4,
      5
     ],
     "StartTime": "07:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0,
     "RoundingMethod": "*up",
     "RoundingDecimals": 5,
     "MaxCost": 0,
     "MaxCostStrategy": "",
     "Rates": [
      {
       "GroupIntervalStart": 0,
       "Value": 129,
       "RateIncrement": 60000000000,
       "RateUnit": 60000000000
      },
      {
       "GroupIntervalStart": 60000000000,
       "Value": 129,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 120000000000,
   "Increments": null,
   "MatchedSubject": "*out:cgrates.org:call:P11585T28864",
   "MatchedPrefix": "+420848",
   "MatchedDestId": "350_Bila_linka_848_TREE0",
   "RatingPlanId": "5775"
  }
]
}

Our Timings.csv and part of RatingPlans.csv are attached

[CSV.zip](https://github.com/cgrates/cgrates/files/74187/CSV.zip)

**Comment by rif** [comment]
Very good catch, thanks a lot for this report!

**Comment by tomec-martin** [comment]
This issue is still present in CGRateS 0.9.1~rc8 (version from 20-Jan-2016). Was this patch included in last build?

**Comment by danbogos** [comment]
Hi Martin,

We have created a new package out of master. Please retest (fresh 
install please or use migrator to migrate your old data).
I believe that the issue was fixed in master.

Thanks,
DanB
