### ISSUE TITLE
Rating the b leg of calls

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#34]
Hello,
I am trying to rate the b leg of the call somehow but not sure of the best way of doing this.  At the moment I have enabled  <param name="log-b-leg" value="true"/> in json_cdr.conf.xml and I am able to see both legs of the call, the a-leg of the call is rated but I am unable to get the B-leg of the call rated.

I understand that CGRates will only rate the calls for the A-leg of the call and I see that no problem but I also need to show the rate and what the provider charged for the call if that makes sense.

DanB you did mention about creating some sort of loop with Freeswitch on IRC so we can get both legs but you never went into the details of how to get it done.  So I would be grateful if you can share this info.

Thanks
Errol

**Comment by danbogos** [comment]
Hi Errol

I would suggest bringing the discussion on the mailing list since this does
not really look like an issue but a general support discussion.

DanB.
Am 02.01.2015 19:24 schrieb "ewsamuels" <notifications@github.com>:
