### ISSUE TITLE
Migrating to 0.10, regex filters

### ISSUE THREAD

**Issue by Dobby16** [cgrates/cgrates#3468]
Hello,

in the "old" version we used regex filters for cdrc (now ers).

I tried to migrate from:
`"cdr_filter": "8(~^004)"`

to: 
`"filters": ["*string:~*req.8(~^004)"]`

but that doesn't seemed to work, please help.

**Comment by porosnicuadrian** [comment]
Hello @Dobby16 

If you are using regex, you will need the type of your filter to be "*regex", not "*string" in order to match. Let me know if this works.

Thanks 
@porosnicuadrian

**Comment by Dobby16** [comment]
Hello there @porosnicuadrian ,

I just tried it with the syntax like:
`"filters": ["*regex:~*req.5:(^0$)"],`
and 
`"filters": ["*regex:~*req.5:^0$"],`
and 
`"filters": ["*regex:~*req.5:!(^0$)"],`
and
`"filters": ["*regex:~*req.5:!^0$"],`

none of these combinations seems to work, can you see what's wrong?

**Comment by porosnicuadrian** [comment]
Hello @Dobby16 

I am sorry for getting you on another version. Actually, the type you need to change is "*rsr" for parsing the value with regex. So for your examples, you could write the filter like this: 
1. "*rsr::~*req.8(~^004)"
2. "*rsr::~*req.5(~^0$)"

Here are some tests with "*rsr" type filters: https://github.com/cgrates/cgrates/blob/v0.10/engine/filters_test.go#L821-L868
And here are the filters docs: https://cgrates.readthedocs.io/en/v0.10/filters.html
Apologies again and hope this works!

Thanks,
@porosnicuadrian
