### ISSUE TITLE
Transfer credits between 2 accounts

### ISSUE THREAD

**Issue by andrewvmail** [cgrates/cgrates#360]
Submitting an issue request for a way to transfer credits between 2 accounts.

Thanks
Andrew

**Comment by noahmehl** [comment]
In the interest of understanding the issue (and not trying to be a dick, I promise you :), I'm wondering why not just accomplish this through the JSON RPC or through HTTP/WS?  I guess I'm wondering how this would be accomplished, and why this logic should exist within CGRates as opposed to the business logic of your (the royal you, not just @andrewvmail) application/s?

**Comment by andrewvmail** [comment]
I just thought doing through CGrates would be better as to it has it's own
way to do transactions, possible cdrlog support also. Currently I am doing
it with JSON RPC. But I don't think I'm not sure what is the proper way to
handle transactions... best practice etc.
I just thought it's better if it's handled by the engine.

AT
