### ISSUE TITLE
AttributeS calling an external API for SentryPeer integration

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#3603]
Hi all,

As per:

https://groups.google.com/g/cgrates/c/acbxqWaRUq0

It would be amazing if `AttributeS` could call an external API, as there are no options at the moment to integrate real time data.

The idea is to generate `BAD_DST` destinations on the fly and notify/act on a hit. These numbers have been collected by the SentryPeer honeypot:

https://github.com/SentryPeer/SentryPeer#restful-api

Thanks,
Gavin.

**Comment by danbogos** [comment]
Hi Gavin,

Sorry it has taken so long for us to get to your issue.

Could we hold some "virtual meeting" together where we can analyze best the integration with SentryPeer?

Ta,
Dan

**Comment by ghenry** [comment]
Hi @danbogos 

https://sentrypeer.com is out now :-)

We'd need to do auth to get a token:

https://docs.sentrypeer.com/authentication

then query phone numbers like so:

https://docs.sentrypeer.com/phone-numbers

or IP addresses:

https://docs.sentrypeer.com/ip-addresses

**Comment by ghenry** [comment]
Thanks for the progress so far @gezimbll

I see you've created an account and an API client.

**Comment by ghenry** [comment]
Just saw your pull request @gezimbll

Thank you so much for the quick turn around! 

 Left a few comments on it.

**Comment by ghenry** [comment]
Is there a way to process incoming webhooks and mark a number/ip address in that payload as a BLACKLIST? So instead of the queries originating from CGRateS to SentryPeer, it can also process a POST - https://docs.sentrypeer.com/webhooks

**Comment by gezimbll** [comment]
Hi @ghenry ,

Please open a new  separate issue for the webhook question,   so we can can look later into it  for a possible implementation.

Thanks,
Gezim

**Comment by gezimbll** [comment]
Hi @ghenry ,

Please can you share some information for use cases of webhook api ?So we can have an idea on
how to integrate on our side.

Best Regards,
Gezim

**Comment by danbogos** [comment]
Hi Gavin,

It makes sense for some use cases but in ours we are already able to process your initial reply since it is filters we have integrated your plugin into. That means that the answer coming from you (blocked) can be further tagged (ie: using AttributeS) and then used in further modules (ie. ThresholdS) where we can execute specific actions (ie: disable_account). 
Based on this, the additional implementation it will only make the reply slower and not useful in CGRateS, or do you see it otherwise?

Thanks,
DanB

**Comment by danbogos** [comment]
Hi Gavin,

OK, let's leave it like this for the moment since all the basic functionality is in-there. We can than come back if enough interest is raised towards expanding it.

Thanks!

DanB
