### ISSUE TITLE
Panic: runtime error: invalid memory address

### ISSUE THREAD

**Issue by vivian-inttel-net** [cgrates/cgrates#3614]
Hello,

Just had CGRates crash while processing calls. Here is the cgrates.log at the time of the crash. Seems to be in the AMQP module, but I may be wrong. 

Mar 10 13:31:07 cust29 cgr-engine[112729]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 10 13:31:07 cust29 cgr-engine[112729]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x13acc8d]
Mar 10 13:31:07 cust29 cgr-engine[112729]: goroutine 1470311 [running]:
Mar 10 13:31:07 cust29 cgr-engine[112729]: github.com/streadway/amqp.(*Connection).NotifyClose(0x0, 0xc00b471ce0)
Mar 10 13:31:07 cust29 cgr-engine[112729]: #011/home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/streadway/amqp/connection.go:273 +0x4d
Mar 10 13:31:07 cust29 cgr-engine[112729]: github.com/cgrates/cgrates/ees.(*AMQPee).Connect.func1()
Mar 10 13:31:07 cust29 cgr-engine[112729]: #011/home/dan/go/src/github.com/cgrates/cgrates/ees/amqp.go:86 +0x45
Mar 10 13:31:07 cust29 cgr-engine[112729]: created by github.com/cgrates/cgrates/ees.(*AMQPee).Connect
Mar 10 13:31:07 cust29 cgr-engine[112729]: #011/home/dan/go/src/github.com/cgrates/cgrates/ees/amqp.go:85 +0x186
Mar 10 13:31:07 cust29 CGRateS <305273a> [113573]: <CoreS> starting version <CGRateS@v0.11.0~dev-20220307085120-0dee207d6a68><go1.17.5>

{
 "ActiveGoroutines": 65,
 "GoVersion": "go1.17.5",
 "MemoryUsage": "6.7MiB",
 "NodeID": "305273a",
 "RunningSince": "Thu Mar 10 13:31:07 EST 2022",
 "Version": "CGRateS@v0.11.0~dev-20220307085120-0dee207d6a68"
}

Thank you
Vivian

**Comment by ionutboangiu** [comment]
Hi Vivian,

I'm sorry to hear the issue is still occurring, but I'm afraid I'll still need your config, or at the very least the "ees" section, to try and reproduce it.

Thanks,
Ionut

**Comment by vivian-inttel-net** [comment]
Hi Ionut,

Thank you for looking into this.
Here is the config:
{

// Real-time Charging System for Telecom & ISP environments
// Copyright (C) ITsysCOM GmbH
//


"general": {
        "node_id": "",                                                                                  // identifier of this instance in the cluster, if empty it will be autogenerated
        "logger":"*syslog",                                                                             // controls the destination of logs <*syslog|*stdout>
        "log_level": 6,                                                                                 // control the level of messages logged (0-emerg to 7-debug)
        "http_skip_tls_verify": true,                                                   // if enabled HttpClient will accept any TLS certificate
        "rounding_decimals": 5,                                                                 // system level precision for floats
        "dbdata_encoding": "*msgpack",                                                  // encoding used to store object data in strings: <*msgpack|*json>
        "tpexport_dir": "/var/spool/cgrates/tpe",                               // path towards export folder for offline TariffPlans
        "poster_attempts": 3,                                                                   // number of attempts before considering post request failed (eg: *http_post, CDR exports)
        "failed_posts_dir": "/var/spool/cgrates/failed_posts",  // directory path where we store failed requests
        "failed_posts_ttl": "5s",                                                               // time to wait before writing the failed posts in a single file
        "default_request_type": "*rated",                                               // default request type to consider when missing from requests: <""|*prepaid|*postpaid|*pseudoprepaid|*rated>
        "default_category": "call",                                                             // default category to consider when missing from requests
        "default_tenant": "cgrates.org",                                                // default tenant to consider when missing from requests
        "default_timezone": "Local",                                                    // default timezone for timestamps where not specified <""|UTC|Local|$IANA_TZ_DB>
        "default_caching":"*reload",                                                    // default actions to do when caching items
        "connect_attempts": 5,                                                                  // initial server connect attempts
        "reconnects": -1,                                                                               // number of retries in case of connection lost
        "connect_timeout": "1s",                                                                // consider connection unsuccessful on timeout, 0 to disable the feature
        "reply_timeout": "2s",                                                                  // consider connection down for replies taking longer than this value
        "locking_timeout": "2s",                                                                        // timeout internal locks to avoid deadlocks
        "digest_separator": ",",                                                                // separator to use in replies containing data digests
        "digest_equal": ":",                                                                    // equal symbol used in case of digests
        "rsr_separator": ";",                                                                   // separator used within RSR fields
        "max_parallel_conns": 200,                                                              // the maximum number of connection used by the *parallel strategy
        "concurrent_requests": 0,                                                               // number of active concurrent requests
        "concurrent_strategy": "*busy",                                                 // strategy for limit active concurrent requests
},

"listen": {
        "rpc_json": ":2012",
        "rpc_gob": ":2013",
        "http": ":2080",
},

"data_db": {                                                            // database used to store runtime data (eg: accounts)
        "db_type": "*redis",                                    // data_db type: <*redis|*mongo>
        "db_host": "127.0.0.1",                                 // data_db host address
        "db_port": 6379,                                                // data_db port to reach the database
        "db_name": "10",                                                // data_db database name to connect to
        "db_user": "cgrates",                                   // username to use when connecting to data_db
        "db_password": "",                                              // password to use when connecting to data_db
        "redis_sentinel":"",                                    // the name of sentinel when used
        "query_timeout":"10s",
        "remote_conns":[],
        "replication_conns":[],
        "items":{
                "*accounts":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*reverse_destinations": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*destinations": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*rating_plans": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*rating_profiles":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*actions":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*action_plans": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*account_action_plans":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*action_triggers":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*shared_groups":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*timings": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*resource_profiles":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*resources":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*statqueue_profiles": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*statqueues": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*threshold_profiles": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*thresholds": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*filters": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*supplier_profiles":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*attribute_profiles":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*charger_profiles": {"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*dispatcher_profiles":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*dispatcher_hosts":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*filter_indexes" :{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
                "*load_ids":{"remote":false, "replicate":false, "limit": -1, "ttl": "", "static_ttl": false},
        },
},


"stor_db": {
        "db_type": "*mysql",                                    // stor database type to use: <*mongo|*mysql|*postgres|*internal>
        "db_host": "127.0.0.1",                                 // the host to connect to
        "db_port": 3306,                                                // the port to reach the stor_db
        "db_name": "cgrates",                                   // stor database name
        "db_user": "cgrates",                                   // username to use when connecting to stor_db
        "db_password": "1234",                                          // password to use when connecting to stor_db
        "max_open_conns": 100,                                  // maximum database connections opened, not applying for mongo
        "max_idle_conns": 10,                                   // maximum database connections idle, not applying for mongo
        "conn_max_lifetime": 0,                                 // maximum amount of time in seconds a connection may be reused (0 for unlimited), not applying for mongo
        "string_indexed_fields": [],                    // indexes on cdrs table to speed up queries, used in case of *mongo and *internal
        "prefix_indexed_fields":[],                             // prefix indexes on cdrs table to speed up queries, used in case of *internal
        "query_timeout":"10s",
        "sslmode":"disable",                                    // sslmode in case of *postgres
        "items":{
                "session_costs": {"limit": -1, "ttl": "", "static_ttl": false},
                "cdrs": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_timings":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_destinations": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_rates": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_destination_rates": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_rating_plans":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_rating_profiles":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_shared_groups": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_actions":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_action_plans":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_action_triggers":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_account_actions": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_resources":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_stats":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_thresholds": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_filters": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_suppliers": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_attributes":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_chargers":{"limit": -1, "ttl": "", "static_ttl": false},
                "versions": {"limit": -1, "ttl": "", "static_ttl": false},
                "tp_dispatcher_profiles":{"limit": -1, "ttl": "", "static_ttl": false},
                "tp_dispatcher_hosts":{"limit": -1, "ttl": "", "static_ttl": false},
        },



},


"schedulers": {
        "enabled": true,
},


"rals": {
        "enabled": true,
        "thresholds_conns": ["*localhost"],
        "stats_conns": ["*localhost"],
        "attributes_conns": ["*localhost"],
},


"cdrs": {
        "enabled": true,
        "store_cdrs": true,
        "stats_conns": ["*localhost"],
        "chargers_conns": ["*localhost"],
        "rals_conns": ["*localhost"],
        "ees_conns": ["*localhost"],
        "sessions_cost_retries": 5,
        "online_cdr_exports": ["*default"]
},

"ers": {
        "enabled": true
},

"ees": {
        "enabled": true,
//      "attributes_conns":[],                                  // RPC Connections IDs
//      "cache": {
//              "*file_csv": {"limit": -1, "ttl": "5s", "static_ttl": false},
//      },
        "exporters": [
                {
                        "id": "*default",                                                                       // identifier of the EventReader profile
                        "type": "*amqp_json_map",                                                                       // exporter type
                        "export_path": "amqp://cg029:2a55f4a0f1b@198.198.198.1:5672/s029",                       // path where the exported events will be placed
                        "concurrent_requests": 0,                                                       // maximum simultaneous requests to process, 0 for unlimited
                        "opts": {
//                              "amqpExchange": "",                                                     // Exchange
//                              "amqpExchangeType": "fanout",                                           // ExchangeType

                        },                                                                                                      // extra options for exporter
//                      "timezone": "",                                                                         // timezone for timestamps where not specified <""|UTC|Local|$IANA_TZ_DB>
//                      "filters": [],                                                                          // limit parsing based on the filters
//                      "flags": [],                                                                            // flags to influence the event processing
//                      "attribute_ids": [],                                                            // select Attribute profiles instead of discovering them
//                      "attribute_context": "",                                                        // context used to discover matching Attribute profiles
//                      "synchronous": false,                                                           // block processing until export has a result
                        "attempts": 1,                                                                          // export attempts
//                      "fields":[
//                              {"path":"*exp.Account", "type": "*composed", "value": "~*req.Account"},
//                              {"path": "*exp.CGRID", "type": "*composed", "value": "~*req.CGRID"},
//                              {"path": "*exp.Source", "type": "*composed", "value": "~*req.source_number"},
//                              {"path": "*exp.Destination", "type": "*composed", "value": "~*req.Destination"},
//                              {"path": "*exp.Usage", "type": "*composed", "value": "~*req.Usage"},
//                              {"path": "*exp.Cost", "type": "*composed", "value": "~*req.Cost", "rounding_decimals": 4},
//                              {"path": "*exp.SetupTime", "type": "*composed", "value": "~*req.SetupTime"},
//                              {"path": "*exp.StartTime", "type": "*composed", "value": "~*req.CostDetails:s/StartTime\\\"\\s?\\:\\s?\\\"([^\\\"]*)\\\".*/$1/"},
//                              {"path": "*exp.AnswerTime", "type": "*composed", "value": "~*req.AnswerTime"},
//
//                      ],
                        "failed_posts_dir": "/var/spool/cgrates/failed_posts",  // directory path where we store failed requests
                },
        ],
},

"chargers": {
        "enabled": true,
        "attributes_conns": ["*localhost"],
},


"sessions": {
        "enabled": true,
        "listen_bijson": "127.0.0.1:2014",              // address where to listen for bidirectional JSON-RPC requests
        "chargers_conns": ["*localhost"],
        "rals_conns": ["*localhost"],
        "cdrs_conns": ["*localhost"],
        "resources_conns": ["*localhost"],
        "routes_conns": ["*localhost"],
        "attributes_conns": ["*localhost"],
        "stats_conns": ["*localhost"],
        "thresholds_conns": ["*localhost"],
        "debit_interval": "60s",
        "channel_sync_interval":"30s",
        "alterable_fields": ["DisconnectReason", "HangupSource", "SIPCode"],

},



"attributes": {
        "enabled": true,
        "indexed_selects": true,
        "string_indexed_fields": ["*req.Account"],
        "prefix_indexed_fields": ["*req.Destination"],
},


"resources": {
        "enabled": true,
        "thresholds_conns": ["*localhost"],
        "string_indexed_fields": ["*req.Account"],
        "prefix_indexed_fields": ["*req.Destination"],
},


"stats": {
        "enabled": true,
        "thresholds_conns": ["*localhost"],
        "string_indexed_fields": ["*req.Account"],
},


"thresholds": {
        "enabled": true,
        "string_indexed_fields": ["*req.Account"],
},


"routes": {
        "enabled": true,
        "resources_conns": ["*localhost"],
        "stats_conns": ["*localhost"],
        "string_indexed_fields": ["*req.Account"],
        "prefix_indexed_fields": ["*req.Destination"],

},


"filters": {                                                            // Filters configuration (*new)
        "enabled": true,
//      "stats_conns": [],                                              // connections to StatS for <*stats> filters, empty to disable stats functionality: <""|*internal|$rpc_conns_id>
//      "resources_conns": [],                                  // connections to ResourceS for <*resources> filters, empty to disable stats functionality: <""|*internal|$rpc_conns_id>
        "apiers_conns": ["*localhost"],                                         // connections to RALs for <*accounts> filters, empty to disable stats functionality: <""|*internal|$rpc_conns_id>
},


"apiers": {
        "enabled": true,
        "scheduler_conns": ["*localhost"],
},


}

**Comment by vivian-inttel-net** [comment]
Hi Ionut,

Not sure if this is helpful, but, the problem seems to occur when the volume of calls is high.
When I have  1-3 calls per second, it works fine. However, when I have 10 or more calls per second, it just crashes.
Another interesting thing I noticed is that this happens only when AMQP is being used.

Thanks
Vivian

**Comment by ionutboangiu** [comment]
Hi Vivian,

I've tried to reproduce the issue, using your configuration, with more than 200+ exports per second and CGRateS was fine with the load (also tried to kill the connection mid-processing and no panic occurred either). You could also share the syslog output. If there is any error coming from AMQP's module, after the connection was established, it should appear there.

Thanks,
Ionut

**Comment by vivian-inttel-net** [comment]
Hi Ionut,

Sorry it took a while to retest, had to compile opensips from scratch so I had crash dump in case I needed it.
The error is the same again:
Mar 21 19:24:19 cust29 cgr-engine[18138]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 21 19:24:19 cust29 cgr-engine[18138]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x13acc8d]
Mar 21 19:24:19 cust29 cgr-engine[18138]: goroutine 2539405 [running]:
Mar 21 19:24:19 cust29 cgr-engine[18138]: github.com/streadway/amqp.(*Connection).NotifyClose(0x0, 0xc01262bbc0)
Mar 21 19:24:19 cust29 cgr-engine[18138]: #011/home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/streadway/amqp/connection.go:273 +0x4d
Mar 21 19:24:19 cust29 cgr-engine[18138]: github.com/cgrates/cgrates/ees.(*AMQPee).Connect.func1()
Mar 21 19:24:19 cust29 cgr-engine[18138]: #011/home/dan/go/src/github.com/cgrates/cgrates/ees/amqp.go:86 +0x45
Mar 21 19:24:19 cust29 cgr-engine[18138]: created by github.com/cgrates/cgrates/ees.(*AMQPee).Connect
Mar 21 19:24:19 cust29 cgr-engine[18138]: #011/home/dan/go/src/github.com/cgrates/cgrates/ees/amqp.go:85 +0x186
Mar 21 19:24:20 cust29 CGRateS <0f9bb75> [24495]: <CoreS> starting version <CGRateS@v0.11.0~dev-20220307085120-0dee207d6a68><go1.17.5>

This from /var/log/messages:
Mar 21 19:24:19 cust29 ./opensips[23284]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Mar 21 19:24:19 cust29 ./opensips[23284]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014
Mar 21 19:24:19 cust29 ./opensips[23285]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Mar 21 19:24:19 cust29 ./opensips[23285]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014

This from journalctl :
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x13acc8d]
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]: goroutine 2539405 [running]:
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]: github.com/streadway/amqp.(*Connection).NotifyClose(0x0, 0xc01262bbc0)
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]:         /home/dan/go/src/github.com/cgrates/cgrates/vendor/github.com/streadway/amqp/connection.go:273 +0x4d
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]: github.com/cgrates/cgrates/ees.(*AMQPee).Connect.func1()
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]:         /home/dan/go/src/github.com/cgrates/cgrates/ees/amqp.go:86 +0x45
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]: created by github.com/cgrates/cgrates/ees.(*AMQPee).Connect
Mar 21 19:24:19 cust29.inttel.net cgr-engine[18138]:         /home/dan/go/src/github.com/cgrates/cgrates/ees/amqp.go:85 +0x186
Mar 21 19:24:19 cust29.inttel.net ./opensips[23284]: client: 3008
Mar 21 19:24:19 cust29.inttel.net ./opensips[23284]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Mar 21 19:24:19 cust29.inttel.net mariadbd[493]: 2022-03-21 19:24:19 17524 [Warning] Aborted connection 17524 to db: 'cgrates' user: 'cgrates' host: 'localhost' (Got an error reading communication packets)
Mar 21 19:24:19 cust29.inttel.net mariadbd[493]: 2022-03-21 19:24:19 17244 [Warning] Aborted connection 17244 to db: 'cgrates' user: 'cgrates' host: 'localhost' (Got an error reading communication packets)
Mar 21 19:24:19 cust29.inttel.net ./opensips[23284]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014
Mar 21 19:24:19 cust29.inttel.net mariadbd[493]: 2022-03-21 19:24:19 16327 [Warning] Aborted connection 16327 to db: 'cgrates' user: 'cgrates' host: 'localhost' (Got an error reading communication packets)
Mar 21 19:24:19 cust29.inttel.net mariadbd[493]: 2022-03-21 19:24:19 13963 [Warning] Aborted connection 13963 to db: 'cgrates' user: 'cgrates' host: 'localhost' (Got an error reading communication packets)
Mar 21 19:24:19 cust29.inttel.net ./opensips[23285]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Mar 21 19:24:19 cust29.inttel.net systemd[1]: cgrates.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 21 19:24:19 cust29.inttel.net ./opensips[23285]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014
Mar 21 19:24:19 cust29.inttel.net systemd[1]: cgrates.service: Failed with result 'exit-code'.
Mar 21 19:24:19 cust29.inttel.net ./opensips[23284]: [6b6b33d05e1a79f21998fbe8323f3edc@19******060] CGRateS auth failed: rc=-2, code=<null>
Mar 21 19:24:19 cust29.inttel.net systemd[1]: cgrates.service: Consumed 30min 46.717s CPU time.
Mar 21 19:24:19 cust29.inttel.net ./opensips[23286]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection
Mar 21 19:24:19 cust29.inttel.net ./opensips[23286]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014
Mar 21 19:24:19 cust29.inttel.net ./opensips[23284]: INFO:cgrates:cgrc_async_read: CGRateS engine reset the connection
Mar 21 19:24:19 cust29.inttel.net ./opensips[23284]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014
Mar 21 19:24:19 cust29.inttel.net ./opensips[23286]: INFO:cgrates:cgrc_async_read: CGRateS engine closed the connection

If you could also let me know how to enable a full debug on CGRates (trying the json config but does nothing).

Thank you
Vivian

**Comment by ionutboangiu** [comment]
Hi Vivian,

You can find all the cgrates related logs in /var/log/cgrates/CGRateS.log. If you are still using the same config you specified in this issue, it should be fine.

Thanks,
Ionut

**Comment by vivian-inttel-net** [comment]
I took some time to compile both OpenSIPs and CGRateS from scratch so I can trap crash dumps.
I notice that in many of the crash dumps, the following: (hoping, you could throw some light):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {8192, 7, 94010342047632, 94010342021312, 0, 21, 895, 0, 0, 281470681751424, 0, 0, 0, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f16e6578537 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 0, 0, 0, 0, 1, 139736255523198, 140732689022976, 140728898420737, 140732689023296, 94008244174848, 8589934593, 94010342047652, 94010342055968, 139736266412360, 94010341998440}},
          sa_flags = 2097823608, sa_restorer = 0x7f16e24cf088}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000055807c56dea6 in sig_alarm_abort (signo=<optimized out>) at shutdown.c:161
        __FUNCTION__ = "sig_alarm_abort"
#3  <signal handler called>
No locals.
#4  0x00007f16e6637fa7 in sched_yield () at ../sysdeps/unix/syscall-template.S:120
No locals.
#5  0x00007f16e1e6f13d in get_lock (lock=0x7f16e24cf088) at ../../parser/../mem/../fastlock.h:230
        i = <optimized out>
        i = <optimized out>
#6  cgr_free_acc_ctx (ctx=<optimized out>) at cgrates_acc.c:198
        l = <optimized out>
        t = <optimized out>
        dlg = <optimized out>
        ctxstr = {s = 0x7f16e1a25e00 <__FUNCTION__.2> "del_tree", len = 329}
        __FUNCTION__ = "cgr_free_acc_ctx"
#7  0x00007f16e1e717cb in cgr_ref_acc_ctx (ctx=<optimized out>, how=how@entry=-1, who=who@entry=0x7f16e1e91adb "general ctx") at cgrates_acc.c:219
        __FUNCTION__ = "cgr_ref_acc_ctx"
#8  0x00007f16e1e8b71c in cgr_free_ctx (param=0x7f16e2bbf710) at cgrates_common.c:1012
        l = <optimized out>
        t = <optimized out>
        ctx = 0x7f16e2bbf710
        __FUNCTION__ = "cgr_free_ctx"
#9  0x000055807c4be30b in context_destroy (ctxtype=ctxtype@entry=CONTEXT_TRAN, ctx=ctx@entry=0x7f16e2a5e780) at context.c:110


Thank you
Vivian

**Comment by ionutboangiu** [comment]
Hi Vivian,

I'm afraid I cannot help you here because the crash messages you have provided appear to be from OpenSIPS' end.

Thanks,
Ionut

**Comment by vivian-inttel-net** [comment]
Thanks for letting me know.

**Comment by vivian-inttel-net** [comment]
Hi Ionut,

Same config. Any thoughts on the AMQP side? What are you using for AMQP?
Please let me know.

Thank you
Vivian

**Comment by ionutboangiu** [comment]
Hi Vivian,

When I tested, I used RabbitMQ, version 3.10.5 (I hope this is what you meant).

Thanks,
Ionuț

**Comment by vivian-inttel-net** [comment]
Hi Ionut,

I am still using 3.9.9 from earlier.

Thank you
Vivian
