### ISSUE TITLE
CGRates failed to start after reboot

### ISSUE THREAD

**Issue by tomec-martin** [cgrates/cgrates#364]
I suppose it is because mysql is not started. Mysql and cgrates have both start order 03. After reboot /etc/init.d/cgrates status gives this:
● cgrates.service - LSB: CGRateS real-time charging system
   Loaded: loaded (/etc/init.d/cgrates)
   Active: active (exited) since Thu 2016-02-18 09:14:13 UTC; 1h 1min ago
  Process: 349 ExecStart=/etc/init.d/cgrates start (code=exited, status=0/SUCCESS)

Feb 18 09:14:13 ip-10-64-10-100 systemd[1]: Started LSB: CGRateS real-time charging system.
Feb 18 09:14:14 ip-10-64-10-100 CGRateS[395]: Could not configure logger database: dial tcp 127.0.0.1:3306: getsockopt: connection refused exiting!

**Comment by danbogos** [comment]
As discussed, we should review this issue when we review the init scripts.

DanB

**Comment by bhepp** [comment]
I am having the same problem on server startup, even though mysql is running in a different container. Both containers are on the same server though. Maybe a simple reconnect mechanism with a reasonable number of retries (the `reconnects` option comes to mind) will be a better approach?

**Comment by tomec-martin** [comment]
I have add this line to init script:
`# Required-Start:    $remote_fs $syslog mysql redis-server`

But the start failed on another error:
`Feb 22 10:26:35 ip-10-64-10-100 CGRateS[887]: Cache rating error: LOADING Redis is loading the dataset in memory`

**Comment by acheraime** [comment]
I'm having the same issue. Just installed CGRateS 0.9.1~rc8 git+dc1e774 (2017-02-19T10:06:50+01:00).
I'm using Redis and Postgres.
Starting cgrates fail with error : CGRateS <rating-server1> [23613]: Could not configure logger database: dial tcp 127.0.0.1:3306: getsockopt: con...d exiting!

**Comment by danbogos** [comment]
Hi

You most probably need to upgrade your configuration.

DanB
Am 25.02.2017 14:51 schrieb "acheraime" <notifications@github.com>:

**Comment by danbogos** [comment]
Did not hear about this issue again. Closing issue. Please reopen if still present.
Thanks,
DanB
