### ISSUE TITLE
[v0.10] MongoDB Hosts always uses 27017 port

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#3673]
Dear Team,

Following this conversation --> https://groups.google.com/g/cgrates/c/wFvFesaXkTo

I see that when I use db hosts that have different ports on each hostname like this: 
`DATADB_HOST=pl-0-eu-central-1.qgnpv.mongodb.net:1024,pl-0-eu-central-1.qgnpv.mongodb.net:1025,pl-0-eu-central-1.qgnpv.mongodb.net:1026`

CGRateS always appends 27017 port to each host. 

logs:
`2022/05/26 10:38:01 error parsing uri: invalid host "pl-0-eu-central-1.qgnpv.mongodb.net:1026:27017": address pl-0-eu-central-1.qgnpv.mongodb.net:1026:27017: too many colons in address`

So if all dbhosts have ports what should we put in "db_port": ?

thank you in advance for your support.

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

commit b715ff4009f982f51a8e3fbb2fd97e48b937a663 worked!!!

Thank you very much

Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

Could you please add this patch https://github.com/cgrates/cgrates/commit/b715ff4009f982f51a8e3fbb2fd97e48b937a663
to the latest master?

thank you in advance.

Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
HI @vtzan,

We added the patch that you mentioned. Please, can you upgrade to the latest master and let me know if it worked.

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian,

It worked! 

Thank you very much.

Best Regards
Vasilios Tzanoudakis
