### ISSUE TITLE
[v0.10] DISPATCHER_ERROR:NOT_FOUND on CacheSv1.ReloadCache

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#3676]
Dear Team,

I am using latest `CGRateS@v0.10.3~dev-20220527094543-b715ff4009f9` and
when a CacheSv1.ReloadCache was sent to a CGRateS Sessions instance with Dispatchers enabled it doesn't work.

```
#
T 2022/06/04 14:20:53.083089 10.100.4.97:56418 -> 10.100.5.212:2070 [AP] #124
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"voiceland.dev","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":["voiceland.dev:+302107001397"],"ChargerProfileIDs":[],"DispatcherProfileIDs":[],"DispatcherHostIDs":[],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":2}

#
T 2022/06/04 14:20:53.083755 10.100.5.212:2070 -> 10.100.4.97:56418 [AP] #126
{"id":2,"result":null,"error":"DISPATCHER_ERROR:NOT_FOUND"}
```

I double checked and Data exist on my MongoDB.
I also trying with cgr-loader binary with text files inside this sessions instance and had the same issue.

cgrates.json config --> [here](https://pastebin.com/Yp8dzzD2)

thank you in advance

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
I also receive this when I try to send SessionSv1.AuthorizeEventWithDigest to sessions instance throught OpenSIPS

```
T 2022/06/04 14:48:27.264293 10.100.0.10:39328 -> 10.100.5.212:2014 [AP] #810
{ "method": "SessionSv1.AuthorizeEventWithDigest", "id": 996706046, "params": [ { "Tenant": "global.tnt", "GetAttributes": true, "Event": { "ID": "CHECK_LOCAL_DOMAINS", "Account": "LOCAL_DOMAINS", "Context": "local_domains" } } ] }
#
T 2022/06/04 14:48:27.265384 10.100.5.212:2014 -> 10.100.0.10:39328 [AP] #811
{"id":996706046,"result":null,"error":"ATTRIBUTES_ERROR:DISPATCHER_ERROR:NOT_FOUND"}
```

which is working when using apier instance which share the same DB: 
```
{
    "id": 996706130,
    "result": {
        "AttributesDigest": "domain1:voiceland.dev,domain2:voiceland.global",
        "ResourceAllocation": null,
        "MaxUsage": 0,
        "SuppliersDigest": null,
        "Thresholds": null,
        "StatQueues": null
    },
    "error": null
}
```

Thanks

**Comment by vtzan** [comment]
Dear Team,

I found what is going on.

I tried to load the dispatcher config on DATADB using the APIER interface from another CGRateS instance and On the first time if there is no data inserted on DATADB
when I load the dispathcer config and the APIER instance sends CacheReload on the Dispatcher Engine I receive the error above

```
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"voiceland.dev","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":[],"ChargerProfileIDs":[],"DispatcherProfileIDs":["voiceland.dev:RALS"],"DispatcherHostIDs":[],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":9}

#
T 2022/06/05 10:30:46.683970 10.100.4.129:2070 -> 10.100.4.97:43058 [AP] #159
{"id":9,"result":null,"error":"DISPATCHER_ERROR:NOT_FOUND"}
```

So to replicate the issue.

1)setup an empty mongoDB
2)start both CGRateS engines (Apier and DispatcherS)
3)provision DispatcherS config using the APIER Engine and watch using ngrep port 2070 on the DispatcherS Engine side the CacheSv1.ReloadCache returning --> DISPATCHER_ERROR:NOT_FOUND

After DATA is loaded on Mongo Database and then I restart the dispatcher+sessions engine everything is working fine. Is this the way it should work or is this a BUG?

thank you in advance

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

I have just found that adding the dispatcher_filter_indexes in cache section like this

```
 "caches":{                                                                                                          
                 "*dispatcher_routes": {"limit": -1, "ttl": "2s"},                                                          
                "*dispatcher_filter_indexes" : {"limit": -1, "ttl": "2s"},                                                  
                },        
```

only the first request :
`{
    "id": 1,
    "method": "APIerSv1.SetDispatcherHost",
    "params": [
        {
            "Tenant": "voiceland.dev",
            "ID": "SELF",
            "Conns": [
                {
                    "Address": "*internal",
                    "Transport": null,
                    "Synchronous": false,
                    "TLS": false
                }
            ]
        }
    ]
}`

gives error on cache reload
```
T 2022/06/05 14:57:40.027482 10.100.4.97:34288 -> 10.100.5.57:2070 [AP] #725
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"voiceland.dev","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":[],"ChargerProfileIDs":[],"DispatcherProfileIDs":[],"DispatcherHostIDs":["voiceland.dev:SELF"],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":0}

##
T 2022/06/05 14:57:40.032151 10.100.5.57:2070 -> 10.100.4.97:34290 [AP] #727
{"id":0,"result":null,"error":"DISPATCHER_ERROR:NOT_FOUND"}
```

The second one which sets the *any to -->SELF is working as it should
```
{
    "id": 1,
    "method": "APIerSv1.SetDispatcherProfile",
    "params": [
        {
            "Tenant": "voiceland.dev",
            "ID": "ALL",
            "Subsystems": [
                "*any"
            ],
            "FilterIDs": [],
            "ActivationInterval": null,
            "Strategy": "*weight",
            "StrategyParams": {},
            "Hosts": [
                {
                    "ID": "SELF",
                    "Weight": 20
                }
            ],
            "Weight": 10
        }
    ]
}
```
```
T 2022/06/05 14:57:44.139932 10.100.4.97:34288 -> 10.100.5.57:2070 [AP] #732
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"voiceland.dev","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":[],"ChargerProfileIDs":[],"DispatcherProfileIDs":["voiceland.dev:ALL"],"DispatcherHostIDs":[],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":1}

T 2022/06/05 14:57:44.176812 10.100.5.57:2070 -> 10.100.4.97:34288 [AP] #735
{"id":1,"result":"OK","error":null}
```

So I suppose this is just a how dispatcher also works according to cache parameters? 

Thank you in advance

Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
Hi @vtzan 

Sorry for the delay, we have started considering this issue now. I got your dispatcherS engine config, but please, for this to continue, I will need the other engine config(as you mention Apier config) and the tariffplans for Dispatchers/Attributes that you are using.

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian,

Thank you in advance for your time on this.

Apier config --> [here](https://pastebin.com/hB9Aumfw)

DispatcherS + Attributes Config --> [here](https://pastebin.com/CVB6aECV)

Best Regards

Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
Hello @vtzan,

As far as I can see from you tariffplans and requests, some of them are using different tenants: "voiceland.dev" and "global.tnt".  For example, in the comment when you request "AuthorizeEventWithDigest", you used "global.tnt", and on reload cache you used "voiceland.tnt". 
Also, same thing for the last tariffplans that you have send to me. The global tenant(default tenant in general config) is "voiceland.dev" in both APIER and Dispatchers engine, and the requests are used on "global.tnt".
By calling a "ReloadCache" on Dispatcher engine, the tenants must coincide in both profile and requests. Also, if you set a dispatcher host, you also must have a dispatcher profile that will use that host, both oh them must be in database, and after that you can ReloadCache properly. Let me know when you verify again the data and in case it won't work, send me again the steps to reproduce again one by one.

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian 

Thank you for your reply.

I am using CGRateS attributes also as a database to save valid domains for my SIP Service.
on first SIP REGISTER/INVITE request,the SIP server asks attributes with a fixed tenant global.tnt if the domain
of the request exists on CGRateS and its working great like this:

```
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"Context":"local_domains","ProcessRuns":null,"Tenant":"global.tnt","ID":"e5eee222-c0b5-4d4c-89e5-fe52f65033ed","Time":null,"Event":{"Account":"LOCAL_DOMAINS","Context":"local_domains","ID":"CHECK_LOCAL_DOMAINS"}}],"id":5531}

##
T 2022/09/07 04:53:12.784274 127.0.0.1:2070 -> 127.0.0.1:35586 [AP] #178
{"id":5531,"result":{"MatchedProfiles":["LOCAL_DOMAINS"],"AlteredFields":["*req.domain1","*req.domain2","*req.domain3","*req.domain4"],"CGREvent":{"Tenant":"global.tnt","ID":"e5eee222-c0b5-4d4c-89e5-fe52f65033ed","Time":null,"Event":{"Account":"LOCAL_DOMAINS","Context":"local_domains","ID":"CHECK_LOCAL_DOMAINS","domain1":"voiceland.dev","domain2":"voiceland.global","domain3":"global_dids","domain4":"global.tnt"}}},"error":null}
```

so this global.tnt tenant has nothing to do with the voiceland.dev tenant whichs hold all other tarrifplans
like attributes/rating/chargers/suppliers and Opensips uses only voiceland.dev tenant for sip session requests.

So when the CGRateS DB is empty and I want to add DispatcherS config for domain global.tnt this is happening

```
{
    "id": 1,
    "method": "APIerSv1.SetDispatcherHost",
    "params": [
        {
            "Tenant": "global.tnt",
            "ID": "SELF",
            "Conns": [
                {
                    "Address": "*internal",
                    "Transport": null,
                    "Synchronous": false,
                    "TLS": false
                }
            ]
        }
    ]
}
```

and Apier host sends CacheReload to the Dispatcher host like this :
```

T 2022/09/07 05:01:51.402717 10.100.3.102:54358 -> 10.100.0.65:2070 [AP] #54
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"global.tnt","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":[],"ChargerProfileIDs":[],"DispatcherProfileIDs":[],"DispatcherHostIDs":["global.tnt:SELF"],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":3}

#
T 2022/09/07 05:01:51.406593 10.100.0.65:2070 -> 10.100.3.102:54358 [AP] #55
**{"id":3,"result":null,"error":"DISPATCHER_ERROR:NOT_FOUND"}**
```

so here the tenant on cacheReload is correct and there is conflict with voiceland.dev.

then I set the dispatcher profile and cacheReload from Apier host to DispatcherS host works well here :

```
{
    "id": 1,
    "method": "APIerSv1.SetDispatcherProfile",
    "params": [
        {
            "Tenant": "global.tnt",
            "ID": "ALL",
            "Subsystems": [
                "*any"
            ],
            "FilterIDs": [],
            "ActivationInterval": null,
            "Strategy": "*weight",
            "StrategyParams": {},
            "Weight": 10,
            "Hosts": [
                {
                    "ID": "SELF",
                    "Weight": 20
                }
            ]
        }
    ]
}

```
----

```
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"global.tnt","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":[],"ChargerProfileIDs":[],"DispatcherProfileIDs":["global.tnt:ALL"],"DispatcherHostIDs":[],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":9}

#
T 2022/09/07 05:06:48.826028 10.100.0.65:2070 -> 10.100.3.102:54358 [AP] #23
**{"id":9,"result":"OK","error":null}**

```

so my question is why the APIerSv1.SetDispatcherHost request above is failing with CacheReload and replies `**{"id":3,"result":null,"error":"DISPATCHER_ERROR:NOT_FOUND"}**`

The funny thing is this. After I set APIerSv1.SetDispatcherProfile and then I set again the same APIerSv1.SetDispatcherHost request above then CacheReload of APIerSv1.SetDispatcherHost is working great :

```
{"method":"CacheSv1.ReloadCache","params":[{"Tenant":"global.tnt","DestinationIDs":[],"ReverseDestinationIDs":[],"RatingPlanIDs":[],"RatingProfileIDs":[],"ActionIDs":[],"ActionPlanIDs":[],"AccountActionPlanIDs":[],"ActionTriggerIDs":[],"SharedGroupIDs":[],"ResourceProfileIDs":[],"ResourceIDs":[],"StatsQueueIDs":[],"StatsQueueProfileIDs":[],"ThresholdIDs":[],"ThresholdProfileIDs":[],"FilterIDs":[],"SupplierProfileIDs":[],"AttributeProfileIDs":[],"ChargerProfileIDs":[],"DispatcherProfileIDs":["global.tnt:ALL"],"DispatcherHostIDs":[],"DispatcherRoutesIDs":[],"FlushAll":false}],"id":6}

#
T 2022/09/07 05:10:03.925094 10.100.0.65:2070 -> 10.100.5.147:53318 [AP] #6
{"id":6,"result":"OK","error":null}
```


Sorry for the big reply here but I hope I was more clear describing this. 
Its not a big issue for me but while working with CGRateS I found it strange and thought it would be good to mention it
in case there is a bug behind. If you think its not we can close this.

Thank you in advance.

Best Regards

Vasilios

**Comment by porosnicuadrian** [comment]
Hello @vtzan,

Thanks for letting me know. 
As I see now from your case, the tenants conflict is not  the cause of the issue.
The problem is that the DispatcherProfile must EXIST in database in order to avoid the error on calling "ReloadCache".
A DispatcherProfile contains one or multiple DispatcherHosts, so it is necessary to have a profile in database and after that, the CacheReload will work, as you mentioned. For this, just do these steps in order:
1.SetDispatcherHost
2.SetDispatcherProfile(this will contain the host that you set previously).
3.CacheReload(in order to work, will search in DATABASE for a DispatcherProfile)

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian,

Great! This is exactly what I do so I will close this case.
Thank you for your support.

Vasilios
