### ISSUE TITLE
When using logger type *stdout, freeswitch connection crashes

### ISSUE THREAD

**Issue by jleren** [cgrates/cgrates#3678]
We see the following message, when starting cgr-engine with logtype *stdout

2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting version <CGRateS@v0.11.0~dev-20220528075001-f495a10c3be2><go1.18.3>
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <CoreS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <CDRs> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [WARNING] WARNING: missing TLS certificate/key file!
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <ThresholdS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <HTTP> enabling handler for JSON-RPC
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <HTTP> enabling handler for WebSocket connections
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <HTTP> start listening at <:2080>
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <Stats> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <SessionS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <ServiceManager> Starting CGRateS Scheduler.
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <ResourceS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <RouteS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <AttributeS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] Starting CGRateS JSON server at <:2012>.
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] Starting CGRateS GOB server at <:2013>.
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] Registering CDRS HTTP Handlers.
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] Registering CDRS RPC service.
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <ApierS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <CoreS> starting <ChargerS> subsystem
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] Starting CGRateS BiJSON server at <127.0.0.1:2014>
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <Scheduler> processing 0 action plans
2022/06/23 12:10:40 CGRateS <CGRFreeswitch> [INFO] <Scheduler> queued 0 action plans
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100375520]

goroutine 59 [running]:
log/syslog.(*Writer).writeAndRetry(0x0?, 0x0?, {0x10139c63a?, 0x0?})
	/usr/local/go/src/log/syslog/syslog.go:251 +0x30
log/syslog.(*Writer).Info(0x140009dff38?, {0x10139c63a?, 0x14000bc54e0?})
	/usr/local/go/src/log/syslog/syslog.go:239 +0x30
github.com/cgrates/fsock.(*FSock).connect(0x140009e78c0)
	/Users/jos/go/pkg/mod/github.com/cgrates/fsock@v0.0.0-20220525160530-35a725c0140f/fsock.go:102 +0xd8
github.com/cgrates/fsock.(*FSock).Connect(...)
	/Users/jos/go/pkg/mod/github.com/cgrates/fsock@v0.0.0-20220525160530-35a725c0140f/fsock.go:86
github.com/cgrates/fsock.NewFSock({0x14000bc54e0, 0x10}, {0x14000bc54c9, 0x7}, 0xffffffffffffffff, 0x0, 0x101de4e98, 0x14000bbdd10, 0x14000bbdce0, {0x101e076b8, ...}, ...)
	/Users/jos/go/pkg/mod/github.com/cgrates/fsock@v0.0.0-20220525160530-35a725c0140f/fsock.go:51 +0x2c4
github.com/cgrates/cgrates/agents.(*FSsessions).Connect(0x14000718f00)
	/Users/jos/Documents/git/external/cgrates/agents/fsagent.go:291 +0x188
github.com/cgrates/cgrates/services.(*FreeswitchAgent).Start.func1(0x140005c2e80?)
	/Users/jos/Documents/git/external/cgrates/services/freeswitchagent.go:68 +0x28
created by github.com/cgrates/cgrates/services.(*FreeswitchAgent).Start
	/Users/jos/Documents/git/external/cgrates/services/freeswitchagent.go:67 +0x26c

It works when changing logtype to *stdout

Here is our cgrates.json:

{

  // Real-time Online/Offline Charging System (OCS) for Telecom & ISP environments
  // Copyright (C) ITsysCOM GmbH

  "general": {
    "log_level": 100,
    "logger": "*stdout",
    "node_id":"CGRFreeswitch",
    "default_tenant": "universe",
  },

  "listen": {
    "rpc_json": ":2012",
    "rpc_gob": ":2013",
    "http": ":2080",
  },

  "data_db": {								// database used to store runtime data (eg: accounts)
 	"db_type": "*redis",					// data_db type: <*redis|*mongo>
 	"db_host": "localhost",					// data_db host address
 	"db_port": 6379, 						// data_db port to reach the database
 	"db_name": "10", 						// data_db database name to connect to
  },

  "stor_db": {
    "db_type": "*internal",
    //"db_port": 5432,
    //"db_host": "localhost",
    //"db_name": "cgrates",
    //"db_user": "cgrates",
    //"db_password": "CGRateS.org",
  },

  "http": {													// HTTP server configuration
    "json_rpc_url": "/jsonrpc",								// JSON RPC relative URL ("" to disable)
    "registrars_url": "/registrar",							// registrar service relative URL
    "ws_url": "/ws",										// WebSockets relative URL ("" to disable)
    "freeswitch_cdrs_url": "/freeswitch_json",				// Freeswitch CDRS relative URL ("" to disable)
    "http_cdrs": "/cdr_http",								// CDRS relative URL ("" to disable)
    "use_basic_auth": false,								// use basic authentication
  },

  "schedulers": {
    "enabled": true,
  },

  "rals": {
    "enabled": true,
    "thresholds_conns": ["*localhost"],
    "stats_conns": ["*localhost"],
  },

  "cdrs": {
    "enabled": true,
    "stats_conns": ["*localhost"],
    "chargers_conns": ["*localhost"],
    "rals_conns": ["*localhost"],
    "sessions_cost_retries": 5,
  },

  "chargers": {
    "enabled": true,
    "attributes_conns": ["*localhost"],
  },

  "sessions": {
    "enabled": true,
    "rals_conns": ["*localhost"],
    "cdrs_conns": ["*localhost"],
    "resources_conns": ["*localhost"],
    "routes_conns": ["*localhost"],
    "attributes_conns": ["*localhost"],
    "stats_conns": ["*localhost"],
    "thresholds_conns": ["*localhost"],
    "chargers_conns": ["*localhost"],
    "debit_interval": "5s",
    //"channel_sync_interval":"",
  },

  "freeswitch_agent": {
    "enabled": true,
    "event_socket_conns":[
      {"address": "10.45.11.73:8021", "password": "fcrulez", "reconnects": -1,"alias":""}
    ],
    "sessions_conns": ["*birpc_internal"],
    "create_cdr": false,
    "extra_fields": [
      "~*req.variable_tiu_billable_company",
      "~*req.variable_tiu_otheraccount",
      "~*req.variable_tiu_pstnprovider",
      "~*req.variable_tiu_calleridname",
      "~*req.variable_tiu_calleridnumber",
      "~*req.variable_tiu_clihidden",
      "~*req.variable_tiu_calleddestination",
      "~*req.variable_tiu_sourcesbc",
      "~*req.variable_rtp_audio_in_mos",
      "~*req.variable_fcp-cdr-dst-is-pickup",
      "~*req.variable_fcp-cdr-src-type",
      "~*req.variable_fcp-cdr-src-user-id",
      "~*req.variable_fcp-cdr-src-company-id",
      "~*req.variable_fcp-cdr-src-device-id",
      "~*req.variable_fcp-cdr-src-service-id",
      "~*req.variable_fcp-cdr-src-pstn-country",
      "~*req.variable_fcp-cdr-src-pstn-provider",
      "~*req.variable_fcp-cdr-src-cli",
      "~*req.variable_fcp-cdr-src-cli-hidden",
      "~*req.variable_fcp-cdr-dst-type",
      "~*req.variable_fcp-cdr-dst-user-id",
      "~*req.variable_fcp-cdr-dst-company-id",
      "~*req.variable_fcp-cdr-dst-phonenumber-id",
      "~*req.variable_fcp-cdr-dst-device-id",
      "~*req.variable_fcp-cdr-dst-service-id",
      "~*req.variable_fcp-cdr-dst-internal-id",
      "~*req.variable_fcp-cdr-dst-pstn-number",
      "~*req.variable_fcp-cdr-dst-pstn-routing-provider",
      "~*req.variable_fcp-cdr-dst-pstn-billing-provider",
      "~*req.variable_fcp-cdr-dst-pstn-level",
      "~*req.variable_fcp-interop-type"
    ],
  },

  "attributes": {
    "enabled": true,
    "string_indexed_fields": ["*req.Account","*req.FraudCheckCompany", "*req.ExtraFields.variable_tiu_billable_company"],
  },

  "resources": {
    "enabled": true,
    "string_indexed_fields": ["*req.Account"],
  },

  "stats": {
    "enabled": true,
    "string_indexed_fields": ["*req.Account","*req.RunID","*req.Destination"],
  },

  "thresholds": {
    "enabled": true,
    "string_indexed_fields": ["*req.Account"],
  },

  "routes": {
    "enabled": true,
    "resources_conns": ["*localhost"],
    "stats_conns": ["*localhost"],
    "rals_conns": ["*localhost"],
    "string_indexed_fields": ["*req.Account"],
  },

  "apiers": {
    "enabled": true,
    "scheduler_conns": ["*localhost"],
  },

}

**Comment by ionutboangiu** [comment]
Hi @jleren,

This issue has been fixed on the latest master.

Thanks, 
Ionut

**Comment by jleren** [comment]
Hi Ionut,

I can confirm that it also works on my end now.

Thank you,
Jon
