### ISSUE TITLE
Redis cluster support broken with redis-7

### ISSUE THREAD

**Issue by gedia** [cgrates/cgrates#3704]
Hello,

Redis v7 produces slightly different output for the 'CLUSTER SLOTS' command which breaks cluster support in CGR. Upgrading the  mediocregopher/radix dependency to v3.8.1 should resolve this issue.

**Comment by porosnicuadrian** [comment]
Hi @gedia,

Before updating,  is it backwards compatible?

Thanks,
@porosnicuadrian

**Comment by gedia** [comment]
Hello @porosnicuadrian ,

Thanks for following up. I'm only now setting things up so I haven't tested extensively. Building with v3.8.1 worked fine, and I was able to run cgr-migrator to update versions (whereas it would fail without the radix version bump).

I hope I'll make some progress in the next few days, but inevitably, only a limited number of (manual) testing will be performed.

If you mean whether radix 3.8.1 is compatible with redis6, I believe it is implied so in the changelog.

BR,
George

**Comment by gedia** [comment]
Hello again,

I haven't run into any issues with Redis V7 cluster and cgrates-0.11.0~dev+20221130195305+258492fcf so far.

The change in radix library is backwards compatible with Redis 6, so I believe it is safe to close this issue now? Thanks!

BR,
George

**Comment by gedia** [comment]
Also, maybe upgrade the dependency in branch 1.0 before closing this. Thanks.
