### ISSUE TITLE
How to remove all accounts

### ISSUE THREAD

**Issue by tomec-martin** [cgrates/cgrates#371]
I was trying to remove all accounts by calling GetAccounts and then RemoveAccount for every found Account. But there was 60s timeout for some calls of RemoveAccount function.
Maybe there could be corrupted data, so at first I should clear it and try with new accounts. Is there any simple way to clear all accounts?

**Comment by rif** [comment]
I you have default redis configuration you can simply go to database 11 and do a del acc_*

Or more aggressive approaches:
redis-cli -n 11 flushdb // flushes entire db 11
redis-cli flushall // flushes all readis databases

**Comment by tomec-martin** [comment]
Flushing redis and recreating data helped, so it was probably caused by some bad data. I will reopen this issue when I will be able to replicate it reliably...
