### ISSUE TITLE
GetActiveSessionIDs: Issue parsing response from Freeswitch "show channels" Request

### ISSUE THREAD

**Issue by ruhnet** [cgrates/cgrates#3749]
With Freeswitch agent and `channel_sync_interval` enabled, looking at ngrep captures of port 2014, it seems that after a session is initiated, it doesn't show up when queried for on `SessionSv1.GetActiveSessionIDs`, as `"error":"NO_ACTIVE_SESSION"` is returned when the query is made. So CGRates forcefully hangs up an active call whenever it syncs the channel at whatever interval is set, assuming that it is a stale session, even though it should proceed.

When I disable `channel_sync_interval` by setting it to 0, the SessionSv1.GetActiveSessionIDs method isn't called and the voice call proceeds as it should. 

Ionuț said it's because the `show channels` request to Freeswitch returns a response that is not being parsed properly by `GetActiveSessionIDs`, and he instructed me to open this issue.

Attached is an ngrep of a call that is being killed in this manner, with `channel_sync_interval` enabled.

[cgr_ngrep_2014_and_8021.txt](https://github.com/cgrates/cgrates/files/9844988/cgr_ngrep_2014_and_8021.txt)

**Comment by ionutboangiu** [comment]
Hi @ruhnet,

Issue should have been fixed. Let me know if it works.

Thanks,
Ionuț
