### ISSUE TITLE
cgrates.json installs in the wrong location

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#38]
Hi DanB,

It seems the latest package dated 21st Jan installs the config file in /etc/cgrates.json instead of /etc/cgrates/cgrates/json and I just wanted to bring that to your attention.  Not sure if it was intentional or not.

regards,

Errol

**Comment by danbogos** [comment]
Hey Errol,

Thank you for your report. Please retest.

DanB

**Comment by ewsamuels** [comment]
Hey Dan,
Now it installs in /etc/cgrates/cgrates/cgrates.json shouldn't it be /etc/cgrates/cgrates.json?
Thanks
Errol

**Comment by danbogos** [comment]
Hi Errrol,

Please retest with latest package. Hopefully will land in the right place this time.

DanB

**Comment by ewsamuels** [comment]
Fixed now thanks
