### ISSUE TITLE
Does cgrates support FreeBSD

### ISSUE THREAD

**Issue by tbswork1** [cgrates/cgrates#3807]
Does cgrates support FreeBSD? We would like to use it with FreeSwitch also running on FreeBSD.

**Comment by arberkatellari** [comment]
Hi @tbswork1 
Based on Go there shouldn't be any issue to build the binaries there. However, we are not aware about the impact of specific libraries we use (e.g. inotify). We don't have any experience with CGRateS on FreeBSD. 
Thanks, @arberkatellari

**Comment by tbswork1** [comment]
inotify is Linux specific so it won't run on FreeBSD. Thanks.

**Comment by danbogos** [comment]
Just for completion, inotify is not really mandatory to run CGRateS on FreeBSD, so chances are that it still works. We just never tested it properly.

DanB

**Comment by tbswork1** [comment]
Alright. But how you watch dir change without inotify then?

**Comment by danbogos** [comment]
By looking at the library we use (fsnotify), it appears that on *BSD systems `kqueue` will be used.

DanB
