### ISSUE TITLE
cache not cleared properly after destinations import

### ISSUE THREAD

**Issue by bhepp** [cgrates/cgrates#381]
I have noticed that if I remove a destination prefix and then load the new destination definitions with `cgr-loader` some older cached version still remains active, even though `cgr-loader` seems to clear the cache.

Steps to reproduce (last tested yesterday with master):

1. Untar [csv.tar.gz](https://github.com/cgrates/cgrates/files/146620/csv.tar.gz) and do a `cgr-loader -verbose -flushdb`
2. Verify the known destinations with `cgr-console 'destination item="DST_100x"'`
3. Get the cost for the 1002 destination `cgr-console 'cost Direction="*out" Tenant="cgrates.org" Category="call" Account="test" Destination="1002" TimeStart="2016-02-24T00:00:00Z" TimeEnd="2016-02-24T00:00:10Z"'`
4. Edit `Destinations.csv`, remove the last line with the `1002` prefix and make a fresh import with `cgr-loader -verbose -flushdb`
5. Verify the new prefixes with `cgr-console 'destination item="DST_100x"'`. The 1002 prefix is no longer in the list.
6. Getting the cost for 1002 with `cgr-console 'cost Direction="*out" Tenant="cgrates.org" Category="call" Account="test" Destination="1002" TimeStart="2016-02-24T00:00:00Z" TimeEnd="2016-02-24T00:00:10Z"'` still works, even though the destination prefix was deleted.

Workaround: a forced cache reload with `cgr-console cache_reload` resolves the problem and the cost request results in `UNAUTHORIZED_DESTINATION`

**Comment by rif** [comment]
just tried to reproduce and I get UNAUTHORIZED_DESTINATION after the second load (no need to reload cache). I will write a test for it.

Meanwhile please try with the latest master and tell us if it's still not working without explicit cache reload for you.

**Comment by bhepp** [comment]
I cannot reproduce this any more. I am also getting UNAUTHORIZED_DESTINATION without having to  reload the cache.
