### ISSUE TITLE
CGRateS refuses to upgrade to websockets (403)

### ISSUE THREAD

**Issue by gedia** [cgrates/cgrates#3833]
Hello,

I'm running an instance of cgrates-0.11.0~dev+20221130195305+258492fcf for testing on debian bullseye, and I can't get it to upgrade a connection to use websockets.

Steps to reproduce:
1. Config:
```
    "http": {
        "auth_users": {},
        "freeswitch_cdrs_url": "/freeswitch_json",
        "http_cdrs": "/cdr_http",
        "json_rpc_url": "/jsonrpc",
        "registrars_url": "/registrar",
        "use_basic_auth": false,
        "ws_url": "/ws"
    },
    "listen": {
        "http": "172.28.159.149:2080",
        "http_tls": "127.0.0.1:2280",
        "rpc_gob": "127.0.0.1:2013",
        "rpc_gob_tls": "127.0.0.1:2023",
        "rpc_json": "127.0.0.1:2012",
        "rpc_json_tls": "127.0.0.1:2022"
    },
```
2. Try connecting:
```
curl ws://172.28.159.149:2080/ws
curl: (22) Refused WebSockets upgrade: 403
```
3. Packet capture:
```
    GET /ws HTTP/1.1
    Host: 172.28.159.149:2080
    User-Agent: curl/7.87.0
    Accept: */*
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Version: 13
    Sec-WebSocket-Key: UcJlRfcDKwiKuyXjdvm31Q==
    
    HTTP/1.1 403 Forbidden
```
/jsonrpc works fine. I also tried supplying the "Origin:" header having read it's a requirement with some implementations, but it didn't make a difference. Is this a configuration problem or a bug? Thanks!

BR,
George

**Comment by marcinkowalczyk** [comment]
Hi,
I've checked in ~5y old 0.9.x release and does not work there neither.

**Comment by gedia** [comment]
I can confirm this works with an appropriate Origin header value. The reason why it didn't work for me in the first place must have been that I provided an IP as Origin value, not a URL (i.e. Origin: X.X.X.X instead of Origin: ws://X.X.X.X)

I'm closing this for now, thanks!
