### ISSUE TITLE
Actions.csv - weight and expiration ignored

### ISSUE THREAD

**Issue by tomec-martin** [cgrates/cgrates#386]
Hi, we have following line in Actions.csv:
```
#ActionsId,Action,ExtraParameters,BalanceId,BalanceType,Directions,Categories,DestinationIds,RatingSubject,SharedGroup,ExpiryTime,TimingIds,Units,BalanceWeight,BalanceDisabled,Weight
add_4405_1_200,*topup,,1_03,*voice,*out,,121_Pevne_linky_TREE0;121P_Pevne_linky_TREE0;122_Mobilni_site_TREE0;122P_Mobilni_site_TREE0,,,2016-05-01,,12000,10,false,798309
```
After executing of this action, ballances are created, but the expiration is set to 0001-01-01 and weight is set to 10 (acording to output of ApierV2 GetAccounts). Expiration is probably in wrong format in csv file (I did not find any example), but with the weight it seems to be a bug.

**Comment by danbogos** [comment]
Hi Martin,

This issue should be resolved in current master code since there has 
been a complete redesign of the way we detect these things.

DanB
