### ISSUE TITLE
Balance value in CallCosts

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#392]
Today we only specify the balance uuid in CallCost information. It will be useful to provide also the balance value so the support can troubleshoot spends based on that.

Example of information in one increment:
``moneybalanceuuid" : "2e3b35ba-dcc6-4d57-98ff-5c5ea9f83200",``
should become:
``"monetary_balance": {"uuid": "2e3b35ba-dcc6-4d57-98ff-5c5ea9f83200", "value": 20.2},``

This should be valid also in case of CompressFactor != 1 where the Value should always represent the updated value at the end of compressing.

DanB

**Comment by rif** [comment]
Added Value and restructured Increment info. Now looking like this:

```json
"Increments": [
		    {
		     "Duration": 1000000000,
		     "Cost": 0,
		     "BalanceInfo": {
		      "Unit": {
		       "UUID": "69e3e961-cb94-4b52-b054-fc53bb30fc34",
		       "Value": 90,
		       "DestinationID": "0723",
		       "Consumed": 1,
		       "TOR": "*voice",
		       "RateInterval": null
		      },
		      "Monetary":  {
                       "UUID": "eb74495d-a63d-47bf-b523-5843f576c1bc",
		       "Value": 16.4,
                      },
		      "AccountID": "vdf:minu"
		     },
		     "CompressFactor": 10
		    }
		   ],
```
