### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#3926]
Dear Team,

I am using latest CGRateS master and I tried RALsV1.GetRatingPlansCost and I have faced an issue.

```
{
    "method": "RALsV1.GetRatingPlansCost",
    "params": [
        {
            "RatingPlanIDs": [
                "UUID1_CUS_VR_IN_20230409193808"
            ],
            "Destination": "+302107001398",
            "SetupTime": "2018-11-07T08:42:20Z",
            "Usage": "30s"
        }
    ],
    "id": 0
}
```

And I see this error : 

```
2023/04/10 09:03:26 CGRateS <master> [ERROR] Destination +302107001398 not authorized for account: voiceland.dev:RT_VOICELAND_OR, subject: *out:voiceland.dev:call-out:RT_VOICELAND_OR
panic: runtime error: makeslice: len out of range
goroutine 13058 [running]:
github.com/cgrates/cgrates/engine.(*TimeSpan).createIncrementsSlice(0xc000ce4a80)
	/usr/src/cgrates/engine/timespans.go:481 +0x12e
github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc000987630)
	/usr/src/cgrates/engine/calldesc.go:593 +0x50a
github.com/cgrates/cgrates/engine.(*CallDescriptor).GetCost(0xc000987630)
	/usr/src/cgrates/engine/calldesc.go:518 +0x59
github.com/cgrates/cgrates/apier/v1.(*RALsV1).GetRatingPlansCost(0x2?, 0xc002720cd0, 0xc0008a7d40)
	/usr/src/cgrates/apier/v1/rals.go:85 +0x5fb
reflect.Value.call({0xc0002fda40?, 0xc000a36e20?, 0x8?}, {0x1d11723, 0x4}, {0xc0028f7ef8, 0x3, 0xc002720be0?})
	/usr/local/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0xc0002fda40?, 0xc000a36e20?, 0x0?}, {0xc0028f7ef8?, 0xc00a26e911?, 0x459100?})
	/usr/local/go/src/reflect/value.go:368 +0xbc
net/rpc.(*service).call(0xc00086ff40, 0xc002720be0?, 0xc0004ccc18?, 0xc009fa1040, 0xc000ce8800, 0xc002720be0?, {0x1975460?, 0xc002720cd0?, 0x6f8ce6?}, {0x1973060, ...}, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x226
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:479 +0x3fe
```

thank you in advance for your support.

Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear @gezimbll,

Thank you for your reply.
Here is the configuration --> [](https://pastebin.com/Ln4untcZ)
Unfortunately we only use apier to load our tarrifplans.

Regarding the panic error even if we have an error in our configuration, the apier service should reply something like that : 
```
{
    "id": 1,
    "result": [],
    "error": null
}
```

thank you in advance for your support.
Best Regards

Vasilios Tzanoudakis

**Comment by gezimbll** [comment]
Hi @vtzan , 

Please in  order to accurately reproduce, maybe best is  to send us an SQL export which we can use to test on our side.

Kind Regards,
Gezim

**Comment by vtzan** [comment]
Dear @gezimbll,

I have shared privately to @danbogos the mongodb dump. I hope this will help you.

Thank you in advance for your time on this case.

Best Regards

Vasilios Tzanoudakis

**Comment by gezimbll** [comment]
Hi @vtzan ,

The problem seems to come from the rate associated with the destination not having a rate slot for the first second interval.
To resolve this issue, please ensure that the rate ""UUID1_CUS_VR_IN_+302107001398""  contains a rate slot with "GroupIntervalStart" to "0s".

Best Regards,
Gezim

**Comment by vtzan** [comment]
Dear @gezimbll,

Thank you very much for your support on this.  You were right. TP Rate didn't had  a rate slot with GroupIntervalStart didn't had "0s". So I fixed that and now its working great!.

Although this was a configuration issue from my side I still believe CGRateS shouldn't crash and return something like "not found" or empty array [] but that's just my opinion off course.

I will close that issue and thank you once again for your fast response on this case.

Best Regards
Vasilios Tzanoudakis
