### ISSUE TITLE
cgr-loader MONGO/MONGO (100k csv) - PARTIALLY_EXECUTED

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#3935]
Hi Teams,

```
cgr-loader -version
CGRateS@v0.11.0~dev-20230306160112-b1b964710454
```

Csv is actualy 100K destinations.
cgr-loader final result : 
```
PARTIALLY_EXECUTED
```

I notice if csv contains more 8k/12k destinations mongo's logs tells this : 

```
... "c":"WRITE",    "id":51803,   "ctx":"conn447","msg":"Slow query","attr":{"type":"remove","ns":"cgrates2.tp_destination_rates" ...
```

I did try to verify if custom mongo settings could help :

```
db.runCommand({profile: 0, slowms: 1000000})
```

Unfortunately, after 13K destinations, new mongo logs:

```
"Interrupted operation as its client disconnected"
"Connection ended"
```

**Comment by arberkatellari** [comment]
Hello,

We checked briefly to see if this issue normally occurs and found no problems on our end. Also, we have other customers that use MongoDB in production and have no known performance issues there. To reproduce your issue on our side, can you please send us your sample test data here or in private?
Thanks!

Best regards,
Arber

**Comment by Integration-IT** [comment]
Hi Arber,

I did change the suite version to restart from a good starting point, the project is compiled from the repo.

```
cgr-console -version
CGRateS@v0.10.3~dev
...
go version
go version go1.20.3 linux/amd64
```

I did change some extra param in the cgrates configuration file for both data_db and stor_db with "mongoQueryTimeout":"600s".
I did change some extra param like "connect_timeout": "300s" and "reply_timeout": "300s".

Same trouble :

```
2023/04/25 22:13:57 Processing file: <AccountActions.csv> 
2023/04/25 22:13:57 Processing file: <ActionPlans.csv> 
2023/04/25 22:13:57 Processing file: <ActionTriggers.csv> 
2023/04/25 22:13:57 Processing file: <Actions.csv> 
2023/04/25 22:13:57 Processing file: <Attributes.csv> 
2023/04/25 22:13:57 Processing file: <Chargers.csv> 
2023/04/25 22:13:57 Processing file: <DestinationRates.csv> 
2023/04/25 22:14:08 Processing file: <Destinations.csv> 
2023/04/25 22:14:19 Processing file: <Filters.csv> 
2023/04/25 22:14:19 Processing file: <Rates.csv> 
2023/04/25 22:14:30 Processing file: <RatingPlans.csv> 
2023/04/25 22:14:32 Processing file: <RatingProfiles.csv> 
2023/04/25 22:14:32 Processing file: <Thresholds.csv> 
2023/04/25 22:14:32 Processing file: <Timings.csv> 
2023/04/25 22:14:32 PARTIALLY_EXECUTED
```

Over 100K destinations, only 12.9K are in the tp_destinations collection.
Over 100k rates, only 3.1K are in the tp_rates collection.

To avoid 'sample test data' misconfiguration I did change the backends to MYSQL/REDIS.

 - cgr-loader : RESULT OK.
 - cgr-console load_tp_from_stordb : RESULT OK.

I can't replicate MONGO/MONGO troubles with MYSQL/REDIS setup.

if you look closely at the clocks, 11 seconds repeat between large files for which datas are partially available!

Weird Mongo driver can't keep the connexion open during loading stage to send an "Interrupted operation as its client disconnected" in mongo's log.
