### ISSUE TITLE
Prefix matching for rating subject in LcrRules

### ISSUE THREAD

**Issue by andmar** [cgrates/cgrates#394]
Following the discussion in #388 here is a feature request for "Prefix matching for rating subject" in the LcrRules, similar to how it's already being done for RatingProfiles when the new config option "rp_subject_prefix_matching" is set to true on the rater configs.

**Comment by andmar** [comment]
Great. @rif can you guys generate a temp package with this?

**Comment by rif** [comment]
already done http://www.cgrates.org/tmp_pkg/

**Comment by andmar** [comment]
Thanks. :)
