### ISSUE TITLE
[SOLVED] APIerSv1.GetCost CRASH

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#3953]
Hi teams,

If the rate is accidentally misconfigured, it is possible to crash the cgrates engine.

If you declare an ID with a "GroupIntervalStart" at 60s, forgetting to declare before that of 0s.
A section is missing, the system has no instruction to proceed with the calculation from 0 to 60s.

To reproduce : just follow [Rates.csv](https://github.com/cgrates/cgrates/blob/master/data/tariffplans/tutorial/Rates.csv) and remove line 2, then call a GetCost.

Effect : Instant crash

```syslog
cgr-engine[24675]: panic: runtime error: makeslice: len out of range
cgr-engine[24675]: goroutine 784 [running]:
cgr-engine[24675]: github.com/cgrates/cgrates/engine.(*TimeSpan).createIncrementsSlice(0xc00019e0c0)
cgr-engine[24675]: #011/usr/src/cgrates/engine/timespans.go:481 +0x12e
cgr-engine[24675]: github.com/cgrates/cgrates/engine.(*CallDescriptor).getCost(0xc00047a140)
cgr-engine[24675]: #011/usr/src/cgrates/engine/calldesc.go:593 +0x4ff
cgr-engine[24675]: github.com/cgrates/cgrates/engine.(*CallDescriptor).GetCost(0xc00047a140)
cgr-engine[24675]: #011/usr/src/cgrates/engine/calldesc.go:518 +0x59
cgr-engine[24675]: github.com/cgrates/cgrates/engine.(*Responder).GetCost.func1()
cgr-engine[24675]: #011/usr/src/cgrates/engine/responder.go:103 +0x32
cgr-engine[24675]: github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard.func1()
cgr-engine[24675]: #011/usr/src/cgrates/guardian/guardian.go:150 +0x29
cgr-engine[24675]: created by github.com/cgrates/cgrates/guardian.(*GuardianLocker).Guard
cgr-engine[24675]: #011/usr/src/cgrates/guardian/guardian.go:149 +0x12a
```

```
* master - v0.9.1rc7-9426-g7a0ff57a3
CGRateS@v0.11.0~dev
```

**Comment by arberkatellari** [comment]
Hi @Integration-IT ,

This issue is fixed in the latest commit. Be sure to update and see if you still have the issue. Thanks for the catch!

Best regards,
Arber

**Comment by Integration-IT** [comment]
Hi @arberkatellari ,

The update can deal with this case.
Syslog warn and the system can't panic any more.

```
error: <UNCOMPUTABLE_INCREMENT with -60000000000>, when creating increments slice ...
```

Your patch detects the anomaly and compensates the first 60 seconds to avoid a panic and a good return from the API.
Thank you.
