### ISSUE TITLE
cgr-engine using 100% cpu when rating calls starting in OFFPEAK and ending in PEAK

### ISSUE THREAD

**Issue by hansgoos** [cgrates/cgrates#397]
Hi,

Running cgrates_0.9.1~rc8_amd64 using the tutorial TP (/usr/share/cgrates/tariffplans/tutorial/) i'm not able to rate calls going from OFFPEAK_WEEKEND to PEAK. For example:

cgr-console 'cost Category="call" Tenant="cgrates.org" Destination="1002" TimeStart="2016-03-13T22:24:38Z" TimeEnd="2016-03-14T07:59:59Z"'

Is working

cgr-console 'cost Category="call" Tenant="cgrates.org" Destination="1002" TimeStart="2016-03-13T22:24:38Z" TimeEnd="2016-03-14T08:59:59Z"'

Is not working. This last cost calculation results in no output, and the cgr-engine taking up 100% cpu.

Regards
Hans

**Comment by rif** [comment]
Hi Hans,

I just tested with the latest master and both costs are returned OK. As you are using a pre-release please reinstall with the latest version online and report id the issue still occurs.

Also please describe if there is any other modification on the original data.

**Comment by hansgoos** [comment]
Hello,

Thanks for your feedback. I also did the tests using CGRateS 0.9.1~rc7 (which is the latest master I suppose). Installed it using the .deb package: cgrates_0.9.1~rc7_amd64.deb

root@dev1:~# cgr-console --version
CGRateS 0.9.1~rc7

Imported the TP
cgr-loader -flushdb -verbose -path=/usr/share/cgrates/tariffplans/tutorial/

and run both cost simulations. The first one is successful, the other not.

One side note, i'm running cgrates on Ubuntu not on debian.

Regards
Hans

**Comment by hansgoos** [comment]
Hello,

Just did a fresh install of debian (8.3) and installed cgrates (+redis-server +mysql-server) using the instructions on: http://cgrates.readthedocs.org/en/latest/installation.html#using-packages

root@debian:/usr/share/cgrates/storage/mysql# cgr-engine -version
CGRateS 0.9.1~rc7

Enabled the rater in the configuration file:

"rater": {
        "enabled": true,
},

and loaded the tutorial TP, but still I get the same behavior.

Regards
Hans

**Comment by danbogos** [comment]
Hi @hansgoos,

I have also tested just now on the code on master but without any issue.

Bellow are the commands I have executed. Can you maybe try them in the order I have posted them and let me know if you get different results? 
For the sake of simplicity, I have also generated a fresh debian package for you here:
http://www.cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb

Please report back your results.

Ta,
DanB

``
pkill cgr-engine
redis-cli -n 10 flushdb
redis-cli -n 11 flushdb
cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutlocal/ &
cgr-loader -verbose -path=/usr/share/cgrates/tariffplans/tutorial
cgr-console 'cost Category="call" Tenant="cgrates.org" Destination="1002" TimeStart="2016-03-13T22:24:38Z" TimeEnd="2016-03-14T08:59:59Z"'
{
 "Direction": "*out",
 "Category": "call",
 "Tenant": "cgrates.org",
 "Subject": "",
 "Account": "",
 "Destination": "1002",
 "TOR": "*voice",
 "Cost": 40.9023,
 "Timespans": [
  {
   "TimeStart": "2016-03-13T22:24:38Z",
   "TimeEnd": "2016-03-13T22:25:38Z",
   "Cost": 0.1,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [
      6,
      0
     ],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0.2,
     "RoundingMethod": "*up",
     "RoundingDecimals": 4,
     "MaxCost": 0,
     "MaxCostStrategy": "",
     "Rates": [
      {
       "GroupIntervalStart": 0,
       "Value": 0.1,
       "RateIncrement": 60000000000,
       "RateUnit": 60000000000
      },
      {
       "GroupIntervalStart": 60000000000,
       "Value": 0.05,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 60000000000,
   "Increments": [
    {
     "Duration": 60000000000,
     "Cost": 0.1,
     "BalanceInfo": {
      "Unit": null,
      "Monetary": null,
      "AccountID": ""
     },
     "CompressFactor": 1
    }
   ],
   "RoundIncrement": null,
   "MatchedSubject": "*out:cgrates.org:call:*any",
   "MatchedPrefix": "10",
   "MatchedDestId": "DST_FS",
   "RatingPlanId": "RP_RETAIL1",
   "CompressFactor": 1
  },
  {
   "TimeStart": "2016-03-13T22:25:38Z",
   "TimeEnd": "2016-03-14T00:00:00Z",
   "Cost": 4.69946,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [
      6,
      0
     ],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0.2,
     "RoundingMethod": "*up",
     "RoundingDecimals": 4,
     "MaxCost": 0,
     "MaxCostStrategy": "",
     "Rates": [
      {
       "GroupIntervalStart": 0,
       "Value": 0.1,
       "RateIncrement": 60000000000,
       "RateUnit": 60000000000
      },
      {
       "GroupIntervalStart": 60000000000,
       "Value": 0.05,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 5722000000000,
   "Increments": [
    {
     "Duration": 1000000000,
     "Cost": 0.00083,
     "BalanceInfo": {
      "Unit": null,
      "Monetary": null,
      "AccountID": ""
     },
     "CompressFactor": 5662
    }
   ],
   "RoundIncrement": null,
   "MatchedSubject": "*out:cgrates.org:call:*any",
   "MatchedPrefix": "10",
   "MatchedDestId": "DST_FS",
   "RatingPlanId": "RP_RETAIL1",
   "CompressFactor": 1
  },
  {
   "TimeStart": "2016-03-14T00:00:00Z",
   "TimeEnd": "2016-03-14T08:00:00Z",
   "Cost": 23.904,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [
      1,
      2,
      3,
      4,
      5
     ],
     "StartTime": "00:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0.2,
     "RoundingMethod": "*up",
     "RoundingDecimals": 4,
     "MaxCost": 0,
     "MaxCostStrategy": "",
     "Rates": [
      {
       "GroupIntervalStart": 0,
       "Value": 0.1,
       "RateIncrement": 60000000000,
       "RateUnit": 60000000000
      },
      {
       "GroupIntervalStart": 60000000000,
       "Value": 0.05,
       "RateIncrement": 1000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 34522000000000,
   "Increments": [
    {
     "Duration": 1000000000,
     "Cost": 0.00083,
     "BalanceInfo": {
      "Unit": null,
      "Monetary": null,
      "AccountID": ""
     },
     "CompressFactor": 28800
    }
   ],
   "RoundIncrement": null,
   "MatchedSubject": "*out:cgrates.org:call:*any",
   "MatchedPrefix": "10",
   "MatchedDestId": "DST_FS",
   "RatingPlanId": "RP_RETAIL1",
   "CompressFactor": 1
  },
  {
   "TimeStart": "2016-03-14T08:00:00Z",
   "TimeEnd": "2016-03-14T09:00:00Z",
   "Cost": 11.9988,
   "RateInterval": {
    "Timing": {
     "Years": [],
     "Months": [],
     "MonthDays": [],
     "WeekDays": [
      1,
      2,
      3,
      4,
      5
     ],
     "StartTime": "08:00:00",
     "EndTime": ""
    },
    "Rating": {
     "ConnectFee": 0.8,
     "RoundingMethod": "*up",
     "RoundingDecimals": 4,
     "MaxCost": 0,
     "MaxCostStrategy": "",
     "Rates": [
      {
       "GroupIntervalStart": 0,
       "Value": 0.4,
       "RateIncrement": 30000000000,
       "RateUnit": 60000000000
      },
      {
       "GroupIntervalStart": 60000000000,
       "Value": 0.2,
       "RateIncrement": 10000000000,
       "RateUnit": 60000000000
      }
     ]
    },
    "Weight": 10
   },
   "DurationIndex": 38122000000000,
   "Increments": [
    {
     "Duration": 10000000000,
     "Cost": 0.03333,
     "BalanceInfo": {
      "Unit": null,
      "Monetary": null,
      "AccountID": ""
     },
     "CompressFactor": 360
    }
   ],
   "RoundIncrement": null,
   "MatchedSubject": "*out:cgrates.org:call:*any",
   "MatchedPrefix": "10",
   "MatchedDestId": "DST_FS",
   "RatingPlanId": "RP_RETAIL1",
   "CompressFactor": 1
  }
 ],
 "RatedUsage": 38122
}
``

**Comment by hansgoos** [comment]
Hello Dan,

Unfortunately same result. In the end the cgr-engine process takes all the memory and get killed. I'm not testing with a fresh installed debian 8.3 in virtual box. Attached all the logging.

[cgrates_output.txt](https://github.com/cgrates/cgrates/files/179245/cgrates_output.txt)
 
Regards
Hans

**Comment by cgrates** [comment]
Hi Hans,

Interesting part is why we cannot reproduce it.

What is your configured timezone on the server? You are running on amd64 
architecture right?

Thanks,
DanB

**Comment by hansgoos** [comment]
Not sure if it helps, but I was trying to install cgrates from source (which failed), but now when I start the cost simulation I get a lot more debug output (see attachement)

Regards
Hans
[cgrates_output2.txt](https://github.com/cgrates/cgrates/files/179285/cgrates_output2.txt)

**Comment by rif** [comment]
Can you confirm that your time and timezone are correct on the server and you are running amd64 architecture? Just for info: how much memory do you have free before running the cgr-engine?

**Comment by hansgoos** [comment]
root@debian:/home/support# uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

root@debian:/home/support# timedatectl
      Local time: Fri 2016-03-18 13:28:17 CET
  Universal time: Fri 2016-03-18 12:28:17 UTC
        RTC time: Fri 2016-03-18 12:28:17
       Time zone: Europe/Amsterdam (CET, +0100)
     NTP enabled: no
NTP synchronized: no
 RTC in local TZ: no
      DST active: no
 Last DST change: DST ended at
                  Sun 2015-10-25 02:59:59 CEST
                  Sun 2015-10-25 02:00:00 CET
 Next DST change: DST begins (the clock jumps one hour forward) at
                  Sun 2016-03-27 01:59:59 CET
                  Sun 2016-03-27 03:00:00 CEST

Before CGR-ENIGE is running
root@debian:/home/support# cat /proc/meminfo
MemTotal:        2058636 kB
MemFree:         1891392 kB
MemAvailable:    1878624 kB
Buffers:            7652 kB
Cached:            75896 kB
SwapCached:            0 kB

**Comment by danbogos** [comment]
Hi Hans,

Would it be possible for us to get remote access into your virtual 
machine? We could still not reproduce your issue on ours.

Ta,
DanB

**Comment by hansgoos** [comment]
Hi Dan,

This VM was running local on my laptop, but i installed a fresh debian 8.3 in VMware (where I encounter the same problem) to which I can give you access. Please send me your IP address.

Regards
Hans

**Comment by rif** [comment]
We'll use 144.76.13.69. If you want to examine it together we can do a tmux session. 
Just ping me on irc or email tomorrow with the details.

-rif

**Comment by rif** [comment]
We identified the problem: there is a glitch in the package building process that does not update the cgrates for the tmp packages. Working to fix the tmp package building process.

**Comment by rif** [comment]
We fixed the package generation glitch and now the tmp packages should be up to date with the latest master.

@hansgoos please test with the latest package and close the issue if the problem is gone.

**Comment by hansgoos** [comment]
Did some testing with the latest tmp packages and everything is working now.

Thanks for your help !
-Hans
