### ISSUE TITLE
[SOLVED] APIerSv1.ExportTPToFolder MISSING OBJECTS

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#3970]
Hi Teams,

This API call exports TP to a folder as unitary csv, but some id are missing.
+1 is ok in project path due to header line.

In /tmp the export path.
In /etc/cgrates the project path.

```bash
wc /tmp/Destinations.csv /etc/cgrates/Destinations.csv 
      1       1      52 /tmp/Destinations.csv
  xxxxxx   xxxxxx xxxxxxx /etc/cgrates/Destinations.csv
```

**Comment by gezimbll** [comment]
Hi @Integration-IT ,

Please update in the latest commit   cause we added a possible fix for this issue.

Best regards,
Gezim

**Comment by Integration-IT** [comment]
Hi @gezimbll,

The patch is working very fine. Thank you for the fix.
