### ISSUE TITLE
CGrates crashing (Package 15th Dec 2015)

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#398]
Hi Guys,
I had a customer on the Dec 15 package that had a crash today, I am aware we are 2 packages behind but I just wanted you to take a look at the Strace to see if the issue was resolved already or not.

https://www.dropbox.com/s/40m168msjir5hap/cgrates.strace?dl=0
Regards,

Errol

**Comment by cgrates** [comment]
Hi @ewsamuels 

You need to increase the number of connections to postgres since this is not officially a bug but a feature (coming from gorm developer ;) ).

DanB

**Comment by ewsamuels** [comment]
Here is the current config for Postgres:
# Add settings for extensions here
# Added by Errol on 9th March

max_connections = 750
shared_buffers = 2560MB
effective_cache_size = 7680MB
work_mem = 1747kB
maintenance_work_mem = 640MB
checkpoint_segments = 32
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100

I will up to 1500 connections and see what happens then.

Regards,

Errol
