### ISSUE TITLE
ActionTriggers Session based / Time based

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#3987]
Hello,

ActionTriggers is a very powerful tool for automatic mitigation.

Please find a sample:
```
CUSTOMER_TRIGGERS,,*min_balance,1,false,300s,,,,*monetary,,,,,,,,,false,ACTION_DISABLE_ACCOUNT,10
```

what is exactly MinSleep set to 300s ?
If trigger match, the action is executed after 300 seconds ?
Or maybe.
If trigger match, execute action ACTION_DISABLE_ACCOUNT, can not execute again if match again during the next 300 secondes ?
Or maybe.
Call this ActionTriggers test every 300s and If trigger match, then execute action ACTION_DISABLE_ACCOUNT ?

In my case, this action trigger check, set to 300s, is called after every end of session and cost lot of data_db trafic in real time. MinSleep has no effect within lot of sessions in less than 300 secondes (balance > 1).

I am trying to understand how to reduce this load part for large CPS and massive data_db exchanges.
Any configuration part to call a trigger test one time per minutes like a "cron job" and not only based at the "end of a session" ?

**Comment by arberkatellari** [comment]
Hello @Integration-IT ,

MinSleep in this case is the amount of delay to be applied in between executions, so your second guess is the right one. This is also explained altogether with ActionTrigger in [ReadTheDocs](https://cgrates.readthedocs.io/en/latest/rals.html?highlight=minsleep#actiontrigger) . If you have any other questions for it, feel free to ask!

P.S. Its better for us if you ask questions like this on our [google groups](https://groups.google.com/forum/#!forum/cgrates) and leave github issues for issues. This way, our community can benifit from our support.

Thanks,
Arber!

**Comment by Integration-IT** [comment]
Thank you @arberkatellari
