### ISSUE TITLE
*max_balance_counter missbehaves

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#399]
Having the following line in ActionTriggers.csv:
``STANDARD_TRIGGERS,daily_spend,*max_balance_counter,1,true,24h,,,,,,,,,,,,,,,,DISABLE_AND_LOG,10``

Would expect to have balance counter modified during/after the call but it does not happen. At the end of the call I have the following account data:
``
root@CgrDev1:/usr/local/goapps/src/github.com/cgrates/cgr_errol_1# cgr-console 'accounts Tenant="cgrates.org" AccountIds=["1001"]'
[
 {
  "ID": "cgrates.org:1001",
  "BalanceMap": {
   "*monetary": [
    {
     "Uuid": "13c24458-afd6-49b2-917e-7e57dbb94ae0",
     "ID": "",
     "Value": 4,
     "Directions": {
      "*out": true
     },
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 20,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    },
    {
     "Uuid": "fb7cecfd-c12a-409f-af7f-a55c69dd20b3",
     "ID": "",
     "Value": 5,
     "Directions": {
      "*out": true
     },
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 10,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {
      "SHARED_A": true
     },
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ],
   "*voice": [
    {
     "Uuid": "d173043b-3d03-43a9-aadd-d0f4b2e5f4d6",
     "ID": "",
     "Value": 120,
     "Directions": {
      "*out": true
     },
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 20,
     "DestinationIDs": {
      "DST_1003": true
     },
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    },
    {
     "Uuid": "d13f2755-c0f5-4179-98bb-03985fd59e01",
     "ID": "",
     "Value": 90,
     "Directions": {
      "*out": true
     },
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 20,
     "DestinationIDs": {
      "DST_1002": true
     },
     "RatingSubject": "SPECIAL_1002",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ]
  },
  "UnitCounters": {
   "": [
    {
     "CounterType": "*balance",
     "Counters": [
      {
       "Value": 0,
       "Filter": {
        "Uuid": null,
        "ID": "daily_spend",
        "Type": null,
        "Value": null,
        "Directions": null,
        "ExpirationDate": null,
        "Weight": null,
        "DestinationIDs": null,
        "RatingSubject": null,
        "Categories": null,
        "SharedGroups": null,
        "TimingIDs": null,
        "Timings": null,
        "Disabled": null,
        "Factor": null,
        "Blocker": null
       }
      }
     ]
    }
   ]
  },
  "ActionTriggers": [
   {
    "ID": "STANDARD_TRIGGERS",
    "UniqueID": "daily_spend",
    "ThresholdType": "*max_balance_counter",
    "ThresholdValue": 1,
    "Recurrent": true,
    "MinSleep": 86400000000000,
    "ExpirationDate": "0001-01-01T00:00:00Z",
    "ActivationDate": "0001-01-01T00:00:00Z",
    "Balance": {
     "Uuid": null,
     "ID": "daily_spend",
     "Type": null,
     "Value": null,
     "Directions": null,
     "ExpirationDate": null,
     "Weight": null,
     "DestinationIDs": null,
     "RatingSubject": null,
     "Categories": null,
     "SharedGroups": null,
     "TimingIDs": null,
     "Timings": null,
     "Disabled": null,
     "Factor": null,
     "Blocker": null
    },
    "Weight": 10,
    "ActionsID": "DISABLE_AND_LOG",
    "MinQueuedItems": 0,
    "Executed": false
   }
  ],
  "AllowNegative": false,
  "Disabled": false
 }
]
``

DanB

**Comment by rif** [comment]
BalanceType was missing
