### ISSUE TITLE
Performance discussion regarding Importing into tp tables

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#40]
Hi Dan,

I have been for the past few days doing some investigation and research to find ways to improve the performance of getting my data into cgrates tp_* tables and thought I would share my finds with you.

As I been mentioning to you on IRC etc I been getting slow performance and as you suggested I took some timing importing my destinations in cgrates as follows:

Here this test imports the 3 csv files using the cgr-loader and most of the test I did it took anywhere from 12 mins to just over 13 mins to load the Destinations.csv file.

> root@demo:~# cgr-loader -flushdb -verbose -to_stordb -tpid="USA_172K" -stordb_type="postgres" -stordb_port=5432 -path=/usr/share/demo/tariffplans/
> 2015/02/05 05:16:33 Processing file: <DestinationRates.csv>
> 2015/02/05 05:16:33 Ignoring line 1, warning: <Line starts with comment character.>
> 2015/02/05 05:24:35 Processing file: <Destinations.csv>
> 2015/02/05 05:24:35 Ignoring line 1, warning: <Line starts with comment character.>
> 2015/02/05 05:37:36 Processing file: <Rates.csv>
> 2015/02/05 05:37:36 Ignoring line 1, warning: <Line starts with comment character.>
> Thu Feb  5 05:46:21 CST 2015

> DestinationRates — 8 mins 2 secs
> Destinations     - 13 mins 1 secs
> Rates            - 8 mins 45 secs

I actually did another test on a Dedicated box with 32G and SSD HardDrives and the same took over 40 mins to complete.  Now sure what that is about...So performance was better on my VMs.

So I decided to do some research about doing large inserts in Postgres and found that the COPY command was highly recommended so I created another file called COPY_Destinations.csv and did the import using this command.

> cgrates=# COPY tp_destinations FROM '/usr/share/cgrtbilling/tariffplans/COPY_Destinations.csv' DELIMITER ',' CSV HEADER;
> COPY 171578
This took a mere 10 secs to import the 171578 destinations.

Here are the links to the files I used
Maybe it would be a good idea to have an API that uses COPY to import csv files to the tp_ tables.

What do you think?

regards,
Errol

**Comment by danbogos** [comment]
Hey Errol,

Thank you for your time for this.

If you want to get faster performance on your tariff plan files you can use the following API call:
https://github.com/cgrates/cgrates/blob/master/apier/v1/tp.go#L54

Before calling the API you should zip the folder containing the tariff plan and attach it's content as base64String.

Hope this helps,
DanB

**Comment by ewsamuels** [comment]
Thanks DanB, I think this would be a better solution and I can combine it with some of the APIs.
