### ISSUE TITLE
Action *reset_counter

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#400]
Today we only have *reset_counters which is not handy when we like to reset a specific one (eg: per id).

DanB

**Comment by danbogos** [comment]
Since I see that *reset_counters are having filter abilities, we need to extend that functionality to be able to pass the counter_id in the filter.

DanB

**Comment by rif** [comment]
By using BalanceID column as counterID when defining a *reset_counters action we can achieve reseting the counter by id with the current code
