### ISSUE TITLE
[SOLVED] [ees] *els - Elasticsearch Missing Header

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4002]
Hi Teams,

Since [0666ec9](https://github.com/cgrates/cgrates/commit/0666ec9082efe26da553138fc9d1c7084cc8d267), the new destination pool is very a good feature. Thank you for the PR.

If you inspect the PUT action performed by "Go-http-client", you could find some useful headers are missing.
Tenant is missing in *els exporter, no timestamp too.

- 1
Tenant field is not in the body.
The tag declaration in my config file is similar to the sample, but the header is not forwarded.
  ```
  {"tag": "Tenant", "path": "*exp.Tenant", "type": "*variable", "value": "~*req.Tenant"},
  ```

- 2
  ```@timestamp``` is missing in the *els, it means, all indexed documents have blank timestamp.
 Probably add this tag in config could help.
  ```
  {"tag": "@timestamp", "path": "*exp.@timestamp", "type": "*datetime", "value": "~*req.SetupTime"},
  ````

- 3
  ```@timestamp``` is missing in the *els, it means, all indexed documents have blank timestamp.
 Probably add the UTC timestamp in "Go-http-client" code side could be a default option, the intended format is ISO 8601.

- 4
_To deal with lot of CDR, a good path is to manage the "rolling lifecycle".
Actually the "elsIndex" option is static and can't use an index that include the dyn date format like "monitoring-es-7-2023.06.16" or "monitoring-kibana-7-2023.06.16".
Cgrates is ready with some [constantes](https://github.com/cgrates/cgrates/blob/master/utils/consts.go) like YearsFieldName,MonthsFieldName,MonthDaysFieldName,WeekDaysFieldName but i was not able to use them in config file._

Update : *4 is out of scope, managed via elsPipeline and ELK pipeline processor.

ex:
```
"elsIndex" : "cdrs-engine-YYYY.MM.DD"
"elsIndex" : "cdrs-engine-$YearsFieldName.$MonthsFieldName.$MonthDaysFieldName"
```

This feature is not totally clear, i don't know if it is a one hand API call for elastic or if it is an implicit entry point for logstash agent forwarder.

**Comment by gezimbll** [comment]
Hi @Integration-IT  ,

With the latest  commit  changes now we can include tenant by defining a template like 
`
{"tag": "Tenant", "path": "*exp.Tenant", "type": "*variable", "value": "~*vars.*tenant"}
`.
Also we added a new template for having `@timestamp` field in els   by including 
`
{"tag": "@timestamp", "path": "*exp.@timestamp", "type": "*datetime", "value": "*now"}.
`
About adding a dynamic  option for elsIndex ,that feature isn't available for now ,if you need to get it implemented from our side  please open an issue so we can look up to it . 

Best Regards,
Gezim

**Comment by Integration-IT** [comment]
Hi @gezimbll.

The tenant tag and timestamp template are working fine, thank you.
About dyn index, it is solved in ELK side by using date index name processor pipeline.

For more info : [Date index name processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-index-name-processor.html)
