### ISSUE TITLE
Unexpected type: float64

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#401]
Hi Guys,

We are doing DB Replication rather than storing CDRs in StorDB.
It appears when a call is made cgrates is generating approx. 200 to 300 lines of errors.
They are all the same:
 
Mar 16 07:46:04 bill CGRateS[2414]: Unexpected type: float64
Mar 16 07:46:04 bill CGRateS[2414]: Unexpected type: float64
Mar 16 07:46:04 bill CGRateS[2414]: Unexpected type: float64
Mar 16 07:46:04 bill CGRateS[2414]: Unexpected type: float64
 
There are Megabytes of these errors in syslog and gigabytes in message and kern.log over last 3 days.

We are using the CGRateS package dated 20th Jan 2016.

Any ideas?

**Comment by danbogos** [comment]
Hi Errol,

Please upgrade to the latest master since we have changed the table 
structure and the issue could be solved already.

Ta,
DanB

**Comment by ewsamuels** [comment]
Hi DanB,

I updated to the package dated 14th March and we are still getting 270 rows of "Unexpected type: float64" in the logs at the end of every call.

root@bill:/var/www/venv# ls -l /usr/bin | grep cgr
-rwxr-xr-x 1 root     root    13925696 Mar 14 19:52 cgr-console
-rwxr-xr-x 1 root     root    18254976 Mar 14 19:52 cgr-engine
-rwxr-xr-x 1 root     root    15162944 Mar 14 19:52 cgr-loader
-rwxr-xr-x 1 root     root    14224928 Mar 14 19:52 cgr-tester

There is nothing showing in the cgrates.strace.

Regards,

Errol

**Comment by cgrates** [comment]
Hi Errol,

If possible please capture the communication with postgres, maybe we 
have some wrong data defined.
A good idea would be to isolate the issue for a single call (so we have 
less logs).

Thanks,
DanB

**Comment by ewsamuels** [comment]
Hi DanB,

I didn't see anything usual in the pgsql logs.   

However, I see the issue occurring on two systems so far and both running Debian Jessie 8.3.  
One has the package 20th Jan and the other March 14th which was upgraded from the Jan 20th package.

I tried to replicate the issue on a system running Wheezy by testing Dec 15th, Jan 20th and Mar 14th package but was unable to replicate the issue.

Tomorrow I will try to replicate on another Wheezy install.

Regards,
Errol

**Comment by ewsamuels** [comment]
Hi DanB,

So far I have tested on 3 systems running Debian Jessie 8.3 and they all have this error.
I tested also 3 systems running Debian Wheezy 7.x and none of them have this error.

I think a pattern is emerging so hopefully it would bring us closer to resolving this.

Regards,

Errol

**Comment by ewsamuels** [comment]
I noticed is that All the Debian 8.3 systems have Redis-Server 2:2.8.17-1+deb8u3. 
The systems running Wheezy have 2:2.4.14-1

I decided to upgrade one of the systems that was running Debian Wheezy 7.9 to Debian Jessie 8.3
The system already had the Mar 14th package and no issue with "Unexpected type: float64".

Fri Mar 18 14:25:44 UTC 2016
root@usdemo:~# cat /etc/debian_version
7.9
root@usdemo:~# ls -l /usr/bin | grep cgr
-rwxr-xr-x 1 root   root    13925696 Mar 14 08:52 cgr-console
-rwxr-xr-x 1 root   root    18254976 Mar 14 08:52 cgr-engine
-rwxr-xr-x 1 root   root    15162944 Mar 14 08:52 cgr-loader
-rwxr-xr-x 1 root   root    14224928 Mar 14 08:52 cgr-tester

**After Upgrade to Debian 8.3**
I tested and there is no issue.  I even uninstalled CGRateS and Reinstalled again and still no issue.
So it appears this problem is occurring only on machines with a clean install of Debian 8.3.

**Comment by ewsamuels** [comment]
Hi DanB,

We updated to the 22nd Mar package and we are still seeing the "Unexpected type: float64" error in the logs.

root@bill:~# ls -l /usr/bin | grep cgr
-rwxr-xr-x 1 root     root    14290592 Mar 22 23:33 cgr-console
-rwxr-xr-x 1 root     root    18603136 Mar 22 23:33 cgr-engine
-rwxr-xr-x 1 root     root    15453760 Mar 22 23:33 cgr-loader
-rwxr-xr-x 1 root     root    14482976 Mar 22 23:33 cgr-tester

Regards,

Errol

**Comment by MarcVoIP** [comment]
Just came across this issue after enabling "cdrs replication". This error must be related to this functionality as I have never seen it before.
As far as I know @ewsamuels uses replication so his systems are affected with this issue.

OS:  Debian 8.3

**Comment by danbogos** [comment]
Hi @ewsamuels, can u please attach here your configuration for replication? Trying to reproduce your issue locally.

DanB

**Comment by danbogos** [comment]
@ewsamuels @MarcVoIP 

Tried myself doing replication but without much luck reproducing the error. For me it works.

Can you maybe isolate the process and detect which of the two (SM or rater) is producing this?

Thanks,
DanB

**Comment by ewsamuels** [comment]
Hi DanB,
For starters I only see the error on a clean install of Debian Jessie.  Systems running Wheezy or Wheezy upgraded to Debian Jessie are fine.

"cdrs": {
        "enabled": true,                                                // start the CDR Server service:  <true|false>
        "extra_fields": ["call_uuid","direction","sip_h_X-custom","sip_h_X-site","sip_h_X-dept","sip_h_X-extension","sip_network_ip","original_read_codec","original_read_rate",
                "write_codec","write_rate","effective_caller_id_name","effective_caller_id_number","rtp_audio_in_quality_percentage","rtp_audio_in_mos","progress_mediamsec"],
        "store_cdrs": false,                                            // store cdrs in storDb
        "rater": "internal",                                    // address where to reach the Rater for cost calculation, empty to disable functionality: <""|internal|x.y.z.y:1234>
        "cdrstats": "",                                                 // address where to reach the cdrstats service, empty to disable stats functionality<""|internal|x.y.z.y:1234>
        "reconnects": 5,                                                // number of reconnect attempts to rater or cdrs
        "cdr_replication":[
                        {"transport": "*http_post", "server": "http://my.domain.com:8282/cdr_http/", "attempts": 1},
        ],
},

**Comment by danbogos** [comment]
Hi Errol,

Would it be possible to get remote access on your host where you can 
replicate the issue with a sample call?

Thanks,
DanB

**Comment by ewsamuels** [comment]
Hi DanB,
I am only seeing this message now.
I will provide access tomorrow.

Regards,

Errol

**Comment by ewsamuels** [comment]
Hi DanB,
As per our IRC Chat confirming the issue was related to the format the CDRs are sent from Freeswitch 1.6
I can confirm that the issue has been fixed as of the package generated on 6th May 2016.
