### ISSUE TITLE
[ees] cache *els bulk tunning speed

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4032]
Hi Teams,

Could you check if the *els export is working when the cache is enabled in order to send the CDRs in bulk mode to the ingestors like csv option does.

Configuration sample part:
```
    "ees": {						// EventExporterService
    	"enabled": true,				// starts the EventReader service: <true|false>
    	"attributes_conns": ["*internal"],      // RPC Connections IDs
        "cache": {
            "*file_csv": {"limit": -1, "ttl": "500ms", "static_ttl": false},
            "*els": {"limit": -1, "ttl": "1s", "static_ttl": false}
        },
...
```

[Tune for indexing speeded](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#tune-for-indexing-speed).

- Indexing speed
- Use bulk requests
- Bulk requests will yield much better performance than single-document index requests. In order to know the optimal size of a bulk request, you should run a benchmark on a single node with a single shard. First try to index 100 documents at once, then 200, then 400, etc. doubling the number of documents in a bulk request in every benchmark run. When the indexing speed starts to plateau then you know you reached the optimal size of a bulk request for your data. In case of tie, it is better to err in the direction of too few rather than too many documents. Beware that too large bulk requests might put the cluster under memory pressure when many of them are sent concurrently, so it is advisable to avoid going beyond a couple tens of megabytes per request even if larger requests seem to perform better

**Comment by gezimbll** [comment]
Hi @Integration-IT ,

 CGRates currently does not support sending CDRs in bulk mode through the *els . Currently, its only supported sending individual CDR as separate document on the fly.If you need this feature implemented  leave the issue open so we can look in the future.

Thanks,
Gezim
