### ISSUE TITLE
Panic on GuardianLock

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#408]
### Started at: Tue Mar 22 06:34:27 PDT 2016
fatal error: concurrent map read and map write

goroutine 1939041 [running]:
runtime.throw(0x114ad60, 0x21)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8e30ab690 sp=0xc8e30ab678
runtime.mapaccess2_faststr(0xd3c5c0, 0xc8201dd4d0, 0xc8440425a0, 0x21, 0x21, 0xc8440425a0)
	/usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8e30ab6f0 sp=0xc8e30ab690
github.com/cgrates/cgrates/engine.(*GuardianLock).Guard(0x15bfa00, 0xc8c0fcab50, 0x0, 0xc8e30ab960, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/guardian.go:42 +0x167 fp=0xc8e30ab8a8 sp=0xc8e30ab6f0
github.com/cgrates/cgrates/engine.(*Responder).GetCost(0xc82005d8b0, 0xc85ee8a9a0, 0xc853dbf180, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/responder.go:108 +0x451 fp=0xc8e30aba30 sp=0xc8e30ab8a8
runtime.call64(0xc820427880, 0x10096d8, 0xc844042540, 0x1800000028)
	/usr/local/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc8e30aba78 sp=0xc8e30aba30
reflect.Value.call(0xe54460, 0x10096d8, 0x13, 0x1048ed8, 0x4, 0xc8e30abef8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc8e30abdc8 sp=0xc8e30aba78
reflect.Value.Call(0xe54460, 0x10096d8, 0x13, 0xc8e30abef8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc8e30abe28 sp=0xc8e30abdc8
net/rpc.(*service).call(0xc8203b5800, 0xc82012c140, 0xc8a436f6a8, 0xc82007ad00, 0xc833140a00, 0x1016760, 0xc85ee8a9a0, 0x16, 0xff89a0, 0xc853dbf180, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x1c2 fp=0xc8e30abf48 sp=0xc8e30abe28
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8e30abf50 sp=0xc8e30abf48
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x49d

goroutine 1 [chan receive, 1616 minutes]:
main.main()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:774 +0x113d

goroutine 17 [syscall, 1616 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 173 [chan send, 1615 minutes]:
github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr.func1(0xc8201f0930, 0xc82031f500, 0xf52740, 0xc830fc59e0, 0xc8201a9f40, 0x104e7b8, 0x4, 0xc830ffe6c0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:430 +0x433
created by github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:432 +0x2f6

goroutine 23 [syscall, 1616 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [chan receive, 1616 minutes]:
database/sql.(*DB).connectionOpener(0xc820346b00)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 151 [chan send, 1615 minutes]:
github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr.func1(0xc8201f0930, 0xc82031ea80, 0xf52740, 0xc82b72f710, 0xc8201a9f40, 0x104e7b8, 0x4, 0xc82b5d4cc0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:430 +0x433
created by github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:432 +0x2f6

goroutine 35 [chan receive, 1615 minutes]:
github.com/cgrates/cgrates/scheduler.(*Scheduler).Loop(0xc82005d860)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/scheduler/scheduler.go:51 +0xa4
main.startScheduler(0xc8202764e0, 0xc820276480, 0x7fc8b4f8cfc0, 0xc8203c2b20, 0xc820276360)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:505 +0x1c5
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:704 +0xb0e

goroutine 6923 [chan send, 1607 minutes]:
github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr.func1(0xc8201f0930, 0xc84670a000, 0xf52740, 0xc847c84c00, 0xc8201a9f40, 0x104e7b8, 0x4, 0xc846b51d40)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:430 +0x433
created by github.com/cgrates/cgrates/engine.(*CdrServer).replicateCdr
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/cdrs.go:432 +0x2f6

goroutine 53 [IO wait]:
net.runtime_pollWait(0x7fc8b4f8dfd8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201d4060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201d4060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201d4000, 0x0, 0x7fc8b35d60d0, 0xc833140880)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820304000, 0xc820030e98, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820304000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/cgrates/cgrates/utils.(*Server).ServeJSON(0xc820322170, 0xc82035f860, 0xe)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/utils/server.go:84 +0x353
created by main.startRpc
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:578 +0x17b

goroutine 38 [select, 1616 minutes]:
main.startCdrcs(0xc820276540, 0xc820276420, 0xc820276360)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:78 +0x324
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:718 +0xc91

goroutine 39 [chan receive, 1615 minutes]:
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect(0xc82005d900, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:263 +0x8ae
main.startSmFreeSWITCH(0xc820276420, 0x7fc8b4fbab10, 0xc820134038, 0xc820276360)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:282 +0x719
created by main.main
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:726 +0xd57

**Comment by rif** [comment]
Pushed a possible fix and created a new tmp package.
Please test and reopen with the new stack-trace if the issue re-appears.
