### ISSUE TITLE
Can't seem to return all accounts for a domain

### ISSUE THREAD

**Issue by noahmehl** [cgrates/cgrates#409]
Tried the following JSON http transactions:

root@cgrates-test-01:~# curl -X POST --data '{"id": 1, "method": "ApierV2.SetAccount", "params": [{"Tenant": "domain.com", "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c","ActionPlanId":"", "ActionTriggersId":"", "AllowNegative":true, "Disabled":false, "ReloadScheduler":true}]}' http://localhost:2080/jsonrpc
{"id":1,"result":"OK","error":null}
root@cgrates-test-01:~# curl -X POST --data '{"id": 2, "method": "ApierV2.SetAccount", "params": [{"Tenant": "domain.com", "Account": "c344134c-9e31-40ba-808a-d6c0b4e689fc","ActionPlanId":"", "ActionTriggersId":"", "AllowNegative":true, "Disabled":false, "ReloadScheduler":true}]}' http://localhost:2080/jsonrpc
{"id":2,"result":"OK","error":null}
root@cgrates-test-01:~# curl -X POST --data '{"id": 3, "method": "ApierV2.GetAccounts", "params": [{"Tenant": "domain.com", "AccountIds":[], "Offset":0, "Limit":100}]}' http://localhost:2080/jsonrpc
{"id":3,"result":null,"error":null}
root@cgrates-test-01:~# curl -X POST --data '{"id": 4, "method": "ApierV2.GetAccounts", "params": [{"Tenant": "domain.com", "AccountIds":["5c1b474f-3a10-48d8-89a4-395a94a95a3c","c344134c-9e31-40ba-808a-d6c0b4e689fc"], "Offset":0, "Limit":100}]}' http://localhost:2080/jsonrpc
{"id":4,"result":[{"ID":"domain.com:5c1b474f-3a10-48d8-89a4-395a94a95a3c","BalanceMap":{},"UnitCounters":{},"ActionTriggers":[],"AllowNegative":true,"Disabled":false},{"ID":"domain.com:c344134c-9e31-40ba-808a-d6c0b4e689fc","BalanceMap":{},"UnitCounters":{},"ActionTriggers":[],"AllowNegative":true,"Disabled":false}],"error":null}

It's id:3 that's a problem.  I'm probably doing something wrong here?

Running version: cgrates_0.9.1~rc8_amd64.deb

**Comment by rif** [comment]
Something weird here:
❯ curl -X POST --data '{"id": 3, "method": "ApierV2.GetAccounts", "params": [{"Tenant": "domain.com", "AccountIds":[], "Offset":0, "Limit":100}]}' http://localhost:2080/jsonrpc
```json
{"id":3,"result":[{"ID":"domain.com:5c1b474f-3a10-48d8-89a4-395a94a95a3c","BalanceMap":null,"UnitCounters":null,"ActionTriggers":null,"AllowNegative":true,"Disabled":false},{"ID":"domain.com:c344134c-9e31-40ba-808a-d6c0b4e689fc","BalanceMap":null,"UnitCounters":null,"ActionTriggers":null,"AllowNegative":true,"Disabled":false}],"error":null}
```

**Comment by noahmehl** [comment]
Are you saying that when you ran the third request it worked?  What can I do to help diagnose my issue?

**Comment by rif** [comment]
yes, I just copy pasted you curl commands and got a good response.
Did you downloaded cgrates deb yesterday? Can you do a ls -al /usr/bin/cgr-engine ?

By the way: you can skip unused parameters, like: 
curl -X POST --data '{"id": 3, "method": "ApierV2.GetAccounts", "params": [{"Tenant": "domain.com"}]}' http://localhost:2080/jsonrpc

**Comment by rif** [comment]
I found the problem. Using mongo I have null result on id:3 as well. Pushing a fix.

**Comment by rif** [comment]
I pushed a fix. Please test and report your results.

**Comment by noahmehl** [comment]
Where do I get the update? Do I need to build from source?

**Comment by rif** [comment]
You can get the same deb file and reinstall it.

**Comment by noahmehl** [comment]
Works great now!
