### ISSUE TITLE
Add filtering for Disabled: True/False on ApierV#.GetAccounts

### ISSUE THREAD

**Issue by noahmehl** [cgrates/cgrates#410]
As a user, it would be nice to be able to filter for accounts on their Disabled status when utilizing ApierV#.GetAccounts.

**Comment by noahmehl** [comment]
@danbogos! WOW thanks for getting to this ;)

~Noah

**Comment by danbogos** [comment]
@noahmehl  it was more @TeoV's effort ;).

DanB
