### ISSUE TITLE
Min/Max Cost as parameters to GetLCR

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#411]
Using these parameters we should filter out the suppliers returned. Scenarios where this logic can be used:
 * Avoid loosing money on routes.
 * Avoid cheap routes for specific traffic profiles

DanB

**Comment by ewsamuels** [comment]
Hi DanB,
Maybe one suggestion could be to add another parameter to [LcrRquest](https://godoc.org/github.com/cgrates/cgrates/engine#LcrRequest) perhaps called "MaxCost" where the cost can be compared with the costs from GetLcr.

Just my 2 cents.

Regards,

Errol

**Comment by danbogos** [comment]
Yes, this is what I mean. Both Min and MaxCost could be provided there.

DanB

**Comment by ewsamuels** [comment]
I am eagerly awaiting this feature.  At the moment I do this in my lua diaplan but would be nice to have it in CGRateS.

**Comment by danbogos** [comment]
In master we have now 2 more filters for ApierV1.GetLcr and ApierV1.GetLcrSuppliers:

 * MinCost: Supplier cost should be higher or equal with this value in order to be considered
 * MaxCost: Supplier cost should be smaller than this value to show up in supplier list.

@ewsamuels, @MarcVoIP please test and report if any issues.

Thanks,
DanBgit
