### ISSUE TITLE
cgrates crash 

### ISSUE THREAD

**Issue by tawanda-telco** [cgrates/cgrates#4114]
We get the following panic from cgrates at high load times -:
Were are running:
***
cgr> status
{
 "ActiveGoroutines": 49,
 "GoVersion": "go1.18.2",
 "MemoryUsage": "61.4MiB",
 "NodeID": "cgr1",
 "RunningSince": "Mon Oct  2 08:35:27 CAT 2023",
 "Version": "CGRateS@v0.11.0~dev-20220318105839-2206e5452f03"
}
***

Oct  2 08:35:27 cgr1 cgr-engine[3076]: panic: runtime error: index out of range [-1]
Oct  2 08:35:27 cgr1 cgr-engine[3076]: goroutine 231540 [running]:
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/engine.(*EventCost).appendCIlFromEC(0xc02bf54d20, 0xc08ed9f7c0, 0x0?)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/engine/eventcost.go:537 +0xa55
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/engine.(*EventCost).appendChargingIntervalFromEventCost(0xc02bf54d20?, 0xc08ed9f7c0?, 0x0?)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/engine/eventcost.go:581 +0xeb
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/engine.(*EventCost).Merge(0xc02bf54d20, {0xc04e8e50d0, 0x1, 0xc0ad65a560?})
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/engine/eventcost.go:696 +0x153
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/sessions.(*SessionS).debitSession(0xc000a20000, 0xc07afa0dc0, 0xc09086c9c0?, 0x0, 0x7f9a344b7fff?)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/sessions/sessions.go:509 +0xb57
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/sessions.(*SessionS).updateSession(0xc000a20000, 0xc07afa0dc0, 0xc09086c990, 0x0?, 0x0?)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/sessions/sessions.go:1544 +0x7ec
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCv1UpdateSession(0xc000a20000, {0x0, 0x0}, 0xc09086c930, 0xc091c07458)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/sessions/sessions.go:2541 +0x9f3
Oct  2 08:35:27 cgr1 cgr-engine[3076]: github.com/cgrates/cgrates/apier/v1.(*SessionSv1).UpdateSession(0x2?, 0xc000a0e290?, 0x1?)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/src/cgrates/apier/v1/sessions.go:60 +0x26
Oct  2 08:35:27 cgr1 cgr-engine[3076]: reflect.Value.call({0xc00081a900?, 0xc000866400?, 0x13?}, {0x1d09d5a, 0x4}, {0xc02915eef8, 0x3, 0x3?})
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/lib/go-1.18/src/reflect/value.go:556 +0x845
Oct  2 08:35:27 cgr1 cgr-engine[3076]: reflect.Value.Call({0xc00081a900?, 0xc000866400?, 0x0?}, {0xc000e90ef8, 0x3, 0x3})
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/lib/go-1.18/src/reflect/value.go:339 +0xbf
Oct  2 08:35:27 cgr1 cgr-engine[3076]: net/rpc.(*service).call(0xc000638380, 0xc0908350e0?, 0xc0005d3740?, 0xc0008180c0, 0xc000868180, 0xc0908350e0?, {0x1c5fd40?, 0xc09086c930?, 0x6e8886?}, {0x1a98d40, ...}, ...)
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/lib/go-1.18/src/net/rpc/server.go:381 +0x226
Oct  2 08:35:27 cgr1 cgr-engine[3076]: created by net/rpc.(*Server).ServeCodec
Oct  2 08:35:27 cgr1 cgr-engine[3076]: #011/usr/lib/go-1.18/src/net/rpc/server.go:478 +0x3fe
Oct  2 08:35:28 cgr1 CGRateS <cgr1> [3157]: <CoreS> starting version <CGRateS@v0.11.0~dev-20220318105839-2206e5452f03><go1.18.2>

**Comment by ionutboangiu** [comment]
Hi,

First of all, I notice that you are running an older version of cgrates. It's recommended to update to the latest version and check if the crash still occurs. To help us find the cause, could you please provide the following:

- The config file you're using to start the engine.
- Information about your general architecture. Specifically, what is sending requests to the `SessionS`?
-  `ngrep` output for `sessionsv1.InitSession` and `sessionsv1.UpdateSession` APIs. If possible, isolate this for the session that caused the crash. If the connection between `SessionS` and the agent is internal, one option would be to change it to `*bijson_localhost` to sniff it using `ngrep` on the jsonrpc port.

Thanks,
Ionuț

**Comment by tawanda-telco** [comment]
> Hi,
> 
> First of all, I notice that you are running an older version of cgrates. It's recommended to update to the latest version and check if the crash still occurs. To help us find the cause, could you please provide the following:
> 
> * The config file you're using to start the engine.
> * Information about your general architecture. Specifically, what is sending requests to the `SessionS`?
> * `ngrep` output for `SessionSv1.InitiateSession` and `SessionSv1.UpdateSession` APIs. If possible, isolate this for the session that caused the crash. If the connection between `SessionS` and the agent is internal, one option would be to change it to `*bijson_localhost` to sniff it using `ngrep` on the jsonrpc port.
> 
> Thanks, Ionuț

Thank you Ionut, I will upgrade to the latest version tonight and run the same tests and see if the crash clears.

**Comment by tawanda-telco** [comment]
Hi Ionut, ran the latest git version of cgrates and had the first 'panic' ~ 18hrs later with slightly different 
log. See below. 

Oct  3 18:10:15 cgr1 cgr-engine[17904]: panic: runtime error: index out of range [-1]
Oct  3 18:10:15 cgr1 cgr-engine[17904]: goroutine 8343269 [running]:
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/engine.(*EventCost).appendCIlFromEC(0xc0f9642b40, 0xc1f3ca9ae0, 0xc0013c71b8?)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/engine/eventcost.go:537 +0xa35
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/engine.(*EventCost).appendChargingIntervalFromEventCost(0xc0f9642b40?, 0xc1f3ca9ae0?, 0x0?)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/engine/eventcost.go:581 +0xdf
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/engine.(*EventCost).Merge(0xc0f9642b40, {0xc0013c7288, 0x1, 0xc09a14dd38?})
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/engine/eventcost.go:696 +0x145
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/sessions.(*SessionS).endSession(0xc0005c4a90, 0xc0f9642a00, 0xc18fc10720, 0xc18fc10728, 0xc103d9cee8, 0xa5?)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/sessions/sessions.go:1606 +0x8ef
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/sessions.(*SessionS).terminateSession(0xc0f9642a00?, 0xc0f9642a00, 0xc06ba016b0?, 0x0?, 0xc153853c98?, 0x98?)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/sessions/sessions.go:1561 +0x65
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/sessions.(*SessionS).BiRPCv1TerminateSession(0xc0005c4a90, 0xc001e9c680, 0xc1117b5780, 0xc0d9012530)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/sessions/sessions.go:2688 +0x155b
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/cgrates/apier/v1.(*SessionSv1).TerminateSession(0x2?, 0xc0022f7c08?, 0x1?, 0x1?)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/apier/v1/sessions.go:71 +0x16
Oct  3 18:10:15 cgr1 cgr-engine[17904]: reflect.Value.call({0xc000846360?, 0xc000d8a0b0?, 0x13?}, {0x2107442, 0x4}, {0xc00009cec8, 0x4, 0x4?})
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/lib/go-1.21/src/reflect/value.go:596 +0xce7
Oct  3 18:10:15 cgr1 cgr-engine[17904]: reflect.Value.Call({0xc000846360?, 0xc000d8a0b0?, 0x7fe1a46eff60?}, {0xc0005906c8?, 0xc10290b8c0?, 0x66?})
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/lib/go-1.21/src/reflect/value.go:380 +0xb9
Oct  3 18:10:15 cgr1 cgr-engine[17904]: github.com/cgrates/birpc.(*Service).call(0xc0005cc0c0, 0x273a700?, 0xc144be80a0?, 0xc0007f6618, 0xc0005907d0?, 0xc0000427e0, 0xc1415849a0, {0x204b380, 0xc1117b5780, 0x16}, ...)
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/tmp/pkg/mod/github.com/cgrates/birpc@v1.3.1-0.20211117095917-5b0ff29f3084/service.go:96 +0x38f
Oct  3 18:10:15 cgr1 cgr-engine[17904]: created by github.com/cgrates/birpc.(*Server).ServeCodec in goroutine 147
Oct  3 18:10:15 cgr1 cgr-engine[17904]: #011/usr/src/cgrates/tmp/pkg/mod/github.com/cgrates/birpc@v1.3.1-0.20211117095917-5b0ff29f3084/server.go:226 +0x53e
Oct  3 18:10:15 cgr1 systemd[1]: Stopped Control CGRateS - carrier grade real-time charging system.
Oct  3 18:10:15 cgr1 systemd[1]: Started Control CGRateS - carrier grade real-time charging system.
Oct  3 18:10:16 cgr1 CGRateS <cgr1> [20575]: <CoreS> starting version <CGRateS@v0.11.0~dev-20231002190400-d003b8c2ae29><go1.21.1>
Oct  3 18:10:16 cgr1 CGRateS <cgr1> [20575]: <ServiceManager> Starting CGRateS Scheduler.
Oct  3 18:10:16 cgr1 CGRateS <cgr1> [20575]: Starting CGRateS JSON server at <127.0.0.1:2012>.
Oct  3 18:10:16 cgr1 CGRateS <cgr1> [20575]: Starting CGRateS GOB server at <127.0.0.1:2013>.
Oct  3 18:10:16 cgr1 CGRateS <cgr1> [20575]: Starting CGRateS BiJSON server at <127.0.0.1:2014>
