### ISSUE TITLE
Failed syncing active_calls from FreeSWITCH

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#413]
`
Mar 31 16:02:00 CgrDev1 CGRateS[6474]: <SM-FreeSWITCH> Syncing active calls, failed converting output from FS: uuid,direction,created,created_epoch,name,state,cid_name,cid_num,ip_addr,dest,application,application_data,dialplan,context,read_codec,read_rate,read_bit_rate,write_codec,write_rate,write_bit_rate,secure,hostname,presence_id,presence_data,callstate,callee_name,callee_num,callee_direction,call_uuid,sent_callee_name,sent_callee_num,initial_cid_name,initial_cid_num,initial_ip_addr,initial_dest,initial_dialplan,initial_context#0125aacf28a-2e9b-45ff-99cb-423e2dd9038e,inbound,2016-03-31 16:01:49,1459432909,sofia/internal/1001@172.16.254.80,CS_EXECUTE,1001,1001,172.16.254.1,1004,sched_hangup,+2700 alloted_timeout,XML,default,G722,16000,64000,G722,16000,64000,,CgrDev1.itsyscom.com,1001@172.16.254.80,,ACTIVE,,,,5aacf28a-2e9b-45ff-99cb-423e2dd9038e,,,1001,1001,172.16.254.1,1004,XML,default#01275610f37-f692-4a98-b28f-ad2e6e272ae8,outbound,2016-03-31 16:01:49,1459432909,sofia/internal/1004@172.16.254.1:5060,CS_EXCHANGE_MEDIA,Extension 1001,1001,172.16.254.1,1004,,,XML,default,G722,16000,64000,G722,16000,64000,,CgrDev1.itsyscom.com,1004@cgrates.org,,ACTIVE,Outbound Call,1004,,5aacf28a-2e9b-45ff-99cb-423e2dd9038e,,,Extension 1001,1001,172.16.254.1,1004,XML,default#012#0122 total.
`

DanB

**Comment by TeoV** [comment]
Done with new call tests.
