### ISSUE TITLE
[DiamAgent] Setting up GrantedUnit to acc balance

### ISSUE THREAD

**Issue by mohammad-safakhou** [cgrates/cgrates#4136]
Hi,
In updating sessions I need to pass the GrantedUnit to account's balance.
Like if they have 1GB of data, instead of passing some constant value I want to pass the whole 1GB.
Is it even a good logical decision to pass the balance? or passing some constant is a good way to go?

**Comment by danbogos** [comment]
Hi @mohammad-safakhou 

Please use our google group to ask questions since it should be better structured for community to learn. 

Ta,
DanB
