### ISSUE TITLE
[*ERS] AMQP concurrent_requests basic.ack exception

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4146]
Hi Teams,

Insprired from [AMQPER / amqp_it_test.go](https://github.com/cgrates/cgrates/blob/405f29ca0064254c2a16b69d75d586263d6c07aa/ers/amqp_it_test.go#L36) to configure the consumer, I have unexpectedly closed TCP connection between MQserver and Cgrates.

[*ERS] *amqp_json_map TO [*ESS] *els : ERROR.
[*ERS] *amqp_json_map queue A TO [*ESS] *amqp_json_map queue B : ERROR.

The context is to consume the CDR in queue A with the *ERS, and use the *ESS to push the valuable CDR as *rated mode with cost details to queue B for a third party.
OR
Consume the CDR in queue A with the *ERS, and use the *ESS to push the valuable CDR with cost details to ELK for a third party analysis.

Both contexts are working very well until **concurrent_requests** is set to a very **low value**.
Actualy not possible to replicate the amqp_it_test.go configuration, got closed TCP connection after few seconds from MQServer.

The main vector to replicate is to play with the "concurrent_requests" parameter and keep all others according to the amqp_it_test.go.

---

`CGRateS@v0.11.0~dev`

---
test:
-  ers "concurrent_requests" : 1 --> STABLE
-  ers "concurrent_requests" : 2 --> operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 1
-  ers "concurrent_requests" : 10 --> operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 1, operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 5, operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 3.
-  ers "concurrent_requests" : 100 --> operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 10, operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 19

**Comment by Integration-IT** [comment]
[Delivery Identifiers: Delivery Tags](https://www.rabbitmq.com/confirms.html#consumer-acks-delivery-tags)
Before we proceed to discuss other topics it is important to explain how deliveries are identified (and acknowledgements indicate their respective deliveries). When a consumer (subscription) is registered, messages will be delivered (pushed) by RabbitMQ using the basic.deliver method. The method carries a delivery tag, which uniquely identifies the delivery on a channel. Delivery tags are therefore scoped per channel.

Delivery tags are monotonically growing positive integers and are presented as such by client libraries. Client library methods that acknowledge deliveries take a delivery tag as an argument.

**Because delivery tags are scoped per channel, deliveries must be acknowledged on the same channel they were received on. Acknowledging on a different channel will result in an "unknown delivery tag" protocol exception and close the channel.**

**Comment by Integration-IT** [comment]
@danbogos please bump 2 000 000 CDR in stress test are locked

**Comment by ionutboangiu** [comment]
Hi,

Thanks for the find and for providing detailed info. This issue should be solved by the latest commit on master. Let us know if you have any other issues.

Also, regarding your latest comment:
> @danbogos please bump 2 000 000 CDR in stress test are locked

Could you please clarify what you meant by this?

Thanks,
Ionuț

**Comment by Integration-IT** [comment]
Hi @ionutboangiu ,

Tested with 1 to 1024 // requests.
Thank you, no error, tags are managed, no exception.
