### ISSUE TITLE
[*ERS] AMQP Prefetch, Acknowledgement Deadlock, Reconnect

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4160]
Hi @ionutboangiu ,

This is related to #4146 (basic.ack exception).
The last patch is working fine.

New behaviors seems to appear.

- *amqp_json_map does not have a max prefetch count to [limit the number of unacknowledged messages](https://www.rabbitmq.com/confirms.html) on a channel (or connection) when consuming (aka "prefetch count").
  - This is done by setting a "prefetch count" value using the basic.qos method.
- After a while I have Unacked message similar to dead lock pending states and i can't see any connections from ERS.
- If a consumer does not ack its delivery for more than the timeout value (30 minutes by default), its channel will be closed with a PRECONDITION_FAILED channel exception.
- When the channel is closed ERS module will never connect again to subscribe and consume new ready messages.
- Finally I have to restart manually the engine again.

---

About the last patch:

_The reader is now closed immediately if the message delivery
channel closes. Therefore, it prevents an endless loop by avoiding
continuous consumption from empty or closed channels._

Because after a while the queue is not empty, does the module could auto reconnect with a timer option to consume new ready messages ?

**Comment by ionutboangiu** [comment]
Hello, 

The feedback was much appreciated. The commit referenced throughout this issue added reconnect support for the AMQP event reader among other things detailed in the commit message. You can now update to latest master and test it. I hope it addressed all your concerns. Let me know if you have any other suggestions.

Thanks,
Ionuț

**Comment by Integration-IT** [comment]
Thank @ionutboangiu ,
No issue after the update.
