### ISSUE TITLE
exclusion of DestinationIDs in balance configuration

### ISSUE THREAD

**Issue by simon-af** [cgrates/cgrates#417]
it could be interesting for us to have a solution to exclude some destinationIDs (with negation "!" ).
it could permit to not match some specific prefix for some balances

**Comment by rif** [comment]
Use ! in the csv or stordb Balance DestinationIDs to mark the exclusion of a destination id, e.g.:

```csv
TOPUP_NEG,*topup,,,,*voice,*out,,GERMANY;!GERMANY_MOBILE,*zero1m,,*unlimited,,100,10,false,false,10
```
