### ISSUE TITLE
Call rating issue

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#418]
Hi DanB,

I have an issue where the CDRs are not rating properly
We normally generate two CDRs, one for the customer and one for the supplier
The getcallcost API shows the correct rates for the customer and also the LCR returns the correct result
However at the end of the call we only get the duration for the customer CDR we 0 rate and 0 cost.  
The suppliers CDR is fine.

I tested with the 29th Mar and the 1st April packages with the same result.

**Supplier CDR**

id               | 34
cgrid            | f8b941d135b00b0b1442c456ce1afb2d028e4138
run_id           | *default
origin_host      | 10.0.70.203
source           | freeswitch_json
origin_id        | b487cad4-9473-4cdd-bee6-e38d4f937d69
tor              | *voice
request_type     | postpaid
direction        | *out
tenant           | sbc.cgrates.org
category         | default
account          | 1062858221
subject          | castdialer
destination      | 16465031165
setup_time       | 2016-04-04 05:40:18
pdd              | 2.220000000
answer_time      | 2016-04-04 05:40:24
usage            | 16.000000000
supplier         | 
disconnect_cause | NORMAL_CLEARING
extra_fields     | {"call_uuid": "19ed99f7-493e-43f6-bc5a-9f4ef52eb8e5", "direction": "outbound", "write_rate": "8000", "write_codec": "PCMU", "sip_h_X-dept": "", "sip_h_X-site": "", "sip_h_X-custom": "", "sip_network_ip": "10.10.250.50", "rtp_audio_in_mos": "4.50", "sip_h_X-username": "", "sip_h_X-extension": "", "original_read_rate": "8000", "progress_mediamsec": "2220", "original_read_codec": "PCMU", "effective_caller_id_name": "", "effective_caller_id_number": "", "rtp_audio_in_quality_percentage": "100.00"}
cost_source      | 
cost             | 0.0015
cost_details     | {"TOR": "*voice", "Cost": 0.00147, "Tenant": "sbc.cgrates.org", "Account": "1062858221", "Subject": "castdialer", "Category": "default", "Direction": "*out", "Timespans": [{"Cost": 0.00147, "TimeEnd": "2016-04-04T05:40:42-04:00", "TimeStart": "2016-04-04T05:40:24-04:00", "Increments": [{"Cost": 0.00049, "Duration": 6000000000, "BalanceInfo": {"Unit": null, "Monetary": {"ID": "", "UUID": "291f6cfa-745c-4df1-9baf-5ad90c821788", "Value": 89.54552, "RateInterval": null}, "AccountID": "sbc.cgrates.org:1062858221"}, "CompressFactor": 3}], "RateInterval": {"Rating": {"Rates": [{"Value": 0.0049, "RateUnit": 60000000000, "RateIncrement": 6000000000, "GroupIntervalStart": 0}], "MaxCost": 0, "ConnectFee": 0, "RoundingMethod": "*middle", "MaxCostStrategy": "0", "RoundingDecimals": 5}, "Timing": {"Years": [], "Months": [], "EndTime": "", "WeekDays": [], "MonthDays": [], "StartTime": "00:00:00"}, "Weight": 10}, "RatingPlanId": "RP_CASTDIALER", "DurationIndex": 18000000000, "MatchedDestId": "United_States_646503", "MatchedPrefix": "1646503", "CompressFactor": 1, "MatchedSubject": "*out:sbc.cgates.org:default:castdialer", "RoundIncrement": null}], "RatedUsage": 18, "Destination": "16465031165"}
extra_info       | 
created_at       | 2016-04-04 05:39:14.103972
updated_at       | 2016-04-04 05:39:14.103972
deleted_at       | 0001-01-01 00:00:00

**Customer CDR**
id               | 35
cgrid            | 78c7241ec7044e6b2f0e9948113cd4de7f49a419
run_id           | *raw
origin_host      | 10.0.70.203
source           | freeswitch_json
origin_id        | 19ed99f7-493e-43f6-bc5a-9f4ef52eb8e5
tor              | *voice
request_type     | *prepaid
direction        | *out
tenant           | sbc.cgrates.org
category         | apolloblackr
account          | 7580810687
subject          | 7580810687
destination      | 16465031165
setup_time       | 2016-04-04 05:40:18
pdd              | 2.280000000
answer_time      | 2016-04-04 05:40:24
usage            | 16.000000000
supplier         | 
disconnect_cause | NORMAL_CLEARING
extra_fields     | {"call_uuid": "19ed99f7-493e-43f6-bc5a-9f4ef52eb8e5", "direction": "inbound", "write_rate": "8000", "write_codec": "PCMU", "sip_h_X-dept": "", "sip_h_X-site": "", "sip_h_X-custom": "", "sip_network_ip": "10.0.70.216", "rtp_audio_in_mos": "4.50", "sip_h_X-username": "", "sip_h_X-extension": "", "original_read_rate": "8000", "progress_mediamsec": "2280", "original_read_codec": "PCMU", "effective_caller_id_name": "19173001321", "effective_caller_id_number": "19173001321", "rtp_audio_in_quality_percentage": "100.00"}
cost_source      | 
cost             | -1.0000
cost_details     | null
extra_info       | 
created_at       | 2016-04-04 05:39:14.130143
updated_at       | 2016-04-04 05:39:14.130143
deleted_at       | 0001-01-01 00:00:00

**Comment by ewsamuels** [comment]
Here notice that GetCost returns the correct result:

curl -X POST -H "Content-Type: application/json" -d '{"method":"Responder.GetCost","params":[{"Direction":"*out","Category":"apolloblackr","Tenant":"sbc.cgrates.org","Subject":"7580810687","Account":"7580810687","Destination":"16465031165","TimeStart":"2016-04-04T22:00:00Z","TimeEnd":"2016-04-04T22:01:00Z"}]}' http://localhost:2080/jsonrpc

{"id":null,"result":{"Direction":"*out","Category":"apolloblackr","Tenant":"sbc.cgrates.org","Subject":"7580810687","Account":"7580810687","Destination":"16465031165","TOR":"*voice","Cost":0.0083,"Timespans":[{"TimeStart":"2016-04-04T22:00:00Z","TimeEnd":"2016-04-04T22:01:00Z","Cost":0.0083,"RateInterval":{"Timing":{"Years":[],"Months":[],"MonthDays":[],"WeekDays":[],"StartTime":"00:00:00","EndTime":""},"Rating":{"ConnectFee":0,"RoundingMethod":"*middle","RoundingDecimals":5,"MaxCost":0,"MaxCostStrategy":"0","Rates":[{"GroupIntervalStart":0,"Value":0.0083,"RateIncrement":6000000000,"RateUnit":60000000000}]},"Weight":10},"DurationIndex":60000000000,"Increments":[{"Duration":6000000000,"Cost":0.00083,"BalanceInfo":{"Unit":null,"Monetary":null,"AccountID":""},"CompressFactor":10}],"RoundIncrement":null,"MatchedSubject":"*out:sbc.cgrates.org:apolloblackr:*any","MatchedPrefix":"1646503","MatchedDestId":"United_States_646503","RatingPlanId":"RP_APOLLOBLACKR","CompressFactor":1}],"RatedUsage":60},"error":null}

**Comment by ewsamuels** [comment]
DanB, 

As per our IRC chat I did some further testing and it seems I am able to replicate the issue.
I have a standalone CGRateS master and 4 x Freeswitch Session Managers
It seems if I restart CGRateS on the Master I run into the issue.....
Only when I restart the Session Manager on the Freeswitch Servers the A-Leg calls are rating correctly again.
It may seem crazy but I was able to replicate it 3 times!

After restarting the session manager on Freeswitch servers and send calls to each server all the calls are rated correctly.  If I restart CGRateS on the Master again and send calls to the 4 servers they are not rating until I restart CGRateS on the Session Manager again.

Hope that helps.

Thanks

Errol

**Comment by danbogos** [comment]
Hi @ewsamuels 

Most probably a reconnect issue from the SM. Will check it and update the issue here.

Thanks for reporting,
DanB

**Comment by danbogos** [comment]
The issue was indeed a reconnect problem. Please retest since it should be fixed.

Thanks,
DanB

**Comment by ewsamuels** [comment]
Thank you
