### ISSUE TITLE
Api parameters validation error when missing {}

### ISSUE THREAD

**Issue by catokx** [cgrates/cgrates#42]
if you call any api and for parameters you miss {} inside [], the server returns empty string without error instead of error json.

**Comment by danbogos** [comment]
Hi,

Thank you for your report. Can u be more explicit in what API are you calling?

If you miss {}, this might be interpreted as empty parameters, hence chances that the API does something. On the other hand, if you miss parameters, maybe the API should not react at all. Please share a ngrep capture of your API call/reply.

DanB

**Comment by catokx** [comment]
this is an example

{"params":,"method":"ApierV1.ReloadScheduler","id":0}

**Comment by danbogos** [comment]
@catokx: That method takes no parameters at all to it should be safe to send anything (or nothing). In the function signature there is a string but that will be ignored. A particularity of Go is that it automatically initializes the variables, even if you don't set them, so if the parameters are missing out of your API calls, they will be initialized to their equivalent 0 values (eg: empty string for strings, 0 for integers, false for bools and so on).

DanB
