### ISSUE TITLE
Issue in saving cdrs for prepaid calls

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#420]
I have came across the issue which is related to cdrs in stordb. 

A-leg of the prepaid call is saved with cost = -1 and empty cost details even if the sm_costs table is populated with the cost.

cdrs entry:  http://pastebin.com/J7qAs3cG
sm_costs entry for the same call :  http://pastebin.com/LTSZ4XC9

The B-leg of the call is of postpaid type and the cost is saved properly.
If I change the A-leg call type to  postpaid too then the cdrs are saved properly.

**Comment by MarcVoIP** [comment]
Update after tests with fresh build (including all dependencies) of cgrates:
 - prepaid calls are now properly rated
 - "deleted_at" in the past was because the servers were not synchronising the time however I have first test the prepaid calls and then sync the servers time. Works still in both cases (even if the time is not sync). 

Conclusion:
  - either cgrates or one of the dependencies caused the issue
  - the issue is resolved

**Comment by danbogos** [comment]
Thanks for reporting!

DanB
