### ISSUE TITLE
Getting the Category or subject a new value in Sessions package.

### ISSUE THREAD

**Issue by WaledEzzi** [cgrates/cgrates#4216]
Dear Dan,

Kindly I want a confirmation for the below proposal:

for the addons, I suggest to my team to let the Sessions invoke a function that exists in another file (handle_sessions.HandleSession) simply in order to get a value for the "Category" or Subject"  from that function, that function needs both **Account** and **Destination** to it and returns a value to be used as **Category** value ..

in the Sessions.go package, I just added the following:
===============================================
// category := me.GetStringIgnoreErrors(utils.Category)
        // if len(category) == 0 {
        //  category = sS.cgrCfg.GeneralCfg().DefaultCategory
        // }
     
category := handle_sessions.HandleSession(Account, Destination)
============================================

I got this idea similar to the Attributes when sessions ask/send all the parameters to the attributes checking if any altered parameters to be changed.

Kindly your comments, recommendations, or confirmation 🫡

Regards
Waled

**Comment by danbogos** [comment]
Hi Waled,

We recommend you to handle any parameter modification is via the AttributeS and not directly within the SessionS logic. That is due to particular responsibilities each module is designed to have, plus that you will break the generic nature of the events. If you start modifying the Category, why not all the parameters in the Event? Each of the users of CGRateS will have different demands and hence the need of AttributeS.

Hope this helps.

DanB

**Comment by WaledEzzi** [comment]
Thank you Dan for your valuable answer ..
I appreciate your cooperation..and apologize for reply here while the case is closed ..

we cant use the attributes as we need to conduct a lot of thing please have a look below :

We need to make  MUC (CUG) as "add on" in a separate package due to the fact I need to manage the subscription for CUG to put the groups and subscribers in a DB (msisdn_groups table) as below:

INSERT INTO msisdn_groups (msisdn, group_id) VALUES ('1001', 1);
INSERT INTO msisdn_groups (msisdn, group_id) VALUES ('1001', 2);
INSERT INTO msisdn_groups (msisdn, group_id) VALUES ('1002', 1);
INSERT INTO msisdn_groups (msisdn, group_id) VALUES ('1003', 2);

**I need to make a code to check if Account and Destination are in the same group to send groupID to **CATEGORY**** 

And not only for CUG , we need to build **addon** for many MUCs similar to CUG.


Appreciate your support ..
Regards,
Waled

**Comment by danbogos** [comment]
Hi Waled,

AttributeS are to cover most of the database interaction out there. FilterS should serve you as queries for matching them.

Of course, we can only advise you what what we think are best practices since we have seen quite some scenarios over the years.
You should however be able to fork CGRateS and maintain it with the additional code you write without any issue (just don't forget to keep the changes public as required by license).

Thanks,
DanB

**Comment by WaledEzzi** [comment]
Hi Dan,

I am sorry for wasting your time with these Questions :
Assume that we have this MUCs (Friend and Family).

Subscribers are subscribed to this MUC
This MUC behaving as below:

Each subscriber has **his own** FnF-list ,and he can call them with special tariff ,,,,but when they call that number they will be charged with a regular tariff rate not with FnF tariff.

e.g:
1001 has the below numbers in his fnf-list:
1002
1003
1004
1005


and 

subscriber 1010:
has the below FnF-list:
1011
1012
1013
1014
1015


Filters.csv:
#Tenant[0],ID[1],Type[2],Path[3],Values[4],ActivationInterval[5]
cgrates.org,FLTR_FnF_1001,*string,~*req.Subject,1001,
cgrates.org,FLTR_FnF_1001,*string,~*req.Destination,1001;1002;1003;1004;1005,
cgrates.org,FLTR_FnF_1010,*string,~*req.Subject,1010,
cgrates.org,FLTR_FnF_1010,*string,~*req.Destination,1011;1012;1013;1014;1015,

Attributes.csv:
#Tenant,ID,Contexts,FilterIDs,ActivationInterval,AttributeFilterIDs,Path,Type,Value,Blocker,Weight
cgrates.org,ATTR_SET_SUBJECT,*any,,,,,,,false,20
cgrates.org,ATTR_SET_SUBJECT,,,,FLTR_FnF_1001,*req.Subject,*constant,Subj_FnF_1001,,
cgrates.org,ATTR_SET_SUBJECT,,,,FLTR_FnF_1010,*req.Subject,*constant,Subj_FnF_1010,,


RatingProfiles.csv:
#Tenant,Category,Subject,ActivationTime,RatingPlanId,RatesFallbackSubject
cgrates.org,call,Subj_FnF_1001,2014-01-14T00:00:00Z,RP_Subject_FnF,
cgrates.org,call,Subj_FnF_1010,2014-01-14T00:00:00Z,RP_Subject_FnF,


And to do the same for each subscriber even if they are 3 MIO subscribers!
Is that what you mean by using the attributes and filters ?

**Comment by WaledEzzi** [comment]
And What about adding a new Module similar to the "AddSon" from the below diagram,please advise ,,,,[LAST QUESTION]

![Screenshot from 2023-11-30 01-27-52](https://github.com/cgrates/cgrates/assets/116760473/ce1bbf03-aa4d-49dd-951d-530b3d9a6c59)

**Comment by WaledEzzi** [comment]
Hello Dan,

We sincerely apologize for bombarding you with numerous queries regarding the product. We understand that it may seem excessive and it was not our intention to go beyond the scope or boundaries set by your expertise.

The reason behind our extensive questioning is rooted in our desire to stay on track, under your guidance, and within the parameters you have established. We believe that once we become a customer, our partnership will be of utmost importance, and we see you as our primary support in that endeavor.

We acknowledge that some of our questions may have appeared trivial or unnecessary, and we genuinely apologize for any inconvenience caused. We greatly appreciate your patience and understanding throughout this process.

As we move forward with your  PROFISSIONAL product, we are eager to understand how we can customize the logic and services of the add-on to meet our specific requirements. 

We believe that having an example of add-on will help us and will be more appreciated..

So Please please your valuable input as usual ..

Regards,
Waled
