### ISSUE TITLE
ApierV2.RemoveBalance doesn't seem to be working

### ISSUE THREAD

**Issue by noahmehl** [cgrates/cgrates#422]
FYI, I'm using MongoDB as my backend.  I'm running into a problem with the following:

root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.SetAccount", "params": [{"Tenant": "domain.com","Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c","AllowNegative":true}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": "OK",
  "error": null
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.SetBalance", "params": [{"Tenant": "domain.com","Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c", "BalanceId": "5ccedcc8-38e2-4b02-b53b-013751b73450", "BalanceType": "*sms", "Value":99}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": "OK",
  "error": null
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.GetAccount", "params": [{"Tenant": "domain.com","Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c"}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": {
    "ID": "domain.com:5c1b474f-3a10-48d8-89a4-395a94a95a3c",
    "BalanceMap": {
      "*sms": [
        {
          "Uuid": "56a183d2-a414-4969-9e42-338686fd5609",
          "ID": "5ccedcc8-38e2-4b02-b53b-013751b73450",
          "Value": 99,
          "Directions": {},
          "ExpirationDate": "0001-01-01T00:00:00Z",
          "Weight": 0,
          "DestinationIDs": {},
          "RatingSubject": "",
          "Categories": {},
          "SharedGroups": {},
          "Timings": [],
          "TimingIDs": {},
          "Disabled": false,
          "Factor": {},
          "Blocker": false
        }
      ]
    },
    "UnitCounters": {},
    "ActionTriggers": [],
    "AllowNegative": true,
    "Disabled": false
  },
  "error": null
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.RemoveBalances", "params": [{"Tenant": "domain.com","Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c", "BalanceType": "*sms", "BalanceId": "5ccedcc8-38e2-4b02-b53b-013751b73450"}]}' http://localhost:2080/jsonrpc | jq '.'
ccount", "params": [{"Tenant": "domain.com","Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c"}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": "OK",
  "error": null
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.GetAccount", "params": [{"Tenant": "domain.com","Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c"}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": {
    "ID": "domain.com:5c1b474f-3a10-48d8-89a4-395a94a95a3c",
    "BalanceMap": {
      "*sms": [
        {
          "Uuid": "56a183d2-a414-4969-9e42-338686fd5609",
          "ID": "5ccedcc8-38e2-4b02-b53b-013751b73450",
          "Value": 99,
          "Directions": {},
          "ExpirationDate": "0001-01-01T00:00:00Z",
          "Weight": 0,
          "DestinationIDs": {},
          "RatingSubject": "",
          "Categories": {},
          "SharedGroups": {},
          "Timings": [],
          "TimingIDs": {},
          "Disabled": false,
          "Factor": {},
          "Blocker": false
        }
      ]
    },
    "UnitCounters": {},
    "ActionTriggers": [],
    "AllowNegative": true,
    "Disabled": false
  },
  "error": null
}

**Comment by rif** [comment]
Pushed a fix. Please test.

**Comment by noahmehl** [comment]
I retested with the package from: http://www.cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb, unfortunately, it's the same result.

**Comment by noahmehl** [comment]
I re-installed from this package: http://www.cgrates.org/tmp_pkg/cgrates_0.9.1~rc8_amd64.deb and have the same result.

**Comment by cgrates** [comment]
Hi Noah,

That package did not contain the fix (since it was generated last evening).

Please reinstall and retest since I have just built a fresh package for you.


DanB

**Comment by noahmehl** [comment]
The new package works great for me.  Thanks!
