### ISSUE TITLE
[*InitS] stor_db custom port parsing issue

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4221]
Hi teams,

Issue to configure custom destinations ports to mount a mongo replica-set.

The base sample : [stor_db](https://github.com/cgrates/cgrates/blob/1154cad0df89b4742912e1bbecf33859500f091d/data/conf/samples/mongoreplica/cgrates.json#L28)

---
conf:
```
    "stor_db": {
    	"db_type": "*mongo",	// stor database type to use: <*mongo|*mysql|*postgres|*internal>
    	"db_host": "x.x.x.x:27017,x.x.x.x:27018,x.x.x.x:27019",
        "db_port": 27017,
        "db_name": "cgrates?replicaSet=rs0&authSource=cgrates",
    	"db_user": "***********",
    	"db_password": ""***********",
...
```
log:
```
[INFO] <CoreS> starting version <CGRateS@v0.11.0~dev><go1.21.4>
<InitS> error received: <error parsing uri: invalid host "x.x.x.x:27019:27017": address x.x.x.x:27019:27017: too many colons in address>, exiting!
[CRITICAL] Could not configure storDB: error parsing uri
``` 
---
conf:
```
    "stor_db": {
    	"db_type": "*mongo",	// stor database type to use: <*mongo|*mysql|*postgres|*internal>
    	"db_host": "x.x.x.x:27017,x.x.x.x:27018,x.x.x.x:27019",
        //"db_port": 27017,
        "db_name": "cgrates?replicaSet=rs0&authSource=cgrates",
    	"db_user": "***********",
    	"db_password": ""***********",
...
```
log:
```
[<InitS> error received: <error parsing uri: invalid host "x.x.x.x:27019:3306": address x.x.x.x:27019:3306: too many colons in address>, exiting!
``` 
---
The engine will put the db_port if ports are set in db_host. if you comment the db_port param the default mysql port is used.

**Comment by ionutboangiu** [comment]
Hello,

Just a quick note on configuring your JSON file: it primarily updates the default settings. So, if you comment out the `db_port` field, it simply considers the default port value.

You've got a couple of options here:

1.  Leave out the port in the `db_host` of the last node and specify it separately in the `db_port` field (just like it's shown in the example configuration you mentioned).
2.  Alternatively, set `db_port` to 0, and it'll be automatically omitted.

Also, a heads-up: ensure you are on the latest master. We've recently fixed an issue related to parsing multiple nodes in mongo URIs.

Hope this helps!

Thanks,
Ionuț
