### ISSUE TITLE
High Memory Consumption

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#423]
Hi Guys,

I am seeing very high memory usage with the cgr-engine and it continues to increase.
I took a few samples below.

**This was taken when there were 0 calls on the system.**
{
"footprint": 564717,
"memstat": 357878
}

**This was taken when there were 71 calls on the system**

root@cgrtbill:~# cgr-console status
{
 "footprint": 1606842,
 "memstat": 970407
}
pmap -x 12482 | grep total

total kB         1721548 1151892 1143720

The System that CGRateS is running on has 8GB Ram.

CGRates Package:

-rwxr-xr-x 1 root   root    14396928 Apr  7 10:25 cgr-console
-rwxr-xr-x 1 root   root    18598880 Apr  7 10:25 cgr-engine
-rwxr-xr-x 1 root   root    15420832 Apr  7 10:25 cgr-loader
-rwxr-xr-x 1 root   root    14577024 Apr  7 10:25 cgr-tester

OS: Debian Wheezy 7.9

**Comment by danbogos** [comment]
Hi Errol

Please post cgr-console cache_stats output.

Thanks
DanB
Am 08.04.2016 18:08 schrieb "Errol Samuels" <notifications@github.com>:

**Comment by ewsamuels** [comment]
Hi DanB,
Thank you for you prompt response.
I made a little script to output the details for greater accuracy.
See attached,
![screen shot 2016-04-08 at 17 46 40](https://cloud.githubusercontent.com/assets/5496519/14391144/3b820ff0-fdb2-11e5-866e-f0126a8efd75.png)

**Comment by danbogos** [comment]
Hi Errol,

Can you confirm whether the memory consumption is related to operating 
calls or due to you loading tariff plans?

DanB

**Comment by ewsamuels** [comment]
Hi DanB,

No we are not loading any tariff plans just calls.  The server is running Nginx, Gunicorn, Postgres, Freeswitch and CGRateS.

Here is another screenshot of the stats approx one hour later.

![screen shot 2016-04-08 at 18 55 27](https://cloud.githubusercontent.com/assets/5496519/14393458/11d45f98-fdbf-11e5-8071-1f5a77ba0c6a.png)

**Comment by ewsamuels** [comment]
Here is another one hour later

![stats3](https://cloud.githubusercontent.com/assets/5496519/14394637/224acbe0-fdc5-11e5-8d90-42a1abbba622.png)

**Comment by rif** [comment]
Please also share the cgrates conf (json file) for this setup.

**Comment by ewsamuels** [comment]
Hi rif,
Here is also a screenshot of stats for today.

![screen shot 2016-04-11 at 20 00 57](https://cloud.githubusercontent.com/assets/5496519/14439022/da596784-0020-11e6-83d6-1c674dc07645.png)

[cgrt_config.txt](https://github.com/cgrates/cgrates/files/213728/cgrt_config.txt)

Regards,

Errol

**Comment by rif** [comment]
Hi Errol,
I see you have cdrstats enable, did you defined any windows for them (time or count)?

**Comment by ewsamuels** [comment]
Hi rif,
We are not using cdrstats as yet and never used it before.

Regards,
Errol

**Comment by ewsamuels** [comment]
Hi Rif,

Starting with new package from 11th April and cdrstats turned off.

root@cgrtbill:/etc/cgrates# ls -l /usr/bin | grep cgr
-rwxr-xr-x 1 root   root    14396928 Apr 11 03:20 cgr-console
-rwxr-xr-x 1 root   root    18607072 Apr 11 03:20 cgr-engine
-rwxr-xr-x 1 root   root    15424928 Apr 11 03:20 cgr-loader
-rwxr-xr-x 1 root   root    14581120 Apr 11 03:20 cgr-tester

![screen shot 2016-04-12 at 11 40 20](https://cloud.githubusercontent.com/assets/5496519/14457603/8133d0bc-00a3-11e6-9b7b-dd3762794587.png)

**Comment by ewsamuels** [comment]
Another one taken at 15:01 hours GMT+1

![screen shot 2016-04-12 at 15 01 51](https://cloud.githubusercontent.com/assets/5496519/14462811/a088f4de-00c0-11e6-9215-a77d093e5162.png)

**Comment by ewsamuels** [comment]
Another taken at 19:15 GMT+1

![screen shot 2016-04-12 at 19 15 23](https://cloud.githubusercontent.com/assets/5496519/14470745/33cd0d3a-00e3-11e6-9f6e-3f7061467631.png)

**Comment by ewsamuels** [comment]
This one taken at 21:08 GMT+1

![screen shot 2016-04-12 at 21 08 37](https://cloud.githubusercontent.com/assets/5496519/14474118/3d8b414c-00f3-11e6-87cf-130f5ce31908.png)

**Comment by ewsamuels** [comment]
End of Day on 12th April 01:50am GMT+1

![screen shot 2016-04-13 at 01 49 24](https://cloud.githubusercontent.com/assets/5496519/14479819/6afd4842-011a-11e6-8de4-aebc4dd39ee8.png)

**Comment by ewsamuels** [comment]
Hi rif,

Just posting this partial log from a CGRateS crash this morning after running out of memory.  Not sure it that helps or if you need more of the log.

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x111aab0, 0x16)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sysMap(0xc92d140000, 0x480000, 0x2000042500, 0x15e33d8)
	/usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0x15c8ca0, 0x480000, 0x1e705a3c0)
	/usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0x15c8ca0, 0x240, 0x0)
	/usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0x15c8ca0, 0x239, 0xc818106300)
	/usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0x15c8ca0, 0x239, 0x100000000, 0x15ca130)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fd2eb0eddb8)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x15c8ca0, 0x239, 0x10100000000, 0xc820014a00)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x470500, 0xc900000000, 0x465ba0)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc820016000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1048

goroutine 2682915 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc925a9ed80 sp=0xc925a9ed78
runtime.mallocgc(0x470500, 0xf9cec0, 0xc900000000, 0xc86dc47430)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc925a9ee58 sp=0xc925a9ed80
runtime.newarray(0xf9cec0, 0x8e0a, 0xc8363cb7a0)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc925a9ee98 sp=0xc925a9ee58
reflect.unsafe_NewArray(0xf9cec0, 0x8e0a, 0xf9cec0)
	/usr/local/go/src/runtime/malloc.go:803 +0x2b fp=0xc925a9eeb8 sp=0xc925a9ee98
reflect.MakeSlice(0x7fd2ee3190a8, 0xd1f780, 0x71a3, 0x8e0a, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:2044 +0x237 fp=0xc925a9ef28 sp=0xc925a9eeb8
reflect.grow(0xd1f780, 0xc887d8a640, 0x197, 0x1, 0x0, 0x0, 0x0, 0xc84a86f0e0, 0xc84a86f0e0)
	/usr/local/go/src/reflect/value.go:1806 +0x1fb fp=0xc925a9efc0 sp=0xc925a9ef28
reflect.Append(0xd1f780, 0xc887d8a640, 0x197, 0xc925a9f2f8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1815 +0x83 fp=0xc925a9f040 sp=0xc925a9efc0
github.com/cgrates/cgrates/vendor/github.com/jinzhu/gorm.queryCallback(0xc865c23100)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/jinzhu/gorm/callback_query.go:76 +0x106c fp=0xc925a9f3f0 sp=0xc925a9f040
github.com/cgrates/cgrates/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc865c23100, 0xc8202316c0, 0x3, 0x4, 0xc865c23100)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/jinzhu/gorm/scope.go:798 +0x68 fp=0xc925a9f430 sp=0xc925a9f3f0
github.com/cgrates/cgrates/vendor/github.com/jinzhu/gorm.(*DB).Find(0xc8a16bd860, 0xce2880, 0xc887d8a640, 0x0, 0x0, 0x0, 0xc8a16bd860)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/jinzhu/gorm/main.go:253 +0xb3 fp=0xc925a9f460 sp=0xc925a9f430
github.com/cgrates/cgrates/engine.(*SQLStorage).GetTpRates(0xc82031e350, 0xc92052d468, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/storage_sql.go:1022 +0x343 fp=0xc925a9f4f8 sp=0xc925a9f460
github.com/cgrates/cgrates/engine.(*TpReader).LoadRates(0xc90a842d80, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/tp_reader.go:144 +0x78 fp=0xc925a9f578 sp=0xc925a9f4f8
github.com/cgrates/cgrates/engine.(*TpReader).LoadAll(0xc90a842d80, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/tp_reader.go:1556 +0xab fp=0xc925a9f5a8 sp=0xc925a9f578
github.com/cgrates/cgrates/apier/v1.(*ApierV1).LoadTariffPlanFromStorDb(0xc831a42000, 0xc92052d468, 0x8, 0x0, 0xc92052d4c0, 0x0, 0x0)
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/apier.go:284 +0x1c3 fp=0xc925a9fa10 sp=0xc925a9f5a8
runtime.call64(0xc89c7c4380, 0x1040b88, 0xc91a4bcd00, 0x2800000038)
	/usr/local/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc925a9fa58 sp=0xc925a9fa10
reflect.Value.call(0xe4af60, 0x1040b88, 0x13, 0x104c2a0, 0x4, 0xc925a9fed8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc925a9fda8 sp=0xc925a9fa58
reflect.Value.Call(0xe4af60, 0x1040b88, 0x13, 0xc925a9fed8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc925a9fe08 sp=0xc925a9fda8
net/rpc.(*service).call(0xc8203d2040, 0xc820132080, 0xc92052d3b0, 0xc840b02680, 0xc91e104320, 0xf25be0, 0xc9296cacc0, 0x199, 0xd11140, 0xc92052d4c0, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x1c2 fp=0xc925a9ff28 sp=0xc925a9fe08
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc925a9ff30 sp=0xc925a9ff28
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x49d

goroutine 1 [chan receive, 2630 minutes]:
main.main()
	/usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:776 +0x1167

goroutine 17 [syscall, 2630 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

**Comment by MarcVoIP** [comment]
hi guys, 
 seems the high memory usage is not just @ewsamuels  issue. Please take a look at this:

`cgr-console cache_stats
{
 "Destinations": 409798,
 "RatingPlans": 10,
 "RatingProfiles": 22,
 "Actions": 0,
 "ActionPlans": 0,
 "SharedGroups": 0,
 "DerivedChargers": 0,
 "LcrProfiles": 8,
 "CdrStats": 16,
 "Users": 6,
 "Aliases": 29,
 "LastLoadId": "7c28b379-a243-4a94-9666-e7de65a8a359",
 "LastLoadTime": "2016-04-26T10:17:46Z"
}`

`cgr-console status
{
 "footprint": 4.5466222e+07,
 "memstat": 2.1409853e+07
}`


I'm using cdrstats. Excerpt from the cgrates.json:
`"cdrstats": {
        "enabled": true,                                                
        "save_interval": "1m",                     
},`

All my stats queues are set for 5 minutes time window only. 
The system handles approximately 300-400 channels for 12 hours a day. 500k call records per day. 
Not sure when cgrates was restarted for the last time, I suspect something like a week or so.

Current RAM usage:   44GB
Suprisingly, it is doing something now even if the server doesn't handle any traffic.
<img width="637" alt="screenshot 2016-04-27 11 02 25" src="https://cloud.githubusercontent.com/assets/17156832/14847244/1643d47c-0c57-11e6-9370-3c6f11ec0b2f.png">


Syslog doesn't show any errors.

**Comment by acheraime** [comment]
Guys,

Any update in regard to this issue? I have to restart my box every other day otherwise it will crash. 
As a reminder this is a dev environment with very low usage.

cgr-console status
{
 "footprint": "574.9MiB",
 "memstat": "472.3MiB"
}

cgr-console cache_stats
{
 "Destinations": 46,
 "RatingPlans": 6,
 "RatingProfiles": 15,
 "Actions": 14,
 "ActionPlans": 11,
 "SharedGroups": 1,
 "DerivedChargers": 1,
 "LcrProfiles": 6,
 "CdrStats": 0,
 "Users": 3,
 "Aliases": 0,
 "LastLoadId": "4f081661-4949-493b-9038-234db5b61584",
 "LastLoadTime": "2016-05-02T07:07:42-04:00"
}

**Comment by superattack** [comment]
We restart it every day and still crashes in live environment. It's nightmare....

**Comment by rif** [comment]
Hopefully this week we eil concentrate on this issue. Please hang on.

**Comment by superattack** [comment]
Good, because we already hired a guy on full-time position just to monitor cgrates. 

Thanks,

**Comment by cgrates** [comment]
:)

**Comment by ewsamuels** [comment]
rif,
I just had cgrates crash and nothing in the strace for the crash, not sure how helpful it will be but here it is:

`
May  9 11:29:36 cgrtbill kernel: [5153458.726317] Out of memory: Kill process 13154 (cgr-engine) score 615 or sacrifice child
May  9 11:29:36 cgrtbill kernel: [5153458.726400] Killed process 13154 (cgr-engine) total-vm:5167256kB, anon-rss:5035916kB, file-rss:3656kB
May  9 11:29:36 cgrtbill kernel: [5153458.734313] cgr-engine invoked oom-killer: gfp_mask=0xd0, order=0, oom_adj=0, oom_score_adj=0
May  9 11:29:36 cgrtbill kernel: [5153458.734316] cgr-engine cpuset=/ mems_allowed=0
May  9 11:29:36 cgrtbill kernel: [5153458.734318] Pid: 13176, comm: cgr-engine Tainted: G           O 3.2.0-4-amd64 #1 Debian 3.2.73-2+deb7u3
May  9 11:29:36 cgrtbill kernel: [5153458.734320] Call Trace:
May  9 11:29:36 cgrtbill kernel: [5153458.734325]  [<ffffffff810b7b82>] ? dump_header+0x78/0x1bd
May  9 11:29:36 cgrtbill kernel: [5153458.734329]  [<ffffffff8135205f>] ? _raw_spin_unlock_irqrestore+0xe/0xf
May  9 11:29:36 cgrtbill kernel: [5153458.734332]  [<ffffffff8109840a>] ? delayacct_end+0x72/0x7d
May  9 11:29:36 cgrtbill kernel: [5153458.734335]  [<ffffffff81165d72>] ? security_real_capable_noaudit+0x40/0x4f
May  9 11:29:36 cgrtbill kernel: [5153458.734337]  [<ffffffff8135205f>] ? _raw_spin_unlock_irqrestore+0xe/0xf
May  9 11:29:36 cgrtbill kernel: [5153458.734339]  [<ffffffff810b7f57>] ? oom_kill_process+0x49/0x26d
May  9 11:29:36 cgrtbill kernel: [5153458.734341]  [<ffffffff810b864e>] ? out_of_memory+0x2ea/0x337
May  9 11:29:36 cgrtbill kernel: [5153458.734343]  [<ffffffff810bc2e6>] ? __alloc_pages_nodemask+0x62a/0x7ab
May  9 11:29:36 cgrtbill kernel: [5153458.734347]  [<ffffffff810ebeb5>] ? kmem_getpages+0x4c/0xd9
May  9 11:29:36 cgrtbill kernel: [5153458.734349]  [<ffffffff810ed264>] ? fallback_alloc+0x13c/0x1dd
May  9 11:29:36 cgrtbill kernel: [5153458.734350]  [<ffffffff810edecd>] ? kmem_cache_alloc+0x73/0xea
May  9 11:29:36 cgrtbill kernel: [5153458.734352]  [<ffffffff81098f77>] ? taskstats_exit+0x53/0x2e0
May  9 11:29:36 cgrtbill kernel: [5153458.734354]  [<ffffffff81352047>] ? _raw_spin_lock_irq+0xa/0x14
May  9 11:29:36 cgrtbill kernel: [5153458.734357]  [<ffffffff8104a08a>] ? do_exit+0x23d/0x717
May  9 11:29:36 cgrtbill kernel: [5153458.734358]  [<ffffffff8104a7e4>] ? do_group_exit+0x74/0x9e
May  9 11:29:36 cgrtbill kernel: [5153458.734361]  [<ffffffff8105637c>] ? get_signal_to_deliver+0x46f/0x491
May  9 11:29:36 cgrtbill kernel: [5153458.734364]  [<ffffffff8100de4f>] ? do_signal+0x38/0x610
May  9 11:29:36 cgrtbill kernel: [5153458.734366]  [<ffffffff8100d75b>] ? __switch_to+0x1f2/0x265
May  9 11:29:36 cgrtbill kernel: [5153458.734370]  [<ffffffff81070033>] ? sys_futex+0x120/0x151
May  9 11:29:36 cgrtbill kernel: [5153458.734372]  [<ffffffff8100e45d>] ? do_notify_resume+0x25/0x68
May  9 11:29:36 cgrtbill kernel: [5153458.734375]  [<ffffffff810fba64>] ? sys_write+0x5f/0x6b
May  9 11:29:36 cgrtbill kernel: [5153458.734377]  [<ffffffff81357380>] ? int_signal+0x12/0x17
May  9 11:29:36 cgrtbill kernel: [5153458.734378] Mem-Info:`

After restarting CGRateS we got this in the strace:

### Started at: Mon May 9 11:30:01 PDT 2016
2016/05/09 11:30:51 method Call has wrong number of ins: 4
2016/05/09 11:30:51 method Call has wrong number of ins: 4
2016/05/09 11:30:51 method LocalProcessCdr has wrong number of ins: 2
2016/05/09 11:30:51 method ProcessExternalCdr has wrong number of ins: 2
2016/05/09 11:30:51 method RateCDRs reply type not a pointer: bool
2016/05/09 11:30:51 method RegisterHandlersToServer has wrong number of ins: 2
2016/05/09 11:30:51 method Timezone has wrong number of ins: 1

Regards,

**Comment by rif** [comment]
Please test with the above mentioned fix and report your results

**Comment by danbogos** [comment]
Hi @ewsamuels 

Please share some feedback regarding whether the issue is still present so we can close this ticket.

Ta,
DanB

**Comment by ewsamuels** [comment]
Hi @danbogos 
I already sent the new heaps to rif on Saturday so perhaps he will be in touch with me tomorrow.

Regards,

Errol

**Comment by ewsamuels** [comment]
Further to my conversation with rif on IRC this morning there should be no further cause for concern.  So closing this ticket.  We will monitor for another week so in the meantime closing this ticket if there is any cause for concern I will open a new ticket.
