### ISSUE TITLE
Date specific Timings not working

### ISSUE THREAD

**Issue by hansgoos** [cgrates/cgrates#424]
Hi,

I'm trying to use date specific Timings to mark calls OFFPEAK during holidays (for example easter).

In my Timings.csv I have the following lines:
ALWAYS,*any,*any,*any,*any,00:00:00
ASAP,*any,*any,*any,*any,*asap
PEAK,*any,*any,*any,1;2;3;4;5,08:00:00
OFFPEAK_MORNING,*any,*any,*any,1;2;3;4;5,00:00:00
OFFPEAK_EVENING,*any,*any,*any,1;2;3;4;5,19:00:00
OFFPEAK_WEEKEND,*any,*any,*any,6;7,00:00:00
OFFPEAK_EASTER,2016,3,28,*any,00:00:00

And in my RatingPlans.csv:
RP_RETAIL1,DR_NETHERLANDS_100CT,PEAK,10
RP_RETAIL1,DR_NETHERLANDS_10CT,OFFPEAK_MORNING,10
RP_RETAIL1,DR_NETHERLANDS_10CT,OFFPEAK_EVENING,10
RP_RETAIL1,DR_NETHERLANDS_10CT,OFFPEAK_WEEKEND,10
RP_RETAIL1,DR_NETHERLANDS_10CT,OFFPEAK_EASTER,9

But calls from 28-March-2016 (Monday) are rated using the PEAK timing. Changing the weight in "RatingPlans.csv" from 9 to 11 doesn't change the behavior.

Tested this using the latest build.

If you need more information please let me know.

PS: attached is my tarrifplan (it's a very simple/basic one)
[tp.tar.gz](https://github.com/cgrates/cgrates/files/212659/tp.tar.gz)

Regards
Hans

**Comment by rif** [comment]
Please change the weight from 9 to 11 and try again.

**Comment by hansgoos** [comment]
Hi Rif,

Just installed the latest version and changed weight to 11. Everything now is working as expected.

Thanks for your help.
Regards
Hans
