### ISSUE TITLE
[CACHE] [socket hang up] replicate to another nodes when destination is down

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4241]
Hi,

The system is fully frozen in case the actual node can not talk to the replication destination with.
Context node 1 want replicate cache to node 2, the node 2 is down.

```
"connCache": {
"strategy": "*broadcast_sync",
  "conns": [
    {
      "address": "x.x.x.x:2013", 
      "transport":"*gob",
      "connect_attempts": 1,
      "reconnects": 1,
      "connect_timeout":"10s",
      "reply_timeout":"3s"
    }
  ],
},
...
"caches":{
  "partitions": {
    ...
    "*attribute_profiles": {"limit": -1, "ttl": "8h", "static_ttl": false, "precache": false, "replicate": true},
    "*attribute_filter_indexes" : {"limit": -1, "ttl": "8h", "static_ttl": false, "replicate": true},
...
  },
  "replication_conns": ["connCache"],
...
```

API answer will never back.
Connect_attempts and reconnects set to -1 can't fix.
Different strategy like first, next, broadcast can't fix.

**Comment by ionutboangiu** [comment]
Hello,

I apologize for the late reply. I've tested with your `rpc_conns` configuration and it works as expected. However, setting `reconnects` to -1 leads to an endless reconnect loop. The `connect_timeout` is reset with each connection attempt and doesn’t stop this loop. Also, `reply_timeout` won't be effective if the node is unreachable.

If the node is back online, reconnection might be slow due to our fibonacci backoff strategy, starting at 10ms. Consider setting a `max_reconnect_interval` to prevent this.

Could you try again with the configuration you've attached and let me know if the issue persists?

Thanks,
Ionuț

**Comment by Integration-IT** [comment]
Hi @ionutboangiu 

Please find additional tests.

Config sample with x.x.x.x is a dead node, cache is only active for *attribute_profiles and *attribute_filter_indexes partitions:
```
"connCache": {
   "strategy": "*broadcast_sync",
   "conns": [
    {
      "address": "x.x.x.x:2013", 
      "transport":"*gob",
      "connect_attempts": 1,
      "reconnects": 1,
      "connect_timeout":"100ms",
      "reply_timeout":"100ms",
      "max_reconnect_interval":"100ms"
    }
  ],
},
```

---
```
systemctl restart cgrates1.service
```

HTTPS POST SessionSv1.AuthorizeEvent with GetAttributes set to false, GetMaxUsage set to true:
- first connection : infinite client loop

HTTPS POST SessionSv1.AuthorizeEvent with GetAttributes set to false, GetMaxUsage set to true:
- second connection : it works

---
```
systemctl restart cgrates1.service
```

HTTPS POST SessionSv1.AuthorizeEvent with GetAttributes set to true, GetMaxUsage set to true:
- first connection : infinite client loop

HTTPS POST SessionSv1.AuthorizeEvent with GetAttributes set to true, GetMaxUsage set to true:
- second connection : infinite client loop
- multiple connections : infinite client loop

---
```
systemctl restart cgrates1.service
```
all hanging clients are relaxed

---
test with different transports, only *gob is relevant:
```
Could not parse config: <<CacheS> unsupported transport <*internal> for connection with ID: <connCache>>
Could not parse config: <<CacheS> unsupported transport <*birpc_internal> for connection with ID: <connCache>>
Could not parse config: <<CacheS> unsupported transport <*birpc_json> for connection with ID: <connCache>>
Could not parse config: <<CacheS> unsupported transport <*birpc_gob> for connection with ID: <connCache>>
Could not parse config: <<CacheS> unsupported transport <*http_jsonrpc> for connection with ID: <connCache>>
```

**Comment by ionutboangiu** [comment]
Hello,

I followed your steps but I still did not manage to reproduce your issue. The setup was pretty basic:

- set an account, a rating profile, a charger profile that doesn't do anything and an attribute profile that matches events containing `"Account": "1001"`.
- here is the config i used: [cgrates.json](https://github.com/cgrates/cgrates/files/14281719/cgrates.json)
- used the following request where I only toggled GetAttributes true/false:
```
{
	"method": "SessionSv1.AuthorizeEvent",
	"params": [{
		"GetAttributes": true,
		"GetMaxUsage": true,
		"Tenant": "cgrates.org",
		"ID": "123456",
		"Time": null,
		"Event": {
			"Account": "1001",
			"Destination": "1002",
			"OriginID": "originID123",
			"RequestType": "*prepaid",
			"SetupTime": "2024-02-13T17:00:00Z",
			"Subject": "1001",
			"Tenant": "cgrates.org",
			"ToR": "*voice",
			"Usage": 300000000000
		}
	}],
	"id": 1
}
```

Replies have either been: `{"id":1,"result":{"MaxUsage":90000000000},"error":null}` when GetAttributes is set to false or `{"id":1,"result":null,"error":"ATTRIBUTES_ERROR:SERVER_ERROR: dial tcp 127.0.0.1:2023: connect: connection refused"}` when set to true, as expected.

 Please let me know if I'm missing something.

Thanks,
Ionuț
