### ISSUE TITLE
CdrsV2.ProcessExternalCdr creating duplicate CGRIDs

### ISSUE THREAD

**Issue by noahmehl** [cgrates/cgrates#428]
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "CdrsV2.ProcessExternalCdr", "params": [{"TOR": "*sms", "AccId": "9d92882f-0d55-47ab-ad97-c3f6f2fa532b", "Direction": "*out", "RequestType": "*pseudoprepaid", "Destination": "5555551112", "Usage": "1", "PDD":"0", "Tenant": "domain.com", "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c"}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": "OK",
  "error": null
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.GetCdrs", "params": [{}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": [
    {
      "CGRID": "95c7e5ccf93f207c64150b0b0b74bfb184c48cb9",
      "RunID": "*raw",
      "OrderID": 1460564147644281900,
      "OriginHost": "",
      "Source": "",
      "OriginID": "",
      "ToR": "*sms",
      "RequestType": "*pseudoprepaid",
      "Direction": "*out",
      "Tenant": "domain.com",
      "Category": "call",
      "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Subject": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Destination": "5555551112",
      "SetupTime": "0001-01-01T00:00:00Z",
      "PDD": "0",
      "AnswerTime": "0001-01-01T00:00:00Z",
      "Usage": "1",
      "Supplier": "",
      "DisconnectCause": "",
      "ExtraFields": {},
      "CostSource": "",
      "Cost": 0,
      "CostDetails": "null",
      "ExtraInfo": "",
      "Rated": false
    },
    {
      "CGRID": "95c7e5ccf93f207c64150b0b0b74bfb184c48cb9",
      "RunID": "*default",
      "OrderID": 1460564147644281900,
      "OriginHost": "",
      "Source": "",
      "OriginID": "",
      "ToR": "*sms",
      "RequestType": "*pseudoprepaid",
      "Direction": "*out",
      "Tenant": "domain.com",
      "Category": "call",
      "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Subject": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Destination": "5555551112",
      "SetupTime": "0001-01-01T00:00:00Z",
      "PDD": "0",
      "AnswerTime": "0001-01-01T00:00:00Z",
      "Usage": "1",
      "Supplier": "",
      "DisconnectCause": "",
      "ExtraFields": {},
      "CostSource": "",
      "Cost": 0,
      "CostDetails": "{\"Direction\":\"*out\",\"Category\":\"call\",\"Tenant\":\"domain.com\",\"Subject\":\"5c1b474f-3a10-48d8-89a4-395a94a95a3c\",\"Account\":\"5c1b474f-3a10-48d8-89a4-395a94a95a3c\",\"Destination\":\"5555551112\",\"TOR\":\"*sms\",\"Cost\":0,\"Timespans\":[{\"TimeStart\":\"0001-01-01T00:00:00Z\",\"TimeEnd\":\"0001-01-01T00:00:01Z\",\"Cost\":0,\"RateInterval\":{\"Timing\":null,\"Rating\":{\"ConnectFee\":0,\"RoundingMethod\":\"\",\"RoundingDecimals\":0,\"MaxCost\":0,\"MaxCostStrategy\":\"\",\"Rates\":[{\"GroupIntervalStart\":0,\"Value\":0,\"RateIncrement\":1000000000,\"RateUnit\":1000000000}]},\"Weight\":0},\"DurationIndex\":0,\"Increments\":[{\"Duration\":1000000000,\"Cost\":0,\"BalanceInfo\":{\"Unit\":{\"UUID\":\"b50bb576-a714-4afe-81a2-ea4c12c0044e\",\"ID\":\"5ccedcc8-38e2-4b02-b53b-013751b73450\",\"Value\":92,\"DestinationID\":\"5555551112\",\"Consumed\":1,\"TOR\":\"*sms\",\"RateInterval\":null},\"Monetary\":null,\"AccountID\":\"domain.com:5c1b474f-3a10-48d8-89a4-395a94a95a3c\"},\"CompressFactor\":1}],\"RoundIncrement\":null,\"MatchedSubject\":\"b50bb576-a714-4afe-81a2-ea4c12c0044e\",\"MatchedPrefix\":\"5555551112\",\"MatchedDestId\":\"*any\",\"RatingPlanId\":\"*none\",\"CompressFactor\":1}],\"RatedUsage\":1}",
      "ExtraInfo": "",
      "Rated": false
    }
  ],
  "error": null
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "CdrsV2.ProcessExternalCdr", "params": [{"TOR": "*sms", "AccId": "146d88b3-070a-469a-ae7a-2008c80bd552", "Direction": "*out", "RequestType": "*pseudoprepaid", "Destination": "5555551112", "Usage": "1", "PDD":"0", "Tenant": "domain.com", "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c"}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": null,
  "error": "SERVER_ERROR: E11000 duplicate key error collection: cgrates-stor.cdrs index: cgrid_1_runid_1 dup key: { : \"95c7e5ccf93f207c64150b0b0b74bfb184c48cb9\", : \"*raw\" }"
}
root@cgrates-test-01:~# curl -s -X POST --data '{"id": 1, "method": "ApierV2.GetCdrs", "params": [{}]}' http://localhost:2080/jsonrpc | jq '.'
{
  "id": 1,
  "result": [
    {
      "CGRID": "95c7e5ccf93f207c64150b0b0b74bfb184c48cb9",
      "RunID": "*raw",
      "OrderID": 1460564147644281900,
      "OriginHost": "",
      "Source": "",
      "OriginID": "",
      "ToR": "*sms",
      "RequestType": "*pseudoprepaid",
      "Direction": "*out",
      "Tenant": "domain.com",
      "Category": "call",
      "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Subject": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Destination": "5555551112",
      "SetupTime": "0001-01-01T00:00:00Z",
      "PDD": "0",
      "AnswerTime": "0001-01-01T00:00:00Z",
      "Usage": "1",
      "Supplier": "",
      "DisconnectCause": "",
      "ExtraFields": {},
      "CostSource": "",
      "Cost": 0,
      "CostDetails": "null",
      "ExtraInfo": "",
      "Rated": false
    },
    {
      "CGRID": "95c7e5ccf93f207c64150b0b0b74bfb184c48cb9",
      "RunID": "*default",
      "OrderID": 1460564147644281900,
      "OriginHost": "",
      "Source": "",
      "OriginID": "",
      "ToR": "*sms",
      "RequestType": "*pseudoprepaid",
      "Direction": "*out",
      "Tenant": "domain.com",
      "Category": "call",
      "Account": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Subject": "5c1b474f-3a10-48d8-89a4-395a94a95a3c",
      "Destination": "5555551112",
      "SetupTime": "0001-01-01T00:00:00Z",
      "PDD": "0",
      "AnswerTime": "0001-01-01T00:00:00Z",
      "Usage": "1",
      "Supplier": "",
      "DisconnectCause": "",
      "ExtraFields": {},
      "CostSource": "",
      "Cost": 0,
      "CostDetails": "{\"Direction\":\"*out\",\"Category\":\"call\",\"Tenant\":\"domain.com\",\"Subject\":\"5c1b474f-3a10-48d8-89a4-395a94a95a3c\",\"Account\":\"5c1b474f-3a10-48d8-89a4-395a94a95a3c\",\"Destination\":\"5555551112\",\"TOR\":\"*sms\",\"Cost\":0,\"Timespans\":[{\"TimeStart\":\"0001-01-01T00:00:00Z\",\"TimeEnd\":\"0001-01-01T00:00:01Z\",\"Cost\":0,\"RateInterval\":{\"Timing\":null,\"Rating\":{\"ConnectFee\":0,\"RoundingMethod\":\"\",\"RoundingDecimals\":0,\"MaxCost\":0,\"MaxCostStrategy\":\"\",\"Rates\":[{\"GroupIntervalStart\":0,\"Value\":0,\"RateIncrement\":1000000000,\"RateUnit\":1000000000}]},\"Weight\":0},\"DurationIndex\":0,\"Increments\":[{\"Duration\":1000000000,\"Cost\":0,\"BalanceInfo\":{\"Unit\":{\"UUID\":\"b50bb576-a714-4afe-81a2-ea4c12c0044e\",\"ID\":\"5ccedcc8-38e2-4b02-b53b-013751b73450\",\"Value\":92,\"DestinationID\":\"5555551112\",\"Consumed\":1,\"TOR\":\"*sms\",\"RateInterval\":null},\"Monetary\":null,\"AccountID\":\"domain.com:5c1b474f-3a10-48d8-89a4-395a94a95a3c\"},\"CompressFactor\":1}],\"RoundIncrement\":null,\"MatchedSubject\":\"b50bb576-a714-4afe-81a2-ea4c12c0044e\",\"MatchedPrefix\":\"5555551112\",\"MatchedDestId\":\"*any\",\"RatingPlanId\":\"*none\",\"CompressFactor\":1}],\"RatedUsage\":1}",
      "ExtraInfo": "",
      "Rated": false
    }
  ],
  "error": null
}

**Comment by noahmehl** [comment]
Actually, no matter how many times I do it, the CDRID is: 95c7e5ccf93f207c64150b0b0b74bfb184c48cb9

Also, I'm using MongoDB :)

**Comment by noahmehl** [comment]
I tried again with "RequestType" and got the same result.

**Comment by danbogos** [comment]
Sorry for the delay, updating the issue with our discussion over IRC:
```
<noahmehl> Oh! Well, when I do the JSON HTTP RPC for processing an external CDR, it always tries to use the same CGRID everytime (at least with MongoDB)
<noahmehl> unless I'm using the API incorrectly
<noahmehl> but, I think CGRID is automatically generated, and I can't set that?
<DanB> yes, you are using it wrongly 
<DanB> check params here:
<noahmehl> lolz
<DanB> https://godoc.org/github.com/cgrates/cgrates/engine#ExternalCDR
<DanB> CGRID is a hash between OriginID and SetupTime
<DanB> if you are not feeding OriginID then we get always same hash
```

DanB
