### ISSUE TITLE
[FEATURE] StoreDB postgresql schema 

### ISSUE THREAD

**Issue by volga629-1** [cgrates/cgrates#4318]
Based on mailing list conversation this is feature request. 

```
Hello Everyone, 
Is possible for store DB postgresql to specify database schema to use ?

Like cgrates.cgrates 


postgres=# \c cgrates
You are now connected to database "cgrates" as user "postgres".
cgrates=# set search_path to cgrates ;
SET
cgrates=# \d
                       List of relations
 Schema  |             Name              |   Type   |  Owner
---------+-------------------------------+----------+----------
 cgrates | cdrs                          | table    |



Thank you

 volga629


```

Reply

```
Currently you cant specify which  database schema to use for postgres storDB.Feel free to open an issue on github so we can look to add in the future.

```

**Comment by volga629-1** [comment]
Thank you, will test it soon.

**Comment by volga629-1** [comment]
is possible to back port  into 0.10.3 branch ?

**Comment by gezimbll** [comment]
Hi @volga629-1 ,

Unfortunately we cannot port it to v0.10 since that branch is only allowed to receive bug fixes.

Thanks,
Gezim

**Comment by volga629-1** [comment]
Thank you. Sent from mobile device typos are expected.On May 7, 2024, at 02:40, gezimbll ***@***.***> wrote:﻿
Hi @volga629-1 ,
Unfortunately we cannot port it to v0.10 since that branch is only allowed to receive bug fixes.
Thanks,
Gezim
