### ISSUE TITLE
Daily debit of monthly payments

### ISSUE THREAD

**Issue by nikbyte** [cgrates/cgrates#433]
Please, add daily debit of monthly actions. So, if we have Actions with monthly price, we must debit it every day partially.

**Comment by danbogos** [comment]
Idea at cold:
Debit action should receive ExtraParams for configuration of the dynamic debits.

Eg: 
{
    "Increments": "*day",
    "Interval": "*month",
}
...
Units: 5

This will translate into: debit the daily equivalent for a monthly cost of 5 units. The algorithm should be able to cope with other Intervals (eg: *year, *month, *week, *day) and other increments (*months, *weeks, *days, *hours as the number of increments in interval).

Example of calculation: 5 /28 if the day is in February in non leap years, or 5/29 in leap years. Additional parameters can be added later (eg: RoudingStrategy).

If no ExtraParameters are specified, the Units 5 is raw debited (as of today code).

DanB

**Comment by rif** [comment]
Example Actions.csv:
```csv
VF,*debit,,,,*monetary,*out,,,,,*unlimited,*any,"{""Method"":""*incremental"",""Params"":{""Units"":10, ""Interval"":""month"", ""Increment"":""day""}}",10,false,false,10
```
Current possible values: 
Increment: day
Interval: year, month, week
