### ISSUE TITLE
Billing only 1 cent per call session, and OpenSIPS failing to handle the method AgentV1.GetActiveSessionIDs.

### ISSUE THREAD

**Issue by PRedemption** [cgrates/cgrates#4339]
# Description:
We are experiencing issues with CGRates where billing is not accurate, and OpenSIPS is failing to handle the method AgentV1.GetActiveSessionIDs. Specifically, when a request is sent to OpenSIPS with the method AgentV1.GetActiveSessionIDs, OpenSIPS fails to reply, indicating it cannot handle the method.

##
T 127.0.0.1:2014 -> 127.0.0.1:48428 [AP] #14
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":2}

#
T 127.0.0.1:2014 -> 127.0.0.1:35772 [AP] #15
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":1}

#
T 127.0.0.1:2014 -> 127.0.0.1:33798 [AP] #16
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":3}

####
T 127.0.0.1:48428 -> 127.0.0.1:2014 [AP] #20
{ "error": "Unknown Method", "result": null, "id": 2 }
#
T 127.0.0.1:35772 -> 127.0.0.1:2014 [AP] #21
{ "error": "Unknown Method", "result": null, "id": 1 }
#
T 127.0.0.1:33798 -> 127.0.0.1:2014 [AP] #22
{ "error": "Unknown Method", "result": null, "id": 3 }
#
T 127.0.0.1:2014 -> 127.0.0.1:33798 [AP] #23
{"method":"AgentV1.DisconnectSession","params":[{"Tenant":"","ID":"aad8c6bd-cf54-467b-b8cb-85d3e6915e11","Time":"2024-05-15T00:46:31.941789426-05:00","Event":{"Account":"xxxxxxxxx","AnswerTime":"1715751991","CGRID":"4b2315e726e723e414f90cacdbf7a7fe0d118520","Destination":"xxxxxxx","DialogEntry":913,"DialogID":374245870,"DisconnectCause":"FORCED_DISCONNECT","OriginHost":"10.110.0.6","OriginID":"0536574699k3u6849m61","RequestType":"*prepaid","SetupTime":"1715751985","Source":"OpenSIPS","Subject":"xxxxxxxxxxx","Usage":3000000000,"UserAgent":"xxx.xx.xxxxx v1.0.5"},"APIOpts":null}],"id":4}

#
T 127.0.0.1:33798 -> 127.0.0.1:2014 [AP] #24
{ "error": "Unknown Method", "result": null, "id": 4 }
#

# OpenSIPS Error:
## OpenSIPS logs errors for the method AgentV1.GetActiveSessionIDs.

# Configuration Changes:
## After modifying cgrates/utils/consts.go to:

const (
        AgentV1                    = "AgentV1"
//      AgentV1DisconnectSession   = "AgentV1.DisconnectSession"
        AgentV1DisconnectSession   = "SessionSv1.DisconnectSession"
//      AgentV1GetActiveSessionIDs = "AgentV1.GetActiveSessionIDs"
        AgentV1GetActiveSessionIDs = "SessionSv1.GetActiveSessionIDs"
        AgentV1AlterSession        = "AgentV1.AlterSession"
        AgentV1DisconnectPeer      = "AgentV1.DisconnectPeer"
//      AgentV1WarnDisconnect      = "AgentV1.WarnDisconnect"
        AgentV1WarnDisconnect      = "SessionSv1.WarnDisconnect"
)

# Billing started to work but now receiving error on balance depletion and terminate session

# cgrates errror 
T 127.0.0.1:2014 -> 127.0.0.1:59136 [AP] #312
{"method":"SessionSv1.DisconnectSession","params":[{"Tenant":"","ID":"e291277d-cbfe-411f-826f-bb6386f8e979","Time":"2024-05-15T01:29:32.745480038-05:00","Event":{"Account":"xxxxxxxx","AnswerTime":"1715754512","CGRID":"c4183413cb815ffd0eec6727dd69d1be3df0060d","Destination":"xxxxxxxxxxxxx","DialogEntry":633,"DialogID":534882206,"DisconnectCause":"FORCED_DISCONNECT","OriginHost":"10.110.0.6","OriginID":"hqtrbw3nofzvfitolp9w","RequestType":"*prepaid","SetupTime":"1715754506","Source":"OpenSIPS","Subject":"xxxxxxxx","Usage":60000000000,"UserAgent":"xx.xx.xx v1.0.5"},"APIOpts":null}],"id":151}

#
T 127.0.0.1:59136 -> 127.0.0.1:2014 [AP] #313
{ "error": "EventStart parameter is invalid or not found", "result": null, "id": 151 }

# opensips error 
 May 15 01:32:20 [1471058] ERROR:cgrates:cgr_acc_terminate: cannot handle terminate: EventStart parameter is invalid or not found
 May 15 01:32:20 [1471058] ERROR:cgrates:cgr_acc_terminate: cannot handle terminate: EventStart parameter is invalid or not found
 May 15 01:32:20 [1471058] ERROR:cgrates:cgr_acc_terminate: cannot handle terminate: EventStart parameter is invalid or not found
 May 15 01:32:20 [1471058] ERROR:cgrates:cgr_acc_terminate: cannot handle terminate: EventStart parameter is invalid or not found

**Comment by PRedemption** [comment]
Thank you for addressing this promptly and resolving the issue. Your swift action is greatly appreciated. I'll be sure to provide feedback after testing it out.

**Comment by PRedemption** [comment]
Hi team
### After testing, I have noticed that the issue persists: the billing is still incorrect, and the following OpenSIPS error continues to appear:

## Opensips error 
May 17 09:55:30 [3073480] ERROR:cgrates:cgrates_process_req: cannot handle method AgentV1.GetActiveSessionIDs
May 17 09:55:30 [3073480] ERROR:cgrates:cgrates_process_req: cannot handle method AgentV1.GetActiveSessionIDs
May 17 09:55:30 [3073480] ERROR:cgrates:cgrates_process_req: cannot handle method AgentV1.GetActiveSessionIDs
May 17 09:55:30 [3073480] ERROR:cgrates:cgrates_process_req: cannot handle method AgentV1.GetActiveSessionIDs

## Cgrates error
T 127.0.0.1:35268 -> 127.0.0.1:2014 [AP] #219
{ "method": "SessionSv1.InitiateSession", "id": 1948843495, "params": [ { "Tenant": "local.xx.xx.zw", "ProcessStatQueues": false, "ProcessThresholds": false, "ReleaseResources": false, "AllocateResources": false, "AuthorizeResources": false, "GetSuppliers": false, "GetAttributes": true, "GetMaxUsage": true, "Event": { "UserAgent": "xxx  v1.0.6", "Subject": "xx.xx", "Source": "OpenSIPS", "OriginHost": "10.110.0.6", "RequestType": "*prepaid", "OriginID": "4q08275081798gtrji29", "DialogID": 628190244, "DialogEntry": 3193, "Account": "101", "SetupTime": "1715932519", "AnswerTime": "1715932529", "Destination": "102" }, "InitSession": true } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:35268 [AP] #220
{"id":1948843495,"result":{"MaxUsage":10800000000000},"error":null}

##
T 127.0.0.1:2014 -> 127.0.0.1:45632 [AP] #222
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":2}

#
T 127.0.0.1:2014 -> 127.0.0.1:54950 [AP] #223
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":1}

#
T 127.0.0.1:2014 -> 127.0.0.1:37276 [AP] #224
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":3}

###
T 127.0.0.1:2014 -> 127.0.0.1:39446 [AP] #227
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":3}

#
T 127.0.0.1:2014 -> 127.0.0.1:35268 [AP] #228
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":1}

#
T 127.0.0.1:2014 -> 127.0.0.1:37284 [AP] #229
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":4}

###
T 127.0.0.1:2014 -> 127.0.0.1:45618 [AP] #232
{"method":"AgentV1.GetActiveSessionIDs","params":[""],"id":2}

##
T 127.0.0.1:37284 -> 127.0.0.1:2014 [AP] #234
{ "error": "Unknown Method", "result": null, "id": 4 }
#
T 127.0.0.1:37276 -> 127.0.0.1:2014 [AP] #235
{ "error": "Unknown Method", "result": null, "id": 3 }
#
T 127.0.0.1:54950 -> 127.0.0.1:2014 [AP] #236
{ "error": "Unknown Method", "result": null, "id": 1 }
#
T 127.0.0.1:45618 -> 127.0.0.1:2014 [AP] #237
{ "error": "Unknown Method", "result": null, "id": 2 }
#
T 127.0.0.1:35268 -> 127.0.0.1:2014 [AP] #238
{ "error": "Unknown Method", "result": null, "id": 1 }
#
T 127.0.0.1:39446 -> 127.0.0.1:2014 [AP] #239
{ "error": "Unknown Method", "result": null, "id": 3 }
##
T 127.0.0.1:45632 -> 127.0.0.1:2014 [AP] #241
{ "error": "Unknown Method", "result": null, "id": 2 }
##
T 127.0.0.1:2014 -> 127.0.0.1:35268 [AP] #243
{"method":"AgentV1.DisconnectSession","params":[{"Tenant":"","ID":"1d78a1b8-f286-401a-9c54-970923c3a653","Time":"2024-05-17T09:55:30.512597747+02:00","Event":{"Account":"101","AnswerTime":"1715932529","CGRID":"d649ce3cc459fb337df7c936edb52ecc1637f193","Destination":"102","DialogEntry":3193,"DialogID":628190244,"DisconnectCause":"FORCED_DISCONNECT","OriginHost":"10.110.0.6","OriginID":"4q08275081798gtrji29","RequestType":"*prepaid","SetupTime":"1715932519","Source":"OpenSIPS","Subject":"41.221.159.214","Usage":3000000000,"UserAgent":"xxxx v1.0.6"},"APIOpts":null}],"id":2}

#
T 127.0.0.1:35268 -> 127.0.0.1:2014 [AP] #244
{ "error": "Unknown Method", "result": null, "id": 2 }
############


## Here is the recommended session configuration for `cgrates.json` based on the client protocol guidelines:
 "sessions": {
        "enabled": true,
        "listen_bijson": "0.0.0.0:2014",
       **"client_protocol": 2.0,**
        "chargers_conns": [
            "*localhost"
        ],
        "rals_conns": [
            "*localhost"
        ],
        "cdrs_conns": [
            "*localhost"
        ],
        "resources_conns": [
            "*localhost"
        ],
        "suppliers_conns": [
            "*localhost"
        ],
        "attributes_conns": [
            "*localhost"
        ],
        "stats_conns": [
            "*localhost"
        ],
        "thresholds_conns": [
            "*localhost"
        ],
        "debit_interval": "3s",
        "channel_sync_interval": "3s"
    },

**Comment by ionutboangiu** [comment]
Just to clarify (since I might not have been completely clear in my previous message), "client_protocol": 2.0 is the current protocol used for all agents except OpenSIPS and isn't compatible with any existing OpenSIPS versions. I realize some might mistake "current" to refer to OpenSIPS instead of CGRates' current implementation (referring to the structure of the RPC requests being sent by SessionS towards the agents).

Setting "client_protocol" to 1.0 (which should be compatible with any OpenSIPS 3.x) in your "sessions" configuration should fix your issue.

Thanks,
Ionuț
