### ISSUE TITLE
 remTPuser

### ISSUE THREAD

**Issue by scipullo** [cgrates/cgrates#435]
HI,
I'm using the ' remTPuser API ( cgratesv8 ) initially he told me that he could not find the column ' tags ' server error , when added on db , the error is gone, but the remTPUser not work

Thank's

**Comment by TeoV** [comment]
Hi @scipullo 
Sorry for the delay but issue somehow slipped down the list.
Can you test it now and come back with a result?

Thanks

**Comment by TeoV** [comment]
This should be resolved
