### ISSUE TITLE
CDRC - Adding support for xml CDRs

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#438]
Useful for XML CDR sources.

DanB

**Comment by danbogos** [comment]
Available in the master.

DanB

**Comment by anthonysomerset** [comment]
Hi @danbogos can you point to example config for this, am looking at this at the moment :)

**Comment by TeoV** [comment]
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/cdrcxmlwithfilter/cgrates.json

**Comment by TeoV** [comment]
Hi @anthonysomerset  
Above I send a sample of config and here is the data used with that sample : 
https://github.com/cgrates/cgrates/blob/master/cdrc/xml_test.go#L34

TeoV
