### ISSUE TITLE
Feature request: API GetTariffPlan

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#439]
Hi DanB,

Further to our chat on IRC earlier I am formally requesting an API call that would allow me to pass the Tenant, Account and Destination number and CGRateS would give me back the Tariff Plan, Rating Subject and the BalanceType so I know whether the call will be using the *monetary balance or the *voice balance. 

For example this scenario has 3 different pricing levels of 1000 minutes each that you thought me how to implement.  Now at any given time when a call is made I want to know which if any of those 3 rate plans will be used or if it will use the normal tariff plan for the call.

curl -X POST -H "Content-Type: application/json" -d '{"method": "ApierV1.AddBalance", "params": 
[{"Tenant":"demo.cgrates.org","Account":"1480270993","BalanceID": " USA_3_CNT","BalanceType":"_voice","Directions":"_out","Value":60000,"Weight":30,"DestinationIds":"United_States","RatingSubject":"USA_3_CNT"}]}' http://localhost:2080/jsonrpc

curl -X POST -H "Content-Type: application/json" -d '{"method": "ApierV1.AddBalance", "params": [{"Tenant":"demo.cgrates.org","Account":"1480270993", "BalanceID": " USA_2_CNT", "BalanceType":"_voice","Directions":"_out","Value":60000,"Weight":20,"DestinationIds":"United_States","RatingSubject":"USA_2_CNT"}]}' http://localhost:2080/jsonrpc

curl -X POST -H "Content-Type: application/json" -d '{"method": "ApierV1.AddBalance", "params": [{"Tenant":"demo.cgrates.org","Account":"1480270993", "BalanceID": " USA_1_CNT", "BalanceType":"_voice","Directions":"_out","Value":60000,"Weight":10,"DestinationIds":"United_States","RatingSubject":"USA_1_CNT"}]}' http://localhost:2080/jsonrpc

Thanks

Errol

**Comment by danbogos** [comment]
hey @ewsamuels 

Since there was no further interest, will close this issue.

DanB
