### ISSUE TITLE
error validating "LoadTariffPlanFromFolder" on api, if it is wrong path

### ISSUE THREAD

**Issue by catokx** [cgrates/cgrates#44]
when i call ApierV1.LoadTariffPlanFromFolder and i pass utils.AttrLoadTpFromFolder item, if the FolderPath value is wrong (eg. a non existant path), the api returns ever OK, here a sample pastebin of the issue captured with ngrep

http://pastebin.com/46vBE9YG

**Comment by danbogos** [comment]
Hi @catokx 

The issue should be fixed in master. There were errors but displayed on syslog only.

DanB
