### ISSUE TITLE
LoadTariffPlanFromStorDb

### ISSUE THREAD

**Issue by scipullo** [cgrates/cgrates#447]
it's my request

"{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV2.LoadTariffPlanFromStorDb\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + "         \"TPid\": \"CGR_API_TESTS\",\n"
                    + "         \"FlushDb\": false,\n"
                    + "         \"DryRun\": false,\n"
                    + "         \"Validate\":true\n"
                    + "     }\n"
                    + " ]\n"
                    + "}";

I do not know why, but making this request , crash cgrates
the gates go down

It works by using this :
"{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV2.LoadTariffPlanFromStorDb\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + "         \"TPid\": \"CGR_API_TESTS\",\n"
                    + "         \"FlushDb\": true,\n"
                    + "         \"DryRun\": true,\n"
                    + "         \"Validate\":true\n"
                    + "     }\n"
                    + " ]\n"
                    + "}";

I'm using the latest version of cgrates , rc8

**Comment by danbogos** [comment]
Hi @scipullo 

Without seeing .strace file (or console crash log) we cannot tell more. Can you please attach that here?

Ta,
DanB

**Comment by scipullo** [comment]
which is the command for cgrates log ?

**Comment by cgrates** [comment]
the .strace file should be located in /var/run/cgrates/cgrates.strace if
you use debian packages. Just attach the last relevant lines here.

Ta,
DanB

**Comment by scipullo** [comment]
I'm using centos7
Now I try them

**Comment by scipullo** [comment]
API 
+ " \"method\": \"ApierV2.LoadTariffPlanFromStorDb\",\n"

strace -e trace=open,read -p 2010 -s 500 -o debug.cgratesApi.txt

[cgrates strace method api ApierV2.LoadTariffPlanFromStorDb.txt](https://github.com/cgrates/cgrates/files/266339/cgrates.strace.method.api.ApierV2.LoadTariffPlanFromStorDb.txt)

**Comment by cgrates** [comment]
Something is not right. There is no dump there.

DanB

**Comment by scipullo** [comment]
i hope this works 


[cgrates strace method api ApierV2.LoadTariffPlanFromStorDb dump.txt](https://github.com/cgrates/cgrates/files/266436/cgrates.strace.method.api.ApierV2.LoadTariffPlanFromStorDb.dump.txt)

**Comment by cgrates** [comment]
Not really. It should be some text specifying where does the code panic.

DanB

**Comment by cgrates** [comment]
Fortunately I see that @J0hnSteel <https://github.com/J0hnSteel> have
already found and fixed the issue with loading from folder.

Will come back with his patch as soon as the tests are passing.

DanB

**Comment by danbogos** [comment]
Long standing issue. Should be fixed by now.

DanB
