### ISSUE TITLE
ApierV1.GetTPAccountAction

### ISSUE THREAD

**Issue by scipullo** [cgrates/cgrates#449]
I take him with this id
  String n = "{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV2.GetTPAccountActionIds\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + "         \"TPid\": \"CGR_API_TESTS\"\n"  
                    + "     }\n"
                    + " ]\n"
                    + "}";

response:"CSVLOAD::cgrates.org:1002".,.....

I try to take a single object with the id just recovered:

  String n = "{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV1.GetTPAccountActions\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + "         \"TPid\": \"CGR_API_TESTS\",\n"
                    + "         \"AccountActionsId\": \"CSVLOAD::cgrates.org:1002\"\n"
                    + "     }\n"
                    + " ]\n"
                    + "}";

response:{"id":39,"result":null,"error":"Wrong TP Account Action Id: CSVLOAD::cgrates.org:1002"}

if you delete a " : " After CSVLOAD , work

example="CSVLOAD:cgrates.org:1002"

request:= "{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV1.GetTPAccountActions\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + "         \"TPid\": \"CGR_API_TESTS\",\n"
                    + "         \"AccountActionsId\": \"CSVLOAD:cgrates.org:1002\"\n"
                    + "     }\n"
                    + " ]\n"
                    + "}";

response:
{"id":39,"result":{"TPid":"CGR_API_TESTS","LoadId":"CSVLOAD","Tenant":"cgrates.org","Account":"1002","ActionPlanId":"PREPAID_10","ActionTriggersId":"STANDARD_TRIGGERS","AllowNegative":false,"Disabled":false},"error":null}

**Comment by TeoV** [comment]
Hi @scipullo,

Should be fixed in master.
https://github.com/cgrates/cgrates/blob/master/apier/v1/tpaccountactions_it_test.go#L56

Thanks,
TeoV
