### ISSUE TITLE
Latest package (24 Feb) crashing with some API calls

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#45]
Hello DanB,

I seem to be having some issues with your latest package dated 24th Feb.
```
>>> connection = CGRConnector()
Connecting to cgr-engine...
>>> from cgrtbilling.json_client import CGRConnector
>>> connection = CGRConnector()
Connecting to cgr-engine...
>>> response = connection.call("ApierV1.SetTPActions",{"ActionsId": "TOPUP_RST_0", "Actions": [{"BalanceWeight": 0.0, "Direction": "*out", "Weight": 20.0, "ExpiryTime": "*unlimited", "DestinationId": "*any", "Units": 0.0, "Identifier": "*topup_reset", "BalanceType": "*monetary"}], "TPid": "DEFAULT"})
('ERROR: ', <type 'exceptions.ValueError'>, ValueError('No JSON object could be decoded',))
Connecting to cgr-engine...
[Errno 111] Connection refused 
```
Then I tried with cgr-loader and got this log:
```
cgr-loader -flushdb -verbose -to_stordb -tpid=DEFAULT -stordb_type="postgres" -stordb_host="127.0.0.1" -stordb_port=5432 -path=/usr/share/tariffplans/
2015/02/27 06:19:15 Processing file: <Actions.csv> 
2015/02/27 06:19:15 Ignoring line 1, warning: <Line starts with comment character.> 
panic: reflect.Value.Addr of unaddressable value

goroutine 16 [running]:
runtime.panic(0x99dca0, 0xc2080dd000)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
reflect.Value.Addr(0x99d220, 0xc208139440, 0x0, 0x62, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/reflect/value.go:345 +0x99
github.com/jinzhu/gorm.Create(0xc208093400)
	/tmp/cgrates/src/github.com/jinzhu/gorm/callback_create.go:73 +0x82b
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc208093400, 0xc20808df00, 0x8, 0x8, 0xb8a7e0)
	/tmp/cgrates/src/github.com/jinzhu/gorm/scope_private.go:297 +0x6b
github.com/jinzhu/gorm.(*DB).Save(0xc20810cdc0, 0xb8a7e0, 0xc208139440, 0xc208139440)
	/tmp/cgrates/src/github.com/jinzhu/gorm/main.go:265 +0x96
github.com/cgrates/cgrates/engine.(*SQLStorage).SetTPActions(0xc20803edc0, 0x7fff2117886a, 0x7, 0xc208116540, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/storage_sql.go:523 +0x521
github.com/cgrates/cgrates/engine.(*TPCSVImporter).importActions(0xc20810a230, 0xc2081163b4, 0xb, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/tpimporter_csv.go:419 +0x2f4
github.com/cgrates/cgrates/engine.(*TPCSVImporter).Run(0xc20810a230, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/tpimporter_csv.go:65 +0x1d3
main.main()
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-loader/cgr-loader.go:127 +0xab0

goroutine 19 [finalizer wait]:
runtime.park(0x4181a0, 0xfe1100, 0xfdf329)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xfe1100, 0xfdf329)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 21 [runnable]:
database/sql.(*DB).connectionOpener(0xc20804a500)
	/usr/local/go/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
	/usr/local/go/src/pkg/database/sql/sql.go:442 +0x27c

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
```
ls -l /usr/bin/ | grep cgr
-rwxr-xr-x 1 root   root    11859552 Feb 24 08:51 cgr-console
-rwxr-xr-x 1 root   root    13990432 Feb 24 08:51 cgr-engine
-rwxr-xr-x 1 root   root    12457504 Feb 24 08:51 cgr-loader
-rwxr-xr-x 1 root   root    11806976 Feb 24 08:51 cgr-tester

Regards

Errol

**Comment by ewsamuels** [comment]
I also tried the older packages which are all using the cgrates.json config with the same issue.  I eventually dropped the database and rolled back to the version dated 4th Dec and works fine.

-rwxr-xr-x 1 root   root     9412096 Dec  4 11:43 cgr-console
-rwxr-xr-x 1 root   root    11489280 Dec  4 11:43 cgr-engine
-rwxr-xr-x 1 root   root     9973216 Dec  4 11:43 cgr-loader
-rwxr-xr-x 1 root   root     9339104 Dec  4 11:43 cgr-tester

regards,

Errol

**Comment by rif** [comment]
Hi Errol, if it's possible send me the tarrif plans that ar generating the error so I can reproduce it. With the file it should go mutch faster.

**Comment by rif** [comment]
Also did you updated database schema with the files from the latest package?

**Comment by ewsamuels** [comment]
Hi rif,
This was actually tested on a clean install so wouldn't the usual database setup script take care of this?
```
cd /usr/share/cgrates/storage/postgres
./setup_cgr_db.sh
```

**Comment by rif** [comment]
No, the cgrates package does not depend on mysql/postgres being installed so it cannot make any action on them. Please update schema and re-test.

**Comment by ewsamuels** [comment]
rif,

Where are the files located to update the schema? 
I only see the files for setup_cgr_db.sh in /usr/share/cgrates/storage/postgres and that is the script I run after I install the cgrates package.

**Comment by rif** [comment]
Yes, that is the right one and only one for postgres.

**Comment by ewsamuels** [comment]
After installing cgrates and redis I run the setup_cgr_db.sh and since it is a clean install from the most recent package we should also have the updated schema - not so?

**Comment by rif** [comment]
Please get the latest package and test again.

**Comment by ewsamuels** [comment]
Hi rif,
This seems to work fine now with new installs but do you have a way to update the schema on existing Postgres installs without losing data?

Thanks
Errol

**Comment by rif** [comment]
We will provide update scripts for the released versions.
For now I guess the best option is to make a diff between the version from december and the current one and perform the alter commands on the tables:

December:
https://github.com/cgrates/cgrates/blob/0bb8691101b9017549cb7a58c931025fba89d0fa/data/storage/postgres/create_tariffplan_tables.sql

Current:
https://github.com/cgrates/cgrates/blob/master/data/storage/postgres/create_tariffplan_tables.sql

**Comment by danbogos** [comment]
Issue confirmed as fixed.
