### ISSUE TITLE
GetTPUserIds

### ISSUE THREAD

**Issue by scipullo** [cgrates/cgrates#451]
I try to make this request:

"{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV2.GetTPUserIds\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + "         \"TPid\": \"CGR_API_TESTS\"\n"  
                    + "     }\n"
                    + " ]\n"
                    + "}";

response :{"id":39,"result":["cgrates.org:"],"error":null}

The user id should not be a string :"cgrates.org:1001"?

for example getTPUser work with "cgrates.org:1001".

**Comment by danbogos** [comment]
hi @scipullo 

Users module was discontinued in between in favor of AttributeS one. Please come back if still issues with new one.

DanB

PS: Sorry for missing the issue.
