### ISSUE TITLE
getCdrs

### ISSUE THREAD

**Issue by scipullo** [cgrates/cgrates#452]
I imported the tariff plan from csv ( testtp )

I added 2- 3 cdr (in db)with +49... destination and destination 222

try this request  "{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV1.GetCdrs\",\n"(or v2)
                    + " \"params\": [\n"
                    + "     {\n"
              +" \"DestinationPrefixes\": [\"222\"]\n"  
                    + "     }\n"
                    + " ]\n"
                    + "}";
**work**,
response:"id":"1637043318","result":[{"CGRID":"1","RunID":"*raw","OrderID":1463470270022166219,"OriginHost":"","Source":"","Or.......

**try another request:**
                    "{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV1.GetCdrs\",\n"(or v2)
                    + " \"params\": [\n"
                    + "     {\n"
              +" \"DestinationPrefixes\": [\"+49\"]\n"  
                    + "     }\n"
                    + " ]\n"
                    + "}";
response:{"id":39,"result":[],"error":null}

i modified destination.csv file ,changing +49 in 49.
i added in cdr with destination 49....

and the request:
 "{\n"
                    + " \"id\": 39,\n"
                    + " \"method\": \"ApierV1.GetCdrs\",\n"
                    + " \"params\": [\n"
                    + "     {\n"
                    + " \"DestinationPrefixes\": [\"49\"]\n"
                    + "     }\n"
                    + " ]\n"
                    + "}";
**work**,
response:"id":"1637043318","result":[{"CGRID":"7","RunID":"*raw","OrderID":1463470270022166219,"OriginHost":"","Source":"","Or.......

I think the problem is the plus  prefix before

thanks in advance

**Comment by danbogos** [comment]
Hi @scipullo 

Sorry for missing your issue here.
Can you please recheck it on master?

Ta,
DanB

**Comment by danbogos** [comment]
Issue looks obsolete.
