### ISSUE TITLE
Tutorial files implemented as API calls with offline TPs

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#455]
Should come up with a full test suite (same as now APierV1 ones) for the tutorial files and make them use the Mongo instead of Redis+MySQL.

DanB

**Comment by iwada** [comment]
@danbogos , I could help with this.
If i understand you perfectly, you looking at reproducing http://cgrates.readthedocs.io/en/latest/apicalls.htmlhttp://cgrates.readthedocs.io/en/latest/apicalls.html with Mongo?

**Comment by danbogos** [comment]
Well, need to reproduce all TP APIs (TP Set/Get + LoadFromStordb) in a 
test file using mongo for all 3 dbs.

Can start from APIs in first part here:
https://github.com/cgrates/cgrates/blob/master/apier/v1/apier_local_test.go

You can make few of them and I can confirm whether you are on right path.

DanB

**Comment by iwada** [comment]
I understand better now

**Comment by danbogos** [comment]
Hi @iwada 

So will you take the task?

DanB

**Comment by danbogos** [comment]
Hi @iwada 

Since there was no feedback from you in the last 5 days, will take the task myself.

DanB

**Comment by iwada** [comment]
Hi @danbogos , apologies on this. Been away a long while. If this is still undone, i'ld see if i can get this done.

**Comment by danbogos** [comment]
Hi @iwada 

No worries. I have already started working on it, so no need for you to do anything for the moment.

Thanks,
DanB
