### ISSUE TITLE
Set Password for MySQL

### ISSUE THREAD

**Issue by HunterNyan** [cgrates/cgrates#456]
"db_passwd" for stordb seems to being set to CGRateS.org even when being specified in the cgrates.json

**Comment by danbogos** [comment]
Hi @HunterNyan 

Can you please elaborate a bit your issue? Did u configure a different password inside MySQL server which you want to use for cgrates user connecting there?

DanB

**Comment by HunterNyan** [comment]
@danbogos That's correct, I set my own username & password for cgrates to use inside MySQL as well as in my cgrates.json. However it appears after some troubleshooting that cgrates forces the password to be 'CGrates.Org' ignoring the customization in the json file.

**Comment by danbogos** [comment]
Which version of cgrates are you u using?
Can you post the db section of your cgrates.json? It could be that you 
are using wrong parameters.

DanB

**Comment by HunterNyan** [comment]
Sure thing.
Version: CGRateS 0.9.1~rc8

JSON that doesn't work:
"stor_db": {                                                                // database used to store offline tariff plans and CDRs
    "db_type": "mysql",                                             // stor database type to use: <mysql|postgres>
    "db_host": "xxx.rds.amazonaws.com",                                 // the host to connect to
    "db_port": 3306,                                                // the port to reach the stordb
    "db_name": "cgrates",                                   // stor database name
    "db_user": "cgrates",                                   // uername to use when connecting to stordb
    "db_passwd": "MyCGratesPassword",                     // password to use when connecting to stordb
    "max_open_conns": 100,                                  // maximum database connections opened
    "max_idle_conns": 10,                                   // maximum database connections idle
},

**Comment by cgrates** [comment]
Try db_passwd -> db_password

You can also have a look and compare with default configuration here:
$src/data/conf/cgrates/cgrates.json

DanB

**Comment by danbogos** [comment]
Closed due to inactivity.

DanB
