### ISSUE TITLE
Getting authentication even if the balance is zero.

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#457]
I see in the FS session variables:
variable_cgr_notify: [+AUTH_OK]

however customer balance is zero. Customer is calling paid destination.

then I see in the cgrates syslog  :  CGRateS[4109]: <Rater> Going negative on account tenant:marctest with AllowNegative: false

Additional info:
cgrates.json configuration under sm_freeswitch:
  "min_call_duration": "6s"

**Comment by danbogos** [comment]
hey @MarcVoIP 

Is this issue still present?

Ta,
DanB

**Comment by danbogos** [comment]
This issue looks obsolete. Should be anyway fixed in the new FreeSWITCHAgent.
