### ISSUE TITLE
 Missing DebitBalance in console

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#458]
There is no option as of now to debit some value from the account directly from the console. 
There is however an API for that:  https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.DebitBalance

Seems there was also console command "balance_debit" some time ago but it is no longer available.

**Comment by rif** [comment]
Did you try debit and debit_max commands?

cgr> help debit

	Usage: debit Direction="*out" Category="" Tenant="" Subject="" Account="" Destination="" TimeStart="0001-01-01T00:00:00Z" TimeEnd="0001-01-01T00:00:00Z" FallbackSubject="" TOR="" DryRun=false

**Comment by MarcVoIP** [comment]
Yes, both these commands allows to debit for the usage however I'm referring to the situation where one wants to debit some value from the account (it is not the call or SMS but just a charge).

**Comment by rif** [comment]
Added back balance_debit please test
