### ISSUE TITLE
 ApierV2.SetTPActions Fails

### ISSUE THREAD

**Issue by iwada** [cgrates/cgrates#459]
With rc8(28/05 build) and Postgres as stor_db, ApierV2.SetTPActions returns

```
ERROR: SERVER_ERROR: pq: column "filter" of relation "tp_actions" does not exist
```

**Comment by TeoV** [comment]
Hey @iwada 
Sorry for the delay but issue somehow slipped down the list.
Can you test it now and come back with a result?

Thanks

**Comment by TeoV** [comment]
This should be resolved
