### ISSUE TITLE
Paginator parameter for ApierV1.GetCdrs gets ignored

### ISSUE THREAD

**Issue by catokx** [cgrates/cgrates#46]
if i specify the Paginator in AttrGetCdrs parameters, the api ignores it and returns ever the same data, here a pastebin of the payload

http://pastebin.com/zw62yBUW

it is with paginator and itemsperpage = 16 and page = 3.
I also activated the mysql log and i have ever the same query applied with any value of the variables of the paginator parameter. I also inspected the source code and it seems to ignore the paginator parameter, but here is specified as available http://godoc.org/github.com/cgrates/cgrates/utils#AttrGetCdrs

**Comment by danbogos** [comment]
@catokx: problem should be fixed in master.

Please note that the Paginator options were changed to stay more flexible on returned values, so you have now Limit (which limits the number of items returned) and Offset - representing the index of the element returned, so in order to reach real pagination you should set offset as value of your pageNumber*limit

Let me us know if any issues.

DanB

**Comment by catokx** [comment]
so theese variables are direct AttrGetCdrs parameters?

**Comment by danbogos** [comment]
They are part of the Paginator object but when calling the JSON API I think you can freely pass them inside your AttrGetCdrs since go will do the matching for you. Simply try adding Limit and Offset to your AttrGetCdrs and see if it does the trick.

**Comment by danbogos** [comment]
@catokx, here is a network capture sample of how should Limit and Offset be used when sent out from JSON-RPC:
```
T 2015/03/03 09:17:43.193498 127.0.0.1:55842 -> 127.0.0.1:2012 [AP]
{"method":"ApierV1.GetTPTimingIds","params":[{"TPid":"TEST_SQL","Limit":100,"Offset":null,"SearchTerm":""}],"id":7}

#
T 2015/03/03 09:17:43.197920 127.0.0.1:2012 -> 127.0.0.1:55842 [AP]
{"id":7,"result":["ALWAYS","ASAP"],"error":null}
```

DanB

**Comment by catokx** [comment]
That is a sample for ApierV1.GetTPTimingIds, what about ApierV1.GetCdrs?

**Comment by danbogos** [comment]
```
{"method":"ApierV1.GetCdrs","params":[{"CgrIds":null,"MediationRunIds":null,"TORs":null,"CdrHosts":null,"CdrSources":null,"ReqTypes":null,"Directions":null,"Tenants":null,"Categories":null,"Accounts":null,"Subjects":null,"DestinationPrefixes":null,"RatedAccounts":null,"RatedSubjects":null,"OrderIdStart":0,"OrderIdEnd":0,"TimeStart":"","TimeEnd":"","SkipErrors":false,"SkipRated":false,"Limit":15,"Offset":30,"SearchTerm":""}],"id":139}
```

**Comment by danbogos** [comment]
@catokx: did u get further progress on pagination issue?

**Comment by danbogos** [comment]
@catokx: was there any news on paginator issue? We would close the ticket due to non response otherwise.

Thanks,
DanB

**Comment by danbogos** [comment]
Hi,

Since there was no answer since more than 2 weeks now will consider the issue fixed. Please reopen if issue is still persistent.

DanB
