### ISSUE TITLE
Configurable cost threshold for Suppliers retrieved via SessionS

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#461]
The goal is to get a list of suppliers for the LCR which are cheaper than the customer cost directly within the Freeswitch SessionManager.

Issue added after consultation with DanB on #cgrates

**Comment by danbogos** [comment]
hi @MarcVoIP 

This feature is available in master using SupplierS. The MaxCost: "*event_cost" will perform revenue protection.
https://godoc.org/github.com/cgrates/cgrates/engine#ArgsGetSuppliers

DanB
