### ISSUE TITLE
ApierV2.CountCdrs possible bug

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#47]
Hi rif,
Further to our chat on IRC here is the note for you.

response = connection.call("ApierV2.CountCdrs",{"Tenants":["my.domain.com"],"Accounts":["3867129383"],"AnswerTimeStart":"2015-02-23T00:00:00Z","AnswerTimeEnd":"2015-03-02T00:00:00Z"})
9:01 PM <esamuels> ('ERROR: ', <type 'exceptions.Exception'>, Exception(u'SERVER_ERROR:pq: R:"check_ungrouped_columns_walker" S:"ERROR" C:"42803" M:"column \\"cdrs_primary.cgrid\\" must appear in the GROUP BY clause or be used in an aggregate function" P:"9" F:"parse_agg.c" L:"1061"',))
9:04 PM <rif> that's one for the issue list, please create an issue on the github

regards,

Errol

**Comment by danbogos** [comment]
Hi Errol,

What version of CGRateS are you running? We have count in our tests and no issues so far.

DanB

**Comment by ewsamuels** [comment]
Sorry, I tested with the wrong version of cgrates.  I meant to close the ticket last night but forgot.
