### ISSUE TITLE
Missing Debian files for packaging from source

### ISSUE THREAD

**Issue by ThomasLobker** [cgrates/cgrates#470]
There is of course a precompiled Debian package available in the repository (without source package) and it installs without problems on different systems including Debian and Ubuntu. But I would like to be able to make changes to the source and recompile, for different architectures or using different libraries, into a fresh Debian package.

Would it be possible to provide the `debian/rules` and `debian/control` files and such in the Git project source? I presume these files are available since you are already providing Debian packages.

It would be appreciated. Thanks!

**Comment by danbogos** [comment]
Hi @ThomasLobker 

The files are part of our soruces. You can check it here:
https://github.com/cgrates/cgrates/tree/master/packages

DanB
