### ISSUE TITLE
Skip Header in csv in CDRC

### ISSUE THREAD

**Issue by HunterNyan** [cgrates/cgrates#476]
Neither the documentation nor the google group clearly explains how I can use regex to skip the first line in my CDR CSV which contains the headers and not the usable rows.

Another option would be to make a configurable option to skip the first X lines.

Thanks.

**Comment by danbogos** [comment]
Hi   @HunterNyan 

You can skip any number of rows by configuring `cdr_filter` option, here:
https://github.com/cgrates/cgrates/blob/master/data/conf/cgrates/cgrates.json#L134

This field is a RSRField type and it takes as field id the index where your condition should match.

DanB

**Comment by HunterNyan** [comment]
Hi @danbogos 

I've been trying to use the cdr_filter but I'm still not exactly sure how to make it exclude the line: Currently I'm trying this: "cdr_filter":"~0:s/^(Unique)$/#${1}/",

Can you please explain what I'm doing wrong?

Thanks,
Hunter

**Comment by danbogos** [comment]
Hi @HunterNyan 

Can you give me a sample of line you want to ignore?

Thanks,
DanB
