### ISSUE TITLE
Feature to temporarily disable a Supplier in LCR

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#477]
Hi rif,
Very often I get customers telling me that they have a provider that is temporarily having technical issues and they are having to remove the Supplier and Rebuild their Tariff Plans because they is no quick way to temporarily disable a Supplier especially when using "Strategy": "*lowest_cost"

Looking at the API Calls for Creating the LCR I see there could be an easy way to do it:

url -X POST -H "Content-Type: application/json" -d '{"method": "ApierV1.SetTPLcrRule","params": [{"TPid": "default_route", "Direction": "*out", "Tenant": "cgrates.org", "Category": "default_route", "Account": "*any", "Subject": "*any", "Rules": [{"DestinationId": "*any", "RpCategory": "default_route", "Strategy": "*lowest_cost", "StrategyParams": "", "ActivationTime": "2016-06-27T18:28:00Z", "Weight": 10.0}]}]}' http://localhost:2080/jsonrpc

So normally when using *priority as the Strategy the values in StrategyParams are considered which makes it easy to remove a supplier temporarily from the LCR if there is an issue.  

However, it appears when using *lowest_cost or *highest_cost the values in StrategyParams are not considered which makes it difficult to temporary remove or disable a supplier who is having issues.
Ideally we would just remove the effected supplier then just Recalculate the LCR without that effected supplier.

What are you thoughts?

Best,

esamuels

**Comment by danbogos** [comment]
Hi @esamuels

The right way to remove a supplier out of a LCR profile is using RemRatingProfile. You can always add it back with another API call. No need of hardcoding any logic in strategy params.

DanB
