### ISSUE TITLE
No Cdr Replication after update to June packages

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#478]
Hello,

After updating to the latest packages in June, we noticed that CDRs are no longer rating and we see the error below in syslog.

CGRateS[14245]: <HttpPoster> Posting to : <>, error: <Post : unsupported protocol scheme

Below is the configuration for cdr_replication that was working before the update.  Not sure what the differences between the May 11th package and the June 17th packages. 

```
    "cdr_replication":[
                    {"transport": "*http_post", "address": "http://cgrates.org:8282/cdr_http/", "attempts": 2, "cdr_filter": "^RunID::*default"},
            ],                                      // replicate the raw CDR to a number of servers
```

Once I reverted back to the May 11th package the cdrs were rated again.

Please advise.

Regards,

ewsamuels

**Comment by danbogos** [comment]
Hey @ewsamuels 

CDR Replication is part of our build tests and I see no issue with it (eg: CDR is properly replicated), so there must be some catch.

Can you maybe compare your configuration with the one we have in the tests bellow?
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/cdrsreplicationmaster/cdrsreplicationmaster.json

Please report your findings.

DanB

**Comment by ewsamuels** [comment]
Hi @DanB,

Yes my config is correct:

 "cdrs": {
        "enabled": true,                                                // start the CDR Server service:  <true|false>
        "extra_fields": [
                "call_uuid","direction","sip_h_X-custom","sip_h_X-site","sip_h_X-dept","sip_h_X-extension","sip_h_X-username","sip_network_ip","original_read_codec","original_read_rate",
                "write_codec","write_rate","effective_caller_id_name","effective_caller_id_number","rtp_audio_in_quality_percentage","rtp_audio_in_mos","progress_mediamsec"
],                                              // extra fields to store in CDRs for non-generic CDRs
        "store_cdrs": false,                                            // store cdrs in storDb
        "rals_conns": [
                {"address": "*internal"}                        // address where to reach the Rater for cost calculation, empty to disable functionality: <""|*internal|x.y.z.y:1234>
        ],
//      "pubsubs_conns": [],                                    // address where to reach the pubusb service, empty to disable pubsub functionality: <""|*internal|x.y.z.y:1234>
//      "users_conns": [],                                              // address where to reach the user service, empty to disable user profile functionality: <""|*internal|x.y.z.y:1234>
//      "aliases_conns": [],                                    // address where to reach the aliases service, empty to disable aliases functionality: <""|*internal|x.y.z.y:1234>
//      "cdrstats_conns": [],                                   // address where to reach the cdrstats service, empty to disable stats functionality<""|*internal|x.y.z.y:1234>
        "cdr_replication":[
                {"transport": "*http_post", "address": "http://cgrates.org:8282/cdr_http/", "attempts": 2},
        ],                                      // replicate the raw CDR to a number of servers
 },

The config above was working before however I did a test on a another Server and I see that the CDRs being replicate but I am getting some http errors because it appears they were changes in how the Replicated CDRs are being sent now.

It seems the slash after cdr_http now causes problems.
 {"transport": "*http_post", "address": "http://cgrates.org:8282/cdr_http/", "attempts": 2},

Are they any changes to the way CDRs are Replicated since May 11 that I need to be aware of?

**Comment by danbogos** [comment]
Hi @errol,

Cannot recall any changes. I also don't understand the differences you 
see. Can you post a sample of "old" vs "new" to be able to spot changes?

Thanks,
DanB

**Comment by ewsamuels** [comment]
Hi @DanB,

There is no old vs new config, its the same cgrates.json config that I am using for both May 11th package that works and the June 28th package where the CDRs are not rated.

I will have to setup a capture to Capture the Replicated CDRs from both packages to see what we are gettings.

I will try to do it today other wise it will be tomorrow.

Thanks

ewsamuels

**Comment by danbogos** [comment]
Yes, this is what I meant also, old vs new in term of CDR format being replicated.

Thank,s
DanB

**Comment by danbogos** [comment]
hey @ewsamuels 

Is this issue still active on your side?
I cannot replicate it here.

DanB

**Comment by ewsamuels** [comment]
@DanB,

Since posting the ticket we went back to the May 11th 2016 package so we
haven't upgraded since that package.

Regards,

Errol

**Comment by danbogos** [comment]
hey @ewsamuels 

OK, feel free to reopen if any issues popping out.

DanB
