### ISSUE TITLE
API ApierV1.RemoveRatingProfile don't work for some cases

### ISSUE THREAD

**Issue by simon-af** [cgrates/cgrates#479]
Hi!

on our production, we are checking slow queries in mongo.
During this check, we observed  some slow query on collection rating_profiles.

Accounts concern by these slow queries concern accounts for which we made a RemoveRatingProfile just before
and 
after checking, we observed that rating profile are in mongo.

i don't know if it change something but in our process, when we make a resiliation,  we remove the account before removing rating profiles.

what do you think about all these observations?

**Comment by simon-af** [comment]
exemple of query:


{
    "op" : "query",
    "ns" : "10.rating_profiles",
    "query" : {
        "find" : "rating_profiles",
        "filter" : {
            "id" : /*out:reglo:call_france:AFM7231092.*/
        },
        "projection" : {
            "id" : 1
        },
        "skip" : 0
    },
    "keysExamined" : 183813,
    "docsExamined" : 0,
    "cursorExhausted" : true,
    "keyUpdates" : 0,
    "writeConflicts" : 0,
    "numYield" : 1436,
    "locks" : {
        "Global" : {
            "acquireCount" : {
                "r" : NumberLong(2874)
            }
        },
        "Database" : {
            "acquireCount" : {
                "r" : NumberLong(1437)
            }
        },
        "Collection" : {
            "acquireCount" : {
                "r" : NumberLong(1437)
            }
        }
    },
    "nreturned" : 0,
    "responseLength" : 124,
    "protocol" : "op_query",
    "millis" : 115,
    "execStats" : {
        "stage" : "PROJECTION",
        "nReturned" : 0,
        "executionTimeMillisEstimate" : 90,
        "works" : 183814,
        "advanced" : 0,
        "needTime" : 183813,
        "needYield" : 0,
        "saveState" : 1436,
        "restoreState" : 1436,
        "isEOF" : 1,
        "invalidates" : 0,
        "transformBy" : {
            "id" : 1
        },
        "inputStage" : {
            "stage" : "FETCH",
            "nReturned" : 0,
            "executionTimeMillisEstimate" : 90,
            "works" : 183814,
            "advanced" : 0,
            "needTime" : 183813,
            "needYield" : 0,
            "saveState" : 1436,
            "restoreState" : 1436,
            "isEOF" : 1,
            "invalidates" : 0,
            "docsExamined" : 0,
            "alreadyHasObj" : 0,
            "inputStage" : {
                "stage" : "IXSCAN",
                "filter" : {
                    "id" : /*out:reglo:call_france:AFM7231092.*/
                },
                "nReturned" : 0,
                "executionTimeMillisEstimate" : 80,
                "works" : 183814,
                "advanced" : 0,
                "needTime" : 183813,
                "needYield" : 0,
                "saveState" : 1436,
                "restoreState" : 1436,
                "isEOF" : 1,
                "invalidates" : 0,
                "keyPattern" : {
                    "id" : 1
                },
                "indexName" : "id_1",
                "isMultiKey" : false,
                "isUnique" : true,
                "isSparse" : false,
                "isPartial" : false,
                "indexVersion" : 1,
                "direction" : "forward",
                "indexBounds" : {
                    "id" : [ 
                        "[\"\", {})", 
                        "[/*out:reglo:call_france:AFM7231092.*/, /*out:reglo:call_france:AFM7231092.*/]"
                    ]
                },
                "keysExamined" : 183813,
                "dupsTested" : 0,
                "dupsDropped" : 0,
                "seenInvalidated" : 0
            }
        }
    },
    "ts" : ISODate("2016-06-30T12:54:03.423Z"),
    "client" : "10.10.41.1",
    "allUsers" : [],
    "user" : ""
}

**Comment by rbarrabe** [comment]
I made a pull request to correct this #540

**Comment by danbogos** [comment]
Great, integrated. Thanks!

DanB
