### ISSUE TITLE
CDRs and API via HTTPS

### ISSUE THREAD

**Issue by AT02020** [cgrates/cgrates#480]
Hello Dan,

As per your suggestion, I am opening a request to get CDRs sent from Freeswitch (JSON_CDR) via HTTPS instead of HTTP.
It would be also beneficial if we can call APIs via HTTPS as well.

Thanks
AT

**Comment by TeoV** [comment]
Hi AT02020,
This feature is available in master.
Please come back if any issues.

Thanks,
TeoV
