### ISSUE TITLE
LCR - ability to ignore suppliers when using SessionManager

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#484]
Following @danbogos advise, opening the issue to include "Ignore Errors" with LCR within SessionManager for Freeswitch.

Background details:
 destinations supported by suppliers depends on their coverage so it happens that the LCR returns error instead of supported list of suppliers if one of the suppliers included in the LCR doesn't support that particular destination.

**Comment by danbogos** [comment]
hey @MarcVoIP 

I finally cached-up with old tickets.

Please re-check with SupplierS module and if issue is still needed, re-open it.

Ta,
DanB
