### ISSUE TITLE
Logger subsystem

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#488]
This new subsystem should have it's own cgrates section of configuration and it should be used to log various parts of CGRateS activity on a selectable medium (dedicated database, syslog/rsyslog or file). It would be useful in case of advanced troubleshooting needed.

It should be a subscriber of pubsubs (subscribe address configurable) and also have subscription rules (again configurable maybe in cgrates.json).

DanB

**Comment by Trial97** [comment]
This is solved by the new subsystem: AnalyzerS
