### ISSUE TITLE
Possible bug in the json_client.py

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#49]
Hi rif,

I have been suspecting for quite some time now that there is a bug in the json_client.py file that you sent me in the zipped app back in October that was probably causing some issues with some API calls. 
So yesterday I made some more tests using this API call using the default json_client.py that you sent me back in October 2014.
> response = connection.call("ApierV1.ExportCdrsToFile",{"ExportDir":"/usr/share/cgrates/cdrs","ExportFileName":"ErrolCDRs.csv","TimeStart":"2015-02-23T00:00:00Z","TimeEnd":"2015-03-09T00:00:00Z"})
Here I noticed that in the resulting ErrolCDRs.csv file I only got 10189 rows.  I decided to increase the buffer size to 8192 as below then I got 35799 rows
> ##### This must loop if resp is bigger than 4K
>         buffer = ''
>         data = True
>         while data:
>             data = self.socket.recv(8192)
>             buffer += data
>             if len(data) < 8192: break
Finally, I decided to increase it even further to 16384 and made the API call again and this time the file produced 51829 rows which turns out to be ALL the CDRs for that period.

Does this seem normal?

Thanks
Errol

**Comment by rif** [comment]
We are using this script ( https://gist.github.com/rif/771c5867badd4912c30b ) in production exporing a lot more CDR than you described with no buffer modification. As long as you have that while loop, the buffer size should not matter concerning getting the whole data.

If you can extract any kind of debug info with the initial buffer size in place it would be great help.

**Comment by ewsamuels** [comment]
Hi rif,
I see there is a slight difference between yours and mine, my has "from threading import Lock" but yours doesn't, is that anything major?

**Comment by rif** [comment]
This script does not need Lock, you must have some more code in the file that does.

**Comment by rif** [comment]
ewsamuels is this still an issue for you?

**Comment by ewsamuels** [comment]
Fixed in the latest package
