### ISSUE TITLE
Crash with API call SetActionPlan

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#50]
Hi DanB,

I am trying to activate a new package with the following API calls but cgrates is crashing:
```
response = connection.call("ApierV1.SetTPActions", {"TPId":"PKG_USA15","ActionsId":"TOPUP_PKG_USA15","Actions":[{"Identifier":"*topup","BalanceType":"*voice","Direction":"*out","Units":15,"ExpiryTime":"*unlimited","DestinationId":"DR_PLAN15USA_United_States","BalanceWeight":20,"Weight":10}]})
```
Then
```
response = connection.call("ApierV1.SetTPActionPlan",{"TPId":"PKG_USA15","Id":"PKG_USA15","ActionPlan":[{"TimingId":"*asap","Weight":10,"ActionsId":"TOPUP_PKG_USA15"}]})
```
Then
```
response = connection.call("ApierV1.SetActionPlan", {"Id":"PKG_USA15","Overwrite":True,"ActionPlan":[{"Time":"*asap","Weight":10,"ActionsId":"TOPUP_PKG_USA15"}]})
```
with this error:
('ERROR: ', <type 'exceptions.ValueError'>, ValueError('No JSON object could be decoded',))
Connecting to cgr-engine...
[Errno 111] Connection refused

##### Started at: Tue Mar 10 06:02:11 CDT 2015

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x488d48]

goroutine 44 [running]:
runtime.panic(0xc29940, 0x116f2f3)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/cgrates/cgrates/apier/v1.(*ApierV1).SetActionPlan(0xc20882dea0, 0xc221ad9677, 0x9, 0xc220249320, 0x1, 0x4, 0x1, 0xc221ad9680, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/cgrates/apier/v1/apier.go:507 +0xa88
reflect.Value.call(0xb36660, 0xcc5728, 0x0, 0x130, 0xce91e0, 0x4, 0xc221ab8e40, 0x3, 0x3, 0x0, ...)
	/usr/local/go/src/pkg/reflect/value.go:563 +0x1210
reflect.Value.Call(0xb36660, 0xcc5728, 0x0, 0x130, 0xc221ab8e40, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/reflect/value.go:411 +0xd7
net/rpc.(*service).call(0xc208098c30, 0xc208043280, 0xc221a95a30, 0xc208856d80, 0xc22134b1c0, 0xc2cf40, 0xc221ad5c50, 0x0, 0x196, 0xa39680, ...)
	/usr/local/go/src/pkg/net/rpc/server.go:382 +0x1c7
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/pkg/net/rpc/server.go:453 +0x427

goroutine 16 [chan receive, 2 minutes]:
main.main()
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:528 +0x156f

goroutine 19 [finalizer wait, 2 minutes]:
runtime.park(0x41ad00, 0x11745c0, 0x11727e9)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x11745c0, 0x11727e9)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 2 minutes]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 22 [chan send, 2 minutes]:
github.com/cgrates/cgrates/balancer2go.func·001()
	/tmp/cgrates/src/github.com/cgrates/cgrates/balancer2go/balancer.go:31 +0x150
created by github.com/cgrates/cgrates/balancer2go.NewBalancer
	/tmp/cgrates/src/github.com/cgrates/cgrates/balancer2go/balancer.go:34 +0xd3

goroutine 23 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc20804e600)
	/usr/local/go/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
	/usr/local/go/src/pkg/database/sql/sql.go:442 +0x27c

goroutine 17 [syscall, 2 minutes]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 39 [IO wait]:
net.runtime_pollWait(0x7f814019f228, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc21ae1b790, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc21ae1b790, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc21ae1b730, 0xeab8c0, 0x0, 0x7f814019e418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:409 +0x343
net.(*TCPListener).AcceptTCP(0xc21eb64190, 0x6, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc21eb64190, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/cgrates/cgrates/engine.(*Server).ServeGOB(0x117cede, 0xc2080e3700, 0xe)
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/server.go:86 +0x2a3
created by main.serveRpc
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:278 +0x105

goroutine 25 [chan receive, 2 minutes]:
main.generalSignalHandler()
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:49 +0x191
created by main.main
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:460 +0xdfd

goroutine 26 [chan receive, 2 minutes]:
github.com/cgrates/cgrates/scheduler.(*Scheduler).Loop(0xc208134210)
	/tmp/cgrates/src/github.com/cgrates/cgrates/scheduler/scheduler.go:44 +0x5d
main.func·001()
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:471 +0xee
created by main.main
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:472 +0xebf

goroutine 38 [IO wait]:
net.runtime_pollWait(0x7f814019f2d8, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc21ae1b640, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc21ae1b640, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc21ae1b5e0, 0xeab8c0, 0x0, 0x7f814019e418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:409 +0x343
net.(*TCPListener).AcceptTCP(0xc21eb64180, 0x10, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc21eb64180, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/cgrates/cgrates/engine.(*Server).ServeJSON(0x117cede, 0xc2080e36e0, 0xe)
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/server.go:64 +0x2a3
created by main.serveRpc
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:277 +0xc9

goroutine 40 [IO wait]:
net.runtime_pollWait(0x7f814019f388, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc21ae1b5d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc21ae1b5d0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc21ae1b570, 0xc221aba000, 0x2000, 0x2000, 0x0, 0x7f814019e418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:232 +0x34c
net.(*conn).Read(0xc21eb641b0, 0xc221aba000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/net.go:122 +0xe7
bufio.(*Reader).fill(0xc221ab8060)
	/usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).ReadSlice(0xc221ab8060, 0xc20802cd0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/bufio/bufio.go:298 +0x22c
bufio.(*Reader).ReadBytes(0xc221ab8060, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/bufio/bufio.go:376 +0xe3
github.com/cgrates/fsock.(*FSock).readHeaders(0xc21d871b00, 0x0, 0x0, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/fsock/fsock.go:221 +0xd7
github.com/cgrates/fsock.(*FSock).readEvent(0xc21d871b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/fsock/fsock.go:261 +0xbb
github.com/cgrates/fsock.(*FSock).readEvents(0xc21d871b00, 0xc221ab8180, 0xc221ab81e0)
	/tmp/cgrates/src/github.com/cgrates/fsock/fsock.go:286 +0x68
created by github.com/cgrates/fsock.(*FSock).Connect
	/tmp/cgrates/src/github.com/cgrates/fsock/fsock.go:435 +0x504

goroutine 31 [chan receive]:
github.com/cgrates/fsock.(*FSock).ReadEvents(0xc21d871b00, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/fsock/fsock.go:494 +0x62
github.com/cgrates/cgrates/sessionmanager.(*FSSessionManager).Connect(0xc21ae1b500, 0x0, 0x0)
	/tmp/cgrates/src/github.com/cgrates/cgrates/sessionmanager/fssessionmanager.go:63 +0x29d
main.startSessionManager(0xc20880ef20, 0x7f81401a0810, 0xc20802a320, 0xc2080055c0)
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:207 +0x45a
created by main.main
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:504 +0x1323

goroutine 33 [chan receive, 2 minutes]:
main.shutdownSessionmanagerSingnalHandler()
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:126 +0x1bd
created by main.main
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:506 +0x1332

goroutine 41 [IO wait]:
net.runtime_pollWait(0x7f814019f0c8, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc21ae1b870, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc21ae1b870, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc21ae1b810, 0xc208094800, 0x200, 0x200, 0x0, 0x7f814019e418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:232 +0x34c
net.(*conn).Read(0xc21eb641c0, 0xc208094800, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/net.go:122 +0xe7
encoding/json.(*Decoder).readValue(0xc20802cea0, 0x7f813ffedbb0, 0x0, 0x0)
	/usr/local/go/src/pkg/encoding/json/stream.go:124 +0x557
encoding/json.(*Decoder).Decode(0xc20802cea0, 0xb8a9e0, 0xc221ab8260, 0x0, 0x0)
	/usr/local/go/src/pkg/encoding/json/stream.go:44 +0x7a
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc221ab8240, 0xc22134b420, 0x0, 0x0)
	/usr/local/go/src/pkg/net/rpc/jsonrpc/server.go:66 +0x9d
net/rpc.(*Server).readRequestHeader(0xc208043280, 0x7f813c2077a0, 0xc221ab8240, 0x0, 0x0, 0xc22134b420, 0xeab900, 0x0, 0x0)
	/usr/local/go/src/pkg/net/rpc/server.go:552 +0x9b
net/rpc.(*Server).readRequest(0xc208043280, 0x7f813c2077a0, 0xc221ab8240, 0xc208856d80, 0xc22134b1c0, 0xc2cf40, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/pkg/net/rpc/server.go:519 +0xbe
net/rpc.(*Server).ServeCodec(0xc208043280, 0x7f813c2077a0, 0xc221ab8240)
	/usr/local/go/src/pkg/net/rpc/server.go:438 +0x69
net/rpc.ServeCodec(0x7f813c2077a0, 0xc221ab8240)
	/usr/local/go/src/pkg/net/rpc/server.go:639 +0x3e
net/rpc/jsonrpc.ServeConn(0x7f813c207740, 0xc21eb641c0)
	/usr/local/go/src/pkg/net/rpc/jsonrpc/server.go:133 +0x53
created by github.com/cgrates/cgrates/engine.(*Server).ServeJSON
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/server.go:71 +0x405

goroutine 35 [IO wait]:
net.runtime_pollWait(0x7f814019f178, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc21ae1b800, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc21ae1b800, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc21ae1b7a0, 0xeab8c0, 0x0, 0x7f814019e418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:409 +0x343
net.(*TCPListener).AcceptTCP(0xc21eb641a0, 0x7f813ffebd00, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net/http.tcpKeepAliveListener.Accept(0xc21eb641a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1947 +0x4b
net/http.(*Server).Serve(0xc221ab8000, 0x7f813c2076e0, 0xc21eb641a0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
net/http.(*Server).ListenAndServe(0xc221ab8000, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1688 +0x14d
net/http.ListenAndServe(0xc2080e3720, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1778 +0x79
github.com/cgrates/cgrates/engine.(*Server).ServeHTTP(0x117cede, 0xc2080e3720, 0xe)
	/tmp/cgrates/src/github.com/cgrates/cgrates/engine/server.go:114 +0x1ef
main.serveHttp(0xc20802a038, 0x1, 0x1)
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:286 +0xc1
created by main.main
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:527 +0x154a
goroutine 36 [chan receive, 2 minutes]:
main.reloadSchedulerSingnalHandler(0xc208134210, 0x7f81401a0450, 0xc2080eb360)
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/registration.go:111 +0x116
created by main.func·001
	/tmp/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-engine/cgr-engine.go:467 +0xa7

I am using the most recent package from 9th Mar 2015.
Let me know if I ave missed anything.
Thanks

Errol

**Comment by danbogos** [comment]
Hi Errol,

The issue should be fixed in the latest master. Please try it and let me know if any issue.

DanB

**Comment by ewsamuels** [comment]
Yes thanks
