### ISSUE TITLE
Add destination name matched in *voice balances

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#51]
Hi DanB,
As per our conversation in the irc channel it would be very useful to Add the match destination in the *voice balances.  In fact it would be good to should the destination name for all call attempts which would be great for reporting purposes.
Regards,
Errol

**Comment by rif** [comment]
Hey Errol,

We put the MatchedDestId in the call cost details, e.g.

"DurationIndex": 60000000000,
"Increments": null,
"MatchedSubject": "*out:cgrates.org:call:1001",
"MatchedPrefix": "1002",
"MatchedDestId": "DST_1002"

If this is not what you are looking for please give more details.

**Comment by ewsamuels** [comment]
Hi rif,
I did a number of test with the most recent update dated today 16th June and it seems we are not getting the MatchedDestination.

Here is the account information:
{
 "Id": "*out:cgrates.org:6889101058",
 "BalanceMap": {
  "*monetary*out": [
   {
    "Uuid": "40adda88-25d3-4009-b928-f39d61590439",
    "Id": "",
    "Value": 19.942004,
    "ExpirationDate": "0001-01-01T00:00:00Z",
    "Weight": 10,
    "DestinationIds": "*any",
    "RatingSubject": "",
    "Category": "",
    "SharedGroup": "",
    "Timings": null,
    "TimingIDs": ""
   }
  ],
  "*voice*out": [
   {
    "Uuid": "9290cee5-4b2e-4e7f-b6f8-d721d5f1c9c8",
    "Id": "",
    "Value": 29580,
    "ExpirationDate": "0001-01-01T00:00:00Z",
    "Weight": 10,
    "DestinationIds": "United_States",
    "RatingSubject": "",
    "Category": "",
    "SharedGroup": "",
    "Timings": null,
    "TimingIDs": ""
   }
  ]
 },
 "UnitCounters": [
  {
   "Direction": "*out",
   "BalanceType": "*monetary",
   "Balances": [
    {
     "Uuid": "",
     "Id": "",
     "Value": 0.0579960000000001,
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationIds": "",
     "RatingSubject": "",
     "Category": "",
     "SharedGroup": "",
     "Timings": null,
     "TimingIDs": ""
    }
   ]
  },
  {
   "Direction": "*out",
   "BalanceType": "*voice",
   "Balances": [
    {
     "Uuid": "",
     "Id": "",
     "Value": 420,
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationIds": "",
     "RatingSubject": "",
     "Category": "",
     "SharedGroup": "",
     "Timings": null,
     "TimingIDs": ""
    }
   ]
  }
 ],
 "ActionTriggers": null,
 "AllowNegative": false,
 "Disabled": false
}

**Here are the details of the call that was made using the voice minutes**

cgrates=> select * from cost_details where cgrid = '59b5214b96f4f9cde48acb06953ef514868b18cf';

id          | 14936
cgrid       | 59b5214b96f4f9cde48acb06953ef514868b18cf
runid       | *default
tor         | *voice
direction   | *out
tenant      | cgrates.org
category    | call_cgr_plat
account     | 6889101058
subject     | 6889101058
destination | 18328003200
cost        | 0.0000
timespans   | [{"TimeStart":"2015-06-16T17:03:13Z","TimeEnd":"2015-06-16T17:10:05Z","Cost":0,"RateInterval":{"Timing":null,"Rating":{"ConnectFee":0,"RoundingMethod":"","RoundingDecimals":0,"MaxCost":0,"MaxCostStrategy":"","Rates":[{"GroupIntervalStart":0,"Value":0,"RateIncrement":1000000000,"RateUnit":1000000000}]},"Weight":0},"DurationIndex":0,"Increments":[{"Duration":1000000000,"Cost":0,"BalanceInfo":{"UnitBalanceUuid":"9290cee5-4b2e-4e7f-b6f8-d721d5f1c9c8","MoneyBalanceUuid":"","AccountId":"*out:cgrates.org:6889101058"},"BalanceRateInterval":null,"UnitInfo":{"DestinationId":"18328003200","Quantity":1,"TOR":"*voice"},"CompressFactor":10}],"MatchedSubject":"","MatchedPrefix":"","MatchedDestId":"","RatingPlanId":""}]
cost_source | SMR
created_at  | 2015-06-16 17:10:12.678605
updated_at  | 2015-06-16 17:10:12.678605
deleted_at  | 0001-01-01 00:00:00

Regards,

Errol

**Comment by ewsamuels** [comment]
Hi rif,
Just confirming this is now fixed in this commit: https://github.com/cgrates/cgrates/commit/bb52349e8f7a6d792c45fff749b753f28dd37847

So closing the ticket.
