### ISSUE TITLE
"cgr-console lcr" returning "Suppliers": null

### ISSUE THREAD

**Issue by J0hnSteel** [cgrates/cgrates#521]
I'm using master version commit 8b6280a6326cb86d623e192a7dae7c2e8da04660. When I first started cgrates it complained and asked for cgr-cloader -migrate". After that step when it started successfully 
Running command:
cgr-console 'lcr Category="MENTAL" Direction="*out" Tenant="mental" Account="testing" Destination="4916275871400" TimeStart="2016-08-29T00:28:00Z" TimeEnd="2016-08-29T00:29:00Z"'
Returned
{
 "DestinationId": "*any",
 "RPCategory": "lcr_MENTAL",
 "Strategy": "*qos",
 "Suppliers": null
}
When I clearly have lcr rules that were successful in the previous version of cgrates from the beginning of the month.  

UPDATE: I've reverted back to commit ae8549e13c4f0bb8482b028ea946cf559cd7a39b and it is working with the old data only version of cgrates changed

**Comment by danbogos** [comment]
Hi @J0hnSteel 

Did u try re-loading your LCRRules/CDRStatsS? There has been a fix in CDRStatS (although should not be related to your issue). 
It will be great if you could test by loading your rules fresh in the latest mater to make sure that the LCR was not broken (maybe just CDRStatS rules).

DanB

**Comment by J0hnSteel** [comment]
@danbogos from redis-cli I did flushall then started the latest master version from cgrates commit ad13dec9e51fae5ed0fa280df0192722b64c08cc and then rpc.call('ApierV1.LoadTariffPlanFromStorDb',{"TPid":"test","Validate":True,"FlushDb":True}) to load all data from DB I got the same result.
Also from cgr-console calling 
cdrstats_metrics StatsQueueId="CDR_1008"
returns
{
 "ACC": -1,
 "ASR": -1
}
suggests to me that cdrstats is working

**Comment by danbogos** [comment]
OK, in order to have suppliers, their status queues need to have data populated (eg: different than -1). Otherwise the supplier will be ignored.

Could it be that your stats were reset when you changed the version?

Thanks,
DanB

**Comment by J0hnSteel** [comment]
The stats that I use are for 1h time window so yes they have reset for sure,but please correct me if I'm wrong as far as I know from documentation if we use LCR with Strategy: *qos if some provider didn't had the chance to process any calls it's stats will be -1 until the first processed call. So with a fresh start shouldn't all providers have -1 in their stats data and equal chance to be chosen from the pull? if it makes any difference the *qos parameter that I use is ASR.

**Comment by danbogos** [comment]
The idea behind this is to be sure you are sending the traffic to the suppliers with expected stats. 
Imagine your calls lasting one day. You will not know if the stats are matching your filters until one day later when the calls will be completed (and CDRs being written) so you could end up with pretty serious losses for 1 day of traffic sent to the wrong/assumed supplier.
A possible fix is to have an alternative route doing "probes" for your suppliers in order to build the stats. That is also the reason you can reuse and customize the stats based on your needs.

Hope it helps.

DanB

**Comment by J0hnSteel** [comment]
OK from your last comment I understand that I need to find a way to populate those stats before using LCR *qos.

**Comment by danbogos** [comment]
Yep, due to it's dynamic nature, you can only populate stats via CDRs so you should either push some "fake" CDRs or use some alternative LCR profile to push traffic towards these stats.

If no more issues (real), I will close the ticket, so feel free to open a new one if anything comes back.

DanB
