### ISSUE TITLE
cgr-loader improvement

### ISSUE THREAD

**Issue by opravil-jan** [cgrates/cgrates#524]
Hello Dan,

in my process of optimization load tariff plans to database(postgresql) I noticed that before each insert of row loader tries to delete the row first. This operation makes the process of tariff plan loading too long. Would be really nice to have parameter in cgr-loader which allows delete whole tariff plan in one delete similar to parameter -flushdb. It makes loading new tariff plan much faster than now. Is it possible to implement?

Thank you

**Comment by danbogos** [comment]
hi @opravil-jan 

This issue should be available now in master.

DanB
