### ISSUE TITLE
Trigger automatic cdr post after mediation

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#53]
Hi Dan,
As per our conversations on IRC I am posting the ticket here as a reminder.
4:43 PM <DanB> esamuels, after each call, not sure whether is productive but you would need to export each call I guess
4:43 PM <DanB> there could be a solution to post the rated cdr to an external server, but that is a feature request again
4:44 PM <DanB> (if you ask me I think it is easier to develop the destination name fixing instead of external cdr posting)
4:44 PM <DanB> but both are doable
4:44 PM <esamuels> DanB, I know that I can capture the Freeswitch CDRs but obviously they won't be rated
4:44 PM <DanB> yes, true
4:45 PM <DanB> but posting the server out is pretty nice feature I think
4:45 PM <esamuels> If I have control of the rated CDRs then I have more flexibility
4:45 PM <esamuels> Especially for Reporting
4:45 PM <esamuels> I have more flexibility to create different types of reports
4:46 PM <DanB> yes and also we take the responsibility of storing the cdr then exporting (we already support do_not_store option in case of non rated cdrs)

regards,
Errol

**Comment by danbogos** [comment]
Hi Errol,

We have pushed a new mechanism which allowes you to replicate rated CDRs once they are rated (close to real-time after being received). Right now we support http post and rpc (http-jsonrpc, jsonrpc and gobrpc).

Please let me know how it works for you.

DanB
