### ISSUE TITLE
Issues on redis timeouts/restart

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#543]
Hey! 

Related to the issues that we have with Redis. So the main problem that we have is when connection did not reconnect when Redis restarts. 

These are the steps to reproduce the issue: 

1- Start Redis
2- Start cgr-engine process
3- Restart Redis
4- Make any API call. 

When this happens, the result is the following: 

```
{"id":"9bd4506a-7c16-11e6-9806-005056a942b8","result":null,"error":"SERVER_ERROR: EOF"}
```
(The example call is ApierV1.LoadTariffPlanFromStorDb)

So, I tried to fix this but is a bit painful. The problem is on Radix.V2 driver.  When Pool.CMD or Pool.Get; Pool.CMD is executed the system didn't check the connection is correct or not. 

Pool.Conn is mainly Redis.Client structure, so from Pool.Conn.Conn can get the TCP status, but all into this are private methods and can't be used at all. 

I tried to make a function that wraps Pool.Cmd as you proposed yesterday, but there is a problem: the error is not different when is a TCP problem or any Redis exception. So if you send a wrong command, you'll never know about that. 

I made today a few workarounds, and I did not find the correct way. For me, the best option is to enable ping on Redis:  you can add, remove, update pools as you want and will work correctly. As you send a ping, you'll know that all the platform works that Redis always return with pong. 

On the other hand, today, meanwhile I was checking the code and I realised that the cgr-engine create two instances of RedisStorage and the system always create two times the maxConns in the system. In our case 200 instead 100. 

So, we do not want to have a fork of this with pings. So if you can advice me about is the solution that you want I'll try to put that in place. 

Regards.

**Comment by danbogos** [comment]
Hey Eloy,

In the wrapper you only need to retry if there is a specific error (EOF). All the others should allow the errors to go back to caller and not retry to the next connection.

Please let me know if clear enough.
DanB

**Comment by eloycoto** [comment]
Hey @danbogos but there are more errors, like connection reset by peer, connection timeout. Not sure that platform need to wrap all of this problems. 

Regards.

**Comment by danbogos** [comment]
Just wrap the ones which you identify and are specific to your case. The rest will come back to the client as they do now, so it is a win already. We will add more in time when we will identify them.

DanB
