### ISSUE TITLE
LCR not working as expected with new cache 

### ISSUE THREAD

**Issue by J0hnSteel** [cgrates/cgrates#546]
The LCR system together with the new caching method does not work as expected and gives odd results.
To reproduce this use the latest master version from cgrates 21.09.2016 is the version that I've tested with.
Tariffplan test data from https://github.com/cgrates/cgrates/tree/master/data/tariffplans/tutorial

redis-cli -> flushall
cgr-loader -verbose -path=(path to the location of the test data)

after the data is loaded execute the following commands in this order

cgr-console 'lcr Category="call" Direction="*out" Tenant="cgrates.org" Account="1006" Destination="1002" TimeStart="2016-09-30T00:28:00Z" TimeEnd="2016-09-30T00:29:00Z"'

cgr-console 'lcr Category="call" Direction="*out" Tenant="cgrates.org" Account="1004" Destination="1001" TimeStart="2016-09-30T00:28:00Z" TimeEnd="2016-09-30T00:29:00Z"'

cgr-console 'lcr Category="call" Direction="*out" Tenant="cgrates.org" Account="1002" Destination="1001" TimeStart="2016-09-30T00:28:00Z" TimeEnd="2016-09-30T00:29:00Z"'

cgr-console 'lcr Category="call" Direction="*out" Tenant="cgrates.org" Account="1001" Destination="1002" TimeStart="2016-09-30T00:28:00Z" TimeEnd="2016-09-30T00:29:00Z"'

as a bonus 

cgr-console 'lcr Category="call" Direction="*out" Tenant="cgrates.org" Account="1020" Destination="1002" TimeStart="2016-09-30T00:28:00Z" TimeEnd="2016-09-30T00:29:00Z"' # this command never runs successfully  

Once we run the LCR request with Account="1001"  and Destination="1002" we get a positive result that returns data. If we try now to run any of the previews LCR requests they return data that we can use.

This is also true for *qos as a strategy 

If we try to use this Tariffplan on cgrates version from 01.08.2016 or somewhere before the new cache was introduced we can call any of the above commands in any order and we'll get a positive result each time.

**Comment by danbogos** [comment]
Hey @J0hnSteel 

Sorry for the delay, there was quite some long list ahead of this one. Please retest and let me know if any issue.

Thanks for your patience!

DanB
