### ISSUE TITLE
Cannot change direction via cdr_http API

### ISSUE THREAD

**Issue by grencik** [cgrates/cgrates#547]
Hi,

when I'm adding a CDR via cdr_http API I cannot change direction of the call. [Here](https://github.com/cgrates/cgrates/blob/25c61b7d650f009f0b91f9408991bff43a5a65c7/engine/cgrcdr.go#L68) I can see that *out direction is hard coded. Is there any reason for this or is this a bug?

Thank you very much :)

Robert

**Comment by danbogos** [comment]
Hi @grencik 

Right now we don't support direction other than *out and that would be the reason in some places in the code we have hardcoded it.
On the other hand, the "Direction" field is not there to really reflect traffic direction but some idea we had in the past of automatic reconciliation.
If you need to bill inbound/outbound calls I suggest you play with category field (you can put there inbound/outbound).

DanB

**Comment by grencik** [comment]
Hi @danbogos 
thanks again :) Even though both directions worked well, I have changed this information to category and the result is the same. Plus now, I can change this information via cdr_http.

Thanks a lot

Robert
