### ISSUE TITLE
Issue with cache_stats  output data

### ISSUE THREAD

**Issue by AT02020** [cgrates/cgrates#561]
Hi Dan,

As we discussed over IRC, I am opening a ticket to look into the issue of returning 11 ReverseDestinations when we run cgr-console  cashe_stats as it showed in below output.
The data loaded into cgrates database has only one destination.

{
 "Destinations": 0,
 "ReverseDestinations": 11,
 "RatingPlans": 1,
 "RatingProfiles": 2,
 "Actions": 0,
 "ActionPlans": 3,
 "SharedGroups": 0,
 "DerivedChargers": 0,
 "LcrProfiles": 0,
 "CdrStats": 0,
 "Users": 0,
 "Aliases": 0,
 "ReverseAliases": 0,
 "ResourceLimits": 0
}

Thanks
AT

**Comment by danbogos** [comment]
hey @AT02020 

Sorry for the delay but was catching up with quite some tasks lately.

Are you aware about the reverse destinations containing the prefixes you have in one destination? Could it be that this is what you saw?

DanB

**Comment by danbogos** [comment]
Obsoleted ticket.

DanB
