### ISSUE TITLE
aliases_matching command broke with the new cache

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#578]
Issue discussed on the channel

LCR query throws {"id":null,"result":null,"error":"SERVER_ERROR: NOT_FOUND"} when using aliases in Account and Subject within the LCR query.

Exemplary requests:
This one works fine: 
'{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"call","Account":"marctest","Subject":"marctest","Destination":"156725142669013"}]}'

This one throws the error: 
'{"method":"ApierV1.GetLcr","params":[{"Direction":"*out","Tenant":"cgrates.org","Category":"call","Account":"myalias","Subject":"myalias","Destination":"156725142669013"}]}'

The alias is created like that:

Params: {"TPid":"20161028115523UPDATEAliasmarctest43","Direction":"_out","Tenant":"cgrates.org","Category":"call","Account":"myalias","Subject":"myalias","Context":"_rating","Values":[{"DestinationId":"_any","Target":"Account","Original":"myalias","Alias":"marctest","Weight":10},{"DestinationId":"_any","Target":"Subject","Original":"myalias","Alias":"marctest","Weight":10}]} Result: {"id":null,"result":"OK","error":null}

**Comment by danbogos** [comment]
hey @MarcVoIP 

I did some tests using latest master and could not reproduce your issue.

Both cgr-console "aliases_matching" as well as LCR work fine with aliases (integrated also both in our test builds).

There must be something specific to your environment.
Would there be possible for you to use .csv files for reproducing the issue? Maybe tutorial files?

Thanks,
DanB

**Comment by danbogos** [comment]
hey @MarcVoIP 

Do you see this issue still there?

Thanks,
DanB

**Comment by MarcVoIP** [comment]
Hi @danbogos 
 I am not able to replicate this on the tutorial files so the issue has to be somewhere in my import process.
I suggest to close the issue.

**Comment by danbogos** [comment]
Thanks!
