### ISSUE TITLE
cgr-loader panic when not using history server

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#579]
Issue reported on the channel:

command: 
cgr-loader -stordb_host 127.0.0.1 -stordb_user root -stordb_passwd pass  -from_stordb -tpid cgrates.org

Result after 1-2 minutes: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x651ccc]

goroutine 2917 [running]:
panic(0xd7ba20, 0xc8200100d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cgrates/cgrates/vendor/github.com/cgrates/rpcclient.(*RpcClient).Call(0xc89fed5730, 0xf6ee40, 0x10, 0xdd2be0, 0xc88be65100, 0xbe1f40, 0xc865045598, 0x7e7aa82c5028, 0xc820011270)
	/root/work/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/rpcclient/rpcclient.go:204 +0x55c
created by github.com/cgrates/cgrates/engine.(*RedisStorage).SetDestination
	/root/work/src/github.com/cgrates/cgrates/engine/storage_redis.go:461 +0x521

Workaround:
  add      -history_server=""  to the cgr-loader command

**Comment by danbogos** [comment]
Fixed in master.

DanB
