### ISSUE TITLE
CDR replication using http_post doesn't include additional fields

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#597]
Following the channel discussion I'm creating an issue regarding CDRs replication.

Config:
  http://pastebin.com/i5Ma20fk

Received replicated CDR:
 http://pastebin.com/ABEkv5Qp

Additional fields are missing:    CostDetails, caller_id_number, rtp_audio_in_quality_percentage, rtp_audio_in_mos

Tested on the current master, built from the source.

**Comment by danbogos** [comment]
FieldID was mixing, fixed.

DanB
