### ISSUE TITLE
Cache - precache doesn't work

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#614]
I’m trying to precache full list of destinations, reverse destinations, etc. to speed up the LCR responses but it is not loading anything from the DB after startup. It takes some extra time to get a response for LCR ,etc
I have tried to  "cache_reload" via cgr-console however the cache_stats result shows 0 for all items.

Config file:

"cache":{
        "destinations": {"limit": 1000000, "ttl":"0s", "precache": true},
        "reverse_destinations": {"limit": 10000000, "ttl":"0s", "precache": true},
        "rating_plans": {"limit": 100000, "ttl":"0s","precache": true},
        "rating_profiles": {"limit": 100000, "ttl":"0s", "precache": true},
        "lcr": {"limit": 1000, "ttl":"0s", "precache": true},
        "cdr_stats": {"limit": 10000, "ttl":"0s", "precache": false},
      "actions": {"limit": 10000, "ttl":"0s", "precache": false},
      "action_plans": {"limit": 10000, "ttl":"0s", "precache": false},
      "action_triggers": {"limit": 10000, "ttl":"0s", "precache": false},
      "shared_groups": {"limit": 10000, "ttl":"0s", "precache": false},
        "aliases": {"limit": 10000, "ttl":"0s", "precache": true},
        "reverse_aliases": {"limit": 10000, "ttl":"0s", "precache": true},
 },

In my case, for 8 suppliers and 400k destinations per supplier the LCR takes around 5-6 seconds to get a response. It is causing high PDD on the service. 

The cache keeps ReverseDestinations after first query so each and every next query for the same destination number gives immediate response .

**Comment by danbogos** [comment]
Hi @MarcVoIP 

Precache will only be effective on start and not on re-load. Right now it clears the cache on re-load as you have correctly noticed it. This was implemented as a shortcut at beginning of the new cache implementation and it remained like this ever since.
The issue on re-load is known and I am currently working for a fix. Will update here when done.

DanB
