### ISSUE TITLE
Loading TP from StorDb resets the cache

### ISSUE THREAD

**Issue by MarcVoIP** [cgrates/cgrates#615]
Scenario:
 1. trying to change the rating profile for one of the accounts, calling the API method in this way:

Method: ApierV1.SetTPLcrRule 
Params: {"TPid":"2016120685022UPDATELCRmarc_test_only94","Direction":"*out","Tenant":"cgrates.org","Category":"call","Account":"marc_test_only","Subject":"marc_test_only","Rules":[{"DestinationId":"*any","RpCategory":"lcrnumbertwo","Strategy":"*lowest_cost","StrategyParams":"","ActivationTime":"2016-12-06T08:50:22Z","Weight":10}]} 
Result: {"id":null,"result":"OK","error":null}

 2. validating the modification:
Method: ApierV1.LoadTariffPlanFromStorDb 
Params: {"TPid":"2016120685022UPDATELCRmarc_test_only94","FlushDb":false,"DryRun":true,"Validate":true} 
Result: {"id":null,"result":"OK","error":null}

 3. Applying the configuration on the data db:
Method: ApierV1.LoadTariffPlanFromStorDb 
Params: {"TPid":"2016120685022UPDATELCRmarc_test_only94","FlushDb":false,"DryRun":false,"Validate":false} 
Result: {"id":null,"result":"OK","error":null}

And now, all the cached items were purged, destinations, reverse destinations, all of them went to 0.

Impact on the production system: 
  When I change the rating profile for one of the accounts the system literally speaking dies. With hundreds of requests per second towards LCR and rater the RAM usage goes high and in my system (64GB RAM machine , using 29GB of RAM for cgrates on normal operation) free RAM is consumed within seconds and the cgrates dies. 
 
In the cgrates version from June 2016 there was no issue like that, I was able to change Rating plans, rating profiles without any issues, there was no delay and cache was keeping the data all the time. 

I'm wondering how it behaves for others who run cgrates under higher load and try to apply some changes like that during the traffic.

**Comment by danbogos** [comment]
Same comment as in #614. Will come back on both when the fix is done.

DanB
