### ISSUE TITLE
AddBalance with negative value...

### ISSUE THREAD

**Issue by pauls1024** [cgrates/cgrates#618]
Using RC8 from git:
apier v1 AddBalance used (old RC7) to accept a -ve value, it now ignores them minus sign and adds the value to the balance.
apier v1 DebitBalance still accepts a -ve value, so one can now use DebitBalance() to add or subtract from a current balance.

It seems counter-intuitive that the following sequence of commands gives a not total of +4 to the account balance... the final AddBalance with value -2 is treated as a +2.

curl -X POST -H "Content-Type: application/json" -d "{\"method\":\"ApierV1.DebitBalance\",\"params\":[{\"Tenant\":\"tenant445\",\"Account\":\"testing\", \"BalanceType\":\"*monetary\", \"BalanceUuid\":\"7d70cc07-2442-47bc-a43a-4ce782879f76\", \"Value\":2}]}" http://127.0.0.1:2080/jsonrpc -v

curl -X POST -H "Content-Type: application/json" -d "{\"method\":\"ApierV1.DebitBalance\",\"params\":[{\"Tenant\":\"tenant445\",\"Account\":\"testing\", \"BalanceType\":\"*monetary\", \"BalanceUuid\":\"7d70cc07-2442-47bc-a43a-4ce782879f76\", \"Value\":-2}]}" http://127.0.0.1:2080/jsonrpc -v

curl -X POST -H "Content-Type: application/json" -d "{\"method\":\"ApierV1.AddBalance\",\"params\":[{\"Tenant\":\"tenant445\",\"Account\":\"testing\", \"BalanceType\":\"*monetary\", \"BalanceUuid\":\"7d70cc07-2442-47bc-a43a-4ce782879f76\", \"Value\":2}]}" http://127.0.0.1:2080/jsonrpc -v

curl -X POST -H "Content-Type: application/json" -d "{\"method\":\"ApierV1.AddBalance\",\"params\":[{\"Tenant\":\"tenant445\",\"Account\":\"testing\", \"BalanceType\":\"*monetary\", \"BalanceUuid\":\"7d70cc07-2442-47bc-a43a-4ce782879f76\", \"Value\":-2}]}" http://127.0.0.1:2080/jsonrpc -v

curl -X POST -H "Content-Type: application/json" -d "{\"method\":\"ApierV2.GetAccount\",\"params\":[{\"Tenant\":\"tenant445\",\"Account\":\"testing\"}]}" http://cgrates:2080/jsonrpc -v

**Comment by danbogos** [comment]
Hi @pauls1024 

We reverted the negative approach with proper method names. Do you mean Debit or Add does not behave?

DanB

**Comment by pauls1024** [comment]
They are inconsistent.
DebitBalance with -ve value increases the balance.  Which is what I expected
AddBalance with -ve value INCREASES the balance too.  Which is unexpected.

Thanks

**Comment by danbogos** [comment]
Well, you should always use positive numbers, no negative.

DanB

**Comment by danbogos** [comment]
Hi @pauls1024 

Did not get your feedback on the issue yet. Are you OK now with Add/Debit balance using only positive numbers?

DanB

**Comment by pauls1024** [comment]
Hi Dan, 
Thanks for the feedback. I have got my app working over the API by replacing all AddBalance() method calls with DebitBalance() calls, and multiplying the value by -1.

In my webapps the ability to call one method with any integer (+ve or -ve) was easier to migrate to in the short term.

I understand that you are not going to "fix"... and that DebitBalance may also stop working with -ve values at some stage as it is an inconsistent and undocumented feature.

I still feel that is confusing that the AddBalance() and DebitBalance() methods are inconsistent, and that the Value parameter in AddBalance() is defined in the docs and API references as a float, but must actually be a positive float.

**Comment by danbogos** [comment]
Paul,

OK I understand what you mean. Will leave this issue here at nice-to-have and come back when I find time to make sure both methods also accept negative values, as per your wish.

Hope that pleases you ;).

DanB

**Comment by pauls1024** [comment]
Thanks Dan.  Keep up the great work!

**Comment by TeoV** [comment]
Hi @pauls1024,

Now when you want to do AddBalance, DebitBalance we add protection for this by taking the absolute value.
(https://github.com/cgrates/cgrates/commit/405b76c8853671d8a7814324cfbaf2b694effddb#diff-eb4b74dd72f8b5fbd4b5a48b437a7b4d ) 

Thanks,
TeoV
