### ISSUE TITLE
(self *ApierV2) ExportTPToFolder

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#622]
Hello

api call:
`{"id": "1", "method": "ApierV2.ExportTPToFolder", "params": [{"FileFormat":"csv","FieldSeparator":",","ExportPath":"/tmp/tp/" }]}`

Panic log:

> goroutine 119 [running]:
> panic(0xfd8d40, 0xc82000e0d0)
>     /usr/local/go/src/runtime/panic.go:464 +0x3e6
> github.com/cgrates/cgrates/apier/v2.(*ApierV2).ExportTPToFolder(0xc82030f710, 0x0, 0xc820426370, 0xc820426390, 0xc8204263a0, 0x0, 0xc820306ab0, 0x0, 0x0)
>     /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v2/tp.go:44 +0x64
> reflect.Value.call(0xf54520, 0x1171c28, 0x13, 0x117c890, 0x4, 0xc820223ef8, 0x3, 0x3, 0x0, 0x0, ...)
>     /usr/local/go/src/reflect/value.go:435 +0x120d
> reflect.Value.Call(0xf54520, 0x1171c28, 0x13, 0xc820223ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
>     /usr/local/go/src/reflect/value.go:303 +0xb1
> net/rpc.(*service).call(0xc8203fe200, 0xc8200156c0, 0xc820426050, 0xc8202ccd00, 0xc820405080, 0x105b160, 0xc820306750, 0x199, 0xdce2a0, 0xc820306ab0, ...)
>     /usr/local/go/src/net/rpc/server.go:383 +0x1c2
> created by net/rpc.(*Server).ServeCodec
>     /usr/local/go/src/net/rpc/server.go:477 +0x49d

**Comment by TeoV** [comment]
Hey @miha- 

Sorry for the delay but issue somehow slipped down the list.
Can you test it now and come back with a result?

Thanks

**Comment by TeoV** [comment]
This should be resolved
