### ISSUE TITLE
REPLY_TIMEOUT, for *data

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#623]
{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params": [{"cgrid":"393","RequestType":"*postpaid","ToR":"*data","Category":"test-voice","Tenant":"softnet-mobil","Account":"38665600615","Destination":"386612356","AnswerTime":"2016-08-03T13:00:00Z","Usage":"3000"}]}

in cdrs (mysql) i get "REPLY_TIMEOUT" in extra_info.

My cdr config: https://github.com/cgrates/cgrates/blob/master/data/conf/samples/tutmysql/cgrates.json

Actions.csv:

Paket_A,*topup_reset,"{""*voice"":60.0,,""*sms"":1.0,""*data"":1048576.0}",,,*generic,*out,,DST_SLO,,,*unlimited,,500,10,false,false,10

If you need anything else please let me know!
br
miha

**Comment by miha-** [comment]
Hey Dan

you to let you know. If I use for data 1024 it works. but I have data from operator in bytes, so I need to put it in mega bytes, so my factor is then "1048576.0".

But with this Factor i does not work.


br
miha

**Comment by miha-** [comment]
Hello

i need to add "reply_timeout" in cgrates.json to bigger value.


tnx
miha

**Comment by miha-** [comment]
Hello

i have used multiply_factoy in cdrc with factor in balances and now it looks ok.


br
miha

**Comment by danbogos** [comment]
Thanks for reporting!

DanB
