### ISSUE TITLE
Issue with RoundingDecimals

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#624]
So, I have 500 shared Units. When i post cdrs via api:
{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params": [{"cgrid":"393","RequestType":"*postpaid","ToR":"*voice","Category":"slo-voice","Tenant":"test-mobil","Account":"38665600615","Destination":"386612356","AnswerTime":"2016-08-03T13:00:00Z","Usage":"1500"}]}

and it should deducte 25 units but new value is: 474.995

Actions.csv
Paket_A,*topup_reset,"{""*voice"":60.0,,""*sms"":1.0,""*data"":1048576.0}",,,*generic,*out,,DST_SLO,,,*unlimited,,500,10,false,false,10
RatingProfiles.csv
*out,test-mobil,slo-voice,*,2016-08-01T00:00:00Z,RP_SLO_VOICE,,
RaingPlan.csv
RP_SLO_VOICE,DR_SLO,*any,10
DestinationRates.csv
DR_SLO,DST_SLO,RT_GENERIC,*up,1,0
Rates.csv
RT_GENERIC,0,1,1,1,0
Destinations.csv
DST_SLO,386

br
miha

**Comment by Trial97** [comment]
Hi @miha- ,

Sorry for delay.
This is happening because of float precision.
To achieve better results please set a bigger value of  `rounding_decimals` in configuration (https://github.com/cgrates/cgrates/blob/master/config/config_defaults.go#L35).

Thanks,
Trial97
