### ISSUE TITLE
High Quality/Qos Low Cost *qos_lowest_cost feature

### ISSUE THREAD

**Issue by J0hnSteel** [cgrates/cgrates#625]
As discussed on IRC there should be a *qos_lowest_cost LCR strategy that will push to top carriers with the lowest cost and highest qos attributes.
To make the job easier I have tried changing 
https://github.com/cgrates/cgrates/blob/master/engine/lcr.go#L538
to **qoss[i].Cost < qoss[j].Cost** and it works but cant tell for sure to what degree

[lcr_test.txt](https://github.com/cgrates/cgrates/files/666067/lcr_test.txt)
this file shows how the strategy works when cdr stats are filled randomly for different carriers
and the output of lcr call after each new cdr stats data
if this is a naive attempt and I do think I miss a step or 2 solution might be present here
https://golang.org/pkg/sort/#example__sortMultiKeys
just can't get my head around it

**Comment by Trial97** [comment]
Available in latest master
