### ISSUE TITLE
Shared units with ToRs and RatingSubject issue

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#626]
Hello

when trying to use RatingSubject so that the call can be deducted and also charged.

test_500,*topup_reset,"{""*voice"":60.0,""*data"":1024.0,""*sms"":1.0,""*mms"":1.0}",,,*generic,*out,,*any,test,,*unlimited,,500,10,false,false,10

*out,test-mobil,slo-sms-mms,test,2016-08-01T00:00:00Z,RP_V_INT_SMS_MMS,,

the issue is that the call gets cost but the balance is not deducted as it should be.

miha

**Comment by danbogos** [comment]
hi @miha- 

Please also attach a CDR replicating your issue on tutorial files.

Thanks,
DanB

**Comment by miha-** [comment]
here is it:)

"Direction":"*out","cgrid":"165","Category":"call","RequestType":"*postpaid","ToR":"*voice","Tenant":"cgrates.org","Account":"1001","Destination":"1002","AnswerTime":"2016-12-03T13:00:00Z","Usage":"120"


*******
{"Direction":"*out","Category":"call","Tenant":"cgrates.org","Subject":"1001","Account":"1001","Destination":"1002","TOR":"*voice","Cost":0.02,"Timespans":[{"TimeStart":"2016-12-03T13:00:00Z","TimeEnd":"2016-12-03T13:02:00Z","Cost":0.02,"RateInterval":{"Timing":{"Years":[],"Months":[],"MonthDays":[],"WeekDays":[],"StartTime":"00:00:00","EndTime":""},"Rating":{"ConnectFee":0,"RoundingMethod":"*up","RoundingDecimals":4,"MaxCost":0,"MaxCostStrategy":"","Rates":[{"GroupIntervalStart":0,"Value":0.01,"RateIncrement":60000000000,"RateUnit":60000000000}]},"Weight":10},"DurationIndex":120000000000,"Increments":[{"Duration":60000000000,"Cost":0.01,"BalanceInfo":{"Unit":null,"Monetary":{"UUID":"6778d0a9-3b73-4e4c-8668-f70a6f903833","ID":"*default","Value":-0.02,"RateInterval":null},"AccountID":"cgrates.org:1001"},"CompressFactor":2}],"RoundIncrement":null,"MatchedSubject":"*out:cgrates.org:call:test","MatchedPrefix":"1002","MatchedDestId":"DST_1002","RatingPlanId":"RP_SPECIAL_1002","CompressFactor":1}],"RatedUsage":120}
***************
{"Tenant":"cgrates.org","ID":"1001","BalanceSummaries":[{"ID":"392cd711-807c-4905-a9b0-c49be1b431ed","Type":"*generic","Value":500,"Disabled":false},{"ID":"*default","Type":"*monetary","Value":-0.02,"Disabled":false}],"AllowNegative":false,"Disabled":false}
***********
IZJEMNI_500,*topup_reset,"{""*voice"":60.0,""*data"":1024.0,""*sms"":1.0,""*mms"":1.0}",,,*generic,*out,,DST_1002,test,,*unlimited,,500,10,false,false,10
************
*out,cgrates.org,call,test,2014-01-14T00:00:00Z,RP_SPECIAL_1002,,

**Comment by danbogos** [comment]
Thanks! Can you also attach the post call which I can use to feed the CDR in?

DanB

**Comment by miha-** [comment]
Hi Dan

here is it:
{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params": [{"Direction":"*out","cgrid":"165","Category":"call","RequestType":"*postpaid","ToR":"*voice","Tenant":"cgrates.org","Account":"1001","Destination":"1002","AnswerTime":"2016-12-03T13:00:00Z","Usage":"120"}]}

**Comment by Trial97** [comment]
Hi @miha-,

We just bumped into this, we will close it as outdated please reopen if needed.

Thanks,
Trial97
