### ISSUE TITLE
(self *ApierV1) GetTPAccountActionIds on RC8

### ISSUE THREAD

**Issue by tstrg** [cgrates/cgrates#629]
I'm using the RC8 and getting error on (self *ApierV1) GetTPAccountActionIds

SERVER_ERROR: Error 1054: Unknown column 'direction' in 'field list

Seems, the MySQL script need to be updated as it was stated in the forum already
https://groups.google.com/forum/#!searchin/cgrates/Unknown$20column$20$27direction$27$20%7Csort:relevance/cgrates/vsK3PpcaD78/qpj5bHHYNQAJ

Request:
`{
"id": 3,
"method": "ApierV1.GetTPAccountActionIds",
"params": [
{
"TPid": "TEST_PLAN"
}
]
}`

Response:
`{
  "id": 3,
  "result": null,
  "error": "SERVER_ERROR: Error 1054: Unknown column 'direction' in 'field list'"
}`

**Comment by danbogos** [comment]
Hey @tstrg 

Thanks for the report. Will check it and revert back most probably during next week. 

DanB

**Comment by TeoV** [comment]
Hi @tstrg 
Sorry for the delay but issue somehow slipped down the list. 
Can you test it now and come back with a result? 

Thanks

**Comment by TeoV** [comment]
This should be resolved
