### ISSUE TITLE
Feature request: voice_multiply_factor

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#631]
Hello

please add also voice_multiply_factor in cgrates.json.

tnx
miha

**Comment by danbogos** [comment]
Hi @miha- 

What should this option do?

Thanks,
DanB

**Comment by miha-** [comment]
Hi Dan

sorry for posting late...

I was thinking now regarding this. I think this can be ignored.


tnx
miha

**Comment by danbogos** [comment]
Sure, np.
Enjoy!
DanB
