### ISSUE TITLE
ApierV1.RemTPLcrRule always returning NOT FOUND error (using MongoDB)

### ISSUE THREAD

**Issue by andmar** [cgrates/cgrates#637]
When using ApierV1.RemTPLcrRule I’m getting a NOT FOUND error for a specific lcr rule id argument, but the same id returns what is supposed to when using ApierV1.GetTPLcrRule, confirming that the id is in fact there.

Used DB (StorDB): MongoDB.
Affected Code (probably): https://github.com/cgrates/cgrates/blob/master/engine/storage_mongo_stordb.go#L412, the 'args' function argument gets a map with a tag key that is passed to the remove function of the mongo lib. The used collection doesn’t have that key in the format (example below) and so the lib returns 'not found'.

> { "_id" : ObjectId("58937084afa538354071e843"), "id" : NumberLong(0), "tpid" : "testtp", "direction" : "*out", "tenant" : "cgrates.org", "category" : "LCR_12313095090499", "account" : "*any", "subject" : "LCR_12313095090499", "destinationtag" : "*any", "rpcategory" : "LCR_DEFAULT", "strategy" : "*highest_cost", "strategyparams" : "BICS;SIPT", "activationtime" : "2014-01-14T00:00:00Z", "weight" : 10, "createdat" : ISODate("0001-01-01T00:00:00Z") }

**Comment by TeoV** [comment]
Hi @andmar 

Sorry for the delay but issue somehow slipped down the list.
Can you test it now and come back with a result?

Thanks

**Comment by TeoV** [comment]
This should be resolved
