### ISSUE TITLE
CGRateS crash with  panic: interface conversion: interface {} is float64, not *float64

### ISSUE THREAD

**Issue by marcinkowalczyk** [cgrates/cgrates#667]
Hi,

 From some time on our test env we can see CGRateS crashes with following in strace

2017/05/10 10:34:54 method Timezone has wrong number of ins: 1
panic: interface conversion: interface {} is float64, not *float64

goroutine 454 [running]:
panic(0x108cac0, 0xc82042b100)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cgrates/cgrates/engine.(*Responder).GetDerivedMaxSessionTime(0xc8202f1740, 0xc820459800, 0xc8203a7870, 0x0, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/engine/responder.go:288 +0x2aa
reflect.Value.call(0x1003140, 0x11e8b78, 0x13, 0x1240a68, 0x4, 0xc820283ee8, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x1003140, 0x11e8b78, 0x13, 0xc820283ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc8202f1780, 0xc82004b680, 0xc8203d7830, 0xc82007dd80, 0xc820369540, 0x1224940, 0xc820459800, 0x16, 0xe53c00, 0xc8203a7870, ...)
        /usr/local/go/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x49d

same happens with build from 3rd May, DB is AWS based Aurora (MySQL5.6). Not sure how to debug this issue. Can you please guide me where to start.

Regards

**Comment by danbogos** [comment]
Hi @marcinkowalczyk 

Please retest using master (have also created another .deb for convenience).

Thanks for reporting!

DanB
