### ISSUE TITLE
Non monetary balance problems

### ISSUE THREAD

**Issue by adamowczarczyk** [cgrates/cgrates#669]
Hi,
I am having an issue trying to force cgrates to debit from minute balances rather than monetary.
When I have any monetary balance on account, the call is debited from that balance.
When I add any minute balance, like so:
`{"method": "ApierV1.AddBalance", "params": [{"Tenant": "mycompany.com","Account":"accountname","BalanceType": "*minutes","Value": 20.0,"Weight": 15,"Overwrite": true}]}`
It still uses the monetary balance rather than minutes.
I fiddled with various Weight values, I set the monetary to `Disabled: true` - still no success. I even removed the monetary balance completely. When I did, the freeswitch tells me there is no balance for that customer, and calls to GetCost return nulls in the Balance section.
Here's my sample minute balance I have on the account:
`"BalanceMap": {
            "*minutes": [
                {
                    "Uuid": "53b5616e-9ec5-4c51-a93f-97794e9f4b39",
                    "ID": "",
                    "Value": 7,
                    "Directions": {},
                    "ExpirationDate": "0001-01-01T00:00:00Z",
                    "Weight": 5,
                    "DestinationIDs": {},
                    "RatingSubject": "",
                    "Categories": {},
                    "SharedGroups": {},
                    "Timings": null,
                    "TimingIDs": {},
                    "Disabled": false,
                    "Factor": null,
                    "Blocker": false
                }
            ],
            "*monetary": []
}`
Is cgrates not respecting non-monetary balances or am I missing something?

**Comment by danbogos** [comment]
hi @adamowczarczyk 

Please add:
 * Your CGRateS version
 * Output of accounts command.
 * Sample CDR (with call cost attached).

DanB

**Comment by adamowczarczyk** [comment]
Hi dan,

Cgrates version: rc8
GetAccount:
`{
    "id": null,
    "result": {
        "ID": "mycompany.com:accountname",
        "BalanceMap": {
            "*minutes": [
                {
                    "Uuid": "53b5616e-9ec5-4c51-a93f-97794e9f4b39",
                    "ID": "",
                    "Value": 7,
                    "Directions": {},
                    "ExpirationDate": "0001-01-01T00:00:00Z",
                    "Weight": 5,
                    "DestinationIDs": {},
                    "RatingSubject": "",
                    "Categories": {},
                    "SharedGroups": {},
                    "Timings": null,
                    "TimingIDs": {},
                    "Disabled": false,
                    "Factor": null,
                    "Blocker": false
                },
                {
                    "Uuid": "841f0d73-a2a1-4cf1-83ca-6e3b51f38416",
                    "ID": "",
                    "Value": 20,
                    "Directions": {},
                    "ExpirationDate": "0001-01-01T00:00:00Z",
                    "Weight": 15,
                    "DestinationIDs": {},
                    "RatingSubject": "",
                    "Categories": {},
                    "SharedGroups": {},
                    "Timings": null,
                    "TimingIDs": {},
                    "Disabled": false,
                    "Factor": null,
                    "Blocker": false
                },
                {
                    "Uuid": "7fb96e67-ea1f-4fb6-b269-07cd74dcd12f",
                    "ID": "",
                    "Value": 180,
                    "Directions": null,
                    "ExpirationDate": "0001-01-01T00:00:00Z",
                    "Weight": 7,
                    "DestinationIDs": null,
                    "RatingSubject": "",
                    "Categories": null,
                    "SharedGroups": null,
                    "Timings": null,
                    "TimingIDs": null,
                    "Disabled": false,
                    "Factor": null,
                    "Blocker": false
                }
            ],
            "*monetary": []
        },
        "UnitCounters": null,
        "ActionTriggers": null,
        "AllowNegative": false,
        "Disabled": false
    },
    "error": null
}`

Sample GetCost result:

`
{
    "id": 1,
    "result": {
        "Direction": "*out",
        "Category": "call",
        "Tenant": "mycompany.com",
        "Subject": "accountname",
        "Account": "",
        "Destination": "48334983735",
        "TOR": "*voice",
        "Cost": 0.025,
        "Timespans": [
            {
                "TimeStart": "2017-01-12T13:39:16Z",
                "TimeEnd": "2017-01-12T13:41:32Z",
                "Cost": 0.0249333288,
                "RateInterval": {
                    "Timing": {
                        "Years": [],
                        "Months": [],
                        "MonthDays": [],
                        "WeekDays": [],
                        "StartTime": "00:00:00",
                        "EndTime": ""
                    },
                    "Rating": {
                        "ConnectFee": 0,
                        "RoundingMethod": "*up",
                        "RoundingDecimals": 4,
                        "MaxCost": 0,
                        "MaxCostStrategy": "",
                        "Rates": [
                            {
                                "GroupIntervalStart": 0,
                                "Value": 0.011,
                                "RateIncrement": 1000000000,
                                "RateUnit": 60000000000
                            }
                        ]
                    },
                    "Weight": 10
                },
                "DurationIndex": 136000000000,
                "Increments": [
                    {
                        "Duration": 1000000000,
                        "Cost": 0.0001833333,
                        "BalanceInfo": {
                            "Unit": null,
                            "Monetary": null,
                            "AccountID": ""
                        },
                        "CompressFactor": 136
                    }
                ],
                "RoundIncrement": null,
                "MatchedSubject": "*out:mycompany.com:call:*any",
                "MatchedPrefix": "48",
                "MatchedDestId": "PL_Fixed",
                "RatingPlanId": "RP_RETAIL",
                "CompressFactor": 1
            }
        ],
        "RatedUsage": 136
    },
    "error": null
}
`

**Comment by danbogos** [comment]
Hi @adamowczarczyk 

Try adding Direction "*out" to your balances. Could it be that this is the reason it does not work since they don't match.

DanB

**Comment by adamowczarczyk** [comment]
As per our chat with Dan, the issue was I was using balancetype *minutes, which does not exist.
For future reference (and google bots):
There is a distinction between BalanceTags and BalanceTypes. BalanceTag dictionary is currently: MONETARY, SMS, INTERNET, INTERNET_TIME, MINUTES
While BalanceTypes dictionary is currently:
*voice, *sms, *data, *monetary

After adding balance of type *voice instead of nonexistent *minutes, the charging works correctly.
