### ISSUE TITLE
CDR database on LevelDB with indexing over bleve

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#67]
In order to be even faster, we are investigating some more modern CDR storing/indexing technologies. An agreed solution is using a fast key/value store like LevelDB indexed with bleve inside CGRateS subsystem.

DanB

**Comment by rif** [comment]
After research it seems this is not a very good solution because we are not using the full text search capabilities in this case. I will continue to investigate the benefits of using mongodb instead.

**Comment by rif** [comment]
Closing this in favor of #237.
