### ISSUE TITLE
Cgrates Authorizing a Destination which does not exist

### ISSUE THREAD

**Issue by aqsyounas** [cgrates/cgrates#670]
During the learning process i have done some modification in default CSVs provided with tutorial. But when i try to call a destination number which does not exit in Destionations.csv I still get +AUTH_OK in freeswitch logs. It should not be the case. Logs are below. 

1. Syslog on Starting cgrates
https://pastebin.freeswitch.org/view/2e8f7e2b

2. Sylog upon populating tariff
https://pastebin.freeswitch.org/view/38adef35

3. cgr-loader -verbose
https://pastebin.freeswitch.org/view/a37c27f0

4. Syslog when call is made on a destionation which does not exist in Destinations.csv file
May  9 19:25:12 debian CGRateS <6b9cd381-d993-4f80-b04d-d9f839838dc4> [8984]: Destination 1004 not authorized for account: cgrates.org:, subject: *out:cgrates.org:call:

5. console status
root@debian:/opt/cgrate_tarrif# cgr-console status
{
 "ActiveGoroutines": 26,
 "Footprint": "10.4MiB",
 "InstanceID": "6b9cd381-d993-4f80-b04d-d9f839838dc4",
 "MemoryUsage": "1.9MiB"
}
 
6. ngrep -t -W byline port 8021 -d any > /tmp/new.txt
https://pastebin.freeswitch.org/view/e7996519

I can clearly see cgrates executing two commands on UUID in ngrep

    T 2017/05/09 19:25:12.756350 127.0.0.1:56978 -> 127.0.0.1:8021 [AP]
    api uuid_setvar a199e33c-386e-4899-bb7a-7df6811c9606 cgr_notify +AUTH_OK

and

    T 2017/05/09 19:25:12.756915 127.0.0.1:56978 -> 127.0.0.1:8021 [AP]
    api uuid_transfer a199e33c-386e-4899-bb7a-7df6811c9606 1004

Please let me know if you need anything else. 
Best Regards.

**Comment by danbogos** [comment]
Based on google group discussion, it turns out that your requests are not set on prepaid, hence the call being allowed by CGRateS (we only authorize calls which are either *prepaid or *pseudoprepaid).

DanB
