### ISSUE TITLE
Bidirectional JSON bug

### ISSUE THREAD

**Issue by andey-ch** [cgrates/cgrates#674]
CGRateS 0.9.1~rc8,
bidirectional JSON inerface going down when sending JSON request to port 2014.

Config:
`"sm_generic": {
	"enabled": true,
	"listen_bijson": "127.0.0.1:2014",
	"debit_interval": "10s",
	"rals_conns": [
 		{"address": "*internal"}
 	],
 	"cdrs_conns": [
 		{"address": "*internal"}
 	],
},
`

Request:
`{"method":"ApierV1.GetAccounts","params":[{"Tenant":"sip.examle.com","AccountIds":["1001"]}],"id":51}`

Log:
May 24 11:34:51 trace /usr/sbin/opensips[8277]: ERROR:cgrates:cgrc_async_read: read() failed with 104(Connection reset by peer)#012 from 127.0.0.1:2014
May 24 11:34:51 trace /usr/sbin/opensips[8277]: INFO:cgrates:cgrc_close: closing connection 127.0.0.1:2014
May 24 11:34:51 trace /usr/sbin/opensips[8281]: ERROR:cgrates:cgrc_async_read: read() failed with 104(Connection reset by peer)#012 from 127.0.0.1:2014

Netstat before:
~# netstat -pan | grep cgr
tcp        0      0 127.0.0.1:2012          0.0.0.0:*               LISTEN      8222/cgr-engine
tcp        0      0 127.0.0.1:2013          0.0.0.0:*               LISTEN      8222/cgr-engine
tcp        0      0 127.0.0.1:2014          0.0.0.0:*               LISTEN      8222/cgr-engine
tcp        0      0 127.0.0.1:2080          0.0.0.0:*               LISTEN      8222/cgr-engine

Netstat after:
~# netstat -pan | grep cgr
tcp        0      0 127.0.0.1:2012          0.0.0.0:*               LISTEN      8222/cgr-engine
tcp        0      0 127.0.0.1:2013          0.0.0.0:*               LISTEN      8222/cgr-engine
tcp        0      0 127.0.0.1:2080          0.0.0.0:*               LISTEN      8222/cgr-engine

cgrates_auth("$fU", "$rU") can't authorise calls also

**Comment by danbogos** [comment]
Hey @andey-ch 

Just a quick one to let you know that I found the issue and will work with @razvancrainea from OpenSIPS to fix it since it is not on CGRateS side.

Will keep the progress here.

DanB

**Comment by razvancrainea** [comment]
Just pushed a commit in OpenSIPS master branch that seems to be related to this bug. @andey-ch , can you give it one more try?

**Comment by ishmaelen** [comment]
I was able to replicate this using 2.4.0-dev git revision: 99ebafd (master) and the same sm_generic config as above. Port 2014 was closed as indicated by netstat.

The request sent from OpenSIPS is shown here:
`{ "method": "SMGenericV1.GetMaxUsage", "id": "12485-332791622", "params": [ { "Destination": "+2000", "RequestType": "*prepaid", "SetupTime": "1332791622", "OriginID": "3129_3jAKjedlodeim397", "Account": "+3000", "Tenant": "base.sq", "EmailAddress": "never.mail@me.com" } ] }`

**Comment by danbogos** [comment]
Hi @ishmaelen,

I have found the issue and fixed. Please retest and report if any problems.

Thanks,
DanB
