### ISSUE TITLE
Diameter-agent - accounting message error " unexpected message ACR"

### ISSUE THREAD

**Issue by jpsc69** [cgrates/cgrates#686]
Hi,

we have this message when an ACR request is received from a CTF: Diameter-agent - unexpected message  ACR.

Please can you investigate this issue?

Thx

Kr
[cgrates_template.zip](https://github.com/cgrates/cgrates/files/1124467/cgrates_template.zip)
[acr on cgrates 200617.txt](https://github.com/cgrates/cgrates/files/1124468/acr.on.cgrates.200617.txt)

**Comment by danbogos** [comment]
hey @jpsc69 

Sorry for delay, we have finally reached this task.

Do u have by chance access to a .pcap sample of ACR/ACA which we can integrate in our build tests?

Ta,
DanB
