### ISSUE TITLE
Mechanism to protect against stale sessions in SessionManager

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#69]
Should involve both CDRS and SM components.

Logic behind:

 * On CDR received in CDRS, try to get the call costs as normal. If not found, retry for a number of times (with delay in between).
 * If after attempts no record was found, calculate CDR as for pseudoprepaid and insert call cost.
 * When session manager closes the session, it should attempt as normally to insert the call cost into the table.
 * On duplication error, it should refund all the balances taken during the complete call.

DanB

**Comment by rif** [comment]
Added the protection mechanism and test for refund. Another issue is to check for switch sessions from time to time and close the stale ones.
