### ISSUE TITLE
OsipsEvent.OriginatorAddress never set?

### ISSUE THREAD

**Issue by shaneneuerburg** [cgrates/cgrates#690]
I'm working on trying to get CDRs to include the CdrHost and/or OriginHost (if I saw that correctly, they are the same). They keep coming in empty and I traced it back to the `OsipsEvent.GetOriginatorIP` method. Inside of that is a check to see if `OriginatorAddress` is set.

I've reviewed all of CGRates' code and checked out the OpenSIPs CGRates module code and couldn't find anywhere that the `OriginatorAddress` would be set.

Is this a bug, or is it automagically getting set somewhere else dynamically that I can't find?

**Comment by danbogos** [comment]
hey @shaneneuerburg 

I have been checking this and it should in theory behave.

How are you connecting from OpenSIPS? Using the new module they have developed or using old module where CGRateS connects to OpenSIPS?

DanB

PS: You can also try to reach me on irc  during europe business hours if you want to move it faster.

**Comment by shaneneuerburg** [comment]
After talking with @danbogos, it appears that with the new OpenSIPS CGRateS module that the responsibility for setting the origin host falls on that module, not the core CGRateS generic session manager.
