### ISSUE TITLE
cdrs_export Error executing command: not_found

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#696]
Hi,
Trying to export CDRs results in file not found error.

Error output:
cgr> cdrs_export CdrFormat="csv" ExportDir="/tmp"
Error executing command: SERVER_ERROR: open /var/spool/cgrates/cdre/cdre_1501658801.*file_csv: no such file or directory

Creating the folder /var/spool/cgrates/cdre/ and running cdrs_export again creates file with the following name "cdre_1501666175.*file_csv"

**Comment by TeoV** [comment]
Hello Michael,
If you type in console help you will see the correct name for parameters ( in your case ExportDir should be ExportPath) and the command looks like this :  cdrs_export CdrFormat="csv" ExportPath="/tmp"

Here are my result after executing command : 
cgr> cdrs_export CdrFormat="csv" ExportPath="/tmp"
{
 "ExportedPath": "/tmp/cdre_1517232548.csv",
 "TotalRecords": 11,
 "TotalCost": 2.62,
 "FirstOrderID": 1,
 "LastOrderID": 13,
 "ExportedCGRIDs": null,
 "UnexportedCGRIDs": null
}

Thanks,
TeoV
