### ISSUE TITLE
Opensips port 2014, disconnect session produces error messages

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#697]
Logs showing error after sending a disconnect to opensips when credit runs out. calls are being disconnected correctly though.

CDRs are also being generated correctly.

NGREP:

T 127.0.0.1:2014 -> 127.0.0.1:47124 [AP]
{"method":"SMGClientV1.DisconnectSession","params":[{"EventStart":{"Account":"9470898910","AnswerTime":"1501763290","Category":"call_standard","Destination":"447596933443","DialogEntry":3745,"DialogID":199040137,"OriginID":"ZWQzYjgxNWRkNDBlNjkxMjU0NzU5MWY0ZDc3MjQ4M2U.","RequestType":"*prepaid","SetupTime":"1501763287","Tenant":"rater.thispbx.com","Usage":"60"},"Reason":"-INSUFFICIENT_FUNDS"}],"id":1}
 
##
T 127.0.0.1:47124 -> 127.0.0.1:2014 [AP]
{ "error": null, "result": 0, "id": 1 }
#
T 127.0.0.1:47123 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.TerminateSession", "id": 1374076932, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501763287", "Category": "call_standard", "OriginID": "ZWQzYjgxNWRkNDBlNjkxMjU0NzU5MWY0ZDc3MjQ4M2U.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "AnswerTime": "1501763290", "Usage": "61s" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47123 [AP]
{"id":1374076932,"result":"OK","error":null}
 
##
T 127.0.0.1:47123 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.ProcessCDR", "id": 1374076936, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501763287", "Category": "call_standard", "OriginID": "ZWQzYjgxNWRkNDBlNjkxMjU0NzU5MWY0ZDc3MjQ4M2U.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "Usage": "61s", "AnswerTime": "1501763290" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47123 [AP]
{"id":1374076936,"result":"OK","error":null}
 
##
T 127.0.0.1:2014 -> 127.0.0.1:47124 [AP]
{"method":"SMGClientV1.DisconnectSession","params":[{"EventStart":{"Account":"9470898910","AnswerTime":"1501763295","Category":"call_standard","Destination":"447596933443","DialogEntry":3807,"DialogID":1716737526,"OriginID":"1_4265755416@192.168.1.147","RequestType":"*prepaid","SetupTime":"1501763293","Tenant":"rater.thispbx.com","Usage":"60"},"Reason":"-INSUFFICIENT_FUNDS"}],"id":2}
 
#
T 127.0.0.1:47124 -> 127.0.0.1:2014 [AP]
{ "error": null, "result": 0, "id": 2 }
##
T 127.0.0.1:47126 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.TerminateSession", "id": 2113425454, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501763293", "Category": "call_standard", "OriginID": "1_4265755416@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "AnswerTime": "1501763295", "Usage": "60s" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47126 [AP]
{"id":2113425454,"result":"OK","error":null}
 
##
T 127.0.0.1:47126 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.ProcessCDR", "id": 2113425450, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501763293", "Category": "call_standard", "OriginID": "1_4265755416@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "Usage": "60s", "AnswerTime": "1501763295" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47126 [AP]
{"id":2113425450,"result":"OK","error":null}

SYSLOG:

Aug  3 14:28:15 vps367591 /usr/sbin/opensips[11443]: ACC: transaction answered: timestamp=1501763295;method=INVITE;from_tag=2167540621;to_tag=7N3err67earjp;call_id=1_4265755416@192.168.1.147;code=200;reason=OK
Aug  3 14:28:15 vps367591 /usr/sbin/opensips[11444]: new branch at sip:9470898910jUAYBj@217.155.52.118:5060
Aug  3 14:28:15 vps367591 /usr/sbin/opensips[11446]: incoming reply
Aug  3 14:29:10 vps367591 /usr/sbin/opensips[11443]: INFO:cgrates:cgrates_process_req: Received new request method=SMGClientV1.DisconnectSession param=0x1f0c160
Aug  3 14:29:10 vps367591 /usr/sbin/opensips[11443]: ACC: request accounted: timestamp=1501763350;method=BYE;from_tag=6cappXN4H11Za;to_tag=d1406b6c;call_id=ZWQzYjgxNWRkNDBlNjkxMjU0NzU5MWY0ZDc3MjQ4M2U.;code=200;reason=Dialog Timeout
Aug  3 14:29:10 vps367591 CGRateS <f603110a-3e19-4f8d-b001-a5aa4b90d48f> [12004]: <SMGeneric> Could not disconnect session: 914101809e5b13c9cb975a11ea446b4b4c3c0ab8, error: reading body json: cannot unmarshal number into Go value of type string
Aug  3 14:29:11 vps367591 CGRateS <f603110a-3e19-4f8d-b001-a5aa4b90d48f> [12004]: <Rater> Going negative on account rater.thispbx.com:9470898910 with AllowNegative: false
Aug  3 14:29:15 vps367591 /usr/sbin/opensips[11443]: INFO:cgrates:cgrates_process_req: Received new request method=SMGClientV1.DisconnectSession param=0x1f0bf40
Aug  3 14:29:15 vps367591 /usr/sbin/opensips[11443]: ACC: request accounted: timestamp=1501763355;method=BYE;from_tag=7N3err67earjp;to_tag=2167540621;call_id=1_4265755416@192.168.1.147;code=200;reason=Dialog Timeout
Aug  3 14:29:15 vps367591 CGRateS <f603110a-3e19-4f8d-b001-a5aa4b90d48f> [12004]: <SMGeneric> Could not disconnect session: c96d5144f6894e55f475e0217b0b6ab51d8e722f, error: reading body json: cannot unmarshal number into Go value of type string

**Comment by danbogos** [comment]
Hey @DigiDaz 
Thanks for reporting!

For the record, the error comes from OpenSIPS inserting wrong result value:
{ "error": null, "result": 0, "id": 1 }

Will get in touch with @razvancrainea  from OpenSIPS to try getting this fixed there.

DanB

**Comment by razvancrainea** [comment]
Hi guys!
@DigiDaz thanks for the report!
@danbogos are you expecting a string in the `result`?

**Comment by danbogos** [comment]
wow, that was fast, thanks @razvancrainea for so fast reply.

Yes, "OK" as reply would be ideal.

Thanks,
DanB

**Comment by razvancrainea** [comment]
Just pushed a fix in the master branch (OpenSIPS/opensips@db5d1bddc95a311da283ea56ec46c6da2259c33f). Let me know how it goes and I will backport it to the 2.3 branch.

**Comment by DigiDaz** [comment]
That didn't actually work though we are now getting an "OK":

NGREP:

T 127.0.0.1:47174 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.GetMaxUsage", "id": 1933966014, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773584", "Category": "call_standard", "OriginID": "OWY4M2NkM2I5OGMzM2RiMGEzYTk5NTY2YWY5ZjVmNDg.", "Account": "9470898910", "Tenant": "rater.thispbx.com" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47174 [AP]
{"id":1933966014,"result":60,"error":null}

##
T 127.0.0.1:47163 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.InitiateSession", "id": 1933966018, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773584", "Category": "call_standard", "OriginID": "OWY4M2NkM2I5OGMzM2RiMGEzYTk5NTY2YWY5ZjVmNDg.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "DialogID": 1504619733, "DialogEntry": 30, "AnswerTime": "1501773587" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47163 [AP]
{"id":1933966018,"result":-1,"error":null}

#####
T 127.0.0.1:47180 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.GetMaxUsage", "id": 1844151040, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773590", "Category": "call_standard", "OriginID": "1_3957620284@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47180 [AP]
{"id":1844151040,"result":38,"error":null}

##
T 127.0.0.1:47162 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.InitiateSession", "id": 1844151036, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773590", "Category": "call_standard", "OriginID": "1_3957620284@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "DialogID": 1600363848, "DialogEntry": 2775, "AnswerTime": "1501773593" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47162 [AP]
{"id":1844151036,"result":-1,"error":null}

##
T 127.0.0.1:2014 -> 127.0.0.1:47162 [AP]
{"method":"SMGClientV1.DisconnectSession","params":[{"EventStart":{"Account":"9470898910","AnswerTime":"1501773593","Category":"call_standard","Destination":"447596933443","DialogEntry":2775,"DialogID":1600363848,"OriginID":"1_3957620284@192.168.1.147","RequestType":"*prepaid","SetupTime":"1501773590","Tenant":"rater.thispbx.com","Usage":"20"},"Reason":"-INSUFFICIENT_FUNDS"}],"id":1}

##
T 127.0.0.1:47162 -> 127.0.0.1:2014 [AP]
{ "error": null, "result": 0, "id": 1 }
#
T 127.0.0.1:47161 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.TerminateSession", "id": 1761772621, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773590", "Category": "call_standard", "OriginID": "1_3957620284@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "AnswerTime": "1501773593", "Usage": "21s" } ] }
###
T 127.0.0.1:2014 -> 127.0.0.1:47161 [AP]
{"id":1761772621,"result":"OK","error":null}

#
T 127.0.0.1:47161 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.ProcessCDR", "id": 1761772617, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773590", "Category": "call_standard", "OriginID": "1_3957620284@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "Usage": "21s", "AnswerTime": "1501773593" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47161 [AP]
{"id":1761772617,"result":"OK","error":null}

##
T 127.0.0.1:2014 -> 127.0.0.1:47163 [AP]
{"method":"SMGClientV1.DisconnectSession","params":[{"EventStart":{"Account":"9470898910","AnswerTime":"1501773587","Category":"call_standard","Destination":"447596933443","DialogEntry":30,"DialogID":1504619733,"OriginID":"OWY4M2NkM2I5OGMzM2RiMGEzYTk5NTY2YWY5ZjVmNDg.","RequestType":"*prepaid","SetupTime":"1501773584","Tenant":"rater.thispbx.com","Usage":"28"},"Reason":"-INSUFFICIENT_FUNDS"}],"id":4}

##
T 127.0.0.1:47163 -> 127.0.0.1:2014 [AP]
{ "error": null, "result": 0, "id": 4 }
#
T 127.0.0.1:47159 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.TerminateSession", "id": 1858304501, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773584", "Category": "call_standard", "OriginID": "OWY4M2NkM2I5OGMzM2RiMGEzYTk5NTY2YWY5ZjVmNDg.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "AnswerTime": "1501773587", "Usage": "28s" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47159 [AP]
{"id":1858304501,"result":"OK","error":null}

##
T 127.0.0.1:47159 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.ProcessCDR", "id": 1858304505, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501773584", "Category": "call_standard", "OriginID": "OWY4M2NkM2I5OGMzM2RiMGEzYTk5NTY2YWY5ZjVmNDg.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "Usage": "28s", "AnswerTime": "1501773587" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47159 [AP]
{"id":1858304505,"result":"OK","error":null}

SYSLOG:

Aug  3 17:20:13 vps367591 /usr/sbin/opensips[30876]: INFO:cgrates:cgrates_process_req: Received new request method=SMGClientV1.DisconnectSession param=0x21b40b0
Aug  3 17:20:13 vps367591 /usr/sbin/opensips[30876]: ACC: request accounted: timestamp=1501773613;method=BYE;from_tag=32QSpaFrpNp2N;to_tag=951065846;call_id=1_3957620284@192.168.1.147;code=200;reason=Dialog Timeout
Aug  3 17:20:13 vps367591 CGRateS <f603110a-3e19-4f8d-b001-a5aa4b90d48f> [12004]: <SMGeneric> Could not disconnect session: ddf5e8c87e6c1ee8a3c1cf6357a22749c363b076, error: reading body json: cannot unmarshal number into Go value of type string
Aug  3 17:20:14 vps367591 CGRateS <f603110a-3e19-4f8d-b001-a5aa4b90d48f> [12004]: <Rater> Going negative on account rater.thispbx.com:9470898910 with AllowNegative: false
Aug  3 17:20:15 vps367591 /usr/sbin/opensips[30874]: INFO:cgrates:cgrates_process_req: Received new request method=SMGClientV1.DisconnectSession param=0x21c6a40
Aug  3 17:20:15 vps367591 /usr/sbin/opensips[30874]: ACC: request accounted: timestamp=1501773615;method=BYE;from_tag=2Sy0mFymSc0Fa;to_tag=58499070;call_id=OWY4M2NkM2I5OGMzM2RiMGEzYTk5NTY2YWY5ZjVmNDg.;code=200;reason=Dialog Timeout
Aug  3 17:20:15 vps367591 CGRateS <f603110a-3e19-4f8d-b001-a5aa4b90d48f> [12004]: <SMGeneric> Could not disconnect session: 8124afa31752e2fe517d7ca7fb4831b0b6858be9, error: reading body json: cannot unmarshal number into Go value of type string

**Comment by DigiDaz** [comment]
No we are not, maybe my bad.....

**Comment by DigiDaz** [comment]
Working perfectly guys, thanks a lot :+1: 

NGREP:

T 127.0.0.1:2014 -> 127.0.0.1:47284 [AP]
{"method":"SMGClientV1.DisconnectSession","params":[{"EventStart":{"Account":"9470898910","AnswerTime":"1501774457","Category":"call_standard","Destination":"447596933443","DialogEntry":2457,"DialogID":1150328845,"OriginID":"1_3919358255@192.168.1.147","RequestType":"*prepaid","SetupTime":"1501774455","Tenant":"rater.thispbx.com","Usage":"20"},"Reason":"-INSUFFICIENT_FUNDS"}],"id":1}

##
T 127.0.0.1:47284 -> 127.0.0.1:2014 [AP]
{ "error": null, "result": "OK", "id": 1 }
#
T 127.0.0.1:47276 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.TerminateSession", "id": 63438847, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501774455", "Category": "call_standard", "OriginID": "1_3919358255@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "AnswerTime": "1501774457", "Usage": "20s" } ] }
###
T 127.0.0.1:2014 -> 127.0.0.1:47276 [AP]
{"id":63438847,"result":"OK","error":null}

##
T 127.0.0.1:47276 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.ProcessCDR", "id": 63438843, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501774455", "Category": "call_standard", "OriginID": "1_3919358255@192.168.1.147", "Account": "9470898910", "Tenant": "rater.thispbx.com", "Usage": "20s", "AnswerTime": "1501774457" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47276 [AP]
{"id":63438843,"result":"OK","error":null}

##
T 127.0.0.1:2014 -> 127.0.0.1:47284 [AP]
{"method":"SMGClientV1.DisconnectSession","params":[{"EventStart":{"Account":"9470898910","AnswerTime":"1501774453","Category":"call_standard","Destination":"447596933443","DialogEntry":1688,"DialogID":670034608,"OriginID":"ZjQ3OGNhOTQwZmQ5YTliZGYyYmE4YTJlMzA5ODk5OGI.","RequestType":"*prepaid","SetupTime":"1501774450","Tenant":"rater.thispbx.com","Usage":"28"},"Reason":"-INSUFFICIENT_FUNDS"}],"id":2}

#
T 127.0.0.1:47284 -> 127.0.0.1:2014 [AP]
{ "error": null, "result": "OK", "id": 2 }
##
T 127.0.0.1:47283 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.TerminateSession", "id": 1298007041, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501774450", "Category": "call_standard", "OriginID": "ZjQ3OGNhOTQwZmQ5YTliZGYyYmE4YTJlMzA5ODk5OGI.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "AnswerTime": "1501774453", "Usage": "28s" } ] }
##
T 127.0.0.1:2014 -> 127.0.0.1:47283 [AP]
{"id":1298007041,"result":"OK","error":null}

##
T 127.0.0.1:47283 -> 127.0.0.1:2014 [AP]
{ "method": "SMGenericV1.ProcessCDR", "id": 1298007037, "params": [ { "Destination": "447596933443", "RequestType": "*prepaid", "SetupTime": "1501774450", "Category": "call_standard", "OriginID": "ZjQ3OGNhOTQwZmQ5YTliZGYyYmE4YTJlMzA5ODk5OGI.", "Account": "9470898910", "Tenant": "rater.thispbx.com", "Usage": "28s", "AnswerTime": "1501774453" } ] }
#
T 127.0.0.1:2014 -> 127.0.0.1:47283 [AP]
{"id":1298007037,"result":"OK","error":null}

SYSLOG:

Aug  3 17:34:37 vps367591 /usr/local/sbin/opensips[31738]: INFO:cgrates:cgrates_process_req: Received new request method=SMGClientV1.DisconnectSession param=0x1ff4f10
Aug  3 17:34:37 vps367591 /usr/local/sbin/opensips[31738]: ACC: request accounted: timestamp=1501774477;method=BYE;from_tag=tK6crtDtQZZ6j;to_tag=3702704152;call_id=1_3919358255@192.168.1.147;code=200;reason=Dialog Timeout
Aug  3 17:34:41 vps367591 /usr/local/sbin/opensips[31738]: INFO:cgrates:cgrates_process_req: Received new request method=SMGClientV1.DisconnectSession param=0x1ff4ee0
Aug  3 17:34:41 vps367591 /usr/local/sbin/opensips[31738]: ACC: request accounted: timestamp=1501774481;method=BYE;from_tag=SaDmpZvptp9KQ;to_tag=8738e61a;call_id=ZjQ3OGNhOTQwZmQ5YTliZGYyYmE4YTJlMzA5ODk5OGI.;code=200;reason=Dialog Timeout

**Comment by razvancrainea** [comment]
Perfect, backported to OpenSIPS 2.3.
Thanks for reporting and testing!

**Comment by danbogos** [comment]
Thanks guys for your efforts. Will close the issue now.

DanB
