### ISSUE TITLE
filter separator issue

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#706]
Hello

when trying to use this filter:
 "cdr_filter": "21(S_OTHER);55(FU_HOME:;FU_HOME_EU:;ACCOUNT_ROAM_WORLD:;ACCOUNT_POSTPAID:)",

i get:
 Could not parse config: %!(EXTRA *errors.errorString=Invalid FilterStartValue in string: ACCOUNT_POSTPAID:))

tbx
miha

**Comment by TeoV** [comment]
Hi Miha,

This should be fixed in master to use the new format of filters.

Thanks,
TeoV
