### ISSUE TITLE
Feature requests: log in stdout / stderr

### ISSUE THREAD

**Issue by alexsosic** [cgrates/cgrates#713]
In order to have a correct docker container, log should be put in stdout / stderr and not in syslog, can this be done please?

**Comment by alexsosic** [comment]
Sorry if I'm being a pain in the ass but I would very much like to know if and when this feature will be possible?

Thanks!

**Comment by danbogos** [comment]
Hey @alexsosic 

No pain here, just time constrains ;).

Cannot give you a straight estimation but let's put it in the 2 months interval.

DanB

**Comment by Edwardro22** [comment]
Greetings @alexsosic  
I got your request done  :) .

**Comment by alexsosic** [comment]
Fantastic @Edwardro22 
Thank you so much!
