### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by paolovisintin** [cgrates/cgrates#720]
Hi, 
seems that the link "Debian apt-get repository" in README.md points to : 
https://cgrates.readthedocs.org/en/latest/tut_freeswitch_installs.html#cgrates

**Comment by danbogos** [comment]
hey @paolovisintin 

Can you provide a PR changing to the right one?

Thanks,
DanB

**Comment by paolovisintin** [comment]
Hey @danbogos , thanks for suggestion, just done!
