### ISSUE TITLE
Show usage charge to subs.

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#736]
Hello Dear CGRateS Team!
We want to show our subscribers charged value at the end of the call.
One of proposals might be to tweak API to return CGRID instead of just "OK", so we could later use that for retreiving the CDR with actual cost details at ProcessCDR.
https://github.com/cgrates/cgrates/blob/2fb17ecca2751b926cbd345932ae3fda9317477b/sessionmanager/smgeneric.go#L1132

or make UpdateSession/TerminateSession to return CostDetails object, or similar/short version, just reflecting the balance id + total usage/cost was applied on prepaid accounts.
https://github.com/cgrates/cgrates/blob/2fb17ecca2751b926cbd345932ae3fda9317477b/sessionmanager/smgeneric.go#L1112

**Comment by TeoV** [comment]
Hi @muxalko,

Now the new SessionS, when you send UpdateSession, response with the AttributeProcessEventReply ( if is active ) and MaxUsage.

Thanks,
TeoV
