### ISSUE TITLE
Load CSV to Mongo 

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#753]
Hi, 
I think there is a problem with loading large CSV files when working with stor/data = mongo/mongo.
My issue is with destinations.csv file containing about 94k rows.
Everything works correctly when using mysql/redis.

 [tariff_golan_basic.zip](https://github.com/cgrates/cgrates/files/1329016/tariff_golan_basic.zip)

**Comment by danbogos** [comment]
Hi  @muxalko 

This issue should be fixed in master (have changed the driver).

DanB
