### ISSUE TITLE
radagent support for authentication

### ISSUE THREAD

**Issue by uppaljs** [cgrates/cgrates#770]
Hi,

Our use case is to authenticate and charge users using our Wifi service via radius agent for cgrates.

Wifi User <--pppoe-->mikrotik<--radius-->cgrates

Currently cgrates radius agent has no authorisation built-in, i.e. any password sent / not sent will result in a access-accept parameter as long as the user is able to access the service per configuration.

This is to request , to add a feature to authorise users as well using Regular Userpassword/ PAP/CHAP/CHAPv2 per mentioned in chapter 2.2 of RFC 2865.

Further details are in chapter 5.2 and 5.3 of the same RFC as well ( CHAP & User-Password).

If there are any traces required , kindly let me know and I'll add them here.

Thanks,

**Comment by gwizo** [comment]
+1

**Comment by uppaljs** [comment]
Hey @danbogos I am open to setting up a pppoe server instance on our cloud for dev if required?

**Comment by danbogos** [comment]
hey @uppaljs 

Thanks for your offer! 
Will come back to it as soon as we are ready to test something.

Have a good one!

DanB

**Comment by TeoV** [comment]
Hi @uppaljs,

We have implemented in master the PAP, CHAP, and MS-CHAP-V2 authentification protocols.
Please check our custom config for example ( https://github.com/cgrates/cgrates/tree/master/data/conf/samples/radagent_internal )
Also for what AVP's we use to tests these functionalities please check the integration tests ( https://github.com/cgrates/cgrates/blob/master/agents/radagent_it_test.go ) and the Tariff plans ( https://github.com/cgrates/cgrates/blob/master/data/tariffplans/oldtutorial/Attributes.csv )

Thanks,
TeoV
