### ISSUE TITLE
Load from csv to stordb crashes cgr-loader

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#780]
Hello Dear CGRateS Team,

After pulling a new version , cgr-loader crashes at row 97, when trying to load csv to mysql:
```
golan@cgr-ptk-node-02:~/proj/src/github.com/cgrates/cgratesgui$ cgr-loader -path=/home/golan/tariff_golan -verbose -validate -to_stordb -stordb_passwd="123456" -stordb_host="10.192.222.26" -tpid="GTP"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5bcb3]

goroutine 1 [running]:
main.main()
        /home/golan/proj/src/github.com/cgrates/cgrates/cmd/cgr-loader/cgr-loader.go:97 +0x263
```

Trying the same with -dry_run, points to row 159
```
golan@cgr-ptk-node-02:~/proj/src/github.com/cgrates/cgratesgui$ cgr-loader -path=/home/golan/tariff_golan -verbose -validate -dry_run -stordb_passwd="CgrateSql" -stordb_host="127.0.0.1" -tpid="GTP"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb5c18c]

goroutine 1 [running]:
main.main()
        /home/golan/proj/src/github.com/cgrates/cgrates/cmd/cgr-loader/cgr-loader.go:159 +0x73c
golan@cgr-ptk-node-02:~/proj/src/github.com/cgrates/cgratesgui$ 
```

With older cgr-loader version, everything works as expected.

CGRateS 0.9.1~rc8 git+5255388 (2017-09-11T17:54:41+02:00) <---- Good 
CGRateS 0.9.1~rc8 git+2c9672c (2017-10-23T19:30:33+02:00) <----- Bad

P.S. API method is working OK 
{
  "id":"0",
  "method":"ApierV1.LoadTariffPlanFromFolder",
  "params":[
    {
      "TPid":"GTP",
      "FolderPath":"/home/cgrates/tariff/",
      "DryRun":false,
      "Validate":true
    }
  ]
}

**Comment by danbogos** [comment]
@muxalko 

please retest and let me know if still issues.

Thanks,
DanB

**Comment by muxalko** [comment]
100% fixed!
Thanks!
