### ISSUE TITLE
Can not connect to MognoDB replica set with ssl option

### ISSUE THREAD

**Issue by max-konin** [cgrates/cgrates#789]
There is bug in go driver for golang (mgo) and PR to fix it https://github.com/go-mgo/mgo/pull/304
But this PR is not merged to upstream. 

I tried to use mgo fork with ssl fix https://github.com/max-konin/cgrates/commit/116f4c7aa0d8a97e05bcd2eb1bf0d79d3587981d but build is failed... I'm not a go developer and mb I'm doing smht wrong

**Comment by danbogos** [comment]
hi @max-konin 

Sorry, we forgot to update this issue since a while. 
Can you please recheck with latest master, we have changed the driver since few month already and I think the new one is better maintained.

Thanks,
DanB

**Comment by max-konin** [comment]
Hi @danbogos 

Thank you for your response. Unfortunately I can not check this in the near future. We changed MongoDB cloud provider and current provider not support ssl so far...

But If I get you right, CGrateS is using https://github.com/cgrates/mgo fork mgo now. I've checked session.go file https://github.com/cgrates/mgo/blob/master/session.go#L387 and it does not include patch for ssl https://github.com/go-mgo/mgo/pull/304/files

**Comment by danbogos** [comment]
@max-konin 

OK, will check it on our side. Thanks for fast reply!

DanB

**Comment by arsperger** [comment]
Hi guys,

We have issue with SSL option, this is our DataDB config:

```
"data_db": {
        "db_type": "mongo",
        "db_host": "host1.com:27017,host2.com:27017,host3.com:27017",
        "db_name": "staging?replicaSet=sr&authSource=admin&ssl=true",
        "db_user": "user",
        "db_password": "password",
        "load_history_size": 10,                                
 },
```

Error:
`CGRateS <460d869> [20600]: Could not configure dataDb: no reachable servers exiting!`

Is it correct way to configure SSL connection?

Thanks!
Arsen.

**Comment by TeoV** [comment]
Hi Arsen,
Here is an example : 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/mongoreplica/cgrates.json

Thanks,
TeoV

**Comment by arsperger** [comment]
Hi Teo,

I saw this, unfortunately it doesn't work. 
Do we need to pass "ssl=true" option? I've tried to set in in the db_name as in my post above. Also tried without this option just like in the example you've sent but it fails with: no reachable servers exiting

**Comment by TeoV** [comment]
Hi Arsen,
As you see in my example you will have to specify the port for the last address, in my case my last address is 192.168.56.204 and for this port 27017. If you don't define the port, this will have default value (6379) and your url connection will be: user:password@host1.com:27017,host2.com:27017,host3.com:27017:6379/staging?replicaSet=sr&authSource=admin&ssl=true . 

Try with this and announce us if this works ? 
"data_db": {
        "db_type": "mongo",
        "db_host": "host1.com:27017,host2.com:27017,host3.com",
         "db_port":27017
        "db_name": "staging?replicaSet=sr&authSource=admin&ssl=true",
        "db_user": "user",
        "db_password": "password",
        "load_history_size": 10,                                
 },

**Comment by arsperger** [comment]
Yes the config is exactly same as in your example above, but it can't connect.

**Comment by max-konin** [comment]
Hi Teo

I've created simple glide app for testing mongo driver

```go
package main
import "github.com/cgrates/mgo"
import "fmt"

func main() {
	url := "mongodb://username:password@host1.com:27017,host2.com:27017,host3.com:27017,host4.com:27017/test?ssl=true&replicaSet=Yufu0-shard-0&authSource=admin"

	session, err := mgo.Dial(url)
	if err != nil {
		fmt.Printf("Error")
		panic(err)
	}

	names, err := session.DatabaseNames()
	fmt.Printf("%v", names)
	fmt.Printf("OK\n")

	// Use session as normal
	session.Close()
}

```
It's not connecting to mongo cluster (no reachable servers).

But if I change `import "github.com/cgrates/mgo"` to `import "github.com/globalsign/mgo"` then it works fine.

There is PR to globalsign/mgo https://github.com/globalsign/mgo/pull/184. It adds SSL support. This PR is slightly different from yours cgrates/mgo. Mb there is an opportunity to use globalsign/mgo or sync  cgrates/mgo with upstream.

We are using MongoDB Atlas and I can create simple cluster for your tests if you need it.

**Comment by vtzan** [comment]
Dear Team,

I can confirm that the problem exists on current master.

MongoDB Atlas provides SSL connections only and because CGRateS has a very good integration
with Mongo I think this is would be a nice fix for the community.

Best Regards
Vasilios Tzanoudakis

**Comment by danbogos** [comment]
Thanks guys, is on our list to fix it!

@max-konin, regarding your suggestion to use gobalsign/mgo, we tried that before forking. The issue we faced is them storing of time.Usage as milliseconds and we need it support it the way Go does it, nanoseconds. Hope at some point that the driver which Mongo folks are developing will be ready for prime-time, so we can start using that one instead.

Will update our fork and let you guys when ready.

DanB

**Comment by danbogos** [comment]
Thanks to @TeoV we also have integrated tests for Mongo Atlas and you can find configs here:
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/mongoatlas/cgrates.json#L20

DanB

**Comment by vtzan** [comment]
Thank you @danbogos I will test soon too.

**Comment by arsperger** [comment]
Hi guys,

We have successfully connected to mongo cluster over SSL. 
Thank you for your quick support. 

Arsen.

**Comment by danbogos** [comment]
Thanks @arsperger for your support too!

DanB
