### ISSUE TITLE
master not building after changes in kamEvAPI

### ISSUE THREAD

**Issue by nevian427** [cgrates/cgrates#804]
Hello,

I'm unable to build master after commit bccf6fc887d03e091cd1240976cf866996b5aada.
Actually prev commit (30906b128eae29907c73b7954704c6ac9284e522) breaks things as well via interface changes.
Last successful build 007a37fa82d6da98e4082197d8c8c28e5f851b27

**Comment by danbogos** [comment]
Hi,

Please try glide install before (so it can fetch the latest kamevapi.

DanB

**Comment by nevian427** [comment]
sorry, forgot to paste error from glide
[INFO]	--> Setting version for github.com/cgrates/kamevapi to be921812bc9e51a5054f3d36dba00d564249d122.
[ERROR]	Failed to set version on github.com/cgrates/kamevapi to be921812bc9e51a5054f3d36dba00d564249d122: Unable to update checked out version: exit status 128

**Comment by danbogos** [comment]
Maybe a temporary issue of glide (try removing glide cache and reinstall).

Here is what I get:
[INFO]	--> Setting version for github.com/cgrates/kamevapi to be921812bc9e51a5054f3d36dba00d564249d122.


No errors and also builds properly after.

DanB

**Comment by nevian427** [comment]
Removing glide cache helps.
Sorry for the noise

**Comment by danbogos** [comment]
Sure, np.

DanB
