### ISSUE TITLE
Kamailio Cgrates lost connection

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#812]
Hi 

I am observing a strange issue: after restart of Kamailio cgrates cannot reconnect.
I run cgrates session manager component on the same instance with the Kamailio, this is my cgrates config:

```
 "general": {
        "instance_id": "",
        "log_level": 7,
        "http_skip_tls_verify": false,
        "rounding_decimals": 5,
        "dbdata_encoding": "msgpack",
        "tpexport_dir": "/var/spool/cgrates/tpe",
        "poster_attempts": 3,
        "failed_posts_dir": "/var/spool/cgrates/failed_posts",
        "default_request_type": "*rated",
        "default_category": "call",
        "default_tenant": "cgrates.org",
        "default_timezone": "Local",
        "connect_attempts": 5,
        "reconnects": -1,
        "connect_timeout": "1s",
        "reply_timeout": "2s",
        "response_cache_ttl": "0s",
        "internal_ttl": "2m",
        "locking_timeout": "5s",
 },


"listen": {
        "rpc_gob": "0.0.0.0:2013",                      
},

 "sm_kamailio": {
        "enabled": true,
        "rals_conns": [
                {"address": "172.20.2.3:2013"}
        ],
        "cdrs_conns": [
                {"address": "172.20.2.3:2013"}
        ],
        "rls_conns": [],
        "create_cdr": true,
        "debit_interval": "10s",
        "min_call_duration": "0s",
        "max_call_duration": "3h",
        "evapi_conns":[
                {"address": "127.0.0.1:8448", "reconnects": -1}
        ],
 },

}
```

When restart Kamailio I see in the log:

```
CGRateS <45e92054-56c1-4d01-b4f7-c18d344443f8> [27449]:<KamEvapi> Disconnecting from Kamailio!
CGRateS <45e92054-56c1-4d01-b4f7-c18d344443f8> [27449]:<KamEvapi> Attempting connect to Kamailio at: 127.0.0.1:8448
/usr/sbin/kamailio[27961]: INFO: <script>: CGRatece: new connection from 127.0.0.1:59364
CGRateS <45e92054-56c1-4d01-b4f7-c18d344443f8> [27449]:<KamEvapi> Successfully connected to Kamailio!
```

Cgrates sometimes tries to reconnect and sometimes it is succeed.

But sometimes I see only:  "<KamEvapi> Successfully connected to Kamailio!"

Without any actual connection being established.

`kamctl fifo sht_dump cgrconn`

returns nothing...

Actually if I even completely stop Kamailio service cgrates will print in the log msg about successful connection... ?!

CGRateS 0.9.1~rc8 

Thanks!

**Comment by arsperger** [comment]
Hi guys, quick update:

This version "CGRateS 0.9.1~rc8" has been installed on debian 8 from packages several month ago.

Today I built latest (master branch) cgrates from the source  on the same server, I don't see message about successful connection when cgrates fails to connect, but it still fails to connect to kamevapi when I restart kamailio service.
The config is the same as in my initial report.

Thanks!

**Comment by danbogos** [comment]
Hi @arsperger 

Sorry for the delay, was absorbed by FreeSWITCH, should be able to have a look on Kamailio nowadays.
I have tried failing Kamailio reconnect but without much luck (have also added failing message just to increase transparency):
`KamEvapi:19:01:32 <KamEvapi> Disconnecting from 10.10.10.205:8448
KamEvapi:19:01:32 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:32 <KamEvapi> Failed connecting to Kamailio at: 10.10.10.205:8448, error: dial tcp 10.10.10.205:8448: getsockopt: connection refused
KamEvapi:19:01:33 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:33 <KamEvapi> Successfully connected to 10.10.10.205:8448!
KamEvapi:19:01:33 <KamEvapi> Disconnecting from 10.10.10.205:8448
KamEvapi:19:01:33 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:33 <KamEvapi> Successfully connected to 10.10.10.205:8448!
KamEvapi:19:01:47 <KamEvapi> Disconnecting from 10.10.10.205:8448
KamEvapi:19:01:47 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:47 <KamEvapi> Failed connecting to Kamailio at: 10.10.10.205:8448, error: dial tcp 10.10.10.205:8448: getsockopt: connection refused
KamEvapi:19:01:48 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:48 <KamEvapi> Failed connecting to Kamailio at: 10.10.10.205:8448, error: dial tcp 10.10.10.205:8448: getsockopt: connection refused
KamEvapi:19:01:49 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:49 <KamEvapi> Failed connecting to Kamailio at: 10.10.10.205:8448, error: dial tcp 10.10.10.205:8448: getsockopt: connection refused
KamEvapi:19:01:51 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:51 <KamEvapi> Failed connecting to Kamailio at: 10.10.10.205:8448, error: dial tcp 10.10.10.205:8448: getsockopt: connection refused
KamEvapi:19:01:54 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:54 <KamEvapi> Successfully connected to 10.10.10.205:8448!
KamEvapi:19:01:54 <KamEvapi> Disconnecting from 10.10.10.205:8448
KamEvapi:19:01:54 <KamEvapi> Attempting connect to Kamailio at: 10.10.10.205:8448
KamEvapi:19:01:54 <KamEvapi> Successfully connected to 10.10.10.205:8448!
`

Any chance you upgrade your CGRateS and try again?

Thanks,
DanB

PS: In the next days will redesign the sm_kamailio into kamailio_agent to use the SessionS module with more powerful APIs, so best is to check config_defaults after upgrading your CGRateS.

**Comment by arsperger** [comment]
Hi Dan, thank you for update! I will look into the new module asap.

Regards,
Arsen.
