### ISSUE TITLE
Existing Balance ExpirationDate when Topup

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#814]
Hello Dear CGRateS Team!

When action type *topup or *topup_reset is executed and balance does exist (same BalanceID), its value is summed, but it's ExpirationDate isn't touched.
I think, it would be more logical to prolong balance expiration in case of *topup or *topup_reset as well?
Let's say to add ExpiryTime (from Action) + ExpirationDate (from current balance) , and set is a new ExpirationDate.

And, in case of *topup_reset, ExpirationDate would be set to *now + ExpiryTime, as it is today, when a new balance is created.

In my opinion, as businesses logic might have different goals, it would be best to have a flag indicating action to switch expiration strategy.

For example: 
*topup - sum value
*topup_reset - reset and set value
*topup_expadd - sum value, prolong expiration
*topup_reset_expadd - reset and set value,  prolong expiration

That will also preserve backward compatibility to existing TP setups others might have.

Thanks,
Michael

**Comment by muxalko** [comment]
Hello Dear CGRateS Team!
I wonder if there is something planned in regards to this feature/request in foreseen future.
If not, I think I can try to manage the fix by myself, and then do a pull request...
Is that a better option ?

Thanks,
Michael

**Comment by muxalko** [comment]
Hello Dear CGRateS Team!
We want to implement that feature, as it is currently our major block from launching.
It seems more logical to have it implemented on CGRateS side and not third party system.
Please advise on which options do we have in regards of completing that task.
Thanks,
Michael

**Comment by danbogos** [comment]
Hi Michael,

We plan implementing this action but right now a bit loaded here.

DanB

**Comment by TeoV** [comment]
Hi Michael , 
We have implemented a new action *set_expiry. 
Please update from master and test it .

Thanks,
TeoV

**Comment by muxalko** [comment]
Hello Teo !
It seems to work fine !
Just to clear things :
1. One should use *set_expiry as a separate action, in addition to *topup or *topup_reset,
2. The only param that used is "ExpiryTime" (along with balance filter of course, "Units" are ignored).
3. ExpirationDate is calculated as : NOW() + ExpiryTime (ex. +1h), it is not relative to the existing balance ExpirationDate.

Correct ?

Thanks,
Michael

**Comment by TeoV** [comment]
Hello Michael,
Your assumtions are correct. Please reopen if any issues.

Thanks,
TeoV

**Comment by muxalko** [comment]
Thanks Teo,
Is relative ExpirationDate (point 3) something you may consider implementing in the future ?

**Comment by TeoV** [comment]
Hey Michael,
Please open a new issue if you need relative ExpirationDate and will consider it in the future.

Thanks,
TeoV
