### ISSUE TITLE
Session manager not exiting on failed RAL connection

### ISSUE THREAD

**Issue by alexsosic** [cgrates/cgrates#817]
Hi everyone,

I've noticed that the session manager fails to exit on missing RAL connection. The cgr-engine instance outputs this and does not quit:
```
2017/11/10 09:34:10 [INFO]Starting CGRateS SMKamailio service.
2017/11/10 09:34:10 [INFO]<CDRC> No enabled CDRC clients
2017/11/10 09:34:12 [CRITICAL]<SMKamailio> Could not connect to RAL:
dial tcp 10.102.9.101:2012: getsockopt: connection refused
2017/11/10 09:34:12 [INFO]<CDRC> No enabled CDRC clients
```

The configuration used is this one:
https://gist.github.com/alexsosic/7718436d3c660becf11b582a15e51c4e

Thanks!

**Comment by danbogos** [comment]
hi @alexsosic 

We have removed completely rals from KamailioAgent, so this issue should become obsoleted.

Thanks,
DanB
