### ISSUE TITLE
Removal of not existing Account 

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#829]
Hello Dear CGRateS Team!

When trying to remove not existing Account (previously removed), the engine crashes with:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcc2141]

goroutine 37118 [running]:
github.com/cgrates/cgrates/apier/v1.(*ApierV1).RemoveAccount(0xc420147480, 0xc420366988, 0x6, 0xc4203669e0, 0xd, 0x0, 0xc4203669f0, 0x0, 0x0)
        /home/golan/proj/src/github.com/cgrates/cgrates/apier/v1/accounts.go:345 +0x361
reflect.Value.call(0xc4203af200, 0xc42035eb38, 0x13, 0xfc2c78, 0x4, 0xc4204b6f20, 0x3, 0x3, 0xf29a40, 0x148a901, ...)
        /home/golan/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc4203af200, 0xc42035eb38, 0x13, 0xc42017c720, 0x3, 0x3, 0xe86960, 0x28cfc701, 0x0)
        /home/golan/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc42040aa80, 0xc420017fc0, 0xc420366850, 0xc4203f0200, 0xc420390280, 0xed6e60, 0xc4203786f0, 0x199, 0xe0edc0, 0xc4203669f0, ...)
        /home/golan/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
        /home/golan/go/src/net/rpc/server.go:481 +0x404
```

my API call:
```
POST /jsonrpc HTTP/1.1.
.
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"ApierV2.RemoveAccount",
  "params":[
    {
      "Tenant":"golant",
      "Account":"9725362130681"
    }
  ]
}
###
```

my version:
CGRateS 0.9.1~rc8 git+5bda6a7 (2017-11-20T10:18:59+01:00)

Thanks,
Michael

**Comment by TeoV** [comment]
Hello Michael,
I try to reproduce your error but without success.
I notice that your API call is wrong : "method":"ApierV2.RemoveAccount" in ApierV2 we don't have this method , only in ApierV1 for example : 
{"method":"ApierV1.RemoveAccount","params":[{"Tenant":"cgrates.org","Account":"1001","ReloadScheduler":false}],"id":4}

You can look in general_test folder at accounts_it_test , run them and capture with ngrep or you can use  cgr-console and capture also with ngrep . 

There is what I capture with ngrep 

T 2017/11/24 10:55:02.955915 127.0.0.1:46385 -> 127.0.0.1:2012 [AP]
{"method":"ApierV1.RemoveAccount","params":[{"Tenant":"cgrates.org","Account":"1001","ReloadScheduler":false}],"id":3}

#
T 2017/11/24 10:55:02.961048 127.0.0.1:2012 -> 127.0.0.1:46385 [AP]
{"id":3,"result":"OK","error":null}

#
T 2017/11/24 10:55:02.961290 127.0.0.1:46385 -> 127.0.0.1:2012 [AP]
{"method":"ApierV2.GetAccount","params":[{"Tenant":"cgrates.org","Account":"1001"}],"id":4}

#
T 2017/11/24 10:55:02.961956 127.0.0.1:2012 -> 127.0.0.1:46385 [AP]
{"id":4,"result":null,"error":"NOT_FOUND"}

#
T 2017/11/24 10:55:02.962122 127.0.0.1:46385 -> 127.0.0.1:2012 [AP]
{"method":"ApierV1.RemoveAccount","params":[{"Tenant":"cgrates.org","Account":"1001","ReloadScheduler":false}],"id":5}

#
T 2017/11/24 10:55:02.965130 127.0.0.1:2012 -> 127.0.0.1:46385 [AP]
{"id":5,"result":"OK","error":null}

#
T 2017/11/24 10:55:02.965387 127.0.0.1:46385 -> 127.0.0.1:2012 [AP]
{"method":"ApierV2.GetAccount","params":[{"Tenant":"cgrates.org","Account":"1001"}],"id":6}

#
T 2017/11/24 10:55:02.965796 127.0.0.1:2012 -> 127.0.0.1:46385 [AP]
{"id":6,"result":null,"error":"NOT_FOUND"}


Please test it with method :  "method":"ApierV1.RemoveAccount", and tell us your result 

Thanks,
TeoV

**Comment by TeoV** [comment]
Hello Michael,
I remark that u can still use ApierV2.RemoveAccount ( forgot about inheritance ) but we recommand to use the version where API is present . 

Thanks,
TeoV

**Comment by muxalko** [comment]
Hello Teo,
I tried both V1 and V2, and now, both return OK, even if the subscriber doesn't exist.

{
  "id":"0",
  "method":"ApierV2.GetAccount",
  "params":[
    {
      "Tenant":"golant",
      "Account":"972536213067"
    }
  ]
}

.
{"id":"0","result":null,"error":"NOT_FOUND"}

.
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"ApierV2.RemoveAccount",
  "params":[
    {
      "Tenant":"golant",
      "Account":"972536213067"
    }
  ]
}
#

{"id":"0","result":"OK","error":null}


That is strange, although, it is not crashing now.
What would be the correct way of verifying the removal was successful ?

Thanks,
Michael

**Comment by TeoV** [comment]
Hello Michael,
We don't return error if the data was already removed , because both mongo and redis do the same .
A simple method is to do a get on removed account and see if this returns "not found" .

Thanks,
TeoV

**Comment by muxalko** [comment]
Noted,
Thanks!
