### ISSUE TITLE
Adding offline support for cdrstats

### ISSUE THREAD

**Issue by danbogos** [cgrates/cgrates#84]
The StatQueues should be dumped regularly (new parameter in the queue, dumpInterval) and when stats server will start, it should load all previous stored cdrstat* keys from datadb).

DanB

**Comment by danbogos** [comment]
After deeper analysis, this offline support should be done in 2 different mechanisms:

 * Configured per server. We should add a new configuration parameter in cdrstats section (save interval) and if that is amended, save the stats at interval and shutdown.
* Configured per stats instance. This will overwrite server defined configuration and have the same effect - save at interval and implicitly on CGRateS shutdown.

The reason for adding it per stats instance would be to keep the flexibility of enabling offline stats only for some instances and maintain performance where that is needed.

The logic on CGRateS start should be something like:
 * Load all cdrstats instance configurations out of dataDb
 * Load where found the existing metrics from dataDb (previously stored).

DanB

**Comment by rif** [comment]
Added basic cdr stats queues saving/restoring. Needs more tests.

**Comment by rif** [comment]
After more fixes and more tests I declare this issue closed.
