### ISSUE TITLE
setAcountActionPlan on empty balance list

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#847]
Hello Dear CGRateS Team,
 There is an issue with setting account action plan, which is working good at creating new accounts and accounts without balance at all, but, if balance list is present and is empty, action plan does nothing.

To reproduce the issue , I use the following TP:
[TP_Minimal.zip](https://github.com/cgrates/cgrates/files/1509823/TP_Minimal.zip)

Then, Use SetAccount API to create an account and add PKG_UNLIM_100M ActionPlan.
```
##
T 2017/11/28 14:19:42.550160 10.192.210.110:52288 -> 10.224.228.186:2080 [AP]
POST /jsonrpc HTTP/1.1.
.
{
  "id":0,
  "method":"ApierV2.SetAccount",
  "params":[
  .{
  .."Tenant":"golant",
  .."Account":"972536213067",
      ."ActionTriggerIDs":["STANDARD_TRIGGERS"],
        "ActionTriggerOverwrite": true,
  .."ActionPlanIDs":["PKG_UNLIM_100M"],
        "ActionPlansOverwrite": true,
  .."ReloadScheduler":true
.}.
]
}

#
T 2017/11/28 14:19:42.582839 10.224.228.186:2080 -> 10.192.210.110:52288 [AP]
HTTP/1.1 200 OK.
.
{"id":0,"result":"OK","error":null}

```

Normally, each balance has expiration set to 1h, then it should be removed by the corresponding action.
We will execute it manually:

```
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"ApierV1.ExecuteAction",
  "params":[
    {
      "Tenant":"golant",
      "Account":"972536213067",
      "ActionsId":"LOG_WARNING_DATA_EXPIRED"
    }
  ]
}

.
{"id":"0","result":"OK","error":null}

```

Which will successfully remove account balances.
 looks like this:

"BalanceMap":{
"*data":[],
"*sms":[],
"*voice":[]
},

If we try to setAccount(with ActionPlan) again, to topup balances, it is not working, leaving balances as is.
We either need to remove balance list manually, or delete account to make it work.

Am I missing something that need to be passed to API, or it is a bug?

Please assist,
Michael

**Comment by muxalko** [comment]
Hello Dear CGRateS Team,
Just wanted to check the status.
Have you succeeded to replicate the issue ?

Thanks,
Michael

**Comment by danbogos** [comment]
Hi @muxalko,

We did it now (unfortunately not enough hours in a day).
Your action plan was considered scheduled to be executed (was not considering that you have already executed tasks but that they were scheduled to run in the future). That would have been OK if you would have had also scheduled tasks, not only asap ones since unscheduling would work there.

The issue should be now fixed in master.

DanB

**Comment by muxalko** [comment]
It works now!
In our case, there is no scheduled executions , only *asap ones,  more like a prepaid bundle purchase.
Just to understand better. What did you mean by unscheduling ?
Can, I just setAccount with an empty ActionPlan ?
Thanks Dan,

**Comment by muxalko** [comment]
Hello Dan,
Actions are executed, and no scheduled execution.
I guess that is why I am not seeing my AccountActionPlan now, right ?
```
POST /jsonrpc HTTP/1.1.
.
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"ApierV2.GetAccountActionPlan",
  "params":[
    {
      "Tenant":"golant",
      "Account":"972536213067"
    }
  ]
}
#

.
{"id":"0","result":[],"error":null}
```

**Comment by danbogos** [comment]
If you have only *asap  actions in your action plan, they are not recorded by scheduler (works like fire and forget), so you will not see them with GetAccountActionPlan.

DanB
