### ISSUE TITLE
Could not write to database: E11000 duplicate key error collection: 10.resource_profiles index: key_1 dup key: { : null }

### ISSUE THREAD

**Issue by basitengr** [cgrates/cgrates#867]
cgr-engine -version
CGRateS 0.9.1~rc8 git+24b59c4 (2017-10-31T14:27:15+02:00)

OS: Debian GNU/Linux 8.10 (jessie)

---------------------------------------------
I setup cgrates with default configuration with kamailio and mongodb
After service initialization and db migration for `cgr-migrator -migrate=*set_versions`
I tried to load cvs from `/usr/share/cgrates/tariffplans/tutorial`

`cgr-loader -datadb_host 127.0.0.1 -datadb_port 27017 -datadb_type mongo -datadb_name 10 -datadb_user cgrdata -datadb_passwd cgrates -verbose`

which was failed with error   
`Could not write to database: E11000 duplicate key error collection: 10.resource_profiles index: key_1 dup key: { : null }`

Dropping index `key_1` from collections `10.resource_profiles` and `10.resource` resolved the issue and data was populated successfully.

if its relevant `user: "cgrdata"` has `roles: [ { role: "dbOwner", db: "10" } ]`

Reporting the issue here because I found it multiple times for each new installation.
There should be only one index (_id_) in each collection. `key_1` is causing problems.

**Comment by Edwardro22** [comment]
Greetings basitengr,
Now the problem should be fixed.
Please test it .

Thanks,
Eduard

**Comment by basitengr** [comment]
I git installed  __CGRateS 0.9.1~rc8 git+8a42c22 (2017-12-19T17:35:36+02:00)__ on fresh minimal Debian GNU/Linux 8.10 (jessie) with kamailio 5.0.5 and mongodb 3.4.

This time i didn't face __duplicate key error__ 

Thank you for the fix.
