### ISSUE TITLE
panic: reflect: Call using map[string]interface {} as type *utils.CGREvent

### ISSUE THREAD

**Issue by uppaljs** [cgrates/cgrates#868]
Hi,

After configuring stats , cgrates crashes with the below error when a Cdr file is processed.

`panic: reflect: Call using map[string]interface {} as type *utils.CGREvent

goroutine 49 [running]:
reflect.Value.call(0xef2f40, 0xc42000e648, 0x1613, 0xfe8e35, 0x4, 0xc4204ace80, 0x2, 0x2, 0xc4204fce98, 0xe2dd00, ...)
        /usr/local/go/src/reflect/value.go:371 +0x1094
reflect.Value.Call(0xef2f40, 0xc42000e648, 0x1613, 0xc4204ace80, 0x2, 0x2, 0xc42000e648, 0x1613, 0xc420128360)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/cgrates/cgrates/utils.APIerRPCCall(0xef2f40, 0xc42000e648, 0xffbb01, 0x14, 0xe9ca60, 0xc4204f91d0, 0xe2dd00, 0xc4227251b0, 0x1, 0x0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/utils/coreutils.go:825 +0x20a
github.com/cgrates/cgrates/apier/v1.(*StatSv1).Call(0xc42000e648, 0xffbb01, 0x14, 0xe9ca60, 0xc4204f91d0, 0xe2dd00, 0xc4227251b0, 0xc4227226a0, 0xc4201de798)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/apier/v1/stats.go:79 +0x80
github.com/cgrates/cgrates/vendor/github.com/cgrates/rpcclient.(*RpcClient).Call.func1(0xc420748000, 0xc420550e40, 0xffbb01, 0x14, 0xe9ca60, 0xc4204f91d0, 0xe2dd00, 0xc4227251b0)
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/rpcclient/rpcclient.go:197 +0xfb
created by github.com/cgrates/cgrates/vendor/github.com/cgrates/rpcclient.(*RpcClient).Call
        /usr/local/goapps/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/vendor/github.com/cgrates/rpcclient/rpcclient.go:200 +0x1d4
`

Config used is following
Filters.csv:

#Tenant[0],ID[1],FilterType[2],FilterFieldName[3],FilterFieldValues[4],ActivationInterval[5]
crates.org,FLTR_STS1,*string,Account,ETI,2014-07-29T15:00:00Z

Stats.csv:

#Tenant[0],Id[1],FilterIDs[2],ActivationInterval[3],QueueLength[4],TTL[5],Metrics[6],Blocker[7],Stored[8],Weight[9],MinItems[10],Thresholds[11]
cgrates.org,Stats1,FLTR_STS1,2014-07-29T15:00:00Z,100,1s,*asr;*acc;*tcc;*acd;*tcd;*pdd,true,true,20,2,THRESH1;THRESH2

**Comment by uppaljs** [comment]
just a small addition, has to do something with the current build , as disabling stats still crashes cgrates

**Comment by danbogos** [comment]
hi @uppaljs 

Can you please attach also your cgrates.json config?

Thanks,
DanB

**Comment by uppaljs** [comment]
This is the cgrates.json file:

[cgrates.txt](https://github.com/cgrates/cgrates/files/1550854/cgrates.txt)

cdrc
[igw.txt](https://github.com/cgrates/cgrates/files/1550862/igw.txt)
