### ISSUE TITLE
Adding FreeSWITCH cgr_ignorepark channel variable

### ISSUE THREAD

**Issue by cgrates** [cgrates/cgrates#87]
Since sometimes there are other applications processing park also, they should be responsible to query max session duration to cgrates and we will avoid race on unparking the calls in this way. We have already a way to not subscribe park (through subscribe_park configuration option) but that does not solve the issue when they got outbound looped through freeswitch for billing purposes.

DanB

**Comment by danbogos** [comment]
Implemented in master.
