### ISSUE TITLE
kamailio evapi and CDR(StorDB) Data too long for column 'origin_id'

### ISSUE THREAD

**Issue by paolovisintin** [cgrates/cgrates#880]
Hi everyone, 
we experienced some troubles in CDR writing as of the error mentioned above: 
```
(Error 1406: Data too long for column 'origin_id' at row 1)
```
doing an `ALTER TABLE` and setting `order_id` to 128 VARCHAR now we're seeing correctly CDR rows (both `*raw` and `*default`)

**Comment by danbogos** [comment]
hey @paolovisintin 

If you can provide a patch to db schema which works for you, we can integrate it into master.

DanB

**Comment by paolovisintin** [comment]
Hey @danbogos , just made a Pull request: 
https://github.com/cgrates/cgrates/pull/881

**Comment by danbogos** [comment]
@paolovisintin 
Thanks for the PR!

DanB
