### ISSUE TITLE
[ERROR] <SMGeneric> SessionTerminate with no active sessions for cgrID:

### ISSUE THREAD

**Issue by TayyabTalha** [cgrates/cgrates#895]
I follow asterisk tutorial. I'm facing following problems
When Hangup I get following error
 2018/01/09 05:57:18 [ERROR] <SMGeneric> SessionTerminate with no active sessions for cgrID: <f9faf26966081adee05c3fb8fcc0b157af5be2ba>
 2018/01/09 05:57:18 [ERROR] <SMAsterisk> Error: SESSION_NOT_FOUND when attempting to terminate session for channelID: fd_r1-1515506234.78

Engine is not setting up variable ${CGRMaxSessionTime}
In asterisk cli log [1002@internal:5] Dial("PJSIP/1001-0000003c", "PJSIP/1002,30,L()")

Other Problem is that it is not hanging up call when balance go in negative
Using CentOS: 
Asterisk version: Asterisk 14.7.2

 Before Call
 "*monetary": [
    {
     "Uuid": "eb241d1c-c860-40e6-a7d6-4b85b0587b94",
     "ID": "",
     "Value": 0.3,
     "Directions": {},
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ],
   
During Call
 "*monetary": [
    {
     "Uuid": "eb241d1c-c860-40e6-a7d6-4b85b0587b94",
     "ID": "",
     "Value": 0.00033,
     "Directions": {},
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ]
   

3 Min cost
cgr> cost Category="call" Tenant="cgrates.org" Subject="1001" Destination="1002" AnswerTime="2018-01-04T13:00:00Z" Usage="3m"
{
 "CGRID": "",
 "RunID": "",
 "StartTime": "2018-01-04T13:00:00Z",
 "Usage": 180000000000,
 "Cost": 0.4004,
 "Charges": [
  {
   "RatingID": "020600b",
   "Increments": [
    {
     "Usage": 60000000000,
     "Cost": 0.2,
     "AccountingID": "",
     "CompressFactor": 1
    }
   ],
   "CompressFactor": 1
  },
  {
   "RatingID": "e37186b",
   "Increments": [
    {
     "Usage": 1000000000,
     "Cost": 0.00167,
     "AccountingID": "",
     "CompressFactor": 120
    }
   ],
   "CompressFactor": 1
  }
 ],
 "AccountSummary": null,
 "Rating": {
  "020600b": {
   "ConnectFee": 0.4,
   "RoundingMethod": "*up",
   "RoundingDecimals": 4,
   "MaxCost": 0,
   "MaxCostStrategy": "",
   "TimingID": "37e6a01",
   "RatesID": "7f2c01c",
   "RatingFiltersID": "86ee106"
  },
  "e37186b": {
   "ConnectFee": 0.4,
   "RoundingMethod": "*up",
   "RoundingDecimals": 4,
   "MaxCost": 0,
   "MaxCostStrategy": "",
   "TimingID": "37e6a01",
   "RatesID": "67b5a70",
   "RatingFiltersID": "86ee106"
  }
 },
 "Accounting": {},
 "RatingFilters": {
  "86ee106": {
   "DestinationID": "DST_1002",
   "DestinationPrefix": "1002",
   "RatingPlanID": "RP_RETAIL2",
   "Subject": "*out:cgrates.org:call:1001"
  }
 },
 "Rates": {
  "67b5a70": [
   {
    "GroupIntervalStart": 0,
    "Value": 0.2,
    "RateIncrement": 60000000000,
    "RateUnit": 60000000000
   },
   {
    "GroupIntervalStart": 60000000000,
    "Value": 0.1,
    "RateIncrement": 1000000000,
    "RateUnit": 60000000000
   }
  ],
  "7f2c01c": [
   {
    "GroupIntervalStart": 0,
    "Value": 0.2,
    "RateIncrement": 60000000000,
    "RateUnit": 60000000000
   },
   {
    "GroupIntervalStart": 60000000000,
    "Value": 0.1,
    "RateIncrement": 1000000000,
    "RateUnit": 60000000000
   }
  ]
 },
 "Timings": {
  "37e6a01": {
   "Years": [],
   "Months": [],
   "MonthDays": [],
   "WeekDays": [
    1,
    2,
    3,
    4,
    5
   ],
   "StartTime": "08:00:00"
  }
 }
}
After Call of 6 min
  "*monetary": [
    {
     "Uuid": "eb241d1c-c860-40e6-a7d6-4b85b0587b94",
     "ID": "",
     "Value": 0.0401,
     "Directions": {},
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 0,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ]

nggrep and asterisk dialplan and cgrates.json
 files are attached
[error_in_case_of_hangup_without_answer.log](https://github.com/cgrates/cgrates/files/1615503/erro
[cgrates.txt](https://github.com/cgrates/cgrates/files/1615537/cgrates.txt)
r_in_case_of_hangup_without_answer.log)
  [extensions.txt](https://github.com/cgrates/cgrates/files/1615545/extensions.txt)
[not_hanging_up_in_case_of_balance_negative.log](https://github.com/cgrates/cgrates/files/1615504/not_hanging_up_in_case_of_balance_negative.log)

**Comment by TeoV** [comment]
Hi TayyabTalha,
Now the issue should be fixed in master. 
Please update and retest.

Thanks,
TeoV
