### ISSUE TITLE
Filter for OriginID in cdrs table in StorDB

### ISSUE THREAD

**Issue by choodov** [cgrates/cgrates#897]
After processing  ExternalCDR to CGRateS StorDB (save via method "CdrsV1.ProcessExternalCDR"),
 there is no API method to get this CDR by "OriginID" field (filter).
It will be good if you can create this filter for OriginID.
Best regards, Aleksandr.

**Comment by TeoV** [comment]
Hello Aleksandr,
We have added the requested filters.
Please test it 

Thanks,
Teov
