### ISSUE TITLE
CDRStats: Reload parameters without reset the values

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#90]
Hi, 

We are using CGRates CDRStats to set customer alerts. As described [here](http://acalustra.com/my-thoughts-about-cgrates.html), so this is our normal cdr_stat values: 

```json
{
  "error": null,
  "id": 4,
  "result": {
    "CdrStats": [
      {
        "Accounts": "eloy",
        "ActionTriggers": "ZD_ALERT_100",
        "Categories": "",
        "CdrHosts": "",
        "CdrSources": "",
        "CostInterval": "",
        "DestinationPrefixes": "",
        "Directions": "",
        "DisconnectCauses": "",
        "MediationRunIds": "",
        "Metrics": "TCC",
        "PddInterval": "",
        "QueueLength": "0",
        "RatedAccounts": "",
        "RatedSubjects": "",
        "ReqTypes": "",
        "SetupInterval": "",
        "Subjects": "",
        "Suppliers": "",
        "TORs": "",
        "Tenants": "foehn",
        "TimeWindow": "24h",
        "UsageInterval": ""
      }
    ],
    "CdrStatsId": "CDR_STAT_eloy",
    "TPid": "test"
  }
}
```

So, if I change the *ActionTriggers* (ZD_ALERT_100), I need to reload the queue, and I'll lose my TCC values in this case. Any way to reload only the trigger?

Regards and enjoy the weekend.

**Comment by danbogos** [comment]
Some ideas regarding the implementation:

 * On load, check if the existing configuration matches fully (including all CDR filters, excluding ActionTriggers) the previously stored configuration or if configuration fields (QueueLength,TimeWindow,Metrics and SetupInterval) are missing. If these preconditions are matched, update previous configuration without flushing data with new ActionTriggers.
 * There could be an API doing exact ActionTriggers reset.

**Comment by rif** [comment]
I pushed the code for this issue.
The cdr stats feature has suffered multiple modifications in the last week so please report any issue (the stats values should survive server restart now).

**Comment by eloycoto** [comment]
Hi, 

Quick one, I've just debug a little bit this, and I'm having the following issue in this line: 

https://github.com/cgrates/cgrates/blob/68ce36543595d20b482c435521b22c0c8723c5a9/engine/storage_redis.go#L677-685

I added the following log line: 
```
log.Printf("values='%v' sq='%v'", values, sq)
```

And I got the following: 
```
values='[130 164 67 100 114 115 144 167 77 101 116 114 105 99 115 129 163 84 67 67 128]' sq='&{[] <nil> map[] {0 0} false}'
```
The log is this:
```
cannot decode non-nil codec value into nil engine.Metric (3 methods)
```

Any idea? If you need more info ping me on IRC. 

Thanks rif.

**Comment by eloycoto** [comment]
Hi folks, 

Happy to say that it's working. In production for a week and no problems founded ;-) 

Thanks

**Comment by rif** [comment]
Nice, thanks eloycoto.
