### ISSUE TITLE
RADIUS supplementary dictionary issue

### ISSUE THREAD

**Issue by semams** [cgrates/cgrates#912]
Hello everyone,

I'm faced on issue using supplementary dictionary for RADIUS (in my case it is 3GPP dictionary).

For tests I use local radclient:

root ~ # echo " User-Name = 12341234123, 3GPP-SGSN-MCC-MNC = *data, Acct-Session-Id = e4921177ab0e3586c37f6a185864b71a@0:0:0:0:0:0:0:0, Filter-Id = *out, Callback-Id = data, Login-LAT-Service = *prepaid, Framed-Route = *any, NAS-IP-Address = 127.0.0.1, Event-Timestamp = 1516352123 "| radclient -s -x 127.0.0.1:1812 auth CGRateS

Command output:
Sending Access-Request Id 5 from 0.0.0.0:35777 to 127.0.0.1:1812
        User-Name = '12341234123'
        3GPP-SGSN-MCC-MNC = '*data'
        Acct-Session-Id = 'e4921177ab0e3586c37f6a185864b71a@0:0:0:0:0:0:0:0'
        Filter-Id = '*out'
        Callback-Id = 'data'
        Login-LAT-Service = '*prepaid'
        Framed-Route = '*any'
        NAS-IP-Address = 127.0.0.1
        Event-Timestamp = 'Jan 19 2018 08:55:23 UTC'
(0) No reply from server for ID 5 socket 3
Packet summary:
        Accepted      : 0
        Rejected      : 0
        Lost          : 1
        Passed filter : 0
        Failed filter : 0
		
When I use an appropriate attribute from embedded RFC2865 dictionary (for example, "Reply-Message" has string type too) all is OK.
		
Please find CGRateS config and log files, 3GPP dictionary and ngrep output attached.

OS: CentOS Linux release 7.3
radclient version 3.0.4
[cgrates_log.txt](https://github.com/cgrates/cgrates/files/1645957/cgrates_log.txt)
[dictionary.txt](https://github.com/cgrates/cgrates/files/1645964/dictionary.txt)
[cgrates_config.txt](https://github.com/cgrates/cgrates/files/1645967/cgrates_config.txt)
[ngrep_rad_3gpp.txt](https://github.com/cgrates/cgrates/files/1645971/ngrep_rad_3gpp.txt)

**Comment by danbogos** [comment]
hi @semams,

I was able to load and process your request just fine using this template:
`
"request_processors": [
                {
                        "id": "SCEAuth",
                        "dry_run": true,
                        "request_filter": "*radReqType(*radAuth)",
                        "request_fields":[
                                {"tag": "TOR", "field_id": "ToR", "type": "*composed", "value": "3GPP/3GPP-SGSN-MCC-MNC", "mandatory": true},
                                {"tag": "OriginID", "field_id": "OriginID", "type": "*composed", "value": "Acct-Session-Id", "mandatory": true},
                                {"tag": "RequestType", "field_id": "RequestType", "type": "*composed", "value": "Login-LAT-Service", "mandatory": false},
                                {"tag": "Direction", "field_id": "Direction", "type": "*composed", "value": "Filter-Id", "mandatory": true},
                                {"tag": "Category", "field_id": "Category", "type": "*composed", "value": "Callback-Id", "mandatory": true},
                                {"tag": "Account", "field_id": "Account", "type": "*composed", "value": "User-Name", "mandatory": true},
                                {"tag": "Destination", "field_id": "Destination", "type": "*composed", "value": "Framed-Route", "mandatory": true},
                                {"tag": "SetupTime", "field_id": "SetupTime", "type": "*composed", "value": "Event-Timestamp", "mandatory": true},
                                {"tag": "Usage", "field_id": "Usage", "type": "*constant", "value": "2048", "mandatory": true},
                                {"tag": "Usage", "field_id": "Usage", "type": "*constant", "value": "2048", "mandatory": true},
                        ],
                        "reply_fields":[
                                {"tag": "MaxUsage", "field_id": "Login-Service", "type": "*composed", "value": "*cgrMaxUsage", "mandatory": true},
                        ],
                },
 	],
`

Please note that in the master version we use now ">" as hierarchy separator in case of vendor attributes (instead of /).


DanB
