### ISSUE TITLE
build crates fails

### ISSUE THREAD

**Issue by lqjack** [cgrates/cgrates#929]
I build in the mac pro. however i execute the build.sh , i get the response as below: 

Building CGRateS ...
# github.com/cgrates/cgrates/utils
utils/birpcint_client.go:61:59: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".NewClientWithCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
utils/server.go:239:53: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to s.birpcSrv.ServeCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
# github.com/cgrates/cgrates/utils
utils/birpcint_client.go:61:59: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".NewClientWithCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
utils/server.go:239:53: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to s.birpcSrv.ServeCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
# github.com/cgrates/cgrates/utils
utils/birpcint_client.go:61:59: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".NewClientWithCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
utils/server.go:239:53: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to s.birpcSrv.ServeCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
# github.com/cgrates/cgrates/utils
utils/birpcint_client.go:61:59: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".NewClientWithCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
utils/server.go:239:53: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to s.birpcSrv.ServeCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
# github.com/cgrates/cgrates/utils
utils/birpcint_client.go:61:59: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".NewClientWithCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error
utils/server.go:239:53: cannot use "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2/jsonrpc".NewJSONCodec(conn) (type "github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec) as type "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec in argument to s.birpcSrv.ServeCodec:
	"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Codec does not implement "github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Codec (wrong type for ReadHeader method)
		have ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenkalti/rpc2".Response) error
		want ReadHeader(*"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Request, *"github.com/cgrates/cgrates/vendor/github.com/cenk/rpc2".Response) error

**Comment by danbogos** [comment]
hi @lqjack 

You are building it wrong. We use Glide for package management so you will need to do "glide install" before ./build.sh.

DanB

**Comment by lqjack** [comment]
thanks reply , i have executed glide cc;glide update; glide install , and successful.

**Comment by danbogos** [comment]
You're welcome!

**Comment by lqjack** [comment]
however how can i solve the issue , i cannot build the cgrates now . during the reason before .  can you provide the solution ?thanks.

**Comment by lqjack** [comment]
@danbogos can you help ?
