### ISSUE TITLE
resets balance to ziro for prepaid

### ISSUE THREAD

**Issue by choodov** [cgrates/cgrates#933]
Please, add an action which resets balance to 0 (ziro), if original balance is smaller than 0 (ziro) 
(*zero_if_negative).
This action need for *repaid type.

**Comment by choodov** [comment]
One more thing. When you create this action and we will use it, will CGRateS store history about when and on what amount of money it reset balance?

**Comment by TeoV** [comment]
Hello choodov,
We have implemented a new action *topup_zero_negative . 
Please update from master and test it .
About the history you can use *cdrlog . We don't keep it . 

Thanks,
TeoV
