### ISSUE TITLE
redis password auth

### ISSUE THREAD

**Issue by andamasov** [cgrates/cgrates#94]
Hello,
getting issue while trying to use redis db with password auth.
We experiencing issue on hosted redis service, but i guess it will be reproducible on any other redis instance with password enabled.
Clients works just fine with password.

On cgrates restart in network capture you can see that initial  connection done with password and all is fine, but then arrive some additional requests(new connection ?) which is not authenticated and cgr-engine dies.
 
Here is sample of trace

http://pastebin.com/EfbDWbPD

**Comment by danbogos** [comment]
Hi @andamasov,

Are you sure that CGRateS crashes in the end? If that is the case, there should be some trace in /var/run/cgrates/cgrates.strace. Can you paste that here?

Ta,
DanB

**Comment by andamasov** [comment]
Hi,
there is not much info there.
root@cgrates-dev:/var/run/cgrates# cat cgrates.strace 

### Started at: Sun Jun 14 11:45:18 EDT 2015

### Started at: Sun Jun 14 12:30:44 EDT 2015

### Started at: Sun Jun 14 12:30:47 EDT 2015

### Started at: Sun Jun 14 12:31:08 EDT 2015

### Started at: Sun Jun 14 12:32:37 EDT 2015

### Started at: Sun Jun 14 12:32:40 EDT 2015

### Started at: Sun Jun 14 12:43:52 EDT 2015

### Started at: Sun Jun 14 12:44:18 EDT 2015

### Started at: Sun Jun 14 12:44:59 EDT 2015

### Started at: Sun Jun 14 12:45:03 EDT 2015

**Comment by danbogos** [comment]
Hi @andamasov 

I agree that there is not much info there. This shows just normal start, no crash. We will need to continue troubleshooting and will inform you as soon as any news.

Thanks,
DanB

**Comment by rif** [comment]
just pushed a fix for this issue, please test and tell us your results

**Comment by andamasov** [comment]
Hello,
can confirm that it starting ok now
