### ISSUE TITLE
Freeswitch json_cdr: CDR server interface URL

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#940]
Hi guys,

I can't find where it is possible to change CDR server json URL. 
In freeswitch json_cdr.conf the URL is configurable, but at the cgrates end seems to be hardcoded.

Thank you.

**Comment by danbogos** [comment]
Hey @arsperger 

Can you give another try pls?

DanB

**Comment by danbogos** [comment]
Sorry, wrong issue :).

DanB

**Comment by TeoV** [comment]
Hi arsperger,
This features is availabele in master .
Please come back if any issues.

Thanks,
TeoV
