### ISSUE TITLE
Problems with cache and restart

### ISSUE THREAD

**Issue by Rolfr57** [cgrates/cgrates#958]
We have made a new build

CGRateS 0.9.1~rc8 git+192ecfd (2018-02-06T14:23:30+02:00)
We flushed the reddis DB and restarted CGRateS.

I loaded the csv files, but I got a warning at the end
2018/02/14 09:55:02 Reloading cache
2018/02/14 09:55:02 WARNING: Got error on cache reload: write tcp 10.40.2.21:59280->10.40.2.21:2013: write: connection reset by peer

I reloaded the cache manually:

{"method":"ApierV1.ReloadCache",
 "params":[{
	"DestinationIDs":null,
	"ReverseDestinationIDs":null,
	"RatingPlanIDs":null,
	"RatingProfileIDs":null,
	"ActionIDs":null,
	"ActionPlanIDs":null,
	"AccountActionPlanIDs":null,
	"ActionTriggerIDs":null,
	"SharedGroupIDs":null,
	"LCRids":null,
	"DerivedChargerIDs":null,
	"AliasIDs":null,
	"ReverseAliasIDs":null,
	"ResourceProfileIDs":null,
	"ResourceIDs":null,
	"StatsQueueIDs":null,
	"StatsQueueProfileIDs":null,
	"ThresholdIDs":null,
	"ThresholdProfileIDs":null,
	"FilterIDs":null,
	"SupplierProfileIDs":null,
	"AttributeProfileIDs":null,
	"FlushAll":false}],
 "id":0}
{"id":0,"result":"OK","error":null}

After this everything seems to work, calls was rated, but the derived chargers with *any for account didn't work, but if I changed it with a specific account name, I was able to initiate a derived run.

Then I tried to restart the CGRates:

Feb 14 10:19:18 CGRates01 systemd[1]: Stopped LSB: CGRateS real-time charging sy
Feb 14 10:19:18 CGRates01 systemd[1]: Starting LSB: CGRateS real-time charging s
Feb 14 10:19:18 CGRates01 systemd[1]: Started LSB: CGRateS real-time charging sy

But it didn't come up correctly.  The following info was given:
root@CGRates01:/etc/init.d# cgr-engine -config_dir=/etc/cgrates -log_level=7
Migration needed: please backup cgrates data and run : <cgr-migrator> 

We had to flush the reddis DB again and then it was possible to start the CGRateS again.

[CSV.zip](https://github.com/cgrates/cgrates/files/1727012/CSV.zip)

**Comment by TeoV** [comment]
Hi Rolfr57,
Sorry to announce you but I can't reproduce your issue . 
My version of engine is : CGRateS 0.9.1~rc8 git+78368d6 (2018-02-19T19:38:45+01:00)
Here is what I did : 
1)Start the engine with the custom confiduration ( for redis ) with : 
cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutmysql
2)Load the data with cgr-loader : 
cgr-loader -datadb_host "127.0.0.1" -datadb_name "10" -datadb_port "6379" -datadb_type "redis" -datadb_user "cgrates" 
3) check the result but it load correctly in cache and don't get error . 
Try again with the new version and if you still have problem tell me step by step what you did and I will try again . 
Until then good luck . 

Thnaks,
TeoV
