### ISSUE TITLE
Can't get any CDR ExtraField in FS event mode

### ISSUE THREAD

**Issue by nevian427** [cgrates/cgrates#960]
We have last master (at time of writing)
CGRateS 0.9.1~rc8 git+296ef1b (2018-02-15T15:36:40+02:00)

In config we have in both sections (cdrs and freeswitch_agent)
        "extra_fields": [
            "progressmsec",
            "answermsec",
            "progress_mediamsec",
            "waitmsec",
            "sip_network_ip",
            "remote_media_ip",
            "sip_from_user_stripped",
            "Channel-Read-Codec-Name",
            "variable_sip_from_user_stripped",
            "caller_id_name"
        ],

We can't get any extra fields if we disable JSON CDRs and enable freeswitch_agent cdrs generator
        "create_cdr": true

DB contains only set of hardcoded variables
{"PDD": "0s", "Supplier": "", "Direction": "*out", "DisconnectCause": "NORMAL_CLEARING"}
[CHANNEL_HANGUP.txt](https://github.com/cgrates/cgrates/files/1728570/CHANNEL_HANGUP.txt)

**Comment by nevian427** [comment]
Fixed in f1e3e5822db00ca90b0dc21e37d426ee5c5cbcb2

**Comment by danbogos** [comment]
Thanks for closing it, indeed it should be fixed now.

DanB
