### ISSUE TITLE
API missing ApierV1.RemActionPlan

### ISSUE THREAD

**Issue by miromiky** [cgrates/cgrates#972]
Hi @danbogos 

i found this:
`https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.SetActionPlan`
`https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.GetActionPlan`

missing: 
`https://godoc.org/github.com/cgrates/cgrates/apier/v1#ApierV1.RemActionPlan`

Can you implement this? thanks.
regards
Miroslav

**Comment by danbogos** [comment]
Duplicate, handled in #971
