### ISSUE TITLE
Stats are not considered to thresholds

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#974]
Hello Dear CGRateS Team!
There is no event processing happening between Stats and Thresholds.

Please assist,
Thanks,
Michael

**Comment by TeoV** [comment]
Hello muxalko,
Please update from master and test it .

Thanks,
TeoV

**Comment by muxalko** [comment]
Hello, Teo !
Actually, from our discussion with Dan, he states that :

> The balanceUpdate is not being sent 
> to StatS, hence your StatS queue aggregating balance will never receive 
> events. Once it does, it will also send to ThresholdS when updated, so 
> you can react on them. 

As for the Queue and Thresholds, those are removed OK once their Profile is deleted.

Thanks,
Michael

**Comment by muxalko** [comment]
A bit confused here, sorry
Once https://github.com/cgrates/cgrates/issues/976 is implemented 
I will recheck Stats -> ThresholdS flow
