### ISSUE TITLE
Feature request: new filter type for checking account balance

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#987]
Hi,
It would be good to have a way via API to keep a part of your balance reserved in case of fraud etc.

For example, you have £1000 prepaid and don't want it to go to 0, but have some limit of say £300 or similar that you can change.

Thanks.

**Comment by ghenry** [comment]
Maybe this is best done via a filter to check the percentage of balance left and then return denied.

**Comment by danbogos** [comment]
Gavin,

Yes, this can be added. Please open a separate issue (or rename this one).

Thanks,
Dan

PS: limiting some value should work easy if you keep it outside of CGRateS

**Comment by ghenry** [comment]
Rename? I think it's pretty clear already?

**Comment by TeoV** [comment]
Hi @ghenry,

We have implemented this and is available in master.
Please have a look here for an example :
https://github.com/cgrates/cgrates/blob/master/general_tests/filters_it_test.go#L514

Thanks,
TeoV

**Comment by ghenry** [comment]
Excellent, so what do we apply that filter too? Thresholds?

**Comment by ghenry** [comment]
Nevermind, it's clear in the test. https://github.com/cgrates/cgrates/blob/master/general_tests/filters_it_test.go#L542
