### ISSUE TITLE
Feature request: Max call duration

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#988]
Hi,
It would be good to set via the API how long a call can be per call rather than hard code a max cost. Something in ThresholdS or similar and alerts around.
Thanks.

**Comment by danbogos** [comment]
Hey @ghenry 

not sure I understand it. Can you attach some example please?

DanB

**Comment by ghenry** [comment]
@danbogos Hi!

You might want to limit how long a person can call a freephone number or premium call number or a conference number as part of a plan/package rather than just a max cost. It helps with Fraud mitigation when calling expensive numbers that payout to the number owner, i.e. inbound calls not just outbound.
Thanks.

**Comment by ghenry** [comment]
Ah, I see this is hardcoded for now:

https://github.com/cgrates/cgrates/blob/master/config/config.go#L169

**Comment by porosnicuadrian** [comment]
HI @ghenry.

MaxCallDuration is not hardcoded anymore.You can configure this from config. 
https://github.com/cgrates/cgrates/pull/2447/commits/41ce68c4eacafb90d82c905cbbaf23a47c9b08da

Thanks, porosnicuadrian

**Comment by ghenry** [comment]
So do I need to change where it is currently set? Thank you.

**Comment by porosnicuadrian** [comment]
Hi @ghenry 

By default, the value of MinCallDuration is 0s and the value of MaxCallDuration is 3h. If you want to change these values, you can go to config and assign the value you want.
https://github.com/porosnicuadrian/cgrates/blob/master/config/config_defaults.go#L45-L46

Thanks,
porosnicuadrian
