### ISSUE TITLE
AttributeS with Diameter Agent

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#999]
Hello Dear CGRateS Team!

Please make *attributes work within diameter_agent > request_processors 
"type": "*composed", 	"value": "^*attributes",

Thanks,
Michael

**Comment by danbogos** [comment]
hey @muxalko 

This feature is now in master.

Some sample usage: `*cgrReply>Attributes>UserPassword` to use the UserPassword attribute in your replies.

Also data converters are now available, sample usage here:
`https://github.com/cgrates/cgrates/blob/master/data/conf/samples/dmtagent/voice.json#L34`

Good luck!

DanB
